processors now actually accepts monkeys
HippieStation/HippieStationdeprecated2020 pull request #10185
Opened 2018-12-22 06:53 UTC by xTrainx

:cl: xTrainx
fix: processors now actually accepts monkeys
/:cl:

[why]:  so fun fact, my last pr did actually turned dead monkeys into bloody buckets, but turns out i forgot to add a way for it to actually eat the monkeys, crazy right? tested locally, worked groovely, although, it now adds gibs along the bucket

2018-12-22 07:10 UTC, xTrainx commented
look at that shit, man, first time travis accepts me at the first hit

2018-12-22 18:44 UTC, yoyobatty commented
Is this for the slime processor or kitchen processor?

2018-12-22 18:52 UTC, yoyobatty commented
This works too right?

2018-12-22 19:20 UTC, xTrainx commented
the slime processor, kitchen processor is unaffected, and yes, it works, the only change from how it was before is that it also leaves some gibs around

2018-12-22 20:04 UTC, Lxtoofonea commented
+1 ahhhh

2018-12-23 00:29 UTC, yoyobatty reviewed
And you've tested it too right?

2018-12-23 00:57 UTC, xTrainx commented
Yes  did, it takes slimes normally and process it the dame, cant take humans and live monkeys are just ejected

2018-12-26 00:53 UTC, yoyobatty requested changes

2018-12-26 00:53 UTC, yoyobatty commented on hippiestation/code/modules/food_and_drinks/kitchen_machinery/processor.dm
> +		return 1
`return TRUE`

2018-12-26 00:53 UTC, yoyobatty commented on hippiestation/code/modules/food_and_drinks/kitchen_machinery/processor.dm
> +			return 1
`return TRUE`

2018-12-26 03:37 UTC, yoyobatty approved these changes

2018-12-26 03:37 UTC, merged