[WIP]Circuitry Copyright Agreement Of 2018 (make circuits id-lockable and sealable)
HippieStation/HippieStationdeprecated2020 pull request #10225
Opened 2018-12-25 17:37 UTC by Shdorsh

[Changelogs]: # Chuckster Corp and Nanotrasen have come to an agreement that the user of their products should have the ability to protect their designs as their own intellectual property. As such, the new printers were fitted with blueprints of permanently sealable assemblies in order to prevent tampering and theft of design. As of now, Chuckster Corp is still busy trying to figure a way to turn the assemblies compatible to Nanotrasen's ID-system for further protection.

:cl: Shdorsh
tweak: circuits can be sealed so no one can tamper with their insides directly.
/:cl:

[why]: Make it so that greyshits don't steal other people's design and have to come up with their own. Also, make circuits more secure to use so people can show off their best without the constant fear of the circuit analyzer.

2018-12-25 17:53 UTC, Carbonhell commented
Jesus christ yes

2018-12-25 22:31 UTC, Shdorsh commented
It's been tested and is now ready

2018-12-26 19:55 UTC, Kawaii-Big-Boss commented
Jesus christ no

2018-12-26 20:04 UTC, Carbonhell commented
Id locked doesn't mean only the id owner can use the circuit, but rather that the circuit code cannot be scanned

2018-12-26 20:05 UTC, Kawaii-Big-Boss commented
So unnecessary gatekeeping to encourage "creativity" and "experimentation" even though 90% of this shit just comes from a discord. Okay.

2018-12-26 20:07 UTC, Shdorsh commented
it enables people to learn how to use circuits themselves instead of copypasting it, which will have its nerf to be only accessible a slight bit later in round on my next pr

2018-12-26 20:08 UTC, Carbonhell commented
what's the point of that
If the code is public you can easily get access to it too
plus idlocking only stops the analyzer from working,if it is only idlocked you can simply check it normally and see what circuits it's made of

2018-12-26 20:08 UTC, Kawaii-Big-Boss commented
Is copypasting even a bad thing, really? The creative people who take the time to learn circuits will be able to do more than the copypastes, whereas those who don't can only use the machines they've been told about.
I fail to see why this is a problem or a necessary inclusion. It just seems like a way to make circuitry an even bigger secret club and circlejerk.

2018-12-26 20:10 UTC, Shdorsh commented
My theory is: copypasting isn't bad, copypasting instantly is

2018-12-26 20:13 UTC, Carbonhell requested changes

2018-12-26 20:13 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/core/assemblies.dm
> +				idlock = debugger.idlock
This being a ref can cause GC problems and i think it is not the proper way to implement this idea
A better one would be a simple locking circuit that locks/unlocks the assembly when pulsed,let the user choose how (keypad,id,etc)

2018-12-26 20:13 UTC, Kawaii-Big-Boss commented
Now, I'm not against that, but
>Make it so that greyshits don't steal other people's design and have to come up with their own. Also, make circuits more secure to use so people can show off their best without the constant fear of the circuit analyzer.
If you want to just add a typing delay or something that'll slow down the rate of copypasting circuits, then whatever I guess?
But this is clearly not the intended goal.

2018-12-26 20:14 UTC, Shdorsh commented
the fact that you do it instantaneously gets you direct access to what would have else been a few minutes of work. making it available later in the round by needing more research points would be nice. also, a circuit club? you can find some code on various discords that lets you learn the basics

2018-12-26 20:15 UTC, Kawaii-Big-Boss commented
Let the people have the circuits, not the club! We SEIZE your circuit properties, damn it!

2018-12-26 20:16 UTC, Shdorsh commented
it's only closed source if the people decide to id-lock, even with the pr implemented. if people had the intent to go around sharing cancer to ruin the station, nothing on this pr would stop them, i'm merely giving them the possibility to not do so.

2018-12-26 20:18 UTC, Kawaii-Big-Boss commented
And I say that possibility shouldn't be there at all. If you're going to make stupid machines, you run the "risk" of other people using them as well. This goes for pretty much anything in the game. Atmos is one such good example, where you can't exactly "hide" all of the pipes running around.

2018-12-26 20:18 UTC, Shdorsh commented
also, the slowed down copying will be another pr. the instant cloning disk will still be available, there will just be another rapid cloning disk, that takes the instant one's current place and the instant will cost a few more research points

2018-12-26 20:21 UTC, Shdorsh commented
if you know how it works and learned some circuitry, you should be able to recreate it yourself, no? well, we'll see what the greater audience has to say on this issue.

2018-12-26 20:56 UTC, DaydreamPuppeh commented
Honestly, I think this will make people use circuits less often. -1

2018-12-26 23:05 UTC, HideAndSeekLOGIC commented
+1 some circuits are too strong for some greytide to just scan and use forever

2018-12-27 00:29 UTC, Carbonhell commented
@HideAndSeekLOGIC this pr is not aimed at preventing that, it's to allow nice big circuits to be done and people to always know who did it

If a circuit is overpowered it must be nerfed

2018-12-27 00:41 UTC, DaydreamPuppeh commented
Switching to a +1. I misunderstood the point of this

2018-12-27 00:50 UTC, Carbonhell commented
Tbh idlocking sounds fine,it pushes people towards actually understanding a circuit rather than copypasting code. But i cannot help but feel that sealing may be a bit too op,considering there is no counter anyhow.

2018-12-27 00:52 UTC, Shdorsh commented
There would be a way if we made the circuit reopenable but have a chance to destroy pin connections. I'd make it roll a prob(30) chance for each circuit in the assembly to remove all its connections.

2018-12-27 03:05 UTC, Kawaii-Big-Boss commented
![free shrug](https://user-images.githubusercontent.com/33744849/50463498-2db42c80-095a-11e9-9ef7-04b001bfa22d.jpg)
Honestly I'm just in the party that hates Circuits' entire existence.

>this pr is not aimed at preventing that, it's to allow nice big circuits to be done and people to always know who did it

Encouraging meta through code, are we Carbon?

2018-12-27 09:37 UTC, Carbonhell commented
what does that mean, meta is unrelated to this,it has no effect whatsoever
But say i do some sort of big circuit to help medics,  but i want to keep the code private to avoid it being replicated and filled with some bad chems, this PR would help me
Your reasonings apply for sealing, i agree it is a bit too op right now, but id locking is fine really, it pushes people interested in how a circuit works to actually use their heads and see how it works

2018-12-27 11:26 UTC, ghost commented
make people unable to directly get the "source code" of the circuit, but let them unseal the circuit and manually see how it works

2018-12-27 17:53 UTC, Shdorsh commented
@zamolxius that's just what id-lock does: turns source code ungettable. however, that would mean that people could still just take the circuit, open it up and get a general understanding of it. that's why there's sealing.

2018-12-29 22:42 UTC, Shdorsh commented
From the feedback judging, seems like people who use circuitry are alright with it. I'll just quickly do something with weakrefs and tweak sealing a bit and then it'll be done.

2019-01-02 15:27 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/core/assemblies.dm
> +				idlock = debugger.idlock
resolved due to usage of weakref (it's in the debugger's code: stores all the refs to weakrefs). just gimme some time to fix the printers so they do the same

2019-01-02 16:02 UTC, Shdorsh commented
It's done.

2019-01-10 15:46 UTC, DeltaFire15 commented
What about emags being used on the circuit?

2019-01-10 17:23 UTC, Shdorsh commented
No emagging circuits currently in existence.

2019-01-19 09:56 UTC, Carbonhell commented
Idlocking is fine, but sealing may be too op. If you unify both, you have a total closedsource bot and that is definitely bad, as goyon said. Either make downsides for the sealing process (for example, you can unseal with a welder but it breaks random pins and such, perhaps), or perhaps let people choose between one or the other, but not both, not sure.
Once the required nerf is in, +1

2019-01-19 13:10 UTC, Shdorsh commented
@Carbonhell that's what I did on the last update, prob(50) to remove the pin connections for each circuit in the assembly.

2019-02-11 14:17 UTC, t-f-w commented
+1

2019-02-20 19:20 UTC, GuyonBroadway approved these changes
Well this looks ok I think.

2019-02-21 12:18 UTC, Carbonhell approved these changes

2019-02-21 12:18 UTC, merged