Liquids - The Moistening
HippieStation/HippieStationdeprecated2020 pull request #10426
Opened 2019-01-20 04:18 UTC by steamp0rt

:cl: steamp0rt
add: Liquids are back!
/:cl:

i'm too lazy to map in drains, someone else do that plz

2019-01-20 04:19 UTC, Manly-Dwarf commented
+1

2019-01-20 04:19 UTC, HideAndSeekLOGIC commented
wow holy shit +1

2019-01-20 04:22 UTC, TheMeatGod commented
+1

2019-01-20 04:26 UTC, yoyobatty commented
Greatly reduce the amount of liquid spawned, 100 units should only create a tiny puddle.

Also see if you can port the pool to using liquid code ...

2019-01-20 04:28 UTC, ghost commented
@yoyobatty That'd nerf it into the ground of being a near-useless mechanic, especially since drains in the hall should eliminate the good ol' "flood the halls" tactic

2019-01-20 05:16 UTC, steamp0rt commented
Also, I was thinking about porting the pool

2019-01-20 06:07 UTC, Lxtoofonea commented
+100, yes please

2019-01-20 06:16 UTC, HideAndSeekLOGIC commented
@steamp0rt I'd suggest still decreasing the amount, it'd probably be for the best

2019-01-20 12:54 UTC, Carbonhell commented
I remember liquids being one of the worst pain in the ass in the history of our server, by slowing down everyone, although their effect was indeed worsened by goofball's scrubber random event pr. I still do not think liquids are a good/fun/engaging mechanic anyhow, can anyone kindly explain with text what they do,how they affect the crew etc? Perhaps @steamp0rt since the PR is yours??

2019-01-20 15:54 UTC, steamp0rt commented
@Carbonhell 

_HONK_
_HoS and 5 security officers slip on a puddle of banana juice_
***HONK***

2019-01-20 17:05 UTC, GuyonBroadway submitted a review, later dismissed

2019-01-20 17:05 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +#define REAGENT_TO_DEPTH 2
honestly 2u of reagent causing something you can drown in is a little silly, might wanna up this to 10 you it takes more than a can of cola to make a swimming pool.

2019-01-20 17:05 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +		if(C.getStaminaLoss() < 85)
First of all  This only checks if your stamina is LESS than 85, which is the wrong way round. Second of all, just loose the stamina loss altogether as it's one of the main reasons liquids were so shitty. It adds nothing of value to the game and just pisses people off.

2019-01-20 17:05 UTC, GuyonBroadway commented on hippiestation/code/modules/research/designs/autolathe_designs.dm
> +/datum/design/drain
I feel that you should just be able to craft these in hand so as to make draining the station much easier, bonus points if you can add prefabricated drains to the RCD/RPD

2019-01-20 17:12 UTC, steamp0rt commented on hippiestation/code/game/objects/liquid.dm
> +#define REAGENT_TO_DEPTH 2
a depth of 1 is far from being able to drown

2019-01-20 17:12 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +#define REAGENT_TO_DEPTH 2
yeah but in that sense 20u of something will make depth 10 in a 1 tile square which very much is.

2019-01-20 17:40 UTC, steamp0rt commented on hippiestation/code/modules/research/designs/autolathe_designs.dm
> +/datum/design/drain
Added it to RPD

2019-01-20 17:40 UTC, steamp0rt commented on hippiestation/code/game/objects/liquid.dm
> +		if(C.getStaminaLoss() < 85)
Removed

2019-01-20 17:42 UTC, steamp0rt commented on hippiestation/code/game/objects/liquid.dm
> +#define REAGENT_TO_DEPTH 2
Ok i've bumped it to 7

2019-01-20 17:53 UTC, DaydreamPuppeh commented
I remember there being issues with liquids before. They pushed people and caused stamina damage which knocked people down. With new liquids, can you fix this issue?

2019-01-20 17:57 UTC, steamp0rt commented
@DaydreamPuppeh i've already removed stamina damage. Not sure about pushing.

2019-01-20 18:33 UTC, steamp0rt commented on hippiestation/code/game/turfs/turf.dm
> +
Fixed

2019-01-20 19:17 UTC, uBadush commented
Nice I will have fun with this

2019-01-20 20:59 UTC, bardofrage commented
I'm not really sure about this, I remember it being a pretty unfun mechanic, it's also pretty silly that you can flood a portion of a hallway using a beaker full of water.

2019-01-20 22:54 UTC, GuyonBroadway commented
@bardofrage  we're tweaking it to be less shit. I.E reducing the amount of fluid created per unit of stuff. Maybe even tweak it so you don't splash and start drowning unless the height difference is bigger than just tile to tileless floor.

2019-01-20 22:55 UTC, GuyonBroadway commented
Not to mention it no longer pushes you around or causes stamina damage just for wading through it.

2019-01-21 09:10 UTC, yobob591 commented
it should push and knock you down if its high pressure liquid or a large amount, also sealab map when +1

2019-01-21 11:14 UTC, GuyonBroadway commented on hippiestation/code/modules/research/designs/autolathe_designs.dm
> +/datum/design/drain
Mind adding hand craftable drain frames too? Just so even the most basic crew can have some resolve vs fluid floods even if it's tedious.

2019-01-21 14:10 UTC, GuyonBroadway commented
Putting a DO NOT MERGE on this till drains are mapped in.

2019-01-21 15:37 UTC, k-k-karma commented
You are not one to decide - the admins are

2019-01-21 15:38 UTC, uBadush commented
Sheit

2019-01-21 15:53 UTC, GuyonBroadway commented
I'm still going to be a stick in the mud about this as without mapped drains fluids will get real annoying real fast.

2019-01-21 15:53 UTC, k-k-karma commented
they evaporate themselvews

2019-01-21 15:54 UTC, k-k-karma commented
and that's the FUN of it just make a drain

2019-01-22 01:55 UTC, steamp0rt commented
I've mapped in drains. Lots of em.

2019-01-22 02:11 UTC, Carbonhell commented
Confirming my -1.

2019-01-22 06:28 UTC, GuyonBroadway requested changes

2019-01-22 06:28 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +#define REAGENT_TO_DEPTH 5
Listen here you sneaky little sod, change this to 10 like I told you and don't change it back when nobody is looking.

I don't care if you think it nerfs it too hard, the biggest complaint about fluids is how a 30u beaker causes a flood. You change this or no fluids are we clear?

2019-01-22 10:37 UTC, GuyonBroadway reviewed
You might bitch but its the number 1 complaint from the players and headmins so it is what it is I'm afraid...

Better to release it nerfed and buff later.

2019-01-22 19:20 UTC, GuyonBroadway submitted a review, later dismissed

2019-01-22 19:28 UTC, GuyonBroadway requested changes

2019-01-22 19:28 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +		if(old.elevation > T.elevation && C.mob_has_gravity())
IMO the fact that going from a tile with a floor on it to an tile-less floor will stun you is pretty shit, we should make this something like (old.elevation+5) so you only get stunned if you fall in the pool. 

Not to mention I think this means if you build a bridge of tables into the middle of a pool of water and walk down it you will still fall in the water while walking on the tables.

2019-01-22 19:35 UTC, GuyonBroadway submitted a review, later dismissed

2019-01-22 19:36 UTC, GuyonBroadway commented
Ok that's better but before we consider testmerging again i want to test this locally personally.

2019-01-22 19:39 UTC, steamp0rt commented
@GuyonBroadway dew it

2019-01-22 19:39 UTC, ghost commented
the quicker the better

2019-01-22 19:42 UTC, GuyonBroadway commented
Even once I confirm this is less terrible we're going to need a test-merge or two because hell if I don't trust this to be as popular as we might think.

2019-01-22 19:57 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +		if(old.elevation+5 > T.elevation && C.mob_has_gravity())
This didn't work, investigating reason.

2019-01-22 21:36 UTC, GuyonBroadway requested changes

2019-01-22 21:36 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +				C.losebreath = max(C.losebreath += 0.4, 8)
this here line is dumb as it means if you stick your head under a puddle and come right back up you can still lose a shittone of oxyloss.

```suggestion
				C.losebreath += 1 //Every second under water is a second not breathing
```

2019-01-22 21:36 UTC, GuyonBroadway commented on hippiestation/code/game/objects/liquid.dm
> +		if(old.elevation+5 > T.elevation && C.mob_has_gravity())
the reason is guyon a dumbo and got it the wrong way round
```suggestion
		if(old.elevation > T.elevation+5 && C.mob_has_gravity())
```

2019-01-22 21:40 UTC, GuyonBroadway submitted a review, later dismissed

2019-01-22 21:41 UTC, GuyonBroadway commented
This is tested and is ok for a **T E S T M E R G E**


Not a full merge, just a test merge, this is a big feature that needs player feedback.

2019-01-22 23:24 UTC, GuyonBroadway requested changes

2019-01-22 23:24 UTC, GuyonBroadway commented on hippiestation/code/controllers/subsystem/liquids.dm
> +	wait = 5
These were edited back when we had the old rubbish server because we thought fluids caused lag. Now we have the goodbox. Find out whst the wait and priority for atmos gasses is and copy those and we'll see how it goes.

2019-01-22 23:53 UTC, steamp0rt commented on hippiestation/code/controllers/subsystem/liquids.dm
> +	wait = 5
```SUBSYSTEM_DEF(air)
	name = "Atmospherics"
	init_order = INIT_ORDER_AIR
	priority = FIRE_PRIORITY_AIR
	wait = 5```

2019-01-23 00:05 UTC, yoyobatty submitted a review, later dismissed

2019-01-23 06:08 UTC, yobob591 commented
+1 dihydrogen monoxide poisoning

2019-01-23 06:14 UTC, HideAndSeekLOGIC commented
10/10 would murder 3 people in 10 seconds with a beaker of fluorosulfuric acid again

2019-01-23 07:23 UTC, earthmoonjune commented
![death](https://user-images.githubusercontent.com/25476136/51589719-773a5d80-1ead-11e9-9ac5-e118832ad103.jpg)
-1

2019-01-23 10:21 UTC, GuyonBroadway commented
Do we have to blacklist lube? A lubeflood is always funny

2019-01-23 10:38 UTC, steamp0rt commented
i'll make a seperate blacklist for just chempiles

2019-01-24 22:18 UTC, optimumtact commented on hippiestation/code/game/objects/liquid.dm
> +	Originally coded by Banthebantz, now coded by steamport.
you didn't change anything in this file

2019-01-24 22:18 UTC, optimumtact commented on hippiestation/code/modules/admin/verbs/liquids.dm
> + | |___| (_) | (_| |  __/ (_| | | |_) | |_| |
nothing in this file

2019-01-24 22:18 UTC, optimumtact commented on hippiestation/code/modules/admin/verbs/spaceliquids.dm
> + | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_
or this one

2019-01-24 22:19 UTC, steamp0rt commented on hippiestation/code/modules/admin/verbs/liquids.dm
> + | |___| (_) | (_| |  __/ (_| | | |_) | |_| |
stfu loser

2019-01-24 22:19 UTC, k-k-karma commented on hippiestation/code/modules/admin/verbs/liquids.dm
> + | |___| (_) | (_| |  __/ (_| | | |_) | |_| |
except all those verbs?

2019-01-24 22:19 UTC, steamp0rt commented on hippiestation/code/game/objects/liquid.dm
> +	Originally coded by Banthebantz, now coded by steamport.
https://github.com/HippieStation/HippieStation/pull/5151

2019-01-24 22:19 UTC, k-k-karma commented on hippiestation/code/modules/admin/verbs/spaceliquids.dm
> + | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_
more verbs

2019-01-24 22:20 UTC, k-k-karma commented on hippiestation/code/game/objects/liquid.dm
> +	Originally coded by Banthebantz, now coded by steamport.
he did, check blame. fixed bugs and shit, fuck off faggot

2019-01-24 22:26 UTC, optimumtact commented on hippiestation/code/modules/admin/verbs/liquids.dm
> +*/
_____          _          _   ____                 
  / ____|        | |        | | |  _ \                
 | |     ___   __| | ___  __| | | |_) |_   _          
 | |    / _ \ / _` |/ _ \/ _` | |  _ <| | | |         
 | |___| (_) | (_| |  __/ (_| | | |_) | |_| |         
	
This conversation was marked as resolved by steamp0rt
  \_____\___/ \__,_|\___|\__,_| |____/ \__, |     _   
  / ____| |                             __/ |    | |  
 | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_ 
  \___ \| __/ _ \/ _` | '_ ` _ \| '_ \ / _ \| '__| __|
  ____) | ||  __/ (_| | | | | | | |_) | (_) | |  | |_ 
 |_____/ \__\___|\__,_|_| |_| |_| .__/ \___/|_|   \__|
                                | |                   
                                |_|

2019-01-24 22:27 UTC, optimumtact requested changes
_____          _          _   ____                 
  / ____|        | |        | | |  _ \                
 | |     ___   __| | ___  __| | | |_) |_   _          
 | |    / _ \ / _` |/ _ \/ _` | |  _ <| | | |         
 | |___| (_) | (_| |  __/ (_| | | |_) | |_| |         
	
This conversation was marked as resolved by steamp0rt
  \_____\___/ \__,_|\___|\__,_| |____/ \__, |     _   
  / ____| |                             __/ |    | |  
 | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_ 
  \___ \| __/ _ \/ _` | '_ ` _ \| '_ \ / _ \| '__| __|
  ____) | ||  __/ (_| | | | | | | |_) | (_) | |  | |_ 
 |_____/ \__\___|\__,_|_| |_| |_| .__/ \___/|_|   \__|
                                | |                   
                                |_|

2019-01-24 22:27 UTC, optimumtact commented on hippiestation/code/modules/admin/verbs/spaceliquids.dm
> +  \_____\___/ \__,_|\___|\__,_| |____/ \__, |     _
_____          _          _   ____                 
  / ____|        | |        | | |  _ \                
 | |     ___   __| | ___  __| | | |_) |_   _          
 | |    / _ \ / _` |/ _ \/ _` | |  _ <| | | |         
 | |___| (_) | (_| |  __/ (_| | | |_) | |_| |         
	
This conversation was marked as resolved by steamp0rt
  \_____\___/ \__,_|\___|\__,_| |____/ \__, |     _   
  / ____| |                             __/ |    | |  
 | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_ 
  \___ \| __/ _ \/ _` | '_ ` _ \| '_ \ / _ \| '__| __|
  ____) | ||  __/ (_| | | | | | | |_) | (_) | |  | |_ 
 |_____/ \__\___|\__,_|_| |_| |_| .__/ \___/|_|   \__|
                                | |                   
                                |_|

2019-01-24 22:27 UTC, optimumtact commented on hippiestation/code/modules/reagents/chemistry/reagents.dm
> +							W.depth = CLAMP(W.depth + (c.reagents.total_volume / REAGENT_TO_DEPTH), 0, MAX_INITIAL_DEPTH)
_____          _          _   ____                 
  / ____|        | |        | | |  _ \                
 | |     ___   __| | ___  __| | | |_) |_   _          
 | |    / _ \ / _` |/ _ \/ _` | |  _ <| | | |         
 | |___| (_) | (_| |  __/ (_| | | |_) | |_| |         
	
This conversation was marked as resolved by steamp0rt
  \_____\___/ \__,_|\___|\__,_| |____/ \__, |     _   
  / ____| |                             __/ |    | |  
 | (___ | |_ ___  __ _ _ __ ___  _ __  |___/ _ __| |_ 
  \___ \| __/ _ \/ _` | '_ ` _ \| '_ \ / _ \| '__| __|
  ____) | ||  __/ (_| | | | | | | |_) | (_) | |  | |_ 
 |_____/ \__\___|\__,_|_| |_| |_| .__/ \___/|_|   \__|
                                | |                   
                                |_|

2019-01-24 22:48 UTC, GuyonBroadway submitted a review, later dismissed
I don't mind you giving yourself inline credit, although supposedly ~~github~~ changelog credit is enough for AGPL to count, this is a matter for hippie as a whole and probably needs a ruling by yoyo and gregg but please don't make your credit lines a massive fuckoff ascii thingy, just your name will do, preferably your ckey.

2019-01-24 22:48 UTC, GuyonBroadway commented on hippiestation/code/modules/admin/verbs/liquids.dm
> +/*
Credit in code is one thing but no giant ascii names please, you are not a 2010 era keygen maker.

2019-01-24 22:48 UTC, GuyonBroadway commented on hippiestation/code/modules/admin/verbs/spaceliquids.dm
> +/*
Credit in code is one thing but no giant ascii names please, you are not a 2010 era keygen maker.

2019-01-24 22:48 UTC, GuyonBroadway commented on hippiestation/code/modules/admin/verbs/spaceliquids.dm
> +  / ____| |                             __/ |    | |
Credit in code is one thing but no giant ascii names please, you are not a 2010 era keygen maker.

2019-01-24 22:48 UTC, GuyonBroadway commented on hippiestation/code/_onclick/hud/parallax.dm
> +/*
Credit in code is one thing but no giant ascii names please, you are not a 2010 era keygen maker.

2019-01-24 22:50 UTC, k-k-karma commented on hippiestation/code/modules/admin/verbs/liquids.dm
> +/*
no, it's fine imo. don't request changes because of your opinion.

2019-01-24 22:51 UTC, GuyonBroadway commented
Formatting is my business! Creditng himself inline is fine doing it in a dumb way isnt.

2019-01-24 22:52 UTC, k-k-karma commented
It's completely fine under AGPL and is funny

2019-01-24 22:52 UTC, steamp0rt commented
you can take your formatting and stick it up yer ass

2019-01-24 22:52 UTC, GuyonBroadway commented on hippiestation/code/_onclick/hud/parallax.dm
> +/*
Not to mention you credit yourself twice with this silly logo.

2019-01-24 22:55 UTC, GuyonBroadway submitted a review, later dismissed
CHANGE IT!!

2019-01-24 23:26 UTC, ghost commented
no

2019-01-24 23:28 UTC, GuyonBroadway commented
Just sayin lad, daddie yoyo and mommy carbonhell might not like this and if either of them hit the -1 this pr is dead in the water.

2019-01-24 23:30 UTC, ghost commented
i'll remove it if someone who matters says to

2019-01-24 23:30 UTC, optimumtact commented
This conversation was marked as resolved by steamp0rt

2019-01-24 23:31 UTC, steamp0rt commented
@yoyobatty please repoban him, he's just doing low effort spam

2019-01-24 23:32 UTC, k-k-karma commented
i have been gitbanned from TG for less

2019-01-25 00:35 UTC, alexkar598 commented on hippiestation/code/game/objects/liquid.dm
> +	Originally coded by Banthebantz, now coded by steamport.
You cannot re license code which is held by the copyright of someone else,this is an entirely DIFFERENT license than the hippiestation one,as such you are illegally re licensing the code which copyright is held by banthebantz

2019-01-25 00:38 UTC, k-k-karma commented
![image](https://user-images.githubusercontent.com/44510065/51717623-79312780-2039-11e9-95aa-d106106c010e.png)
lol

2019-01-25 00:38 UTC, steamp0rt commented
adding an AGPLv3 header to AGPLv3 code isn't re-licensing lol

2019-01-25 00:39 UTC, alexkar598 commented
Yeah,it’s fine,nvm what I said,while your licensing it in another thing it’s fine since it’s compatible

2019-01-25 01:07 UTC, Carbonhell commented
I already -1ed this

2019-01-25 01:11 UTC, steamp0rt commented
oh shit it's someone who matters

2019-01-25 01:11 UTC, steamp0rt commented
should i remove the ascii thing, carbon

2019-01-25 01:14 UTC, Carbonhell commented
no like the problem are liquid themself, i remember them being one of the worst mechanic i have ever seen, i will try to play a test round with this testmerged and see if it is actually different than before. I honestly doubt though.

2019-01-25 01:58 UTC, AnthonyJNgo commented
Is carbon confirming giant ascii credits are good to go? Excellent

2019-01-25 09:57 UTC, Carbonhell commented
@steamp0rt listen to what the maintainers say or write a decent reason as for why you aren't doing what they say ("i'll remove it if someone who matters says to") or I won't let any PR from you be merged anymore from now on

2019-01-25 11:01 UTC, k-k-karma commented
the ascii credits are fine, they're his attribution and we have an issue with code being stolen w/o credit and even hidden to look like it was w/o credit

2019-01-25 11:16 UTC, GuyonBroadway commented
I dispute that assertation as yogs added credits to thier code after being told not including our names could be a violation of agpl.

Tg also updated thier wheelchair pr accordingly.

Twas an earnest mistake that they corrected.

2019-01-25 11:38 UTC, steamp0rt commented
ascii things removed


@optimumtact needs to find something else to mock now

2019-01-25 23:28 UTC, optimumtact commented
@steamp0rt there's always you

2019-01-27 09:30 UTC, danzargar commented
@optimumtact Your the one who needs mocking 4dplaner

2019-01-27 15:51 UTC, steamp0rt commented
^

2019-01-27 21:32 UTC, optimumtact commented
it's planner

2019-01-31 10:20 UTC, Jujumatic commented
lol guys remember when we had liquids and unstable mutagen would give you mutations every tick so after wading through 1 square you became horribly disabled? it was kinda funny though. but no. liquids only work in dwarf fortress go away

2019-01-31 10:40 UTC, GuyonBroadway commented
To be fair you can do the same with mutagen floor tiles.

And mutagen can be blacklisted from fluids.

2019-02-20 16:08 UTC, Carbonhell commented
Stale.

2019-02-20 16:08 UTC, closed without merging

2019-02-20 21:38 UTC, optimumtact commented
This conversation was marked as resolved by steamp0rt

2019-02-20 22:10 UTC, GuyonBroadway commented
@optimumtact go back to puttin' yer willy in the commit history for the sake of a dumb joke.