Xenomorph can be tamed
HippieStation/HippieStationdeprecated2020 pull request #10436
Opened 2019-01-20 19:55 UTC by xTrainx

:cl: xTrainx
add: Added the ability to feed Xenos with docility potions, which effectively mindslave the xeno to the feeder, this takes about 7 seconds
add: you can name a succefully tamed xeno
/:cl:

[why]:  currently the only reason to make a xeno in xenobiology is in a loss loss state. If the xenobiologist manages to to breed, grow and kill the the xeno, then the xeno player only got to sit on a box wiouth much to do. If the xeno manages to break enclosure, then the xenobiologist gets a bwoink. All in all, the risk is too high for the reward in my opinion. 

keep in mind that for someone to succefully tame a xeno, they would have to either be willing or they would have to somehow incapacitate them for 7 seconds, so this potions can't be used in an uncontrolled ambient. 

Anyway, with this xeno players would have a bit more freedom and could actually roam the station a bit, although at the risk of being shot to death, so they should probably stay close to the master. Although it doesn't bound the xeno and the xenobiologist some what, by default, no one learns a new language, so the xenobiologist would need to find other ways to give orders to the xenobiologist (but if he can harvest other xenos for the hivemind organ, they would be able to communicate just fine)

if the bounded xeno happens to be a queen, it is my opinion that the remaining xenos in the station are to follow their command (xenos are a team antag, technically speaking), although they would have a bit more freedom, as in, they don't need to directly listen to the tamer, and if they are attacked by someone they don't have to just bite the bullet, even if the queen tells her to just die.

while i believe all the reasons i stated are true, the reason im committing this boils down to i think it would be pretty cool, also if this gets passed i would try to make some xenos buckabled ( at leasts queen and princess)

2019-01-20 20:09 UTC, Carbonhell requested changes

2019-01-20 20:09 UTC, Carbonhell commented on hippiestation/code/modules/research/xenobiology/xenobiology.dm
> +		return ..()
This will also make the "it only works on slimes and xenos" message appear

2019-01-20 20:09 UTC, Carbonhell commented on hippiestation/code/modules/research/xenobiology/xenobiology.dm
> +	to_chat(user, "<span class='notice'>hold still while you feed the potion.</span>") //warns about the taming process starting
Hold

2019-01-20 20:09 UTC, Carbonhell commented on hippiestation/code/modules/research/xenobiology/xenobiology.dm
> +		to_chat(target,"<span class='userdanger'> You MUST obey any command given to you by your master (that doesn't violate any rules). Unless your master specifically tells you so, You are not to act li
Weird initial space in the string

2019-01-20 20:09 UTC, xTrainx commented
incidentally, when testing, i named my xenomorph lifts-her-tails

2019-01-20 20:18 UTC, xTrainx commented
if a xeno is docilified, objetives would take priority over queen loyalty, xenos wouln't have any objetives that take priorty, although i would argue that unless specifically told by the master they shouldn't rambo the nest themselve or otherwise put it to danger, but i feel it would be at admin discration...

also not everything in this game is to put your pee pee in

2019-01-20 20:44 UTC, DaydreamPuppeh commented
+1

2019-01-20 21:34 UTC, HideAndSeekLOGIC commented
The love potion exists for exactly this purpose. If you want to add a specific effect to tame xenos, add it to that

2019-01-20 21:46 UTC, HideAndSeekLOGIC commented
Also, I need to make Xenia harder to get, pinks are wayyy to easy to speedrun and cuck the station with

2019-01-21 09:08 UTC, yobob591 commented
does love potion work on player controlled mobs? if not +1 pet xenos are cool af

2019-01-21 09:09 UTC, HideAndSeekLOGIC commented
@yobob591 yes, but sometimes the mob in question tries to erp

2019-01-22 02:14 UTC, Carbonhell commented
How does the love potion work?is it the same of this?

2019-01-22 02:20 UTC, HideAndSeekLOGIC commented
Kind of, pretty much means that the alien is enslaved to the potion user.

2019-01-22 02:54 UTC, xTrainx commented
it adds a memory to the mob's mind saying that they are in love, only holds water in MRP-HRP servers tbh

2019-01-25 04:45 UTC, Maroonenahmoron commented
There needs to be either a way to incapacitate xenos, or perhaps give the potion to them via the console.

2019-01-26 00:03 UTC, xTrainx commented
thanks to @steamp0rt nerf, they normal alium (including larvas) can by stunned and tamed, but taming a queen probably requires a bit of creative thinking

2019-02-09 05:19 UTC, HideAndSeekLOGIC commented
@Maroonenahmoron @xTrainx beepsky smash or chloral hydrate will knock em out

2019-02-21 12:20 UTC, Carbonhell commented
sure +1

2019-02-21 12:25 UTC, Carbonhell commented on hippiestation/code/modules/research/xenobiology/xenobiology.dm
> +		protect_objective.explanation_text = "Protect [user], your Master. Obey any command given by them, do not do anything that would harm then, and do not kill others as that could give him problems (u
Maybe specify whether this takes precedence over queen's orders or not

2019-02-21 12:26 UTC, Carbonhell commented on hippiestation/code/modules/research/xenobiology/xenobiology.dm
> +		var/newname = copytext(sanitize(input(user, "Would you like to give the Xeno a name?", "Name your new pet", "pet Xeno") as null|text),1,MAX_NAME_LEN)
i feel like there's a better way than using those 3 procs

2019-02-21 13:49 UTC, Maroonenahmoron commented
I still feel neutral about this, what can the xenos do if they're being hunted/targeted by the crew although their master might have good intentions? How will the tamed xenos interact with ones that aren't tamed (random event xenos)? There should be a way for people to differentiate between regular and tamed xenos.

2019-02-21 14:11 UTC, Pyko1 commented
in before lusty xenomorph maids

2019-02-21 14:50 UTC, t-f-w commented
i mean i guess +1

2019-02-23 08:04 UTC, Manly-Dwarf commented
n

2019-02-23 10:23 UTC, Jujumatic commented
is this stale?

2019-02-23 23:32 UTC, HideAndSeekLOGIC commented
@Maroonenahmoron the xenobiologist can just say over the radio that the ayys are friendly. He can also give them the bluespace slime potion.

2019-02-24 04:21 UTC, Maroonenahmoron commented
@HideAndSeekLOGIC Not everybody is going to trust messages on common comms that the current aliens running around are friendly. As for bluespace slimes, they shouldn’t be a necessity for marking them different to regular aliens.

2019-02-25 09:30 UTC, TheMeatGod commented
What if examining the xeno, it showed a message like “this xeno in particular looks less threatining”

2019-03-05 09:09 UTC, Jujumatic commented
Stale, re-open if you still want to work on it

2019-03-05 09:09 UTC, closed without merging