Revert "[MIRROR] Abductor camera console eyes are now visible to ghosts"
HippieStation/HippieStationdeprecated2020 pull request #10480
Opened 2019-01-24 21:30 UTC by Manly-Dwarf

Reverts HippieStation/HippieStation#10278

2019-01-24 21:35 UTC, k-k-karma commented
why

2019-01-25 07:30 UTC, GuyonBroadway requested changes

2019-01-25 07:30 UTC, GuyonBroadway commented on code/modules/antagonists/abductor/machinery/camera.dm
>  	eyeobj.icon = 'icons/mob/cameramob.dmi'
This isn't even modular

2019-01-26 14:20 UTC, Carbonhell commented
???

2019-01-26 14:26 UTC, closed without merging