Rebalances shields properly.
HippieStation/HippieStationdeprecated2020 pull request #10659
Opened 2019-02-15 06:35 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
add: Shields can be wielded to have a 75% block damage only when facing their attacker and at the cost of a free hand.
tweak: Telescopic riot shields now extend with alt click
balance: Shields no longer block projectiles
balance: Shields not including energy based must be wielded to block damage
balance: Shields not including energy based now give you 15 melee, 5 bullet and 15 bomb armor when equipped
balance: Energy shields no longer block damage but will still deflect energy based weapons
balance: Shields now have their block chances reduced by the value of incoming damage
/:cl:

## About The Pull Request
What this does is make energy shields less over fucking powered by ONLY having them deflect projectiles and not have a 50% fucking block which makes them waaay more appropriately balanced. Shields and I mean all of them except energy based ones, give an armor bonus when equipped/held, and will give away a 75% block chance when wielded (two handed) and only when facing said attacker that isn't firing a projectile at you. In addition, the stronger the weapon used against the shield holder, the less likely they are to block the attack. 

## Why It's Good For The Game
Did I mention that this will affect additional arms? Yes, you're forced to sacrifice 2 slots to wield them, and if you stack them with energy shields, you only have one slot free for a gun. The part of it is, you still get insane armor bonus, but the crew can still use shotguns against you without issue. I've considered the nanosuit too when doing this. At worst, the nanosuit has armor mode which is a 50% block to all damage, stacking with the shield, you get a 75% non-projectile, directional block only when held in both hands + an energy shield which deflects energy based weapons. The worst case scenario is you can't effectively use melee weapons and energy based weapon. This is not a problem considering you can use a shotgun and AT WORST with all of this including the shotgun, the most effective this robust nukie has is a 50% block chance with armor! Ta da! Nanosuit with 4 arms, riot and energy shield can still be powerful as fuck (I mean all together it's 44 TC NOT including discounts and guns) but not completely stupidly overpowered, broken and impossible to kill. 

I hope I did this right, I've considered just about every single factor into play here and spent a long time perfecting the code itself, I hope I've covered anything. If there is something that you're not sure about, I prefer if you would ask rather than assume the worst.

2019-02-15 16:41 UTC, JohnMcLaime commented
Couldnt you just elance the dude to one hit kill them, anyway, you ruined it for people who cant get nanosuit and 2 extra arms. 75 block chance only against melee is nothing when you cant use your second arm to fight back.

Would be better if you made it stamina based:
Block chance equals your stamina, your stamina gets drained when you are hit, solves multiple shields in arms abuse.

Even just adding slight slowdown when you wield it would have probably fixed it, as nanosuit is already slow outside of speedmode and wielding multiple shields would make you a turtle thats easy to run away from, grenade etc.

2019-02-15 17:41 UTC, yoyobatty commented
The whole point of this is to nerf shields in general, explosive Lance's will always be a thing, also how would taking stamina damage fix anything? Slowdowns at some point are more lethal than physical damage because you can't simply but a bandage over stamina damage.

2019-02-15 17:51 UTC, Jujumatic requested changes
The shield name is going to pop up twice so fix that ree also a recommendation but not necessary, pls let monkey wield shield, monkey riot army will be hilarious

2019-02-15 17:51 UTC, Jujumatic commented on hippiestation/code/game/objects/items/shields.dm
> +	var/sf = findtext(name," (Wielded)")
Pretty sure there's an extra space with "  (Wielded) ", shouldn't affect anything other than my raging OCD but yeah

2019-02-15 17:51 UTC, Jujumatic commented on hippiestation/code/game/objects/items/shields.dm
> +		name = copytext(name,1,sf)
This will turn into ```copytext(name,1,findtext(name, " (Wielded) ")```, name is going to pop up twice isn't it?

2019-02-15 17:51 UTC, Jujumatic commented on hippiestation/code/game/objects/items/shields.dm
> +		return
I want monkeys to wield shields :,(

2019-02-15 17:56 UTC, k-k-karma commented
Yoyo; you fucking retard - energy shields only block projectiles of energy already; they have a 0% block chance otherwise

2019-02-15 17:59 UTC, yoyobatty commented on hippiestation/code/game/objects/items/shields.dm
> +		name = copytext(name,1,sf)
No? I test my code which is actually copied from the 2 handed code

2019-02-15 18:00 UTC, yoyobatty commented on hippiestation/code/game/objects/items/shields.dm
> +		return
Too much runtimes

2019-02-15 18:03 UTC, yoyobatty commented
Well apparently I missed the return false on hit_reaction under energy shield, I just got told info from goyon so I guess this will make him think I did something related to e shields.

2019-02-16 06:28 UTC, Manly-Dwarf commented
Riot Shields are pure cancer.
+1.

2019-02-20 16:13 UTC, Carbonhell commented
I prefer /tg/'s approach, -1

2019-02-20 19:38 UTC, Lxtoofonea commented
i agree with carbon here -1

2019-02-21 14:17 UTC, t-f-w commented
+1

2019-02-21 21:41 UTC, Carbonhell commented
The mirror rebalance was merged. Is this still needed?

2019-02-23 08:04 UTC, Manly-Dwarf commented
Probably not. The /tg/ changes will do their job, assuming that the telescopic riot shield can break and they don't just ignore .357s.

2019-02-23 10:41 UTC, Jujumatic commented
-1 so leaving this for now

2019-02-23 23:34 UTC, HideAndSeekLOGIC commented
@yoyobatty are you still going through with this or will you close?

2019-02-25 04:04 UTC, HideAndSeekLOGIC commented
@yoyobatty Considering that this has a total of -1 from headmins, I'll probs close this PR this time tomorrow unless you or someone else objects. The TG changes should do what this PR does anyways.

2019-02-25 09:24 UTC, TheMeatGod commented
-1

2019-03-05 02:01 UTC, HideAndSeekLOGIC commented
Few weeks old and no reply from @yoyobatty, it's closing time

2019-03-05 02:01 UTC, closed without merging