Adds healing while asleep
HippieStation/HippieStationdeprecated2020 pull request #10698
Opened 2019-02-19 21:48 UTC by mikolaj007

## Changelog
:cl:
add: You now heal while you sleep.
/:cl:

## About The Pull Request
Adds a chance to heal 1 brute, tox, burn damage per tick while you sleep.
the chance depends on 2 factors:
-if you are sleeping on a bed, a table or anywhere else
-if you are covered by a bedsheet, and the coolness of the bedsheet. (normal bedsheets are ok, bedsheets like clown, mime or medical are better and captain/syndie bedsheet gives the best bonus)

healing ranges from 10% to 40% per tick, 200 of which happen during 40 second sleep.

## Why It's Good For The Game

Gives actual use to dorms and the ability to survive even if the medbay is fucked.
Sleeping lasts 40 seconds of total incapacitation, so you are trading some health for vulnerability.

2019-02-19 21:50 UTC, Jujumatic commented
did you try compiling this? Cool and Supercool aren't defined as anything

2019-02-19 21:51 UTC, mikolaj007 commented
they are defined, just look at files changed. i forgot to add them in the first commit.

2019-02-19 21:53 UTC, Jujumatic submitted a review, later dismissed

2019-02-19 22:38 UTC, mikolaj007 commented
the only thing i see being changed is removing rng and going from % per tick to x heal per 10 ticks

2019-02-19 23:17 UTC, uBadush commented
RNG is bad you could reduce the healing but it happens every tick

2019-02-20 16:20 UTC, WarRage333 commented
I can't really figure it out from code but if you're wearing the bedsheet as a cloak it does not give the benefit?

2019-02-20 18:11 UTC, mikolaj007 commented
@WarRage333 yea, it doesnt give benefit

2019-02-20 18:11 UTC, mikolaj007 commented
also this was my first attempt at modularizing. prolly gonna fix something soon

2019-02-20 18:11 UTC, RafRoq requested changes
I would still like to see a non rng version

2019-02-20 18:12 UTC, mikolaj007 commented
ok

2019-02-20 18:16 UTC, mikolaj007 commented
removed rng

2019-02-20 18:20 UTC, mikolaj007 commented
now its modularized

2019-02-20 18:21 UTC, mikolaj007 commented
welp i fucked up somewhere, brb

2019-02-20 18:34 UTC, mikolaj007 commented
ye, i fucked up somewhere, fixing

2019-02-20 18:40 UTC, mikolaj007 commented
alright, it works now.

2019-02-20 20:02 UTC, Carbonhell commented
Interesting idea, willing to give it a try. +1

2019-02-20 20:07 UTC, k-k-karma commented on hippiestation/code/datums/status_effects/debuffs.dm
> +		human_owner.drunkenness *= 0.997 //reduce drunkenness by 0.3% per tick, 6% per 2 seconds
this is 0.003%

2019-02-20 20:08 UTC, mikolaj007 commented on hippiestation/code/datums/status_effects/debuffs.dm
> +		human_owner.drunkenness *= 0.997 //reduce drunkenness by 0.3% per tick, 6% per 2 seconds
this isnt my code, i just copy pasted that part from the original sleep code.

2019-02-21 12:43 UTC, TheMeatGod commented
+1

2019-02-21 12:44 UTC, mikolaj007 commented
ensured you never lose health due to sleep and nerfed space sleep.
ready to merge

2019-02-21 14:08 UTC, t-f-w commented
Does sound neat, +1

2019-02-22 10:43 UTC, Carbonhell requested changes

2019-02-22 10:43 UTC, Carbonhell commented on hippiestation/code/datums/status_effects/debuffs.dm
> +	if((locate(/obj/structure/bed) in owner.loc)) //if in bed +10%
this doesn't check if you're actually buckled to a bed,even being on the same tile of a bed works

2019-02-22 10:43 UTC, Carbonhell commented on hippiestation/code/datums/status_effects/debuffs.dm
> +	for(var/i in SuperCool)
what's the point of having two separate lists if there's no difference between them?

2019-02-22 10:43 UTC, Carbonhell commented on hippiestation/code/datums/status_effects/debuffs.dm
> +	//if(prob(probability))	//non rng edit. if we bring back rng, just tab the adjusts and make them -1
just remove this, if someone wants to add probability it's easy

2019-02-22 10:46 UTC, mikolaj007 commented on hippiestation/code/datums/status_effects/debuffs.dm
> +	if((locate(/obj/structure/bed) in owner.loc)) //if in bed +10%
because you still are immobilized and horizontal for the duration.
If you dont buckle yourself, your loss if you get vented into space or whatever

2019-02-22 10:48 UTC, mikolaj007 commented on hippiestation/code/datums/status_effects/debuffs.dm
> +	for(var/i in SuperCool)
Cool stuff gives +5, supercool stuff gives +10(total)      
Supercook stuff currently is the syndie and the captain bedsheet
I didnt know how to merge a list so i went the easy way.

2019-02-22 11:04 UTC, Carbonhell submitted a review, later dismissed

2019-02-22 16:27 UTC, mikolaj007 commented
alright, done

2019-02-22 19:29 UTC, Jujumatic requested changes
The dme is also changed but dw I'll fix it when you're done

2019-02-22 19:29 UTC, Jujumatic commented on hippiestation/code/datums/status_effects/debuffs.dm
> +		human_owner.drunkenness *= 0.997 //reduce drunkenness by 0.3% per tick, 6% per 2 seconds
Take out all of the tg code you put into this and call ..() at the end of your version of sleep code so that all of the tg sleep code gets called, if you haven't commented out tg's version of sleep

2019-02-22 19:29 UTC, Jujumatic commented on hippiestation/code/datums/status_effects/debuffs.dm
> +		owner.adjustToxLoss((-healing/100), 0)
Making things futureproof is good coding practice, however in this case putting this at a later point in time wouldn't be difficult at all if it was needed. Remove it as it's an unnecessary check for something we're not implementing for the foreseeable future

2019-02-22 19:29 UTC, Jujumatic commented on hippiestation/code/datums/status_effects/debuffs.dm
> +			owner.emote("snore")
All this is tg code as well iirc so take this off since it'll be called in the original sleep pric

2019-02-22 19:29 UTC, Jujumatic commented on hippiestation/code/datums/status_effects/debuffs.dm
> +			owner.emote("snore")
Proc smh

2019-02-22 19:31 UTC, Jujumatic commented
I think a few of my comments were eaten, basically remove any tg code you copied into your version of sleep code and just call ..() at the end of your code so we call all of tg's sleep code

2019-02-23 08:01 UTC, Manly-Dwarf commented
As long as this doesn't also apply to unconsciousness, +1.

2019-02-23 10:22 UTC, Jujumatic approved these changes

2019-02-23 10:39 UTC, merged