[WIP] Crew Objectives: super shitcode edition
HippieStation/HippieStationdeprecated2020 pull request #10771
Opened 2019-03-02 01:16 UTC by Jujumatic

So I've seemingly made the skeleton for crew objectives thus far, had to spend a few days reading datums and looking around the codebase to see what the hell I even needed to do but I think I've got a good idea of what needs to be done. This is probably going to take a while but lol

Give some crew objectives, whether or not it's restricted to a job and what it should be

As it currently stands, crew objectives will only be given on roundstart itself. That can probably be fixed pretty easily though.

Already an approved feature so votes are not needed I don't think

:cl:
add: Added crew objectives!!! Objectives are created for all non-antags and can be generic or based on your job type.
/:cl:

2019-03-02 01:17 UTC, Jujumatic commented on hippiestation/code/game/gamemodes/objective.dm
> +/datum/objective/crew/clown/honk/check_completion()
idk how to check for this yet lol

2019-03-02 12:22 UTC, Carbonhell commented
If there is a feature request for this in github issue tracker, add "Fixes #issuenum" to the PR description

2019-03-02 12:24 UTC, Carbonhell requested changes

2019-03-02 12:24 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/crew/crew.dm
> +	M = var/datum/antagonist/crew/C
wtf is this syntax

2019-03-02 12:25 UTC, Carbonhell commented
Your syntax is wrong in multiple places

2019-03-08 22:37 UTC, Jujumatic commented
Will re-open once I get this done properly

2019-03-08 22:37 UTC, closed without merging