Makes the briefcase the lawyer starts with very robust, and makes it fit on the belt slot
HippieStation/HippieStationdeprecated2020 pull request #10781
Opened 2019-03-04 23:45 UTC by JF260

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Makes the lawyers briefcase more robust, and it now fits on the belt slot
/:cl:

## About The Pull Request
Gives the lawyers starting briefcase 14 force (where toolboxes are 12) and allows it to fit on your belt slot.

## Why It's Good For The Game
Makes the lawyer slightly more interesting. In the future, I will make more lawyer changes for the sake of making lawyer an actual job. Here are some of my ideas:
Giving lawyers an instant transmission automatically linked to their briefcase, and find some IC way to explain it or at least make it thematic.
Encourage admins to enforce contracts.
Allow them to fold paper into different things.
But hey, that's all for later. For now, this gives lawyer an iota of individuality, instead of just being the love child of sec and assistant.

2019-03-04 23:47 UTC, Jujumatic requested changes

2019-03-04 23:47 UTC, Jujumatic commented on code/game/objects/items/storage/briefcase.dm
Reeee modularise

2019-03-04 23:47 UTC, JF260 commented on code/game/objects/items/storage/briefcase.dm
fair, gimme a sec

2019-03-04 23:52 UTC, JF260 commented on code/game/objects/items/storage/briefcase.dm
done

2019-03-04 23:57 UTC, Jujumatic approved these changes

2019-03-05 01:00 UTC, Manly-Dwarf commented
Can you still knock people out by hitting them on the head?

2019-03-05 02:05 UTC, JF260 commented
> Can you still knock people out by hitting them on the head?

The thing where you knock people silly? I'm not sure, but if its possible, that would be a fun addition.

2019-03-05 05:22 UTC, yoyobatty commented
It's under species.dm or human_defense.dm somewhere maybe spec_attackedby

2019-03-06 10:30 UTC, Maroonenahmoron commented
I dunno about teleporting it, you can put several objects in a briefcase like traitor objectives or syndicate items and being able to summon them out of the blue is unbalanced. Otherwise, I’m happy with 14 force and being put on belt slot. +1

2019-03-07 16:29 UTC, Lxtoofonea commented
+1 for what mr maroon said

2019-03-08 22:31 UTC, Jujumatic commented
needs one more +1

2019-03-10 04:41 UTC, t-f-w commented
sure +1

2019-03-10 05:04 UTC, Manly-Dwarf commented
-1 for shilling the PR

2019-03-10 09:03 UTC, merged