Crossbow Fixes
HippieStation/HippieStationdeprecated2020 pull request #10803
Opened 2019-03-06 13:17 UTC by IHadMyUsernameTaken

## Changelog
:cl:
fix: Crossbows now show their current state properly.
fix: Crossbows won't now cause a runtime error when examined without a rod loaded in, and the text explaining to you that there is a rod loaded will now show the article for the rod properly.
/:cl:

## About The Pull Request
The reason for why the overlays were shown oddly on the crossbow seemed to be more or less due to the fact that none of the previous overlays were cut before applying another combination of them to show the current state of the crossbow. To fix this, I just introduced the cut_overlays call to get rid of any previous combination before applying another combination of the overlays appropriate for the current state. Fixes #10429.

If you examined a crossbow, the examine proc would lastly try to output text related to the loaded rod by first looking at its BB variable. This causes a problem in the case that there was no rod loaded, because if there is no rod in the crossbow, chambered is null, and so the BB variable doesn't exist, so the check for the BB variable was changed to be a check for the chambered rod itself, as the BB variable will also then exist. The article for the loaded rod in the text that gets shown if this check is passed wasn't shown properly, so the \A macro is now being used to handle that.

## Why It's Good For The Game
The first fix should help with the problem that crossbows had with showing their overlays. As for the other two fixes, a player wouldn't really see any difference when the runtime error happens and would still understand what is meant with the text even if the loaded rod has two articles, but I would suppose that fixing these is more preferable than letting them be around.

2019-03-07 02:11 UTC, Manly-Dwarf commented
nice

2019-03-07 09:40 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +		to_chat(user, "\A [chambered.BB] is loaded.")
I'm sure this will still runtime as chambered.BB will still be called, and it seems that it's undefined in this block

2019-03-07 09:41 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +		to_chat(user, "\A [chambered.BB] is loaded.")
Doing "\A" won't make a difference to this

2019-03-07 10:06 UTC, Jujumatic commented
Ok I tested this out, the check won't work as it'll be checking for BB in a var that is registered as null, but it'll run just fine if you have a rod inside the crossbow. so what you do is you check if chambered has a value or not first, then do if chambered.BB has a value

like thus:
``if (chambered)
    if(chambered.BB)
        to_chat(user, "A [chambered.BB] is loaded.")
``
@IHadMyUsernameTaken

2019-03-07 10:08 UTC, Jujumatic requested changes
yeah do that thing

2019-03-07 10:28 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +		to_chat(user, "\A [chambered.BB] is loaded.")
The \A macro does seem to make the article be shown properly on the rod from what I tested, but if you still think I should just keep it as A, I'll do that. I'm going to add the check for the BB variable though.

2019-03-07 10:40 UTC, Jujumatic commented
The descriptions showed properly even when I reverted your changes, just that it caused a runtime to pop up when there was no rod inside

2019-03-07 11:16 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +		to_chat(user, "\A [chambered.BB] is loaded.")
The check for chambered.BB and putting \A back to being A should be done now.

2019-03-07 12:10 UTC, Jujumatic requested changes

2019-03-07 12:10 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
This will still runtime as you're passing chambered.BB before checking if it's null

You need to check if chambered is null first and *then* check for what's inside chambered aka chambered.BB

2019-03-07 12:15 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
This is essentially checking if chambered has a value and is passing chambered.BB at the same time, regardless of whether chambered is null or not

2019-03-07 13:07 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
Wouldn't the && operator first evaluate the value of chambered, and if it's null or any other value that would cause it to be evaluated false, short-circuit such that it will not consider looking at chambered.BB to cause a runtime error from trying to look at the BB value of null?

2019-03-07 13:09 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
I didn't seem to get any runtime errors of this kind either when I tried this out locally.

2019-03-07 13:34 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
It would evaluate them in that order but it wouldn't stop chambered.BB from being evaluated, as you have not set any condition that needs to be met before chambered.BB is evaluated. The runtime will only happen if you examine the crossbow when there's no bolt loaded in

2019-03-08 08:08 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
But by the definition of the && operator, it should not evaluate the chambered.BB value if chambered is null, right? From what I understand, the check I wrote here and the two checks that you showed for me are equivalent in the sense of their purpose. To illustrate this, let's consider them. Firstly, if we wrote

```
if(chambered)
	if(chambered.BB)
		to_chat(user, "A [chambered.BB] is loaded.")
```
it certainly would do what you say, it checks that chambered is not null first before trying to evaluate the chambered.BB value to see if it can output the text. However, if we use

```
if(chambered && chambered.BB)
	to_chat(user, "A [chambered.BB] is loaded.")
```

the evaluation would proceed as follows. 
If chambered is not null, it evaluates the right hand side value and then outputs the text if chambered.BB is not null either.
If chambered is null, the way how the short-circuited and operator works is that it will stop any further evaluation from happening and the text will not be shown, because it has found the first false value, which is chambered in this case.
Therefore, the left hand side value of the && operator is the condition that needs to be true before chambered.BB can be evaluated to determine if the text should be outputted in this check, so this is equivalent to the two checks you provided, since this is making sure that chambered is not null first to let the && operator in the check evaluate the chambered.BB value and it uses the chambered.BB value to further determine if it can output the text.

If this still isn't convincing enough though, I'll replace the check I'm using here with the one you showed, as it does do the wanted checks.

2019-03-08 08:24 UTC, yoyobatty commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
You can simple put chambered.?BB to replace what's around the &&

2019-03-08 08:39 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
Yeah the ?. operator seems to work rather nicely here, so I'll go ahead and add that as the change.

2019-03-08 08:44 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
seems that && would work fine as well actually, myb

2019-03-08 08:45 UTC, Jujumatic commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
but technically ?. is more "efficient" as everything is evaluated once

so if just goes like 
```
if(chambered?.BB)
    do_whatever
```

2019-03-08 09:18 UTC, IHadMyUsernameTaken commented on hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
> +	if (chambered && chambered.BB)
Yeah don't worry, it should be using ?. now though.

2019-03-08 22:33 UTC, Jujumatic approved these changes

2019-03-08 22:33 UTC, merged