[MIRROR] Corrects ED-209 tablecrafting recipe
HippieStation/HippieStationdeprecated2020 pull request #10947
Opened 2019-03-22 03:41 UTC by HonkBot

Original PR: https://github.com/tgstation/tgstation/pull/43163
----------------------------
Mistake from #42930
:cl: ShizCalev
fix: ED-209 tablecrafting recipe has been corrected to use a DRAGNet
/:cl:

2019-03-24 22:43 UTC, Jujumatic commented
this doesnt make sense you'll only be able to make 2 bots then

2019-03-25 01:19 UTC, yoyobatty requested changes
Someone fix or I will, also, make them use the taser and comment the change

2019-03-25 04:11 UTC, yoyobatty submitted a review, later dismissed

2019-03-25 08:52 UTC, yoyobatty approved these changes

2019-03-25 08:52 UTC, merged