Fixes some runtimes, poor initialization parent calls and chem tanks.
HippieStation/HippieStationdeprecated2020 pull request #11105
Opened 2019-04-06 03:23 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: YoYoBatty
admin: Clear turf chems verb is now available.
code: Fixed heat exchanger manifold runtiming.
code: Fixed a dna related runtime.
fix: Fixed incorrect initial reagent flags on chemical tanks.
tweak: Chem tanks now have an examine hint to see if the lid is opened or closed.
/:cl:

## About The Pull Request
This PR is essentially addressing some shit code we have hanging around.

## Why It's Good For The Game
We need more code improvements and QOL stuff like this.

2019-04-06 10:18 UTC, Jujumatic requested changes

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +		to_chat(user, "It's lid is closed.")
Its

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +		to_chat(user, "It's lid is open.")
Its

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +	create_reagents(tank_volume, DRAWABLE | AMOUNT_VISIBLE)
I would think reagent_dispensers already has create_reagents
You might be calling create_reagents twice because of this...

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/game/turfs/turf.dm
> +	. = ..()
there's no parent to this, just use ..()

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/game/atoms.dm
> +	. = ..()
no parent, use ..()

2019-04-06 10:18 UTC, Jujumatic commented on hippiestation/code/datums/dna.dm
> +	. = ..()
i don't know much about dna so i have no idea how this will work

2019-04-06 10:18 UTC, Jujumatic commented on code/modules/admin/admin_verbs.dm
> +	/client/proc/kill_turf_chems /*hippie -- destroys all chem piles*/
you didn't define this proc, where is it?

2019-04-06 10:26 UTC, yoyobatty commented on code/modules/admin/admin_verbs.dm
> +	/client/proc/kill_turf_chems /*hippie -- destroys all chem piles*/
It exists in hippie admin verbs.

2019-04-06 10:26 UTC, yoyobatty commented on hippiestation/code/datums/dna.dm
> +	. = ..()
It adds missing arguments.

2019-04-06 10:26 UTC, yoyobatty commented on hippiestation/code/game/atoms.dm
> +	. = ..()
Parent is the TG proc

2019-04-06 10:27 UTC, yoyobatty commented on hippiestation/code/game/turfs/turf.dm
> +	. = ..()
Parent is tg proc

2019-04-06 10:28 UTC, yoyobatty commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +	create_reagents(tank_volume, DRAWABLE | AMOUNT_VISIBLE)
Create reagents deletes reagents if they already exist which is the goal to removable drainable flag from reagents.flags

2019-04-06 10:28 UTC, yoyobatty commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +		to_chat(user, "It's lid is closed.")
Yes

2019-04-06 10:28 UTC, yoyobatty commented on hippiestation/code/modules/reagents/reagent_dispenser.dm
> +		to_chat(user, "It's lid is open.")
Yes

2019-04-07 21:33 UTC, Jujumatic approved these changes

2019-04-07 21:34 UTC, Jujumatic commented
fuck it, if everything dies we can just revert

2019-04-07 21:34 UTC, merged