Realclown
HippieStation/HippieStationdeprecated2020 pull request #11129
Opened 2019-04-08 15:45 UTC by Eagle-Eyess

:cl: EagleEyes
add: clowns cant abuse mutadone anymore
/:cl:

clowns were never meant to use guns (except for antags). you wanna use a gun dont play clown or get brain surgery... dummies

2019-04-08 15:46 UTC, Jujumatic commented
Wait hold up this is going to make every single person who gets the clumsy trait completely unable to remove it

2019-04-08 15:50 UTC, Eagle-Eyess commented
ill fix this later

2019-04-08 15:50 UTC, Jujumatic commented
:)

2019-04-08 16:08 UTC, yoyobatty submitted a review, later dismissed
Maybe create a sub mutation of clumsy called clown and replace the clowns mutation with it then add this var

2019-04-08 19:06 UTC, Manly-Dwarf commented
yes

2019-04-09 22:03 UTC, Jujumatic submitted a review, later dismissed
looks good though there might be a double indentation on line 6 or it's just my eyes fucking with me

2019-04-11 14:19 UTC, Eagle-Eyess commented
this code should now finally work. (thanks yoyo)

2019-04-11 14:53 UTC, Jujumatic requested changes

2019-04-11 14:53 UTC, Jujumatic commented on hippiestation/code/datums/mutations/clumsy/clown.dm
> +			M.mutadone_proof = TRUE//jew jew fooking sucks and yoyo is better
:japanese_goblin:

2019-04-11 14:53 UTC, Jujumatic commented on hippiestation.dme
> +#include "hippiestation\code\datums\mutations\clumsy\clown.dm"
This isn't the path of the original proc we're editing though. You always make a modularised path which is based on the path of where you got the code from

2019-04-12 01:28 UTC, yoyobatty commented
I also realized after that this is the job outfit equip therefore adding the job clown check us redundant

2019-04-15 09:11 UTC, Maroonenahmoron commented
Yes, thank you! +1

2019-04-15 10:11 UTC, Jujumatic approved these changes

2019-04-15 10:12 UTC, Jujumatic commented
this is unnecessarily expensive but fuck yoyo, fuck code and fuck the entire codebase being built on shitcode. also fuck tg cause why not

2019-04-15 10:12 UTC, merged