Surplus Exclusive Items Two Electric Boogaloo
HippieStation/HippieStationdeprecated2020 pull request #11247
Opened 2019-04-23 21:58 UTC by Manly-Dwarf

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: Manly Dwarf
add: You can now find a ton of extra, secret items inside of Surplus Crates for free!
/:cl:

## About The Pull Request

## Why It's Good For The Game

I'll write this later who cares

Also someone needs to fix the goat plushie and buttshoes runtiming every single time their squeak gets called, code is outdated.

2019-04-23 21:59 UTC, Manly-Dwarf commented
Carbonhell requested changes 9 minutes ago
"holy shit why are all of the items in one file, split them up"

2019-04-23 21:59 UTC, Carbonhell submitted a review, later dismissed
"holy shit why are all of the items in one file, split them up"

2019-04-23 22:00 UTC, Manly-Dwarf commented
no

2019-04-23 22:04 UTC, k-k-karma commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	seed = null
change to generic banana seed9

2019-04-23 22:08 UTC, Carbonhell requested changes

2019-04-23 22:08 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		START_PROCESSING(SSobj, src)
What is this for? I do not see any process() redefinition

2019-04-23 22:08 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	var/mob/living/user = usr
Isn't there a better proc to redefine, rather than Click?

2019-04-23 22:09 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	seed = null
n

2019-04-23 22:09 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		START_PROCESSING(SSobj, src)
mop/advanced

2019-04-23 22:09 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	var/mob/living/user = usr
nope

2019-04-23 22:13 UTC, TDcoolguy300 commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		priority_announce("[firer], age 45, gave themselves up to authorities after blowing up [target]. They are now serving a life sentence.","Blood Debt!", 'hippiestation/sound/misc/lubricator.ogg')
You can check if the firer is a human mob and get their age variable
```
var/age = 45
if(ishuman(M))
   var/mob/living/carbon/human/H = M
   age = M.age
```
And then replace the 45 with [age]
Don't actually copypaste this because it's fucked and github doesn't let me add tabs for whatever reason.

2019-04-23 22:14 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		priority_announce("[firer], age 45, gave themselves up to authorities after blowing up [target]. They are now serving a life sentence.","Blood Debt!", 'hippiestation/sound/misc/lubricator.ogg')
Age 45 is a reference to the film, intentional.

2019-04-23 22:28 UTC, Carbonhell submitted a review, later dismissed

2019-04-23 22:28 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	if(iscarbon(loc))
what???

2019-04-23 22:28 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	playsound(user, on ? 'sound/weapons/saberon.ogg' : 'sound/weapons/saberoff.ogg', 35, 1)
I think you can spam this sound since there is no delay here, how long is this sound? Could it cause problems?

2019-04-23 22:28 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	visible_message("<span class='warning'>[usr] puts the [src] on. It's covered in ash.</span>")
Why are you using usr instead of user here?

2019-04-23 22:29 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	playsound(user, on ? 'sound/weapons/saberon.ogg' : 'sound/weapons/saberoff.ogg', 35, 1)
Copypasted esword cope

2019-04-23 22:29 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	if(iscarbon(loc))
Intentionally confuses the code so it won't spam log messages and still play sounds, doesn't runtime, yell at Yoyobatty

2019-04-23 22:29 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	visible_message("<span class='warning'>[usr] puts the [src] on. It's covered in ash.</span>")
Who knows

2019-04-23 22:30 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	if(iscarbon(loc))
...what? If loc can be a carbon, why do you typecast it as an open turf then?

2019-04-23 22:31 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	if(iscarbon(loc))
Hahahahahahah

2019-04-23 22:31 UTC, Carbonhell commented on hippiestation/code/modules/uplink/surplus_items.dm
> +	if(iscarbon(loc))
Fuck, accidentally resolved this. Anyway, this makes no sense, you call get_turf, which returns a turf, it cannot return a carbon, this will never pass.

2019-04-23 22:51 UTC, Lxtoofonea commented
+1

2019-04-23 23:54 UTC, Manly-Dwarf commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		t_loc.pry_tile(src, usr, TRUE)
Can you morons stop messing with the code

2019-04-23 23:55 UTC, k-k-karma commented on hippiestation/code/modules/uplink/surplus_items.dm
> +		t_loc.pry_tile(src, usr, TRUE)
dindu nuffin

2019-04-24 22:23 UTC, Manly-Dwarf commented
merge dis

2019-04-24 22:24 UTC, k-k-karma commented
needs +1

2019-04-24 22:28 UTC, mikolaj007 commented
+1

2019-04-25 06:55 UTC, Manly-Dwarf commented
okok +1
merge dis

2019-04-25 18:54 UTC, Zyzarda commented
content is good +1

2019-04-25 18:54 UTC, AnthonyJNgo commented
+1, get batty to sign off on this too and we are g2g

2019-04-25 18:57 UTC, yoyobatty commented
Will approve code in few hours but +1

2019-04-25 19:06 UTC, yobob591 commented
sounds cool +1

2019-04-27 20:08 UTC, Manly-Dwarf commented
"Will approve code in a few hours"
2 days ago

2019-04-27 23:59 UTC, merged

2019-04-28 00:00 UTC, Manly-Dwarf commented
:spoi: