Gibs rework 2: Electric Boogaloo
HippieStation/HippieStationdeprecated2020 pull request #11340
Opened 2019-05-04 06:15 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Gibs monster has a very small chance of reproducing when eating.
fix: Fixed Gibs monster getting stuck eating one mob.
balance: Gibs monster moves and attacks faster.
fix: Gibs nobody longer has the horrorform login message
tweak: Gibs will appear frustrating if it fails to get it's meal at low health.
balance: Gibs are a little bit more smarter now.
/:cl:

## About The Pull Request
I tested this new mob out on the live server and discovered a lot of issues with it. Getting stuck eating the same dead mob forever, moving way too slowly, not appearing very intelligent, attacking rather slow, etc...
This will give them a significant buff, although a few variables will be subject to tweaking as testing continues.

## Why It's Good For The Game
I think this mob should have enough bite to live up to it's bark. I am curious to see how the playerbase will react to it.

2019-05-04 08:30 UTC, Majick1 commented
+1 we'll do it live

2019-05-04 17:12 UTC, bigbluebeaker commented
+1 interested in seeing how this plays out

2019-05-06 00:29 UTC, Manly-Dwarf commented
farty party all the time

2019-05-06 00:30 UTC, cris5311 commented
+1 
cant see how to not +1 this

2019-05-06 00:44 UTC, ghost requested changes
minor nitpick but otherwise it looks okay

2019-05-06 00:44 UTC, McBawbaggings commented on hippiestation/code/modules/mob/living/simple_animal/hostile/sentientgibs.dm
> +				visible_message("<span class='warning'>[lunch] appears frustrated!</span>", \
Firstly, this message is kind of dry. Secondly, it should be [src], not [lunch] as the subject here.
You should probably throw in a jitter effect here as well as something like "[src] vibrates in exasperation!"

2019-05-06 00:52 UTC, yoyobatty commented on hippiestation/code/modules/mob/living/simple_animal/hostile/sentientgibs.dm
> +				visible_message("<span class='warning'>[lunch] appears frustrated!</span>", \
Done

2019-05-06 00:55 UTC, ghost approved these changes

2019-05-06 01:01 UTC, merged