Makes voice of god a even bigger force to be reckoned with
HippieStation/HippieStationdeprecated2020 pull request #11451
Opened 2019-05-13 16:06 UTC by WarRage333

## Changelog
:cl:

balance: Voice of god is now way stronger

/:cl:

## Why It's Good For The Game

adds farting and screaming to voice of god

2019-05-13 17:02 UTC, yoyobatty requested changes
Modularise this or place a header and trailer comment indicating it's a hippie edit.

2019-05-13 18:51 UTC, WarRage333 commented
done didly done

2019-05-13 20:34 UTC, Manly-Dwarf commented
Did you fix Voice of God spam automuting people?

2019-05-13 20:41 UTC, yoyobatty commented
That's probably better to put it another PR, maybe even upstream.

2019-05-13 22:35 UTC, Carbonhell commented
> Did you fix Voice of God spam automuting people?

/atom/movable/proc/say(message, bubble_type, var/list/spans = list(), sanitize = TRUE, datum/language/language = null, ignore_spam = FALSE, forced = null)

to fix, just add ignore_spam = TRUE to any say() calls in the code forced by some object (example: voice of god)

2019-06-06 23:06 UTC, mikolaj007 commented
+1 sure why not

2019-06-07 04:04 UTC, AnthonyJNgo commented
Honestly, voice of god shouldn't be immune to spam, you shouldn't be saying SCREAM 20 times in a row anyways. +1.

2019-06-07 05:00 UTC, yoyobatty approved these changes

2019-06-18 14:44 UTC, ghost requested changes

2019-06-18 14:44 UTC, steamp0rt commented on code/modules/surgery/organs/vocal_cords.dm
> +	var/static/regex/fart_words = regex("fart|poo|poop|defecate") //hippie edit
can be modularized by adding them under `hippiestation/code/modules/surgery/organs/vocal_cords.dm`

2019-06-18 14:44 UTC, steamp0rt commented on code/modules/surgery/organs/vocal_cords.dm
> +	// hippie start -- FART
can just make a seperate proc that does like
```
else
 hippie_voice_of_god(message)
```

2019-06-18 16:00 UTC, WarRage333 commented on code/modules/surgery/organs/vocal_cords.dm
> +	var/static/regex/fart_words = regex("fart|poo|poop|defecate") //hippie edit
Tried to but didn't work on my server when I tested it,  prolly me just being bad tho

2019-06-26 02:07 UTC, MaterialisticThings commented
+1 only if we can fix it from muting you

2019-07-01 23:49 UTC, lunaman22 commented
+1 AAAAAAAAAAAAAAAAA

2019-07-15 11:48 UTC, WarRage333 commented
I really don't have the know-how how to fix these properly if anyone wants to take over this feel free

2019-07-15 11:48 UTC, closed without merging