[DO NOT EVEN THINK OF MERGING] IT'S UPSTREAM MERGE TIME
HippieStation/HippieStationdeprecated2020 pull request #11766
Opened 2019-06-14 03:29 UTC by steamp0rt

2019-06-14 18:41 UTC, yoyobatty commented
reagent id's need to be ported. Lmao.

2019-06-14 18:46 UTC, steamp0rt commented
LUCKILY I GOT A SCRIPT THAT FIXES RECIPES

2019-06-18 22:46 UTC, CocaColaTastesGood commented
Ash lizards only get 1 puddle

2019-06-20 21:16 UTC, yoyobatty requested changes

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/automatic.dm
This needs to be reverted

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/automatic.dm
>  	icon_state = "[initial(icon_state)][magazine ? "" : "-e"]"
Fix this too

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/launchers.dm
> -
this too

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/toy.dm
> +
this breaks it

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/toy.dm
> +
ditto

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/toy.dm
> +
ditto

2019-06-20 21:16 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic/toy.dm
> +	add_overlay("[icon_state]_toy")
ditto

2019-06-22 18:21 UTC, Carbonhell commented
> Why are we upstream merging?

2019-06-22 19:02 UTC, cris5311 commented
This caused the removal of VR, right? If so, dont fucking merge it.

2019-06-22 19:11 UTC, steamp0rt commented
@cris5311 we can readd it if we want. but didn't it cause alot of problems? like spamming ghosts?

2019-06-22 19:14 UTC, cris5311 commented
@steamp0rt i never got spammed by VR as ghost. It was acctually a thing which made dying quite bearable and when me and some other ghost found out it was removed after we got blown up in a clowncar in outerspace we were all very angry and sad.

2019-06-22 19:14 UTC, steamp0rt commented
@cris5311 also didn't some people lag the server via beam rifles from VR?
also having the window flash when alt+tabbed due to `Idiot McDumbFace has did blahblah at Syndicate VR` is very annoying.

2019-06-22 19:18 UTC, cris5311 commented
@steamp0rt i can see how that could be annoying. Maybe just remove the beamrifles from VR then? I never got the windowflash 

> when alt+tabbed due to `Idiot McDumbFace has did blahblah at Syndicate VR`

but i might have missed that due to not paying too much attention after im dead and deciding to not respawn as a ghost role or watch the game.

2019-06-23 16:57 UTC, steamp0rt commented on _maps/map_files/HippieStation/hippiestation.dmm
> -	icon_state = "conveyor_map";
Um, did StrongDMM clean up default icon_states/invalid dirs?

2019-06-24 05:44 UTC, HideAndSeekLOGIC commented
@steamp0rt shouldn't designers and maintainers be the ones to make the final decisions on whether or not these changes to through?

2019-06-24 05:45 UTC, HideAndSeekLOGIC commented
I don't quite understand this whole PR

2019-06-24 06:46 UTC, Majick1 commented
I feel like there's just too much going on here for normal +- votes, leave this to the headmins/maintainers

2019-06-24 06:50 UTC, HideAndSeekLOGIC commented
@Majick1 I don't understand the whole concept of a mass merge. Why not simply mirror the PRs that you want instead?

2019-06-24 06:50 UTC, HideAndSeekLOGIC commented
If Hippie is going to go their own way they might as well go their own way

2019-06-24 14:21 UTC, Majick1 commented
This was started before HGTOW, and it looks like a bunch of map and menu fixes the mirror bot missed for whatever reason

2019-06-25 09:11 UTC, optimumtact commented
beautiful

2019-06-25 17:31 UTC, steamp0rt commented
@optimumtact begone thot

2019-06-25 21:39 UTC, AnthonyJNgo commented
This is not to be merged until given headmin approved tag.

2019-06-25 22:59 UTC, AnthonyJNgo commented
Last one.

2019-06-25 23:01 UTC, steamp0rt commented
wat?

2019-06-25 23:01 UTC, merged