Plate Armor
HippieStation/HippieStationdeprecated2020 pull request #11887
Opened 2019-07-30 18:51 UTC by zamolxius

:cl: zamolxius
add: Added plate armor, welded from metal.
imageadd: added the sprites for the plate armor
/:cl:

## Why It's Good For The Game
Adds plate armor, it has negative resistance towards thermal damage sources like laser or cold, negative resistance towards armor because no insulation, it protects decently against radiation and bio because it's thick metal, but it slows you down. It has great resistance towards melee and bullet damage.

2019-07-30 18:51 UTC, zamolxius commented
https://i.imgur.com/DX5S7iN.png

2019-07-30 18:51 UTC, zamolxius commented
https://i.imgur.com/yRTRaJ3.png

2019-07-30 19:04 UTC, yoyobatty requested changes

2019-07-30 19:04 UTC, yoyobatty commented on hippiestation/code/modules/crafts/vest.dm
> +	armor = list("melee" = 50, "bullet" = 40, "laser" = -15, "energy" = -15, "bomb" = 15, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80)
Bullet should probably be 25 or 30, plate armor is incapable of properly protecting you from bullets/arrows.

2019-07-30 19:04 UTC, yoyobatty commented on hippiestation/code/modules/crafts/vest.dm
> +/obj/item/clothing/head/plate_armor_helmet
could make this a subtype of existing armor helmets/hardhats

2019-07-30 19:04 UTC, yoyobatty commented on hippiestation/code/modules/crafts/vest.dm
> +	armor = list("melee" = 40, "bullet" = 40, "laser" = -15,"energy" = -15, "bomb" = 25, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80) //stats copied from the security helmet, with melee and bullet
Same thing related to my suggestion of the bullet damage tweaks

2019-07-31 16:45 UTC, Manly-Dwarf commented
probably should not slow you down

2019-07-31 18:21 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +	armor = list("melee" = 50, "bullet" = 40, "laser" = -15, "energy" = -15, "bomb" = 15, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80)
obj/item/clothing/suit/armor/plate/crusader
	name = "Crusader's Armour"
	desc = "Armour that's comprised of metal and cloth."
	icon_state = "crusader"
	w_class = WEIGHT_CLASS_BULKY
	slowdown = 2.0 //gotta pretend we're balanced.
	body_parts_covered = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
	armor = list("melee" = 50, "bullet" = 50, "laser" = 50, "energy" = 40, "bomb" = 60, "bio" = 0, "rad" = 0, "fire" = 60, "acid" = 60)

2019-07-31 18:21 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +	armor = list("melee" = 50, "bullet" = 40, "laser" = -15, "energy" = -15, "bomb" = 15, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80)
thoughts

2019-08-01 18:42 UTC, zamolxius commented
this is ready @yoyobatty

2019-08-04 15:19 UTC, AnthonyJNgo commented
Cool idea, abstaining for now, would like to see this ironed out so it is completely polished if/when it gets enough +1s. Consider me on the fence leaning towards +1.

2019-08-04 15:48 UTC, zamolxius commented
this isnt my first contribution dude

2019-08-04 17:16 UTC, AnthonyJNgo commented
@zamolxius You have a [first time contributor] tag next to your name.

2019-08-05 13:19 UTC, nemvar reviewed
Upstream coder here. Everyone starts somewhere so please don't think I'm trying to be hostile with this.

If you have any questions about why certain things that I point out here are bad, just ask.

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	START_PROCESSING(SSobj, src)
Why are you processing this? You don't even use process().

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		armor = list("melee" = 50, "bullet" = 10, "laser" = -10, "energy" = -25, "bomb" = 10, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80) //this is a menacing plate armor
This is not how armor datums work. Armor is only a list until it gets turned into a datum on Initialize.

My recommendation for this whole init is to turn it into a lootdrop instead. This doesn't make much sense.

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		I.use(10)
You can upgrade the armor with a single piece of cloth. There is no check if there's actually 10 of them in the stack before you call this.

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	if((istype(I, /obj/item/stack/sheet/cloth)) && (src != padded))
``src != padded``? That's complete nonsense. src is the object that owns this proc, not a boolean.

Should be ``!padded``

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		return 0
If the wearer has gloves this doesn't work? Doesn't make any sense

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	V.emote("scream")
This runtimes if the hitby isn't a mob, which it isn't if the person got damaged by a thrown object or a melee weapon.

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	if((istype(I, /obj/item/stack/sheet/cloth)) && (src != padded))
This is hurting my upstream sensibilities towards duplicate code.

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	var padded = FALSE
It's a sin against the coding gods to do ``var padded`` instead of ``var/padded``

2019-08-05 13:19 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	subcategory = CAT_WEAPON
I don't know hippie crafting categorys, but it's a bit weird how this is in CAT_WEAPON. Don't you have a category for armor or something?

2019-08-05 13:21 UTC, nemvar commented
Also merge conflict

2019-08-05 14:36 UTC, zamolxius commented
aught  bro much appreciated but what to use for using the stack up?  i used the thing cloth usually uses but it didnt work

2019-08-05 14:36 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +	START_PROCESSING(SSobj, src)
its used like that in the HECK suit,  dunno

2019-08-05 14:37 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +		armor = list("melee" = 50, "bullet" = 10, "laser" = -10, "energy" = -25, "bomb" = 10, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80) //this is a menacing plate armor
aka make it a dummy item that just diversifies into the various types on spawn?

2019-08-05 14:37 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +		return 0
the spikes arent too large

2019-08-05 14:38 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +	var padded = FALSE
oh damn ill keep it in mind bro

2019-08-05 14:38 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +	subcategory = CAT_WEAPON
nah it's combat shit bro

2019-08-05 14:42 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		armor = list("melee" = 50, "bullet" = 10, "laser" = -10, "energy" = -25, "bomb" = 10, "bio" = 25, "rad" = 20, "fire" = -15, "acid" = 80) //this is a menacing plate armor
Well yes, obj/effect/lootdrop is already a thing, just use that as the crafting result.

2019-08-05 14:43 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		return 0
No, the thing is that it checks for the gloves of the **wearer** instead of the gloves of the **attacker**

2019-08-05 14:47 UTC, zamolxius commented on hippiestation/code/modules/crafts/vest.dm
> +		return 0
lmao wtf.  so it should be hitby.gloves or V.gloves instead?

2019-08-05 14:52 UTC, nemvar commented
In rough terms this is how you make sure you actually use 10 units.
```
/obj/item/clothing/suit/armor/plate_armor/steel/attackby(obj/item/I, mob/user, params)
	. = ..()
	if(!istype(I, /obj/item/stack/sheet/cloth))
		return
	if(padded)
		to_chat(user, "[src] is already padded")
		return
	var/obj/item/stack/cloth/c_stack = I
	if(c_stack.get_amount < 10)
		to_chat(user, "You don't have enough cloth fucko)
		return
	c_stack.use(10)
	padded = TRUE
	desc += " This one is padded, and thus it is easier to move comfortably while wearing it."
	slowdown = 0.2
```
Ideally, you wouldn't do that thing with the description and instead add the ``" This one is padded, and thus it is easier to move comfortably while wearing it."`` message if ``padded == TRUE`` in the examine() proc.

2019-08-05 14:56 UTC, AnthonyJNgo commented
@nemvar Due criticism is always welcome, thanks for actually going through and doing a review with him.

2019-08-05 14:56 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +	START_PROCESSING(SSobj, src)
The HECK suit uses processing to create hallucinations for the wearer. This calls nothing on process, so this is redundant.

2019-08-05 14:59 UTC, zamolxius commented
oh damn man,  many thanks

2019-08-05 15:58 UTC, nemvar commented on hippiestation/code/modules/crafts/vest.dm
> +		return 0
This entire proc should look something like this:
```
/obj/item/clothing/suit/armor/plate_armor/steel/hit_reaction(mob/living/carbon/human/owner, mob/living/carbon/human/hitby, attack_text = "the attack", final_block_chance = 0, damage = 0, attack_type = MELEE_ATTACK)
	if(!spikey || attack_type == PROJECTILE_ATTACK || !istype(hitby) || hitby.gloves)
		return FALSE
	//to_chat(hitby, "You hurt yourself when trying to punch [src]), Or some other kind of user feeback, no idea if it already generates a message.
	hitby.emote("scream")
	return TRUE
```

2019-08-05 16:30 UTC, Manly-Dwarf commented
@nemvar thanks for helpin him out tg guy

2019-08-05 18:14 UTC, nemvar commented
Come on, that's just rude. At least give this the proper merge conflict label.

2019-08-05 18:19 UTC, nemvar commented
Oh and on the topic of merge conflicts, you have two of them.

To solve them, just checkout this branch on your local repo and pull upstream/master into it. You should get an error and then have to resolve those conflicts manually.

Then just push to origin and you are good to go.

2019-08-22 00:30 UTC, Fikou commented on hippiestation/code/modules/crafts/vest.dm
> +	subcategory = CAT_WEAPON
theres a clothing category, it contains durathread stuff which is armor

2019-08-22 00:46 UTC, yoyobatty commented
> In rough terms this is how you make sure you actually use 10 units.
> 
> ```
> /obj/item/clothing/suit/armor/plate_armor/steel/attackby(obj/item/I, mob/user, params)
> 	. = ..()
> 	if(!istype(I, /obj/item/stack/sheet/cloth))
> 		return
> 	if(padded)
> 		to_chat(user, "[src] is already padded")
> 		return
> 	var/obj/item/stack/cloth/c_stack = I
> 	if(c_stack.get_amount() < 10)
> 		to_chat(user, "You don't have enough cloth fucko)
> 		return
> 	c_stack.use(10)
> 	padded = TRUE
> 	desc += " This one is padded, and thus it is easier to move comfortably while wearing it."
> 	slowdown = 0.2
> ```
> 
> Ideally, you wouldn't do that thing with the description and instead add the `" This one is padded, and thus it is easier to move comfortably while wearing it."` message if `padded == TRUE` in the examine() proc.
> 
> EDIT: I forgot some brackets in the middle.

You could also try using 

`if(c_stack.use(10))
	to_chat(user, "You don't have enough cloth fucko)
	return
`
instead of 
`
	if(c_stack.get_amount() < 10)
		to_chat(user, "You don't have enough cloth fucko)
		return
	c_stack.use(10)
`
since /stack/proc/use returns true or false, it already takes care of the check

2019-09-18 13:33 UTC, HideAndSeekLOGIC commented
Come on dude, we told you basically everything you need to fix up. This is so close to being merged.

2019-09-29 00:23 UTC, AnthonyJNgo commented
This is a cool idea, fix the issues and it could easily get enough +1s to be put in.

2019-09-30 13:08 UTC, zamolxius commented
remade here -> #12130

2019-10-01 13:48 UTC, closed without merging

2019-10-01 13:49 UTC, zamolxius commented
will work on the rest later,  for now the basic plate armor can be found at #12130