Chem dispenser negative macro value on max tier
HippieStation/HippieStationdeprecated2020 pull request #11902
Opened 2019-08-12 20:08 UTC by yorii

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl: yorii
tweak: Chem dispenser now supports negative values in macros when using a femtomanipulator.
/:cl:

## About The Pull Request 
Adds a quick and easy QoL improvement/buff for chemists who like to write more advanced macros.

## Why It's Good For The Game
It saves you a few clicks and from future carpal tunnel syndrome.

2019-08-12 20:10 UTC, steamp0rt commented
+1 but i'd personally prefer it be all tiers, but with precision based on tier

2019-08-12 20:11 UTC, steamp0rt commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +						say("Femtomanipulator required to remove chemicals from mixture!"
you forgot a `)`

2019-08-12 20:11 UTC, yorii commented
This commit was created on GitHub.com and signed with a verified signature using GitHub’s key.

You can sue me if this code doesn't work.

2019-08-12 20:12 UTC, yorii commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +						say("Femtomanipulator required to remove chemicals from mixture!"
FUGGGGGGGGGGg..... I am commit sudoku now

2019-08-12 20:12 UTC, yorii commented
> +1 but i'd personally prefer it be all tiers, but with precision based on tier

Oh... well in that case...

2019-08-12 20:17 UTC, yorii commented
it was even less code changes then :3

2019-08-12 20:29 UTC, ghost requested changes
YOU DIDN'T EVEN DO THIS RIGHT -- you edited the `dispense` topic, not `dispense_recipe`

LUL

2019-08-12 20:37 UTC, yorii commented
it's the same isn't it? the recipe calls on this function to actually do the dispensing?

2019-08-12 20:39 UTC, yorii commented
oh no shit you're right you have it split up for two separate add_reagent functions...

2019-08-13 00:14 UTC, yorii commented
You forgot to adjust the powerusage for negative values, unless we want removing reagents to recharge the powercell?

2019-08-13 03:44 UTC, yorii reviewed
is all good now

2019-08-13 04:25 UTC, ghost submitted a review, later dismissed

2019-08-13 15:06 UTC, yorii commented
Hi sorry, these changes aren't enough it seems, only tested them on tg until now and you seem to have a slightly different chem_dispenser.dm, don't merge for now :)

I think it's this part:
`max(chemicals_to_dispense[key], res)`

2019-08-13 15:20 UTC, yorii commented
Changed a max to a round and another missing abs(value) for the recipe validation check, but now it's actually even tested 🥇

2019-08-13 19:41 UTC, ghost approved these changes

2019-08-16 23:49 UTC, cris5311 commented
+1


Yeah thats good shit, now we only need super macros which can call on saved macros

2019-08-18 05:28 UTC, Manly-Dwarf commented
chemistry powergame never ends
time to make entire recipes in one click

2019-08-20 18:27 UTC, merged

2019-08-20 22:42 UTC, DONKARMA commented
why

2019-08-20 22:57 UTC, Manly-Dwarf commented
why