Removes reactive teleport armor from RD's locker
HippieStation/HippieStationdeprecated2020 pull request #12015
Opened 2019-09-12 01:27 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
del: Removed roundstart reactive teleport armor
/:cl:

## About The Pull Request
What it says on the tin. RD is the ultimate power gamer's job, and the RTA's purpose is only for being extra robust at combat.

## Why It's Good For The Game
Because science is extremely broken and what can be powergamed will be powergamed on hippiestation. Research director really does not need an RTA to do research, it's exclusively used by powergaming traitors and validhunters who need an extra brisk of luck to carry them to safety in the event they get fairly struck by an opponents taser.

2019-09-12 01:43 UTC, Majick1 commented
I'll +1, doesn't make sense to give them a hardsuit AND armor

2019-09-12 01:45 UTC, Manly-Dwarf commented
the RTA does not assist the RD in doing his job, it's purely a combat powergame item
re-add flightsuits and replace his regular hardsuit with it. except make the flightsuit less bad or something I dunno
I know flightsuit also doesn't really help but at least it's not the damn RTA

2019-09-12 01:48 UTC, yoyobatty commented
I'm sort of more on the idea of balancing departments and nerfing powergaming items as a whole so that's something that we'll have to discuss on another PR.

2019-09-12 01:54 UTC, Manly-Dwarf commented
I don't want balance, I want more fun features. If coders have all this time to totally overhaul things, then please add more stuff while you're at it.
The only thing that I'd want balanced in particular right now is Wizard (because people seem to agree it's unfun and too easy, we discovered the meta for him). Most everything else would be cleaning up a lot of nitpicks and fixing problems by adding more content, like to Security, Medbay, Engineering, etc.

2019-09-12 01:59 UTC, yoyobatty commented
One department at a time. Security and Medbay are slightly ahead in terms of powergame but not AS bad as science. Security is essentially powergame or hangout and kill traitors or wait until they storm and ruin sec, hide and take out the big dogs one by one with your robust shit. Medbay is basically make an OP virus, make OP chems, get 100's of healing chems and patches and then syringe nerds or release a deadly virus if you're a traitor. Engineering is setup power, make sure it doesn't go to shit and if you're a traitor either release sing, tesla, blowup SM, flood plasma or all 4 of those. Engineering is probably in most need of work since it's only really FUN for traitors.

2019-09-12 09:14 UTC, ghost commented
It's still a traitor objective.

2019-09-12 09:16 UTC, Majick1 commented
Just swap it to something else in the RD locker

2019-09-12 09:20 UTC, ghost commented
there's already a holotool objective. there's nothing else worth stealing tho

> the RTA does not assist the RD in doing his job, it's purely a combat powergame item

it's meant to be "cool experimental science item", along with the holotool, which kinda fits the RD though.

2019-09-12 09:28 UTC, Majick1 commented
If we're keeping with that, maybe give him a random high tier data disk every round

2019-09-12 11:18 UTC, cris5311 commented
-1

Im not a science player and i see that sci is op (kinda expected on a RESEARCH station however) but most of the recent nerfs are kinda thoughtless.

The armour isnt that strong as one males it out but it is still strong.

Im willing to reconsider and +1 this, but you havent even put enough thought in to remove it as a traitor item and this seems a lot like grudge code. We left TG because of grudgcode.

PS RDs arent that roubust and i habent died too much to them. Hovever ive ssen my fair share of RDs die to the armour

2019-09-12 11:21 UTC, yoyobatty commented
It's an rng win vs tase item

2019-09-12 11:30 UTC, Majick1 commented
There is a bit of grudge code going on which hopefully doesn't cut too deep, but part of the game is departments depending on each other, and science has largely been able to work independently except for sometimes mining if they go heavy on robotics. When there's no engineering, medical, or sec but a fully staffed science department every round during normal pop that's also a huge problem

2019-09-12 11:37 UTC, WarRage333 commented
As a RD main i approve
The items shit and only power gaming assholes go for it, i usually just hide it so noone can use it

2019-09-12 13:56 UTC, yoyobatty commented
It's not though if you see guys like romathebest effectively use it. I can remove it as a traitor objective or I can increase the amount of rads and negative effects generated by it's teleport as an alternative to it. It's currently an rng item that more often than not benefits the wearer. It's a useful validhunt item but often when worn by traitors it gives them an extra life against an ambush by sec or validhunter.

2019-09-12 14:36 UTC, enthethan commented
bit shit to just remove it ... not a nerf not a change just straight removing it . tg level of balancing imo

2019-09-12 14:42 UTC, diegoxt45 commented
stop removing shit, you already learned the playerbase doens't like that, just put it on techweb with like a really expensive manufactiring and points, bam you fixed it, now it's an end-game sci powergame armor

2019-09-12 14:44 UTC, enthethan commented
> stop removing shit, you already learned the playerbase doens't like that, just put it on techweb with like a really expensive manufactiring and points, bam you fixed it, now it's an end-game sci powergame armor

another item that would be seen once in a blue moon / every 50 rounds because hippie rounds are that short,,

2019-09-12 14:46 UTC, SireTurret commented
HURR DURR REMOVE REMOVE!!

ME NO LIKEY!!!!

SCIENCE TOO OP!!! HURR!!!

Y'all already nerfed research. The RTA can fuck you over in many ways, send you to space, into a room full of burning plasma, etc. It's not really that OP. This is grudgecode at it's finest.

2019-09-12 15:40 UTC, robloxgothgf commented
tg 2?

2019-09-12 15:42 UTC, yoyobatty commented
Science mains seething.

2019-09-12 15:47 UTC, diegoxt45 commented
> Science mains seething.

oranges 2 in hippie? like; yes sad: no

2019-09-12 16:48 UTC, notoriousBIGGIOS commented
scientist main here
gets stolen every round anyway by some Lisa Green wannabe
+1

2019-09-12 16:55 UTC, ghost commented
yeah its shit just make it a HEV suit

2019-09-12 18:57 UTC, Manly-Dwarf commented
A reminder that the RTA was removed from the RD's locker, just like this PR, pre-rebase 2016.
https://github.com/HippieStationArchive/HippieStation13-1/pull/1872 (was closed)
https://github.com/HippieStationArchive/HippieStation13-1/pull/1921
That's right, even in our glory days we didn't want this damn thing because it sucks.
I would prefer if Yoyobatty replaced it with something that actually helps the RD do his job, but if anyone can tell me HOW the RTA actually helps the RD do his job, and why it's more than just a combat powergame item, you can justify it staying around.
Yes, the removal/nerf shit is garbage and I don't like it. We disconnected from TG for this very reason. That doesn't change that the RTA is complete dogshit and has been dogshit for years.
Also having to fight a powergaming RD as a gangster just to have your teammates fuck you over by shooting the RD when he has the RTA on is nothing short of infuriating.

The pre-rebase PRs have the same arguments we have here; that plain removal is boring. At least the RTA and other reactive armors are already in Research so Yoyo's job is done for him.
At its fundamental core, the RTA is a bad item. Instantly bailing you out of any situation is worth any risk it might give you, whether it be rads or otherwise, especially because you can get bailed out on complete accident and get locked in a random room neither of you have access to, and even then you can't tell what room the RD even ended up in.
Sure, you could add a tracer to the RTA so where the RD ends up, you'll immediately see. That doesn't really matter as if it's in an area you have to break into, you'll likely waste all of the stun duration or damage you've had on the RD just breaking in as he then proceeds to get up, use a hand teleporter, and start screeching that you're a traitor over comms.
Combine this with someone who isn't actually an RD, someone who is actually out to powergame, and you have some serious shit. Even the space problem is hardly a problem thanks to the existence of Cryoxadone, if you're robust and you're using the RTA, you should be carrying that shit around any way. That's what Camille, Cappy and all the other actually good players did when the RTA wasn't removed way back when.
So it's RNG combat, it gives a massive advantage to the person wearing it at little cost, the cost can be mitigated on top of that, and is a pure powergame item.
Justify this in terms of game design, not just "stop removing shit." The latter part does not need much argumentation, removals without anything new are boring and bad. But as I've pointed out, it's not like this thing being removed is a new idea for HippieStation.

2019-09-12 19:02 UTC, Manly-Dwarf commented
Since this technically has the same functionality as the 2016 RTA now (being that you have to research it), this is marked as an Old Hippiestation Port.

2019-09-12 19:07 UTC, Manly-Dwarf commented
@diegoxt45 so this means what you wanted is fulfilled. if for some reason it's NOT then I'll get yoyo to add it to this PR

2019-09-12 19:13 UTC, SireTurret commented
Okay, after Manly unleashed his unholy rage upon me I actually agree with some of his statements.

The RTA is something which was solely used for powergaming, can't argue with that. Moving it to R&D means people will start researching stuff if they want to powergame, which is good.

I'd also like it if there was a replacement for the RTA which wouldn't be useless (like a HEV suit having VOX how is that useful lunaman bro) and will actually make people do their job.

2019-09-12 19:13 UTC, Manly-Dwarf commented
That is something that's necessary, yes. Some suit that could replace the RD's hardsuit that he could upgrade with time would actually be a good middle ground. Sure it'd still likely be a combat powergame item but at least it's not the damn RTA.

2019-09-12 19:49 UTC, enthethan commented
You pose a very good point @kbb I still dislike the removal with no compensation I think this should be put on hold until rd gets a non powergamey replacement maybe like an unique jetpack or idk some shit like that

2019-09-12 19:52 UTC, Manly-Dwarf commented
Going to see if I can manage to either code a hardsuit myself or force Yoyobatty to. It'll probably just be a weird gimmicky suit that can be upgraded with chips that you research and produce.

2019-09-12 19:55 UTC, enthethan commented
I think rds hardsuit should become cooler not any resistances added just cooler maybe like an integrated special jetpack like flightsuits

2019-09-12 20:03 UTC, yoyobatty commented
I can code a mean hardsuit. See: nanosuit

2019-09-12 22:32 UTC, Majick1 commented
Like I suggested earlier, slot in a random high tier data disk, non combat nanite module or non hulk genetics sequence per round to make up for it

2019-09-13 01:55 UTC, WarRage333 commented
Just replace one of The subpart bootleg anomaly core armors with rta just which one

2019-09-13 02:01 UTC, yoyobatty commented
RTA can already be made: https://github.com/HippieStation/HippieStation/blob/master/code/modules/clothing/suits/reactive_armour.dm

2019-09-14 00:50 UTC, GuyonBroadway commented
Compromise, make the RD start with a random anomaly core in their locker so they can build some variation of reactive armour once the pertinent tech is unlocked.

2019-09-14 01:05 UTC, yoyobatty commented
That's not a bad proposal

2019-09-14 01:16 UTC, WarRage333 commented
Phazons retardedly cheap to make tho

2019-09-14 01:21 UTC, Majick1 commented
At least it would make phazon a viable option most rounds

2019-09-14 04:12 UTC, Manly-Dwarf commented
don't like that idea, as there's a chance the RD starts with the core for the reactive stealth armor
which is like the RTA but on steroids

2019-09-14 09:53 UTC, enthethan commented
You still nees the research and mats for it though which can never come or come late

2019-09-14 11:26 UTC, cris5311 commented
@yoyobatty remove it as traitor item or nerf the item itself. Both are fine with me. Just dont remove it while keeping it as traitor item. That just encourages murderboning if you cant greentext anyway.

2019-09-14 11:57 UTC, Fikou commented
remove it from traitor objective

2019-09-14 17:28 UTC, ghost requested changes
https://github.com/HippieStation/HippieStation/blob/master/code/game/gamemodes/objective_items.dm#L85
It still exists as an objective item to steal.

2019-09-20 14:15 UTC, yoyobatty commented
> https://github.com/HippieStation/HippieStation/blob/master/code/game/gamemodes/objective_items.dm#L85
> It still exists as an objective item to steal.

Fixed

2019-09-21 16:52 UTC, cris5311 commented
> > https://github.com/HippieStation/HippieStation/blob/master/code/game/gamemodes/objective_items.dm#L85
> > It still exists as an objective item to steal.
> 
> Fixed

+1, as promised

2019-09-21 18:48 UTC, AnthonyJNgo commented
The difference between TG and us is that this isn't suggesting we remove the item from the game entirely. RTA will still exist, it just won't be a roundstart freebie. +1.

2019-09-29 00:34 UTC, AnthonyJNgo commented
I realize this is a bit unpopular, however after careful consideration I have decided that it really is a necessary balance move that needs to be made. RTA will still be in-game, it just will not be a freebie. I'll keep an eye out on rounds and how this plays out from here on out and see if it was a good move or not, but I am confident this is good.

2019-09-29 00:34 UTC, merged