Tg machine components
HippieStation/HippieStationdeprecated2020 pull request #12030
Opened 2019-09-17 13:55 UTC by yoyobatty

https://github.com/tgstation/tgstation/pull/46486
https://github.com/tgstation/tgstation/pull/46485
https://github.com/tgstation/tgstation/pull/46502
https://github.com/tgstation/tgstation/pull/46560
https://github.com/tgstation/tgstation/pull/46568
https://github.com/tgstation/tgstation/pull/46570

Haven't had a chance to fully test this, but it's basically just code improvements and a handful of fixes. Also maintains some of our stuff as well.

2019-09-17 21:48 UTC, steamp0rt commented on code/game/machinery/doors/airlock.dm
> +	else if(istype(C, /obj/item/doorCharge))
door charges still exist? wtf

2019-09-17 21:49 UTC, ghost requested changes
shouldn't you add `spaceship_navigation_beacon.dm` to the hippie dme?

2019-09-18 00:31 UTC, yoyobatty commented
> shouldn't you add `spaceship_navigation_beacon.dm` to the hippie dme?

yes

2019-09-18 00:32 UTC, yoyobatty commented on code/game/machinery/doors/airlock.dm
> +	else if(istype(C, /obj/item/doorCharge))
For us, yes.

2019-09-18 00:42 UTC, ghost submitted a review, later dismissed

2019-09-20 21:41 UTC, ghost approved these changes

2019-09-20 21:42 UTC, ghost requested changes
fix the runtimes
```
[00:49:55] Runtime in gravitygenerator.dm,82: Cannot execute null.get status().

  proc name: get status (/obj/machinery/gravity_generator/part/get_status)

  src: the gravitational generator (/obj/machinery/gravity_generator/part)

  src.loc: the floor (112,123,2) (/turf/open/floor/plasteel/dark)

  call stack:

  the gravitational generator (/obj/machinery/gravity_generator/part): get status()

  the gravitational generator (/obj/machinery/gravity_generator/part): update icon()

  the gravitational generator (/obj/machinery/gravity_generator/part): power change()

  the gravitational generator (/obj/machinery/gravity_generator/part): LateInitialize()

  Atoms (/datum/controller/subsystem/atoms): InitAtom(the gravitational generator (/obj/machinery/gravity_generator/part), /list (/list))

  the gravitational generator (/obj/machinery/gravity_generator/part): New(0)

  the gravitational generator (/obj/machinery/gravity_generator/main/station): setup parts()

  the gravitational generator (/obj/machinery/gravity_generator/main/station): Initialize(1)

  Atoms (/datum/controller/subsystem/atoms): InitAtom(the gravitational generator (/obj/machinery/gravity_generator/main/station), /list (/list))

  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)

  Atoms (/datum/controller/subsystem/atoms): Initialize(29887)

  Master (/datum/controller/master): Initialize(10, 0, 1)
```

2019-09-20 21:44 UTC, yoyobatty commented
> fix the runtimes
> 
> ```
> [00:49:55] Runtime in gravitygenerator.dm,82: Cannot execute null.get status().
> 
>   proc name: get status (/obj/machinery/gravity_generator/part/get_status)
> 
>   src: the gravitational generator (/obj/machinery/gravity_generator/part)
> 
>   src.loc: the floor (112,123,2) (/turf/open/floor/plasteel/dark)
> 
>   call stack:
> 
>   the gravitational generator (/obj/machinery/gravity_generator/part): get status()
> 
>   the gravitational generator (/obj/machinery/gravity_generator/part): update icon()
> 
>   the gravitational generator (/obj/machinery/gravity_generator/part): power change()
> 
>   the gravitational generator (/obj/machinery/gravity_generator/part): LateInitialize()
> 
>   Atoms (/datum/controller/subsystem/atoms): InitAtom(the gravitational generator (/obj/machinery/gravity_generator/part), /list (/list))
> 
>   the gravitational generator (/obj/machinery/gravity_generator/part): New(0)
> 
>   the gravitational generator (/obj/machinery/gravity_generator/main/station): setup parts()
> 
>   the gravitational generator (/obj/machinery/gravity_generator/main/station): Initialize(1)
> 
>   Atoms (/datum/controller/subsystem/atoms): InitAtom(the gravitational generator (/obj/machinery/gravity_generator/main/station), /list (/list))
> 
>   Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
> 
>   Atoms (/datum/controller/subsystem/atoms): Initialize(29887)
> 
>   Master (/datum/controller/master): Initialize(10, 0, 1)
> ```

This is a TG thing and no, I won't since TG hasn't and I have no idea how to fix them.

2019-09-20 21:46 UTC, ghost approved these changes
apparently tg has the runtime too so /shrug

2019-09-20 21:46 UTC, merged