Sawn-off Shotgun Invisibility Fix
HippieStation/HippieStationdeprecated2020 pull request #12079
Opened 2019-09-19 14:31 UTC by IHadMyUsernameTaken

## Changelog
:cl:
fix: All sawn-off shotguns are visible again.
/:cl:

## About The Pull Request
The change done in #12024 made all shotguns except the riot shotgun (doesn't apply to contenders either, but we don't consider them here) use the projectile.dmi file with the newer sprites.
Due to this change, only the sawn-off riot shotgun would have a visible sprite; the file with the new sprites doesn't have any icon state for sawn-off shotguns such that they would have "-sawn" in their name, which was assumed to be true for all sawn-off guns in the update_icon proc of ballistic guns.

I made all shotguns use the projectile.dmi file with the old sprites for their icon states, since to me it seemed that the change I mentioned above wasn't intentional, and make the update_icon proc use "_sawn" to form the name of the sawn-off weapon's icon state for when someone either intentionally or not happens to make a shotgun use the other projectile.dmi file; icon states of the sawn-off shotguns in the Hippie station projectiles.dmi file had to be renamed to use "_sawn" to take this change into account.

The comment about the sawn-off shotgun sprite fix didn't seem relevant to me anymore, since it was only added due to the change from using an underline to a hyphen that I had done, so I removed it.

Fixes #12032.

## Why It's Good For The Game
This should make all sawn-off shotguns have visible sprites regardless of which projectiles.dmi file you decide to use and make them use their old sprites again, since the change to the newer ones most likely wasn't intended.

2019-09-19 15:28 UTC, yoyobatty requested changes

2019-09-19 15:28 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic.dm
> +		icon_state = "[unique_reskin[current_skin]][sawn_off ? "_sawn" : ""]"
Leave the //hippie edit in

2019-09-19 15:28 UTC, yoyobatty commented on code/modules/projectiles/guns/ballistic.dm
> +		icon_state = "[initial(icon_state)][suppressed ? "-suppressed" : ""][sawn_off ? "_sawn" : ""]"
Add //hippie edit

2019-09-20 07:03 UTC, IHadMyUsernameTaken commented on code/modules/projectiles/guns/ballistic.dm
> +		icon_state = "[initial(icon_state)][suppressed ? "-suppressed" : ""][sawn_off ? "_sawn" : ""]"
The comments should be added now.

2019-09-20 14:19 UTC, yoyobatty approved these changes
You sure this doesn't break anything?

2019-09-20 14:40 UTC, IHadMyUsernameTaken commented
I haven't seen anything pointing to that direction from local testing at least.

2019-09-28 02:29 UTC, merged