makes holoparasite ability scout a reasonable amount
HippieStation/HippieStationdeprecated2020 pull request #12086
Opened 2019-09-21 03:26 UTC by diegoxt45

🆑
balance: scout now costs 1 points.
/🆑

why did this cost 3 points

2019-09-21 03:32 UTC, ghost requested changes

2019-09-21 03:32 UTC, steamp0rt commented on hippiestation/code/modules/guardian/abilities/minor/snares.dm
>  /datum/guardian_ability/minor/snare
that isn't scout

2019-09-21 03:33 UTC, diegoxt45 commented on hippiestation/code/modules/guardian/abilities/minor/snares.dm
>  /datum/guardian_ability/minor/snare
oh yeah.....

2019-09-27 22:31 UTC, Manly-Dwarf commented
+1

2019-09-28 00:38 UTC, ghost approved these changes

2019-09-28 00:39 UTC, merged