Saying "owo" or "uwu" now gives you brain damage
HippieStation/HippieStationdeprecated2020 pull request #12096
Opened 2019-09-22 10:27 UTC by SireTurret

[Guidelines]: # 

## Changelog
:cl:Turret
add: Furfags eternally BTFO.
/:cl:

## About The Pull Request

This is pretty self-explanatory.
## Why It's Good For The Game

because no one likes furries here

2019-09-22 10:30 UTC, notoriousBIGGIOS commented
+1

2019-09-22 10:33 UTC, notoriousBIGGIOS reviewed
seemsgood

2019-09-22 12:03 UTC, ghost requested changes

2019-09-22 12:03 UTC, steamp0rt commented on hippiestation/code/modules/mob/living/say.dm
> +	if(findtext(message, "owo"))	//You're a furfag and should die
```if(findtext(message, "rouge") || findtext(message, "owo") ||| findtext(message, "uwu"))```

2019-09-22 14:26 UTC, ghost submitted a review, later dismissed

2019-09-22 16:32 UTC, TrickyDickRichard commented
yes

2019-09-22 16:32 UTC, SireTurret commented
speedmerge

2019-09-22 18:29 UTC, Majick1 commented
+1

2019-09-23 11:36 UTC, mikolaj007 commented
-1 UwU

2019-09-23 17:34 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/say.dm
> +	if(findtext(message, "rouge") || findtext(message, "owo") || findtext(message, "uwu")) //thanks steamp0rt
At this point I feel like we should setup some config file and have the code check through everything in said config for dumbo words.

2019-09-24 17:06 UTC, WarRage333 commented
![](http://1.media.dorkly.cvcdn.com/63/80/660afd65c095aa1b7dfb8fd28286ee86-simcity-regrets.jpg)

2019-09-25 17:13 UTC, karmaisblackandbluepilled commented
+1 i am racist against furries

2019-09-27 10:50 UTC, ghost submitted a review, later dismissed

2019-09-28 15:09 UTC, AnthonyJNgo submitted a review, later dismissed
Added nya and hola to this

2019-09-29 00:19 UTC, AnthonyJNgo approved these changes

2019-09-29 00:19 UTC, merged