Adds the Auto-Doc Mark IX
HippieStation/HippieStationdeprecated2020 pull request #12128
Opened 2019-09-29 21:47 UTC by steamp0rt

:cl:
add: Added the Auto-Doc Mark IX, a machine capable of performing most surgeries automatically!
/:cl:

[Video of the autodoc in action](https://streamable.com/9tuk5)

2019-09-29 22:28 UTC, diegoxt45 commented
reduce the time the surgery takes and we'l be GOOD

2019-09-29 22:29 UTC, diegoxt45 commented
also add e-mag functionality

2019-09-29 22:33 UTC, steamp0rt commented
@diegoxt45 the more you upgrade it, the faster it goes.

also if you emag it, it'll give the next/current guy a fate worse than death.

2019-09-29 22:34 UTC, diegoxt45 commented
> @diegoxt45 the more you upgrade it, the faster it goes.
> 
> also if you emag it, it'll give the next/current guy a fate worse than death.

which is...

2019-09-29 22:34 UTC, steamp0rt commented
they'll be nuggeted, given severe brain damage, and have their screen shake for a while. also they'll slur.

2019-09-29 22:35 UTC, diegoxt45 commented
> they'll be nuggeted, given severe brain damage, and have their screen shake for a while. also they'll slur.

sounds like a fun gimmick

2019-09-29 22:56 UTC, MaterialisticThings commented
+1

2019-09-29 22:57 UTC, karmaisblackandbluepilled commented
+1 can't wait for viv to veto it

2019-09-29 23:06 UTC, Majick1 commented
+1 for the item itself yeah

2019-09-30 05:26 UTC, GuyonBroadway commented
This is something I've wanted for literal years.

Like since 2015.

2019-10-03 10:52 UTC, cris5311 commented
+1

2019-10-04 14:43 UTC, diegoxt45 commented
why ins't this merged yet

2019-10-05 06:37 UTC, Maroonenahmoron commented
This looks like a fantastic machine to add in, I’ll give this my +1

2019-10-05 22:19 UTC, AnthonyJNgo commented
This just sounds unbalanced as hell, but it's popular, so I'm open to being told how it isn't gamebreaking.

2019-10-05 22:28 UTC, steamp0rt commented
@AnthonyJNgo 

1. it takes 55k techweb points total to unlock.  
2. if someone finds you in it, and emags it, you're at their mercy.
3. you can't stop the surgery once it's started. this is bad if someone clicks on a bad surgery before you click on a good one.  
4. it can't do brainwashing, organ removal, or stun reduction surgery.

2019-10-05 22:45 UTC, yoyobatty commented
Any checks if it gets destroyed in the middle of surgery ?

2019-10-05 23:07 UTC, steamp0rt commented
@yoyobatty 
```
/obj/machinery/autodoc/Destroy()
	active_surgery.complete()
	open_machine()
	return ..()
```

yes

2019-10-06 01:02 UTC, epicss13gamer commented
Woot woot better autosurgeon +1

2019-10-06 08:45 UTC, WarRage333 commented
You can do any self surgery in under a minute, its really not overpowered lmao

2019-10-06 15:18 UTC, diegoxt45 commented
also +1

2019-10-07 12:37 UTC, yoyobatty commented on hippiestation/code/game/machinery/autodoc.dm
> +			victim.emote("scream")
Jesus Christ, how horrifying.

2019-10-07 12:41 UTC, yoyobatty requested changes

2019-10-07 12:41 UTC, yoyobatty commented on hippiestation/code/game/machinery/autodoc.dm
> +/obj/machinery/autodoc/emag_act(mob/user)
Probably log this proc.

2019-10-07 12:42 UTC, yoyobatty commented
Code looks good, I would like to test this myself to see if I can come with any possible ways to break this.

2019-10-07 13:36 UTC, WarRage333 commented
What would happen if you get teleported away mid surgery by bluespace dust ingestion or genetic power random teleport

2019-10-07 22:23 UTC, yoyobatty approved these changes

2019-10-07 22:24 UTC, merged