Re-opens SM cider
HippieStation/HippieStationdeprecated2020 pull request #12187
Opened 2019-10-17 21:25 UTC by Toxici11i

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Adds the SM cider (not a botany buff i swear...)
/:cl:

## About The Pull Request
Adds a new unique drink, with the chance of spewing an organ, or just simply turning to dust!

## Why It's Good For The Game
Eventually there will be a way for traitors to craft this, for now, its a buff to botany and something to roll for memes as strange seeds.

2019-10-17 21:47 UTC, ElephantSeal commented
at least it isn't nerfing chem.

2019-10-18 00:04 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	..()
that's kinda of a large space

2019-10-18 08:10 UTC, Toxici11i commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	..()
i blame the old coder, will fix

2019-10-22 04:15 UTC, AnthonyJNgo requested changes
Internet died on me and submitted a blank review.

2019-10-22 04:18 UTC, AnthonyJNgo requested changes
Alright my internet spazzed out on me, lets try that review one more time.

2019-10-22 04:18 UTC, AnthonyJNgo commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "who would have thought supermatter was alcoholic"
Can you screenshot this and show what it looks like ingame? I want to make sure the capitalization and everything is correct. The sentence could also be worded a little better. I know it is nitpicky, but it is such a small PR so I feel we should just nip this in the bud. Easy change.

2019-10-22 04:18 UTC, AnthonyJNgo commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "tastes like you're being dusted"
Likewise for this

2019-10-22 04:18 UTC, AnthonyJNgo commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/SMcider/on_mob_life(mob/living/carbon/M)
Just to be clear, this is purely a bad effect item? No good effects whatsoever right? How will people acquire this drink?

2019-10-22 16:18 UTC, Toxici11i commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "who would have thought supermatter was alcoholic"
I wasnt the original opener, i just re-opened it after the old coder del'd their account. Ill do some changes.

2019-10-22 16:19 UTC, Toxici11i commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "tastes like you're being dusted"
on it

2019-10-22 16:19 UTC, Toxici11i commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/SMcider/on_mob_life(mob/living/carbon/M)
Adminbus/strange seeds (the only two ways of rolling it)

can_synth is on so strange seeds can roll it.

2019-10-22 16:57 UTC, AnthonyJNgo approved these changes
Lgtm would like @yoyobatty to also review but this seems pretty straightforward

2019-10-22 16:57 UTC, AnthonyJNgo commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/SMcider/on_mob_life(mob/living/carbon/M)
Lol, nice changes to the description

2019-10-22 17:18 UTC, Toxici11i commented on hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "who would have thought supermatter was alcoholic"
Also, the SM cider will use the default glass sprite (no override defined and no new icons) because the other coder was lazy.

2019-11-03 09:51 UTC, HideAndSeekLOGIC commented
No point in letting this stew, merg time

2019-11-03 09:52 UTC, merged