Dab
HippieStation/HippieStationdeprecated2020 pull request #12202
Opened 2019-10-23 22:22 UTC by AnthonyJNgo

:cl:
add: You can dab now, with fun effects on success and failure!
/:cl:

You can now dab! Doing it correctly will make you do a sick dab and make you trip out a bit. Doing it incorrectly will cause you to scream out something and hurt your brain.

*dab

closes #9909  (It took a YEAR for this to be done and I ended up doing it? Thanks Carbon!)

![KHlJgu95is](https://user-images.githubusercontent.com/38970088/67438618-05b94800-f5c2-11e9-8ff9-db18c101a3b3.gif)

2019-10-23 22:25 UTC, QuarianCommando commented
Seems to be an issue in the code. The brain damage won't proc all the time the way it's written.

2019-10-23 22:27 UTC, Manly-Dwarf commented
No *smug style animation 0/10

2019-10-23 22:29 UTC, Manly-Dwarf commented
also the lines it makes you say are criminally unfunny

2019-10-23 23:06 UTC, AnthonyJNgo commented
They're braindamaged, it's supposed to be ironically unfunny.

2019-10-23 23:10 UTC, Manly-Dwarf commented
criminally unfunny either way

2019-10-23 23:11 UTC, DaydreamPuppeh commented
Why is there no actual dab

2019-10-23 23:27 UTC, ghost approved these changes
dab

2019-10-23 23:30 UTC, Manly-Dwarf commented
this is trash don't actually merge this until it can live up to the hype of a dab emote

2019-10-23 23:41 UTC, AnthonyJNgo commented
@Manly-Dwarf I refuse to live under this dictatorship, I am obviously being singled out for my lack of artistic ability.

2019-10-24 11:59 UTC, actioninja commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +	R.say(pick("CARBON COME BACK PLS!!","WE DON'T EVEN NEED MAINTAINERS!","HIGHPOP BY AUGUST!!"))
based

2019-10-24 12:00 UTC, zamolxius commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +	R.say(pick("CARBON COME BACK PLS!!","WE DON'T EVEN NEED MAINTAINERS!","HIGHPOP BY AUGUST!!"))
based

2019-10-24 12:01 UTC, Dinopeaks commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +	R.say(pick("CARBON COME BACK PLS!!","WE DON'T EVEN NEED MAINTAINERS!","HIGHPOP BY AUGUST!!"))
Based

2019-10-24 12:08 UTC, actioninja commented
I made a dab emote a while ago that tyrannical fruit rejected, among other things it ripped off your arms, could cause special brain traumas, and could break your legs.

2019-10-24 12:11 UTC, zamolxius commented
pr it actioninja

2019-10-24 14:27 UTC, AnthonyJNgo commented
@actioninja @zamolxius Alright I could flesh it out a bit and add some of those things onto it, if it will appease @manly-dwarf

2019-10-25 05:47 UTC, Manly-Dwarf commented
show it off actioninja

2019-10-25 05:52 UTC, actioninja commented
I deleted the branch which had some fixes on it but this is roughly it https://github.com/tgstation/tgstation/pull/43682/files
restraint check doesn't work and you could still do it while cuffed or while missing arms to rip your arms off and escape cuffs.

2019-10-25 06:19 UTC, zamolxius commented
seems like a fair tradeoff

2019-10-25 08:10 UTC, Manly-Dwarf commented
we need to find a good dab sprite and make it appear like the smug emote

2019-10-27 07:54 UTC, karmaisblackandbluepilled commented
-1 because of the braindamage

2019-11-12 03:47 UTC, Maroonenahmoron commented
No animation, no satisfaction

2019-12-14 03:20 UTC, ghost requested changes

2019-12-14 03:20 UTC, HideAndSeekLOGIC commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +		return FALSE // This will tell you that the emote is unusable as well.
the 'Unusable Emote' message is very annoying and should not be there. Fix that and I'll merge.

2020-01-02 08:06 UTC, yoyobatty commented
Stales.

2020-01-02 08:06 UTC, closed without merging