[REVIEW HEAVILY] SCP 173, 999 and 294
HippieStation/HippieStationdeprecated2020 pull request #12224
Opened 2019-10-28 00:06 UTC by Toxici11i

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: added 294, 173 and 999
/:cl:

## About The Pull Request
Adds the Iconic SCPs 294 173 and 999

## Why It's Good For The Game
Lots of people have been wanting it, and with Halloween coming, this would be perfect for a testmerge for the duration - perfect for memebus.

2019-10-28 00:09 UTC, ElephantSeal commented
I like it

2019-10-28 00:35 UTC, ghost requested changes

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	maxHealth = 5000000000
Can just use `INFINITY` here.

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	to_chat(user, "<span class='warning'>SCP 173, Neck Snapper.</span>")
```suggestion
	. = ..()
	. += "<span class='warning'>SCP 173, Neck Snapper.</span>"
```

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +/mob/living/scp_173/Destroy()
Why is this here

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +			var/datum/reagent/D = new path
Can just check `can_synth` instead of doing `- /datum/reagent/medicine/adminordrazine`

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +			spawn(2000)
Do not use `spawn()`

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +	sleep(10)
Do not use `sleep()`

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/safe/scp999.dm
> +	to_chat(user, "<span class='notice'>SCP 999, hug monster</span>")
```suggestion
	. = ..()
	. += "<span class='notice'>SCP 999, hug monster</span>"
```

2019-10-28 00:35 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/safe/scp999.dm
> +	return ..(a,b,f)
```suggestion
	return ..()
```

2019-10-28 09:49 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +	sleep(10)
this is old ass code, on it

2019-10-28 12:21 UTC, Toxici11i commented
![image](https://user-images.githubusercontent.com/26260490/67678015-76bf7d80-f97d-11e9-8ad8-afeaa0ea43dc.png)

2019-10-28 12:26 UTC, WarRage333 commented
Wish we still had 294 as a space ruin
Always good to have more memes

2019-10-28 13:13 UTC, ghost requested changes

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	return ..(a,b,f)
```suggestion
	return ..()
```

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	maxHealth = 5000000000
```suggestion
	maxHealth = INFINITY
```

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	health = 5000000000
```suggestion
	health = INFINITY
```

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +/mob/living/scp_173/Destroy()
Why is this useless piece of code here? Resolving the convo doesn't solve the problem.

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +/obj/machinery/scp294/New()
```suggestion
/obj/machinery/scp294/Initialize()
	. = ..()
```

2019-10-28 13:13 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/safe/scp999.dm
> +	return ..(a,b,f)
```suggestion
	return ..()
```

2019-10-28 13:15 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +/mob/living/scp_173/Destroy()
oh this, i thought i removed it but copypasted it back. it was for when you would dust 173 incase of it somehow dying

2019-10-28 18:56 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +/mob/living/scp_173/Destroy()
resolved

2019-10-28 18:57 UTC, Manly-Dwarf commented
finna get sued by lion

2019-10-28 19:20 UTC, MrHardDrive commented
hopefully

2019-10-28 19:47 UTC, epicss13gamer commented
get you scp13 shit outta here nigga or I will re-request adding cum to the game

2019-10-28 20:09 UTC, Toxici11i commented
> get you scp13 shit outta here nigga or I will re-request adding cum to the game

>scp13
>implying that this is a permanent implementation and not a very temporary thing over haloween

2019-10-28 20:46 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +			var/datum/reagent/D = new path
resolved

2019-10-28 20:54 UTC, ghost requested changes

2019-10-28 20:54 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
> +	..()
```suggestion
```

2019-10-28 20:56 UTC, karmaisblackandbluepilled commented
+1
auuuuuHGAUGAHGUGGUUAUUUG HCOOOOOOOMING

2019-10-28 21:04 UTC, Toxici11i commented
> +1
> auuuuuHGAUGAHGUGGUUAUUUG HCOOOOOOOMING

karma? Liking anything i do?

n a n i

2019-10-28 21:05 UTC, steamp0rt commented
@Toxici11i that's lunaman

2019-10-28 21:05 UTC, Toxici11i commented
> @Toxici11i that's lunaman

this explains everything

2019-10-28 21:05 UTC, karmaisblackandbluepilled commented
inshallah call me karma again and I will strike you with great vengeance and righteous fury

2019-10-28 21:06 UTC, Toxici11i commented
> inshallah call me karma again and I will strike you with great vengeance and righteous fury

as long as you keep giving me funny meme arrows i dont really care what happens to me

2019-10-28 21:06 UTC, Toxici11i commented
This was all tested, should work fine. 999 works fully, and is less spammy since code improvements, 173 is still fucking terrifying like it was in CB and 294 is functional and works perfectly. (cough N-AMINO)

2019-12-01 22:29 UTC, cris5311 commented
+1
make it a sesional thing and/or adminbus

2019-12-02 16:37 UTC, Toxici11i commented
> +1
> make it a sesional thing and/or adminbus

its already adminbus only, they dont spawn anywhere

2019-12-06 22:55 UTC, DON-KARMA commented
scp is for faggots

2019-12-06 23:08 UTC, Toxici11i commented
> scp is for faggots

implying being a rabbi main isnt

2019-12-16 19:15 UTC, qwertyquerty commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +			H.visible_message("<span class='notice'>[H] blinks.</span>")
Why not just make them use the blink emote?

2019-12-16 19:21 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +			H.visible_message("<span class='notice'>[H] blinks.</span>")
because its easier to differentiate, also, just doing blink by itself doesnt blind you here

2019-12-19 16:59 UTC, MaterialisticThings commented
scp 1488

2019-12-19 17:01 UTC, ElephantSeal commented
> scp 1488

http://www.scp-wiki.net/scp-1488

2019-12-19 20:42 UTC, Manly-Dwarf commented
ok can we merge this yet? i'm gonna merge this

2019-12-19 20:47 UTC, merged

2019-12-20 09:19 UTC, Toxici11i commented
AHHHH COOOOOMING AHH HAH HHH HAAA

2019-12-23 08:09 UTC, Manly-Dwarf commented
holy shit this is some of the worst code I have ever seen why did I merge this