Scrake zombie species event [WIP]
HippieStation/HippieStationdeprecated2020 pull request #12311
Opened 2019-11-13 03:27 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Adds the scrake, a zombie like species from Killing Floor
add: Add a very rare random event to spawn a scrake, selecting from a ghost
/:cl:

## About The Pull Request
Title. Scrake is a tank that is very resistant to a lot of damage and gets upset if you attack him too much. He's got a chainsaw, apron and surgical mask much like a real doctor. He's only really good at amputating limbs and your internal organs.

Pics to come soon.

## Why It's Good For The Game
It was supposed to be for Halloween but it I decided to take some time to refine it.

2019-11-23 21:24 UTC, Fikou commented on hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
> +/datum/species/scrake
why not make this a child of zombie, shares lots of trais

2019-11-23 21:25 UTC, Fikou commented on hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_PRIDE | ERT_SPAWN
also putting it into pride mirror might not be the best idea

2019-11-23 21:30 UTC, Fikou commented on hippiestation/code/modules/evil/scrake.dm
> +		FS.volume = 2.0 //big stomper
this might make people gib the guy wearing the scrake stuff and then become scrake themselves by taking the apron

2019-11-30 19:34 UTC, yoyobatty commented on hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
> +/datum/species/scrake
pershaps

2019-11-30 19:34 UTC, yoyobatty commented on hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
> +	changesource_flags = MIRROR_BADMIN | WABBAJACK | MIRROR_PRIDE | ERT_SPAWN
you may be right

2019-11-30 19:35 UTC, yoyobatty commented on hippiestation/code/modules/evil/scrake.dm
> +		FS.volume = 2.0 //big stomper
It should delete upon dropping, I will confirm that

2019-12-04 03:35 UTC, HideAndSeekLOGIC commented on hippiestation/code/modules/uplink/uplink_items.dm
> -	surplus = 10
I don't think this should be in the PR

2019-12-04 03:36 UTC, ghost submitted a review, later dismissed
I don't think I see anything in here that particularly stands out. As long as you tested this (and fix up the nanosuit suprlus thing) I'll merge

2019-12-04 23:18 UTC, ghost requested changes
good enough

2019-12-04 23:18 UTC, steamp0rt commented on hippiestation/code/modules/clothing/scrake.dm
> +	..()
`. = ..()`

2019-12-04 23:18 UTC, steamp0rt commented on hippiestation/code/modules/clothing/scrake.dm
> +	..()
`. = ..()`

2019-12-05 00:33 UTC, ghost approved these changes

2019-12-05 00:57 UTC, merged