[REVERT/PORT]Reverts TG #28851 - Removal Of Cortical Borers
HippieStation/HippieStationdeprecated2020 pull request #12344
Opened 2019-11-23 12:40 UTC by Toxici11i

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Readded cortical borers (The event itself is disabled and i highly recommend against using the gamemode) - ADMINBUS ONLY FOR NOW
/:cl:

## About The Pull Request
Readds cortical borers - adorable headslugs that want nothing more but to snuggle up inside your brain, pump you with heal juice and make you vomit out eggs

## Why It's Good For The Game
These were removed because of "lack of maintainment" AKA tg's way of saying "we dont like them". fuck /tg/, they are awesome

2019-11-23 12:41 UTC, zamolxius commented
based

2019-11-23 12:44 UTC, karmaisblackandbluepilled commented
+1

2019-11-23 12:47 UTC, cris5311 commented
+1

2019-11-23 12:48 UTC, Toxici11i commented
![image](https://user-images.githubusercontent.com/26260490/69478897-82bd2480-0def-11ea-9cea-4c3124ce38d3.png)
travis is being retarded, disregard linter errors

2019-11-23 15:21 UTC, ghost submitted a review, later dismissed
Just some basic things

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_html.dm
> +/mob/living/simple_animal/borer/proc/get_html_template(content)
Why not just do tgui-next?

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_topic.dm
> +		for(var/datum in typesof(/datum/borer_chem))
```
for(var/D in typesof(/datum/borer_chem))
	var/datum/borer_chem/test = D
	if(initial(test.chemname) == topic_chem)
		C = new D
		break
```

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_topic.dm
> +		if(!istype(C, /datum/borer_chem))
Redundant check

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer.dm
> +	borer_chems += /datum/borer_chem/epinephrine
Are you kidding me?

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer.dm
> +			if(victim.reagents.has_reagent("sugar"))
This won't work.

Reagent IDs aren't strings anymore, you use the type now.

2019-11-23 15:21 UTC, steamp0rt commented on hippiestation/code/game/gamemodes/miniantags/borer/borer.dm
> +		if(C.chemname)
Can still do the `initial` trick here.

2019-11-23 15:34 UTC, Toxici11i commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_html.dm
> +/mob/living/simple_animal/borer/proc/get_html_template(content)
im not programming tgui next

also because this already works, we can focus on improvements after the original is in

2019-11-23 15:35 UTC, Toxici11i commented on hippiestation/code/game/gamemodes/miniantags/borer/borer.dm
> +			if(victim.reagents.has_reagent("sugar"))
this will be broken yes, fix it I must

2019-11-23 16:00 UTC, Toxici11i commented
ok i broke something within topic

2019-11-23 16:16 UTC, Toxici11i commented
> Just some basic things

im assuming your initial thing was referencing the large list

2019-11-23 18:18 UTC, Toxici11i commented
Also, the errors are from the linters failing, not sure why. it compiles and works just perfectly. Travis says so itself.

2019-11-23 19:52 UTC, Manly-Dwarf commented
borers are smelly and hardly count as "antags"

2019-11-23 21:02 UTC, Fikou commented
> borers are smelly and hardly count as "antags"

implement them the vg way, nonantag friends that can give you some neat buffs like become a shield/sword/hookshot or heal you and need you to reproduce

2019-11-23 21:09 UTC, zamolxius commented
or make them npcs you coax in your flesh and then expose to different stimuli to make them evolve.  brute damage for carapace/claws,  space for propulsion,  radiation for something else??

2019-11-23 21:11 UTC, Toxici11i commented
> borers are smelly and hardly count as "antags"

why do hiveminds exist then

2019-11-24 16:27 UTC, Toxici11i commented
> or make them npcs you coax in your flesh and then expose to different stimuli to make them evolve. brute damage for carapace/claws, space for propulsion, radiation for something else??

this sounds like ultimate powergame gear, no thank you

2019-11-24 16:57 UTC, Toxici11i commented
ok linting issue fixed. events fixed. this can be implemented now and it should work at near 100%, event will trigger etc

2019-11-27 15:21 UTC, ExpAntique commented
+1 they could be a really good at least side antag if we put some elbow grease into them. I will never understand why /tg/ just purges code out of existence instead of disabling or noting it out.

2019-11-27 16:16 UTC, steamp0rt commented
@ExpAntique yeah, i think their logic is that code that nobody wants to update or maintain is a liability, and it'll slow down any future improvements

that's a load

2019-11-27 17:58 UTC, Toxici11i commented
For now, these will trigger correctly, and spawn in the round as a random event. Ill have to study event code more in depth and do some adjustments to make them occur more frequently(we desperately need more side-antags) while still allowing a fair chance for ayys/other midrounds to occur

also half of the side antags that normally should occur(like nightmare or revenant) never occur unless admins press buttons

2019-12-06 22:55 UTC, DON-KARMA commented
based but port the VG ones

2019-12-06 23:07 UTC, Toxici11i commented
vg borers will make the clown unstoppable

2019-12-14 03:23 UTC, ghost requested changes

2019-12-14 03:23 UTC, ghost commented on code/_compile_options.dm
> -								//uncommented, but not visible in the release version)
why

2019-12-14 03:23 UTC, HideAndSeekLOGIC commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_events.dm
> +	max_occurrences = 0
Are you sure this makes them adminbus-only?

2019-12-14 03:25 UTC, Toxici11i commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_events.dm
> +	max_occurrences = 0
> For now, these will trigger correctly, and spawn in the round as a random event. Ill have to study event code more in depth and do some adjustments to make them occur more frequently(we desperately need more side-antags) while still allowing a fair chance for ayys/other midrounds to occur

also half of the side antags that normally should occur(like nightmare or revenant) never occur unless admins press buttons

read le comments...

2019-12-14 03:26 UTC, Toxici11i commented on code/_compile_options.dm
> -								//uncommented, but not visible in the release version)
i did this to generate a new branch that was 100% up to date

2019-12-14 03:27 UTC, HideAndSeekLOGIC commented on code/_compile_options.dm
> -								//uncommented, but not visible in the release version)
fair enough

2019-12-14 03:27 UTC, HideAndSeekLOGIC commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_events.dm
> +	max_occurrences = 0
Just checked and confirmed

2019-12-14 03:28 UTC, Toxici11i commented on hippiestation/code/game/gamemodes/miniantags/borer/borer_events.dm
> +	max_occurrences = 0
This AKA means that no, they are no longer adminbus only as it stands. they will trigger as an event correctly, and spawn.

2019-12-14 03:28 UTC, ghost approved these changes
if shit breaks then we'll find out soon enough.

2019-12-14 03:28 UTC, Toxici11i commented
> if shit breaks then we'll find out soon enough.

the only thing that could plausibly break is events, since that was the hardest to test. The actual antag and mob itself works so 🤷‍♂

2019-12-14 03:28 UTC, HideAndSeekLOGIC commented
This is adminbus-only so I'll just merge this.

2019-12-14 03:28 UTC, Toxici11i commented
> This is adminbus-only so I'll just merge this.

NO ITS NOOOOT STOOOOP

2019-12-14 03:28 UTC, Toxici11i commented
> > This is adminbus-only so I'll just merge this.
> 
> NO ITS NOOOOT STOOOOP

AAAAAAAAAAAAAAAAA

2019-12-14 03:29 UTC, HideAndSeekLOGIC commented
@Toxici11i max_occurrences = 0

2019-12-14 03:29 UTC, Toxici11i commented
> > > This is adminbus-only so I'll just merge this.
> > 
> > 
> > NO ITS NOOOOT STOOOOP
> 
> AAAAAAAAAAAAAAAAA

The event can still proc, its just raaare

2019-12-14 03:29 UTC, Toxici11i commented
> @Toxici11i max_occurrences = 0

that means unlimited...

2019-12-14 03:31 UTC, HideAndSeekLOGIC commented
@Toxici11i it does not mean unlimited.

2019-12-14 03:31 UTC, Toxici11i commented
> @Toxici11i it does not mean unlimited.

ok then im retard, feel free to merge

2019-12-14 03:32 UTC, merged

2019-12-14 20:02 UTC, mkikt4743 commented
seems cool, please merge

2019-12-14 20:13 UTC, steamp0rt commented
@mkikt4743 are you blind

2019-12-14 20:14 UTC, mkikt4743 commented
no just deaf