New brewing recipes - HGTOW edition
HippieStation/HippieStationdeprecated2020 pull request #12361
Opened 2019-11-26 23:46 UTC by QuarianCommando

## Changelog
:cl:
add: Added a few new drink reagents for brewing.
/:cl:

Added a few new drinks that can only be made through brewing. Made the changes directly to the code instead of putting it in the glorified mod folder because I can't be bothered to make the brewing system work with shit from the hippiestation folder, and because we've separated from tee gee anyway.

Fuck amari, fuck code standards, and fuck TG. HGTOW.

2019-11-26 23:47 UTC, ghost requested changes
> Fuck amari, fuck code standards

🤔

2019-11-26 23:48 UTC, ghost submitted a review, later dismissed
Eh whatever, code looks like it'll work fine. Did you test it?

2019-11-26 23:49 UTC, QuarianCommando commented
Yeah, hence those last two commits. Works fine, although glowing berries creates so many reagents besides wasteland gin that you have to separate them with a reagent grinder to not get a generic failed beverage.

2019-11-27 09:13 UTC, FantasticFwoosh commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_name = "Abrsosia"
Typo, and [the taste is misleading](https://github.com/HippieStation/HippieStation/pull/12361/files#diff-81f7c0a4df6099bec4d42e1d86656c66R2118), honey mixed drinks already exist with mead from actual honey reagents.

> it should stand solo as a mixed drink cocktail with honey to be appropriate or a upgrade/variation over hard cider but that's my opinion seperate from my criticism. Take [mead](https://github.com/HippieStation/HippieStation/blob/f36040b814f46c69ecb66b06cdd8af59e47f3f69/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm#L929) and red-mead for example.

2019-11-27 10:01 UTC, QuarianCommando commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_name = "Abrsosia"
Whole point of the new drinks is to run them through the brewing system so that it has a reason to exist. This may not be a lot, but I plan on having every plant you can grow in hydro have some sort of drink it turns into instead of a generic fruit wine. Obviously making a recipe for all of them would be a problem.

2019-11-27 10:30 UTC, karmaisblackandbluepilled commented
+1 very based

2019-11-28 04:33 UTC, QuarianCommando commented
This just in - AppVeyor is a steaming pile of shit.

2019-12-14 03:12 UTC, ghost approved these changes
code

2019-12-14 03:14 UTC, HideAndSeekLOGIC commented on code/modules/hydroponics/grown/apple.dm
> +	distill_reagent = /datum/reagent/consumable/ethanol/mead/ambrosia
add a `// hippie --` comment everywhere. Or don't. 

Just don't blame me when your PR gets deleted by accident a year later.

2019-12-14 03:16 UTC, ghost requested changes

2019-12-14 03:16 UTC, HideAndSeekLOGIC commented on code/modules/hydroponics/grown/berries.dm
> +	distill_reagent = /datum/reagent/consumable/ethanol/devilskiss
comment here too, you know the drill

2019-12-14 03:16 UTC, HideAndSeekLOGIC commented
@QuarianCommando add the hippie comments and I'll merge this

2019-12-17 09:50 UTC, zamolxius commented
@QuarianCommando

2020-01-02 15:05 UTC, closed without merging