makeshift laser rifle
HippieStation/HippieStationdeprecated2020 pull request #12366
Opened 2019-11-29 13:34 UTC by zamolxius

## Changelog
:cl: AdeptMechanicus and Gorram_Swangs
add: Added a makeshift laser rifle
/:cl:

adds a makeshift laser rifle. Damage and powercell values may need work, give feedback, otherwise the PR is ready for merge

2019-11-29 13:57 UTC, zamolxius commented on hippiestation/code/modules/projectiles/guns/energy/laser.dm
> +	damage = 18
would you rather it be a big ZOOOOP with 20-25 and uses up the whole powercell or a numerous zappity-zap with something like 5-10 damage and shoots 5~ times

2019-11-30 10:12 UTC, zamolxius commented
![dreamseeker_6YoH0QMWBo](https://user-images.githubusercontent.com/29981240/69899122-8f4ef900-136a-11ea-9abd-11b4855b22c2.png)
![dreamseeker_GwMOtyISQ6](https://user-images.githubusercontent.com/29981240/69899126-9413ad00-136a-11ea-8c50-0ea60c3b59bc.png)

ready for merge

2019-11-30 15:23 UTC, Toxici11i commented
add a chance for an "overload" to occur on strong mode when fired, causing it to "explode" - dealing decent burn/brute and have a possbility to dismember your arm

2019-11-30 17:49 UTC, zamolxius commented
based but ill make the damage 30 burn then though

2019-12-01 04:59 UTC, yoyobatty commented on hippiestation/code/modules/projectiles/guns/energy/laser.dm
> +	reflectable = REFLECT_NORMAL
Doesn't it inherit all these vars from laser

2019-12-01 12:15 UTC, zamolxius commented on hippiestation/code/modules/projectiles/guns/energy/laser.dm
> +	reflectable = REFLECT_NORMAL
removed

2019-12-01 22:42 UTC, cris5311 commented
+1
add a "overload" option where it is basically a medium grenade

2019-12-02 16:17 UTC, Manly-Dwarf commented
could be pretty cool, new improvised weapons are always neat

2019-12-04 03:24 UTC, HideAndSeekLOGIC commented on hippiestation/code/datums/components/crafting/recipes.dm
> +				/obj/item/screwdriver)
Take the screwdriver out of `reqs` and put it into
```
tools = list(/obj/item/screwdriver)
```
otherwise, this recipe consooms the screwdriver.

2019-12-04 03:28 UTC, HideAndSeekLOGIC commented on hippiestation/code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/gun/energy/laser/makeshiftLasRifle
remove capitalisation (make it `makeshiftlasrifle`)

2019-12-04 03:29 UTC, ghost requested changes
As long as you tested this, fix up the nitpicks and I'll merge

2019-12-04 13:27 UTC, zamolxius commented on hippiestation/code/datums/components/crafting/recipes.dm
> +				/obj/item/screwdriver)
done

2019-12-04 13:27 UTC, zamolxius commented on hippiestation/code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/gun/energy/laser/makeshiftLasRifle
done

2019-12-04 15:47 UTC, ghost approved these changes

2019-12-04 15:47 UTC, HideAndSeekLOGIC commented
I'll take @Manly-Dwarf 's comment as a +1. Merg time.

2019-12-04 15:47 UTC, merged