removes a MLP reference [is #12431]
HippieStation/HippieStationdeprecated2020 pull request #12435
Opened 2019-12-18 07:45 UTC by zamolxius

is #12431 but redone
## Changelog
:cl: zamolxius & Elephant Seal
fix: fixed a My Little Pony: Friendship is Magic reference in the codebase
/:cl:

2019-12-18 08:00 UTC, FantasticFwoosh commented
You can just set it up so that it closes:#prnum so that it'd do it autonomously via git keyword but its good that you took the user feedback of that thread on board.

2019-12-18 08:03 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
i would condense this, probably to just the first sentence

2019-12-18 08:05 UTC, Toxici11i commented
/tg/ moment

2019-12-18 08:10 UTC, HideAndSeekLOGIC commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
No

2019-12-18 08:10 UTC, ghost submitted a review, later dismissed
This is a based PR.

2019-12-18 08:11 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
why, the way it is now is chatspammy

2019-12-18 08:12 UTC, HideAndSeekLOGIC commented
+1 this is in the spirit of Hippie

2019-12-18 08:14 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
make it less chat spammy god dammit it's literally just a whole wikipedia page paragraph

2019-12-18 08:16 UTC, zamolxius commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
the beta tg sentence vs the CHAD HIPPIE INFODUMP

2019-12-18 08:27 UTC, Toxici11i commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
stop being a faggot, the shotgun has an entire copypasta as its description.

2019-12-18 08:29 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
> stop being a faggot, the shotgun has an entire copypasta as its description.

because it's a copypasta faggot
just change it to something like this 
The name applejack is derived from the traditional method of producing the drink, jacking, which refers to the practice of freeze-distilling, which was used to make the beverage. This method of distilling meant that the drink historically easier, but the product was more expensive than grain alcohols.

2019-12-18 08:29 UTC, Toxici11i commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
aka "its in the spirit of hippie" or "stay mad you inane faggot"

2019-12-18 08:31 UTC, TrickyDickRichard commented
-1 until the desc gets changed call me mad again

2019-12-18 08:32 UTC, Toxici11i commented
+1 fuck trickydick hes an unfun faggot

2019-12-18 11:19 UTC, mikolaj007 commented
+0, pointless PR, but im not gonna stop you

2019-12-18 11:32 UTC, HideAndSeekLOGIC commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
TrickyDick is wrong. @zamolxius, leave the whole article. Dick is outvoted.

2019-12-18 11:56 UTC, HideAndSeekLOGIC commented
Think that other PR had enough approvals, merg time

2019-12-18 12:00 UTC, ghost submitted a review, later dismissed

2019-12-18 12:00 UTC, HideAndSeekLOGIC commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "like you should shoot some redskins"
"You can taste" is the message that pops up when you taste something. The taste_description here should be changed to make more sense.

2019-12-18 16:45 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	taste_description = "like you should shoot some redskins"
i think it was supposed to say "you feel like you could shoot some redskins" but i guess that was for the description actually just make it say "apple cider with added death"

2019-12-18 16:47 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
im not outvoted for shit neither of these other people are designers

2019-12-18 16:48 UTC, TrickyDickRichard commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "juice, for adults."
why

2019-12-18 16:54 UTC, zamolxius commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	description = "juice, for adults."
ah,  accident

2019-12-18 17:45 UTC, TrickyDickRichard commented
i dont know how to use github is the description changed

2019-12-18 17:52 UTC, zamolxius commented
ill do it tomorrow

2019-12-19 12:37 UTC, zamolxius commented
merge

2019-12-19 18:30 UTC, Manly-Dwarf requested changes
why is there an entire wikipedia paragraph
tl;dr you plagiarist

2019-12-19 20:53 UTC, Manly-Dwarf commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	glass_desc = "The name applejack derives from the traditional method of producing the drink, jacking, the process of freezing fermented cider and then removing the ice, increasing the alcohol conten
```suggestion
	glass_desc = "Applejack is created by distilling cider via a method known as jacking, where the beverage is frozen and the ice is removed, leaving only the alcoholic content."
```
"hey can i copy your homework"
"yeah just change it so the teacher can't tell"

2019-12-19 21:21 UTC, TrickyDickRichard commented
> why is there an entire wikipedia paragraph
> tl;dr you plagiarist

exactly look at these nogs

2019-12-19 22:03 UTC, Manly-Dwarf approved these changes

2019-12-19 22:06 UTC, TrickyDickRichard commented
+1 epic now

2019-12-20 00:16 UTC, HideAndSeekLOGIC commented
@Manly-Dwarf that's the joke you cancerous bollock

2019-12-20 02:31 UTC, boodaliboo commented
+1 hahahahha p[acman

2019-12-20 04:18 UTC, HideAndSeekLOGIC commented
alright, merging

2019-12-20 04:18 UTC, merged

2019-12-20 09:19 UTC, Toxici11i commented
hasbro gonna finna sue us for copyright infingement on the applejack icon btw