WOOOO REMOVING MOST RESTRICTIONS HAHAHAHA
HippieStation/HippieStationdeprecated2020 pull request #12447
Opened 2019-12-21 21:57 UTC by Toxici11i

Changelog
🆑
del: removed 90% of the "restricted" statechange shit
/🆑

About The Pull Request
lunaman told me to do it - Im removing most of the restrictions on statechanges

Why It's Good For The Game
Let me make goddamn mutation toxin knives - also bleach knives lmao

For real though this will have issues ((probably)) because I believe certain stuff WAS blacklisted for a reason. I kept ((most)) of the gases there but removed plasma
Tell me if any shit that was disabled due to bugs was removed.

2019-12-21 21:58 UTC, karmaisblackandbluepilled commented
+1 Allah bless you.

2019-12-21 22:03 UTC, ghost requested changes
No. All of these were disallowed from being statechanged FOR A REASON.

2019-12-21 22:03 UTC, karmaisblackandbluepilled commented
I will put this at the hands of the designers, they will be the ones to cast the vote.

2019-12-21 22:09 UTC, mikolaj007 commented
im neutral on mutation toxin, on one hand it's a funny gimmick making the entire station felinids, on the other hand it's unfunny when spammed, and im pretty sure it was spammed quite a bit.
+0
neurotoxin got nerfed, so i got nothing against it being removed from the list +1

i don't know why most of these were blacklisted, but i assume that there's a good reason for most of em.

2019-12-21 22:25 UTC, Toxici11i commented
> im neutral on mutation toxin, on one hand it's a funny gimmick making the entire station felinids, on the other hand it's unfunny when spammed, and im pretty sure it was spammed quite a bit.
> +0
> neurotoxin got nerfed, so i got nothing against it being removed from the list +1
> 
> i don't know why most of these were blacklisted, but i assume that there's a good reason for most of em.

mutation toxin takes warhammers to convert you in 1 hit, on a 20s delay
things like watervapour, bleach and capsacin were blacklisted because they "may break stuff" or are "too op"
mutation toxin and neuro was blacklisted because "OP"
the rest had decent reasons
smokepowder was potentially universe breaking

2019-12-21 22:34 UTC, Toxici11i commented
![image](https://user-images.githubusercontent.com/26260490/71314507-802b0a80-2441-11ea-974b-1dc2f17f95c4.png) - space cleaner
https://cdn.discordapp.com/attachments/276456582500319244/658073578427777040/unknown.png - thermite
![image](https://user-images.githubusercontent.com/26260490/71314518-9fc23300-2441-11ea-874a-93f5c80daa90.png) - bleach
![image](https://user-images.githubusercontent.com/26260490/71314534-e152de00-2441-11ea-905e-2c346dfa3acf.png) - water
![image](https://user-images.githubusercontent.com/26260490/71314548-0ba49b80-2442-11ea-84e9-b885c3cf0fcb.png) - neurotoxin

2019-12-21 22:37 UTC, Toxici11i commented
Mutation toxin cannot be put into gas form due to it not having a vapour temp defined

this means you cannot memenade people with it, but still.

2019-12-21 22:52 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/consumable/ethanol/neurotoxin,
this got removed because it was waaaay too op

2019-12-21 22:52 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/carbondioxide,
this is bad

2019-12-21 22:52 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/toxin/plasma,
bad too

2019-12-21 22:53 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/smoke_powder,
bad

2019-12-21 22:53 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/consumable/sugar,
sugar already creates its own sugar pile, may want to test this

2019-12-21 22:53 UTC, yoyobatty commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/mutationtoxin)
ditto to neurotoxin

2019-12-21 22:56 UTC, Manly-Dwarf commented
no we already know why
and chemist buffs suck

2019-12-21 22:57 UTC, Manly-Dwarf commented
also you removed neurotoxin knives
nice try idiot

2019-12-21 22:58 UTC, SireTurret commented
lunaman told me to do it

Well that's all I needed to know. 

-1

2019-12-21 23:03 UTC, SireTurret commented
i retract my statement but toxic still needs to show us that this is a good PR

2019-12-21 23:14 UTC, Toxici11i commented
> also you removed neurotoxin knives from the blacklist
> nice try idiot

they got nerfed heavily, along with potass + water knives and i am more than willing to back this up with evidence. If you want MORE, testmerge it temporarily, try it ingame.

2019-12-21 23:15 UTC, Toxici11i commented
This is partly to do with reagent application code
`C.reagents.add_reagent(reagent_type.type, max(0, (0.2 * stabby) * max(1, armour_block - armour_penetration)))` changes that make it factor in armor, cap it at a certain amount and the level of "stabby" (sharpness and density) they have.

They also do not chempile under normal circumstances so

2019-12-21 23:16 UTC, Toxici11i commented
https://cdn.discordapp.com/attachments/276456582500319244/658082543832268810/unknown.png

2019-12-21 23:17 UTC, Manly-Dwarf commented
how completely odd
knives used to be really powerful
what changed them

2019-12-21 23:18 UTC, Toxici11i commented
> how completely odd
> knives used to be really powerful
> what changed them

reagent application code got changed drastically from what i can see, and got nerfed. Your more likely to kill yourself from the brute of the potassium knife, or bleed out, than you are to cause a light explosion that will likely only do 10 brute due to the low amount of both potass + water in your bloodstream

(5u of potass + water is harmless in a dispenser, doesnt even damage it)

2019-12-21 23:19 UTC, Toxici11i commented
> how completely odd
> knives used to be really powerful
> what changed them

To put simply, daggers now apply less reagents per stab, and also now factor in your level of armor (jumpsuits have some passive armor) ontop of things like firesuits, spacesuits and armour pieces that esc get

2019-12-21 23:19 UTC, Manly-Dwarf commented
re-buff knives instead then

2019-12-21 23:19 UTC, Toxici11i commented
> re-buff knives instead then

no because that would ruin the entire point of being able to statechange these chems rofl

2019-12-21 23:19 UTC, Toxici11i commented
> re-buff knives instead then

and then let you instaclose that PR because too op

2019-12-21 23:20 UTC, Toxici11i commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/mutationtoxin)
does not

2019-12-21 23:21 UTC, Toxici11i commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/consumable/sugar,
turns to caramel and then to carbon before reaching a vapour state

2019-12-21 23:21 UTC, Manly-Dwarf commented
BUFF KNIVES

2019-12-21 23:21 UTC, Toxici11i commented on hippiestation/code/_globalvars/lists/typecache.dm
> -	/datum/reagent/consumable/ethanol/neurotoxin,
they got nerfed ( the chems ), and the way reagents are now applied also got nerfed

2019-12-21 23:21 UTC, Toxici11i commented
> BUFF KNIVES

only if this goes well and gets testmerged and given a chance to prove its not cringe

2019-12-21 23:33 UTC, Toxici11i commented
Also, for the neuro/bleach/capsa to start having a major effect, i had to stand in it for something like 6 or so seconds before I accumulated enough to start actually having the effects, and that was with 200u or so to cover such a large area.

2019-12-22 01:39 UTC, cris5311 commented
+1 seems fine to me, but ill look into it in detail ~~tomorrow~~ in the morning when i got some sleep

2019-12-22 01:40 UTC, cris5311 commented
Id also +1 a knife buff, not sure about both together might be op but needs testing/number crunching

2019-12-22 01:58 UTC, TrickyDickRichard commented
what of fuck

2019-12-22 11:09 UTC, Toxici11i commented
> Id also +1 a knife buff, not sure about both together might be op but needs testing/number crunching

Yeah, im waiting to see how effective this PR is in play before considering buffing knives, and then scaling knives to how effective/useful they are in play.

If we do both at once the fabled potassium/water meta may work again, and I dont want that at this moment in time.
Any knife buffs will involve adjusting the reagent application upon hit to be slightly higher, and adjusting HOW its applied.

2020-01-02 08:14 UTC, yoyobatty commented
I would add water to the solidified state change blacklist.

2020-01-03 10:48 UTC, Toxici11i commented
> I would add water to the solidified state change blacklist.

why doe? i tested it ingame and all it does is create a small slipzone that wearing the jannie boots or magboots allows you to run at near full speed, or sliding.

I dont see why theres a need to blacklist anything other than gases like plasma (look at the pool for example) unless its an extremely gamebreaking thing

2020-01-03 12:12 UTC, Toxici11i commented
Im re-requesting a review from steamport, as he gave a generic "no, these were restricted for a reason" instead of actually explaining why they were restricted.

2020-01-03 12:22 UTC, zamolxius commented
its retarded, as expected from toxic

mutation toxin knives would make anyone with one invulnerable at melee range as he could just stab anyone constantly and have him constantly drop down and morph

2020-01-03 12:34 UTC, Toxici11i commented
> its retarded, as expected from toxic
> 
> mutation toxin knives would make anyone with one invulnerable at melee range as he could just stab anyone constantly and have him constantly drop down and morph

you retard, this was tested and with evidence. It takes 7-8 hits with a dagger to morph somebody, as it only applies like 0.1u of the reagent per stab.

2020-01-03 12:35 UTC, Toxici11i commented
> its retarded, as expected from toxic
> 
> mutation toxin knives would make anyone with one invulnerable at melee range as he could just stab anyone constantly and have him constantly drop down and morph

Also, on that note, you can still make cryo fluid knives, which literally do upwards of 40 oxygen damage per 4 ticks

2020-01-03 12:51 UTC, zamolxius commented
> > its retarded, as expected from toxic
> > mutation toxin knives would make anyone with one invulnerable at melee range as he could just stab anyone constantly and have him constantly drop down and morph
> 
> Also, on that note, you can still make cryo fluid knives, which literally do upwards of 40 oxygen damage per 4 ticks

doesnt excuse making everything else super strong. restrict that instead of unrestricting these

2020-01-03 13:05 UTC, MrEpicSax commented
+1 big fan.

2020-01-03 13:14 UTC, Toxici11i commented
> > > its retarded, as expected from toxic
> > > mutation toxin knives would make anyone with one invulnerable at melee range as he could just stab anyone constantly and have him constantly drop down and morph
> > 
> > 
> > Also, on that note, you can still make cryo fluid knives, which literally do upwards of 40 oxygen damage per 4 ticks
> 
> doesnt excuse making everything else super strong. restrict that instead of unrestricting these

but it this doesnt make it super strong? this isnt a knife buff, just unrestricting statechanges

2020-01-03 13:14 UTC, zamolxius commented
yes, unrestricts lots of shit. fuck off you always add shit to help yourself. gay

2020-01-03 13:14 UTC, Toxici11i commented
> yes, unrestricts lots of shit. fuck off you always add shit to help yourself. gay

what

2020-01-03 13:17 UTC, Toxici11i commented
> yes, unrestricts lots of shit. fuck off you always add shit to help yourself. gay

If you read the original list, lots of it was restricted for varying reasons that dont actually make sense, like bleach or capsaicin, or water. Im not sure how unrestricting them from statechanging (Freezing/liquid/vapour) changes anything? If you can point out how having capsaicin vapour/water vapour etc would benefit only me, go ahead. Otherwise, stop being an enraged homosexual

2020-01-03 13:51 UTC, diegoxt45 commented
fuck off you retard we all know why this PR exists

2020-01-03 13:59 UTC, Toxici11i commented
> fuck off you retard we all know why this PR exists

fuck off you retard we all know that you neither play, nor intend to anymore
this pr was made because you can make fungal tb knives, cryo fluid knives etc but cant make a condensed capsaicin knife?

yeah ok retard

also how would this PR benefit me exactly?

2020-01-03 14:00 UTC, zamolxius commented
im sure youve found a way, autist

2020-01-03 14:00 UTC, Toxici11i commented
> im sure youve found a way, autist

not really

2020-01-03 14:00 UTC, karmaisblackandbluepilled commented
diego die a violent death you fucking buffoon, stop commenting on shit

2020-01-07 04:46 UTC, AnthonyJNgo commented
Going to have to strike this one down for now. Pitch the idea to one of the other headmins, or even better, a current maintainer/head maintainer, and have them pitch it to the headmins. This PR is simple, but could possibly have **extreme** effects in-game.

2020-01-07 04:46 UTC, closed without merging

2020-01-07 17:21 UTC, Toxici11i commented
dont close pr's that are still in need of voting because you personally do not like it.

2020-01-07 17:41 UTC, Toxici11i commented
> Going to have to strike this one down for now. Pitch the idea to one of the other headmins, or even better, a current maintainer/head maintainer, and have them pitch it to the headmins. This PR is simple, but could possibly have **extreme** effects in-game.

also dwarf literally told me to buff knives in this PR