173 Improvements
HippieStation/HippieStationdeprecated2020 pull request #12478
Opened 2019-12-27 14:51 UTC by Toxici11i

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: better ways of checking for attacks, blinking and some more feedback to the player
/:cl:

## About The Pull Request
Lets 173 attack people in full darkness if blink code isnt running because of how it was done.

## Why It's Good For The Game
This will include other miscellaneous changes that make 173 code more robust, less buggy and more reliable for the player.

2020-01-05 22:40 UTC, ghost submitted a review, later dismissed

2020-01-05 22:44 UTC, Toxici11i commented
travis failing on soundlen stuff from another PR that was merged

2020-01-05 22:55 UTC, Toxici11i commented
temporarily fucked it while im redoing it

2020-01-05 23:00 UTC, Toxici11i commented
Travis will fail because yoyos grapeblast PR is causing issues

2020-01-06 07:29 UTC, Toxici11i commented
Travis fucked and its not the PR

2020-01-07 01:59 UTC, Toxici11i commented
requesting review

2020-01-07 02:09 UTC, ghost requested changes

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				visible_message("<span class='danger'>[src] Crushes [H] with raw force!</span>")
fix capitalization

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				to_chat(src, "<span class='warning'><I>Why would we waste our energy attacking Ourselves?</I></span>")
fix capitalization

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +
unneeded space

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +		if(client)
why not `if(client && can_be_seen(get_turf(loc)))`?

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				visible_message("<span class='danger'>[src] Crushes [H] with raw force!</span>")
fix capitalization

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				to_chat(src, "<span class='warning'><I>Why would we waste our energy attacking Ourselves?</I></span>")
fix capitalization

2020-01-07 02:09 UTC, steamp0rt commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	var/list/our_view = view(src, 23)
Why is "our_view" 23 tiles?!

2020-01-07 03:11 UTC, Manly-Dwarf commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				to_chat(src, "<span class='warning'><I>Why would we waste our energy attacking Ourselves?</I></span>")
```suggestion
				to_chat(src, "<span class='warning'><I>You can't hit yourself!</I></span>")
```

2020-01-07 03:11 UTC, Manly-Dwarf commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				visible_message("<span class='danger'>[src] Crushes [H] with raw force!</span>")
```suggestion
				visible_message("<span class='danger'>[src] crushes [H] with raw force!</span>")
```

2020-01-07 03:12 UTC, Manly-Dwarf commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				visible_message("<span class='danger'>[src] Crushes [H] with raw force!</span>")
```suggestion
				visible_message("<span class='danger'>[src] crushes [H] with raw force!</span>")
```

2020-01-07 03:12 UTC, Manly-Dwarf commented
added suggestions so it'll be really easy to fix the quick shit

2020-01-07 17:22 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	var/list/our_view = view(src, 23)
"our view" is just a variable that defines how long scp-173 can make people blink for

2020-01-07 17:23 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +				visible_message("<span class='danger'>[src] Crushes [H] with raw force!</span>")
the ..() and return is needed or the AI fucks itself

2020-01-07 17:33 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +		if(client)
pointless posting to a non-existent client

2020-01-07 17:34 UTC, Toxici11i commented on hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
> +	var/list/our_view = view(src, 23)
As in, it doesnt set 173's view but simulates a 23 long and 23 wide box going around 173 to detect if people are in range

2020-01-07 17:35 UTC, Toxici11i commented
Done, the 23 view thing is where 173 has a box thats 23x23 around it that if people enter, they start blinking

2020-01-15 20:01 UTC, AnthonyJNgo commented
You need votes and new reviews. You also have merge conflicts that need to be resolved.

2020-01-15 20:13 UTC, Toxici11i commented
> You need votes and new reviews. You also have merge conflicts that need to be resolved.

dont mark things as stale when it isnt reee

2020-01-15 20:14 UTC, Toxici11i commented
> You need votes and new reviews. You also have merge conflicts that need to be resolved.

also @AnthonyJNgo check the merge conflict, its where i modified the statuecode

2020-01-15 20:14 UTC, Toxici11i commented
<<<<<<< patch-19
		if(T && T in targets && T != usr)
=======
		if(T && (T in targets))
>>>>>>> master

2020-01-15 20:14 UTC, AnthonyJNgo commented
One week with no update/commit/comment from the creator of the PR is long enough to be counted as stale. You've replied so I'll remove that.

2020-01-15 20:15 UTC, Toxici11i commented
Not sure why its giving me merge conflicts when all ive done is included an extra bit onto statue.dm as a code improvement

2020-01-15 20:16 UTC, AnthonyJNgo commented
Find the conflict and see what the issue is. Most likely we have merged a pr that does something to one of the related files which is where the conflict is coming from.

2020-01-15 20:16 UTC, Toxici11i commented
> Find the conflict and see what the issue is. Most likely we have merged a pr that does something to one of the related files which is where the conflict is coming from.

nope lmao, thats why im confused

2020-01-15 20:17 UTC, Toxici11i commented
ok fixed it seems

2020-01-19 18:31 UTC, danhibiki commented
I’m ok with these tweaks +1

2020-01-29 22:54 UTC, closed without merging

2020-01-30 09:15 UTC, Toxici11i commented
what the fuck this was merge ready and had 0 conflicts

2020-01-30 09:15 UTC, Toxici11i commented
fucking niggerdel