Dwarves finally coming to the station, this was literally five hours …
HippieStation/HippieStationdeprecated2020 pull request #12491
Opened 2019-12-30 10:35 UTC by AnthonyJNgo

…straight of coding and debugging.
## Changelog
:cl:
add: Dwarves are now a ghost role! They're a bit basic right now, updates coming soon.
del: Beach, Seed Vault, Ash Walkers Syndicate Base, Free Golems, Vet Hospital are all gone now.
tweak: Dwarves is highly experimental, right now they're infinite spawns so if you die due to bugs you can just pop back in.
/:cl:

About The Pull Request

Alright, I wagered a resignation over this PR, so I hope you all understand if it isn't as polished as I wanted it to be. I had THREE different coders delay things on me, AAAAAAAAAAAAAAAAAA. In any case, I worked through the night (started at 11/12, it's 5AM now) and I'm happy to say that we have an extremely basic, but functional version of dwarves. I'll do a tl;dr near the end of this description as well. Basically all ghost roles were removed, and dwarves are replacing them. As it is now I believe dwarves have the same amount of content the other ghost roles had which is very little. Beach bum was just running around on the beach, the plant people just grew plants, and the syndicate roles were honestly garbage. I don't plan on stopping here though, we'll have more things coming, I just wanted literally anything rolled out before the new year came in.

Anyways, here's the tl;dr:

**Additions:**

A part of a snowy Dwarven fortress will now spawn in Lavaland! This is hardcoded to spawn every time, so dwarves will ALWAYS be an available ghost role.

The Altar of Armok is blessed, you can respawn an infinite number of times! This will definitely change, however, for now it can stay like this since I foresee plenty of people dying due to unintended bugs.

Some fluff messages were edited slightly, you most likely won't notice the change.

**Removals:**

All other ghost roles were removed. There is still some golem code and I also left the pirates since those are more of an event than anything.

The ruins associated with those roles were also deleted.

Lavaland atmos has been somewhat gutted. I'll tinker with it more later, but for now it doesn't matter, it's still hostile to humans and it doesn't really affect dwarves.

**Known Issues:**

Dwarves should really either properly breathe CO2, or just have something that binds them to the Z level of their fortress preventing them from raiding the station. As of now they're nobreathe.

Pressure might still harm and kill you as a Dwarf, even though you have the resist traits. I'm looking into this, I'm probably just forgetting something super minor. In any case your starting area is completely habitable and well lit.

The role really shouldn't have infinite uses, but it's fine for now.

There is no way to stop Dwarves from going on station at this point, except for the hazardous Lavaland. Please refrain from doing so, although you wouldn't be able to do anything anyways. Any dwarves seen on the station may be subject to adminbus or punishment.

Obviously the lack of features, but this project is ongoing and will continue to be fleshed out. As it is, I believe it is on par with the removed roles.

![DwarfFortress](https://user-images.githubusercontent.com/38970088/71578378-e52bd380-2ac5-11ea-827a-edd216ae7416.png)

2019-12-30 10:46 UTC, Toxici11i commented
-1
removes both golems and ashwalkers meaning that dwarves have no competition

HGTOW anyone?

Also its not headmin approved just because you made it. stop being gay

2019-12-30 10:49 UTC, zamolxius commented
its cool +1

2019-12-30 10:52 UTC, AnthonyJNgo commented
@Toxici11i I'm not approving my own idea, the idea has been greenlit by former and present Headmins. 
#10769 by KBB, #12365 which was the pre-pr to this one. 
Dwarves will NEVER have competition from ash lizards or golems because neither of those ghost roles have ANY content. Ash lizard is spawn and try to bum rush station, golem is spawn and try to bum rush station. Neither of them have actual gameplay or features. Dwarves is different and will have actual things that you can do such as smithing ores that you mine, crafting, fighting new npcs such as goblin villages, etc.

2019-12-30 11:00 UTC, Jujumatic approved these changes
looks good so far though the lavaland atmos will probably need to be fixed pretty quickly after this goes in, public beta time go

2019-12-30 11:00 UTC, Jujumatic commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +	inherent_traits = list(TRAIT_RESISTLOWPRESSURE,TRAIT_RESISTHIGHPRESSURE,TRAIT_NOBREATH)//temporary nobreath
no high pressure on lavaland but this can be removed once nobreath is fixed too

2019-12-30 11:00 UTC, Jujumatic commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
>  				H.adjustBruteLoss(10)
ow, that's going to trigger every time the tick goes down. hope that doesn't tick too often...

2019-12-30 11:00 UTC, Jujumatic commented on code/game/objects/structures/ghost_role_spawners.dm
> +	of blasphemous elf magic. In the fortress you were..."
filthy ELVES

2019-12-30 11:00 UTC, Jujumatic commented on code/game/objects/structures/ghost_role_spawners.dm
> +	var/dwarfstory = rand(1,2)
this should be pretty easy to expand and make more random stories as dwarves develop, nice

2019-12-30 11:00 UTC, Jujumatic commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +	coldmod = 0
their beards and alcohol will protect them against the snow

2019-12-30 11:00 UTC, Jujumatic commented on code/datums/atmosphere/planetary.dm
> +		/datum/gas/carbon_dioxide=100,
this may cause normal people without o2 canisters to instantly pass out and potentially die

2019-12-30 11:00 UTC, Jujumatic commented on hippiestation/code/modules/surgery/organs/lungs.dm
> +    desc = "A pair of extremely small lungs. They don't look human at all." //this description was bad
maybe you could say they're soaked in alcohol or something idk

2019-12-30 11:04 UTC, AnthonyJNgo commented
Travis having a literal stroke because the maps won't compile. Of course they won't compile, I smashed the delete key on them.

2019-12-30 12:01 UTC, wheezl commented
+1

2019-12-30 12:08 UTC, TheSpartyn commented
At least keep the syndicate base, the comms agent role is a very unique one that dwarves wont replace.

2019-12-30 12:25 UTC, zamolxius commented
yeah agreed with spartyn no need to remove so much content. syndicate base is ok

2019-12-30 12:41 UTC, Pyko1 commented
-1 not really a big fan of removing those templates from the actual code, why not just make them not be a part of the list of possible ruins?

No harm keeping them there, if we ever want to use them again.

2019-12-30 14:05 UTC, GuyonBroadway commented
Yeah why are we nixing all of the lavaland roles anyway? Sounds like trying to sneak in grudgecode on top of features.

2019-12-30 14:07 UTC, steamp0rt commented
@GuyonBroadway cuz dwarves are BETTER

2019-12-30 14:09 UTC, ghost requested changes

2019-12-30 14:09 UTC, steamp0rt commented on code/game/objects/structures/ghost_role_spawners.dm
> +//Dwarves, the ultimate ghost role.
couldn't you have just unticked this file, and made a new one?

2019-12-30 14:19 UTC, Maroonenahmoron commented
-1, I like the enthusiasm but not the removal of other spawners. They’re isolated places for people to learn new techniques for chemistry, mining, botany and surviving in lavaland.

Placeholders for dwarves look good though, how about making their fortress have some wooden flooring? I would love to design a starting base.

2019-12-30 14:20 UTC, GuyonBroadway commented
@steamp0rt it's a modular system jackass, no reason we can't have everything.

2019-12-30 14:50 UTC, AnthonyJNgo commented
Comma agent imo is legitimately terrible.

@guyonbroadway I was told by KBB that Dwarves should be the role that replaces all other lavaland roles since we’ll also be changing lavaland. 

@Maroon they’ll still be able to experiment with those things, and learn to survive in lavaland.

2019-12-30 15:54 UTC, AnthonyJNgo commented on code/game/objects/structures/ghost_role_spawners.dm
> +//Dwarves, the ultimate ghost role.
I could have, yes, but I think we’re going a bit overboard with “stash this away for later”. We want to make the code better, not have a million unused things thrown around in our codebase. This is a direct replacement.

2019-12-30 16:15 UTC, Pyko1 commented on code/game/objects/structures/ghost_role_spawners.dm
> +//Dwarves, the ultimate ghost role.
Codebase size is hardly an issue, and at least personally i believe its always better to keep the code even if the feature is never used in the game again. Someone could still use the code as an example or recycle parts of it.

2019-12-30 16:20 UTC, Pyko1 commented
Yeah even if dwarves are going to be the defacto lavaland race, the other templates should be saved, as if anything else they could be loaded for some gimmic.

Not to mention in future if we run dwarfs 100% of the time, people might get bored and want to see them return once in a while, so then it would be an easy change in configs, instead of having to re-add them.

2019-12-30 17:10 UTC, GuyonBroadway commented
Look me in the eye and say a three way war between assliggers, Lavaland Gaylems and Dorfs isn't the best thing that could happen to lavaland.

2019-12-30 17:12 UTC, KingTerrytheTerrible commented
we dont have the pop for that and you aren't helping our pop issue by leaving

2019-12-30 17:14 UTC, xTrainx commented
Don’t kill lavaland sub people that’s gay

2019-12-30 18:10 UTC, Manly-Dwarf commented
stop voting on this it's already approved
we have said for a long ass time that the other spawners would be removed once dwarves would come in, and only now you noticed?

1: A lot of the spawners take up a huge amount of space and offer legitimately nothing to the round (see: beachbums, who when spawned only murder each other before committing suicide). Or it's the comms agent, who will proceed to lag the server by blowing up the base and metagrudge his killer by stalking him on cameras. Or attempt to read WGW.
The ash lizards are the closest thing to something that has effort, but they're really simple. If Dwarves are going to be as complicated as they are, there's no reason to have these other spawners.
2: The spawners are not maintained and have nothing added to them. For a long time everyone has agreed that they're forgettable. Again, Beach Bums. Now we have a problem with them being removed?
3: There's nothing you can do as any of the spawners that you won't be able to do as a Dwarf. They just take up a ton of space.
4: If the argument is that Lavaland clutter doesn't matter because it's huge, you're forgetting that the Dwarves are going to have actual basebuilding in them and likely aren't going to want to have to deal with being surrounded by massive, useless ghost role ruins.

The most valuable ghost role by far is the syndicate base, and probably the only one I'd consider keeping since its isolated on a lake any way. 80% of rounds it either goes silent or just gets blown up by someone who picked the ghost role while bored, assuming they didn't pick comms agent to start screeching who their killer was over comms.
I do agree it's probably not worthwhile to outright remove the templates from the code.

2019-12-30 18:11 UTC, Manly-Dwarf commented
like who even picks the vetrenarian ghost role
are you seriously telling me "noooo don't remove that" when it does nothing, and Dwarves will already be able to have that neat base
i hope you guys are arguing for the lavalizards/syndi outpost and not that

2019-12-30 18:26 UTC, Manly-Dwarf commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
>  				H.adjustBruteLoss(10)
its only temporary as far as we've concerned, but I've told vivadel a thousand times that it's absolutely atrocious

2019-12-30 18:26 UTC, Manly-Dwarf commented on code/game/objects/structures/ghost_role_spawners.dm
> +	of blasphemous elf magic. In the fortress you were..."
finna rewrite this probably

2019-12-30 18:27 UTC, Manly-Dwarf commented on code/datums/atmosphere/planetary.dm
> +		/datum/gas/carbon_dioxide=100,
its a good thing miners get a lot of those at least

2019-12-30 18:27 UTC, Manly-Dwarf commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
> +	coldmod = 0
join the dwarfcord to find out why

2019-12-30 18:36 UTC, AnthonyJNgo commented
I’m going to make some changes for the dwarf PR. I’ll comment out all the other lavaland roles, I’ll leave the syndicate base, ash lizards, golems in rotation.

2019-12-30 18:38 UTC, AnthonyJNgo commented on hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
>  				H.adjustBruteLoss(10)
I think it’ll go over a lot smoother during actual gameplay, if it doesn’t it’s literally a one line change so no big deal.

2019-12-30 18:40 UTC, AnthonyJNgo commented on code/game/objects/structures/ghost_role_spawners.dm
> +	of blasphemous elf magic. In the fortress you were..."
If you have a better intro thing absolutely, I just made it up on the spot to explain why/how a random patch of snowy mountain terrain landed on lavaland. Once the whole lavaland is converted to snow bio it’ll be different of course.

2019-12-30 18:40 UTC, AnthonyJNgo commented on code/game/objects/structures/ghost_role_spawners.dm
> +	var/dwarfstory = rand(1,2)
Yep. The nice thing about this is the role is decided at roundstart so you can’t just suicide repeatedly to get a different one.

2019-12-30 18:58 UTC, GuyonBroadway commented
Just cus it's been approved in discord doesn't mean it can;t be subject to change following criticism, going "NUH UH DUN DEAL!" is oranges level reasoning.

2019-12-30 19:07 UTC, Manly-Dwarf commented
that's ok, i explained my reasoning here and agree that there's a valid point to be made about the syndi lavaland base. we could probably keep that, replace the comms agent with a botany room, and be good to go. or we could move it to space since there is (or was? dunno if vivadel also removed space roles) a comms agent in space as well as one on lavaland.
comms agent is the real problem with the lavaland base. otherwise it's pretty much fine.

all of the others are bad. golems are only used by nerds like toxic to put a million of them on the station and then run around murderboning since free golems have no orders, so i am not surprised he would vouch for them.

2019-12-30 19:08 UTC, GuyonBroadway commented
Also we should not delete or disable them outright. Just make them not viable for the lavaland spawner.

2019-12-30 19:09 UTC, Manly-Dwarf commented
agreed

2019-12-30 19:09 UTC, GuyonBroadway commented
Who needs nations when you have dwarves vs Ashliggers vs Golems?

2019-12-30 19:12 UTC, Manly-Dwarf commented
dwarves and humans are already going to be the main competing force. i don't think you understand this.
dwarves aren't just able to kill the miners, they are also directly competing with them for the exact same resource. the more they stick around, the more they'll be allowed to thrive. there's a good chance there will be rounds where dwarves or miners don't run into each other at all, and also a good chance that the miners will be wiped out while the dwarves get CO2 tanks and hijack their shuttle.
they don't just exist as a silly lavaland role, they also exist to make mining more interesting and more dangerous. most miners by now already know how to deal with the lacking variety in mobs, and dwarves also gives us an excuse to add more of those.

it might be cool to have a respawn dome where people can 1v1, but we already had that in VR in the past. it might be better to just make a thunderdome not operated entirely by admins and make a system where ghosts can fight each other. i have wanted to do that for a while but i am poopy at code

2019-12-30 19:15 UTC, Toxici11i commented
>>>not implying dwarves will just build 9 spears and become unga spearthrower

2019-12-30 19:17 UTC, Manly-Dwarf commented
![free shrug](https://user-images.githubusercontent.com/33744849/71596873-0b299600-2b0f-11ea-96bb-23a9df7e6203.jpg)

2019-12-30 19:19 UTC, cris5311 commented
-1 dvarves good removing lavaland roles bad

2019-12-30 19:21 UTC, Manly-Dwarf commented
i am genuinely very surprised by how many people, despite me telling them for a year on end that dwarves were going to replace all ghost roles, are now upset that dwarves are doing exactly what they were supposed to do
what is up with you people

2019-12-30 19:22 UTC, cris5311 commented
I mean throw out the vet but the other lavaland roles have uses

2019-12-30 19:23 UTC, Manly-Dwarf commented
yeah we should find a way to merge the botany base and syndie base, and keep those one way or another. completely agree there, those have use.

2019-12-30 19:50 UTC, mkikt4743 commented
dwarfs good +1

2019-12-30 22:31 UTC, GuyonBroadway commented
In a perfect world we could have a system whereby the main "off station mining hazard" is picked randomly or determined by config.

2019-12-30 22:38 UTC, FantasticFwoosh commented
In a perfect world we could finish the Dwarf Ruin + elves/goblin/funstuff bells and whistles side activities that come with and then make the entire thing cost the **_entire ruin budget_** so that we don't have to go full :b: :registered: over removing a ton of content.

2019-12-31 02:25 UTC, cris5311 commented
Also ashliggers make dwarfs more interesting. i mean who dosnt like hunting liggers?

2019-12-31 05:41 UTC, Manly-Dwarf commented
"a ton of content"
did i miss something? barely even a month ago i could talk to everyone about how little and how worthless the ghost role ruins were and how they added almost nothing, and everyone agreed
now suddenly everyone's in a hissy over a proper merging/replacement under the name "dwarves"
also no, ashlizards don't make dwarves more interesting. they really just kind of detract. if we had a higher population, maybe they'd be worthwhile. but what would they do that the dwarves couldn't?
let's keep the syndicate outpost, add botany to it and then we have that perfect world. if you just wanna practice silly stuff, you still can. if you want to compete against the miners, you can (as a dwarf). there's no faults with this way to go as I see it.

i still like that ghost thunderdome idea too

2020-01-01 01:37 UTC, Maroonenahmoron commented
Dwarves good, syndicate base is good... whatever happened to syndicate cargo shuttle? If they could order supplies for “syndicate experiments” then it should be fine to get rid of plant people+golems.

Liggers could be a rare ruin so they don’t take away dwarf glory but make it like an event where they can either interact or war with each other.

The other spawners such as beach bum + veterinarians will be overshadowed so they’re good to be booted out.

2020-01-01 03:32 UTC, Fikou commented
just make the golem ship have a botany room and a chemistry/virology room and theres no need for podmen or syndies lol

2020-01-01 05:31 UTC, TriggeredBoi commented
I've always liked how golems can setup their own RND stuff on their ship and build almost everything from there.
On an especionally long round, I once managed to build an entire working Xenobiology setup.
Golems are cool.

And the Liberator's legacy is a pretty unique item. If the golems really are to be removed, at least move that awesome little box to some other ruin.

2020-01-01 08:04 UTC, Manly-Dwarf commented
gonna be completely honest, might just take the existing code and try to go at another sprint
trying to merge dwarves in this incomplete state without all of this stuff is makin me realize it would just be another ghost ruin. not much is in there yet, and while you can say "yet", that don't change that it's fuckin barren right now and there's no reason to remove the other roles

2020-01-01 08:05 UTC, Manly-Dwarf commented
tl;dr it's WAY too early to merge them, not enough content to justify removals. -1

2020-01-02 14:48 UTC, Fikou commented
@AnthonyJNgo i can pr you a bigger golem ship map for when you finish this to replace podmen and lavaland syndies if you want

2020-01-05 22:18 UTC, mkikt4743 commented
it doesn't fit in with rest of lavaland with the snow and shit, make lavaland snowland first

2020-01-07 04:58 UTC, AnthonyJNgo commented
Update, still actively working on this.

2020-01-14 23:08 UTC, AnthonyJNgo commented
Promise I'll have some more commits out soon, been busy upkeeping other aspects of the server.

2020-01-28 10:49 UTC, FantasticFwoosh commented
Looking kind of stale at the moment, anything you can update us on?

2020-01-28 10:51 UTC, AnthonyJNgo commented
Sorry, I have been pretty busy working on preparing everything for the host swap. Host swap SHOULD be finalized maybe later today and then I’ll be able to get more work on this done. Thanks for the patience.

2020-02-19 09:55 UTC, SireTurret commented
so sad this is nowhere near completion

2020-02-19 12:14 UTC, AnthonyJNgo commented
Yeetus deletus

2020-02-19 13:44 UTC, karmaisblackandbluepilled commented
so sad this is nowhere near completion

2020-02-22 04:18 UTC, AnthonyJNgo commented
This PR will be resubmitted as separate smaller PRs to ensure what we want gets in and what we don't want stays out or gets modified.

2020-02-22 04:18 UTC, closed without merging