Adds extremely trippy sound effects to grape blast
HippieStation/HippieStationdeprecated2020 pull request #12495
Opened 2019-12-31 02:40 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: Grape blast will now cause auditory hallucinations
/:cl:

## About The Pull Request
Title. I'm using the SoundQuery to modify already playing sound files so they become extremely distorted and vivid. 

## Why It's Good For The Game
Muh immersion and trippy effects.

2019-12-31 03:10 UTC, yoyobatty commented
Ignore the linting errors, not corrected for 513.

2019-12-31 22:39 UTC, Manly-Dwarf commented
sure

2020-01-01 00:07 UTC, steamp0rt commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	C.client << sound
SEND_SOUND

2020-01-01 02:01 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	C.client << sound
No u

2020-01-02 06:14 UTC, MaterialisticThings commented
+1 based

2020-01-02 06:16 UTC, MrEpicSax commented
Want it. Need it. Have to have it.

2020-01-02 18:57 UTC, ghost requested changes

2020-01-02 18:57 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/static/list/sounds2 = list()
Unused variable?

2020-01-02 18:57 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/turf/T = locate(C.x + pick(-1, 1), C.y + pick(-1, 1), C.z)
Why change a descriptive name to a less descriptive one

2020-01-02 18:57 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +				sounds = H.client.SoundQuery()
hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm, line 331, column 22:

error: undefined proc: "SoundQuery" on /client

2020-01-02 18:57 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +					if(S.len <= 3)
hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm, line 333, column 10:

error: undefined field: "len" on /sound

2020-01-02 18:57 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +					if(prob(30))
can these animates even stack

2020-01-02 18:58 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/static/list/sounds2 = list()
Was a temporay one for debugging

2020-01-02 18:59 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/turf/T = locate(C.x + pick(-1, 1), C.y + pick(-1, 1), C.z)
Really had no impact since it's only used to spawn the brain hallucination.

2020-01-02 18:59 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +				sounds = H.client.SoundQuery()
It exists, tg stations linting doesn't know of this proc since it's new to 513.

2020-01-02 18:59 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +					if(prob(30))
Yes sir, works good

2020-01-02 19:00 UTC, yoyobatty commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +					if(S.len <= 3)
len is a hidden variable in datum sound, I used sounds2 list to be able to see sound properties and len is infact a variable that isn't documented in byond for sounds, I will probably update the linter so it doesn't complain

2020-01-02 19:03 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	var/turf/T = locate(C.x + pick(-1, 1), C.y + pick(-1, 1), C.z)
Neither here nor there but it seems silly

2020-01-02 19:05 UTC, ghost approved these changes

2020-01-02 20:29 UTC, ghost approved these changes

2020-01-02 20:29 UTC, merged