Fixed Chaplain rolling Anti-Chap Antagonists
HippieStation/HippieStationdeprecated2020 pull request #12645
Opened 2020-03-21 00:36 UTC by ProtozoaPrime

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
fix: Chaplains can no longer roll anti-chaplain antagonists
/:cl:

## About The Pull Request
This adds chaplains to the restricted roles for the "choice" antagonists, stopping them from choosing the devil or vampire roles.

## Why It's Good For The Game
Bug fixes are good for the video game

2020-03-21 01:10 UTC, carlopault commented
+1 speedmerge this

2020-03-23 01:27 UTC, AnthonyJNgo commented on hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
>  	antag_flag = ROLE_TRAITOR
Are you sure this restrics from devil and other antichaplain antags? It looks like it is just traitor.

2020-03-23 01:27 UTC, AnthonyJNgo commented on hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	restricted_roles = list("Cyborg", "Chaplain")
I see you added Chaplain here, which is under the Traitor role.

2020-03-23 01:28 UTC, AnthonyJNgo commented on hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
>  	restricted_roles = list("AI", "Cyborg", "Security Officer", "Warden", "Detective", "Head of Security", "Captain", "Chaplain", "Head of Personnel", "Vice Officer")
Example here, where Chaplain is already listed as a restricted role under bloodcult.

2020-03-23 01:31 UTC, AnthonyJNgo commented
Revoked my earlier comments, I'd like @yoyobatty to double check this but it looked fine to me.

2020-03-23 09:47 UTC, ProtozoaPrime commented
Oh yeah, this PR is a direct fix for #11966

2020-03-24 23:42 UTC, yoyobatty commented
This just stops Chaplain from being able to pick traitor, hivemind, vamp or devil. You need to set it so they can't choose vampire or devil exclusively.

2020-03-24 23:50 UTC, yoyobatty commented on hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	restricted_roles = list("Cyborg", "Chaplain")
```suggestion
	restricted_roles = list("Cyborg")
```

2020-03-24 23:53 UTC, yoyobatty requested changes
One thing you could do under line 37-42
```
If(M.mind.assigned_role == "Chaplain")
    to_chat(M, "Error; Cannot select this antag with your current role")
    return
```

2020-03-26 00:13 UTC, ProtozoaPrime commented
Gamer moment :sunglasses:

2020-03-26 00:19 UTC, yoyobatty approved these changes
Eh, why not

2020-03-26 00:20 UTC, merged