Curator Buff + Origami Book
HippieStation/HippieStationdeprecated2020 pull request #12741
Opened 2020-04-28 07:26 UTC by carlopault

![image](https://user-images.githubusercontent.com/48893662/80457850-f4008680-88fd-11ea-8e55-1138932a825f.png)

## Changelog
:cl:Carlospaul
add: New origami crafting book that allows you to craft items exclusive to the book. 
add: new item: paper house
add: new item: paper sword
add: new item: paper throwing star
add: new item: paper handcuffs (shittiest handcuffs in the game now)
add: new item: paper identification card (starts with maint access)
tweak: Any crafting recipes that you learn are placed in a new crafting tab: **Learned Rcps.**
tweak: Changed the color of the curator's Forbidden Knowledge bookshelf in his backroom to draw attention to it.
balance: The curator's Forbidden Knowledge shelf now spawns with a randomly selected crafting recipe book, **so make sure to check it roundstart.**
imageadd: New sprites for the origami stuff
/:cl:

## About The Pull Request
Poopoo peepeee can't think of anything to put here. 

## Why It's Good For The Game
Curator is hot dog shit right now. More content is good and curator buff is good.

2020-04-28 07:32 UTC, MrEpicSax commented
+1 speedmerge

2020-04-28 07:33 UTC, byandaccount commented
+1 loving the idea of giving the curator origami, opens up alot of potential for new funny items.
plus the idea of the curator sitting in a circle with the crew teaching them how to fold paper amuses me greatly.

2020-04-28 07:44 UTC, carlopault commented
> +1 loving the idea of giving the curator origami, opens up alot of potential for new funny items.
> plus the idea of the curator sitting in a circle with the crew teaching them how to fold paper amuses me greatly.

The curator won't just have origami. The random book spawn could also create those 2 crafting books that Lunaman make: USSR-3 Public Disturbance Manual and Anarchist's Compendium

2020-04-28 10:23 UTC, karmaisblackandbluepilled commented
breddy gud +3

2020-04-28 14:15 UTC, cris5311 commented
+1

2020-04-28 22:52 UTC, Zyzarda commented
+2 well thought out minicontent for a job with no use

2020-04-29 00:35 UTC, OK-Computer-OK commented
+1 very cool

2020-04-29 00:55 UTC, mkikt4743 commented
+1 I wanna be curator and have a shop based on whatever book I spawn with

2020-04-30 17:05 UTC, boodaliboo commented
out of curiosty what other crafting books are there

2020-04-30 17:54 UTC, mkikt4743 commented
read dude read

2020-05-01 16:59 UTC, OK-Computer-OK commented
nice

2020-05-01 22:34 UTC, Mastergodown submitted a review, later dismissed
+1 bruh epic i know this doesnt even do anything but if i have a checkmark i look 5% cooler

2020-05-02 15:54 UTC, Fikou commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +	result = /obj/item/grenade/chem_grenade/tuberculosis
are you reatarded

2020-05-02 15:56 UTC, Fikou commented on hippiestation/code/modules/crafts/origami.dm
> +	access = list(ACCESS_MAINT_TUNNELS)
infinite maint access cards seems kinda broken

2020-05-02 18:27 UTC, mkikt4743 commented
merge already

2020-05-03 02:43 UTC, carlopault commented on hippiestation/code/modules/crafts/origami.dm
> +	access = list(ACCESS_MAINT_TUNNELS)
eh it's just maint access, what's the worst thing that could happen? I could try making it so that the paper ID can only be crafted once. IC reason could be that such a masterpiece of an ID replica can only be made with such perfection once in a lifetime or some shiet

2020-05-03 03:31 UTC, carlopault commented
Added "DO NOT MERGE" to the title so I can receive more feedback.

2020-05-03 12:15 UTC, MrEpicSax commented
Give curator the option to select one of the books instead of gay rng. It's the kind of rng that is just gonna hamper some people 66% of the time. consistency is good and respecting peoples time is good.

2020-05-03 18:55 UTC, carlopault commented
Go ahead and merge it idc. I added a beacon to the curator backroom so the curator can choose which crafting book to summon. It pulls from a list of all crafting books currently in the game.

2020-05-05 14:53 UTC, mkikt4743 commented
MERGE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2020-05-05 23:07 UTC, mkikt4743 commented
FUCKING MERGE IT NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHH!!!!!!!!!!!!!!!!!!

2020-05-05 23:32 UTC, yoyobatty requested changes

2020-05-05 23:32 UTC, yoyobatty commented on code/modules/cargo/packs.dm
> +					/obj/item/book/granter/crafting_recipe/)
/ at the end won't work

2020-05-05 23:32 UTC, yoyobatty commented
Please make sure you actually test this all

2020-05-06 04:30 UTC, carlopault commented on code/modules/cargo/packs.dm
> +					/obj/item/book/granter/crafting_recipe/)
![image](https://user-images.githubusercontent.com/48893662/81138677-d308e880-8f30-11ea-80c2-0e05bddc1a4f.png)
crate seems to work fine

2020-05-06 13:56 UTC, mkikt4743 commented
me when this one ain't merged = )-;

2020-05-07 04:31 UTC, illusineer commented
cool

2020-05-07 04:36 UTC, nednaZ commented
+1
I can't wait to start cuffing everyone with paper handcuffs

2020-05-07 15:52 UTC, yoyobatty approved these changes

2020-05-07 15:52 UTC, merged