Curator Overhaul: Crafting Book Catalog
HippieStation/HippieStationdeprecated2020 pull request #12787
Opened 2020-05-20 00:17 UTC by carlopault

![image](https://user-images.githubusercontent.com/48893662/82390153-ef665400-9a0b-11ea-94d5-77e4e0a7ff00.png)

## Changelog
:cl:
add: The library now has a computer that can be used to print crafting books: **Spacestar Ordering Book Catalog**. The computer operates on special ink cartridges that the curator spawns with (1 cartridge spawns on the computer).
add: Added many new crafting books (books that give you crafting recipes)
add: Added new items (hook spear, super binoculars, toy guitar, etc) to the game that can be crafted via the crafting books obtainable through the Spacestar Ordering Book Catalog.
tweak: Removed the crafting book beacon from the library backroom as it no longer has a purpose.
tweak: Cargo can now order Spacestar-brand ink cartridges.
balance: The curator has been given more things to do now (duh).
soundadd: New sounds for one of the new items.
imageadd: New sprites for the new stuff (Sprites by Mr. Epic Sax and Punkinguy).
code: Changed the obj pathing of crafting granter books. All of this was coded with the help of Neo.
/:cl:

## About The Pull Request
This would not be possible without the help of @Neo1w . Many thanks to him. Check the changed files tab to look at all the new shit, there is too much to list here.

## Why It's Good For The Game
The curator will have more things to do, which is good.

2020-05-20 00:18 UTC, Punkinguy commented
+1, sprited about everything in this

2020-05-20 00:19 UTC, MrEpicSax commented
+1 very good

2020-05-20 01:13 UTC, wheezl commented
+1 once you make sure this doesn't break anything else, good job.

2020-05-20 01:38 UTC, yoyobatty requested changes

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/datum/reagent/blood = 200,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stack/rods = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stock_parts/manipulator = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stack/ducttape = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/clothing/shoes = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/organ/heart = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/dice = 20,)
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stack/ore/bluespace_crystal = 7,)
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/datum/reagent/medicine/perfluorodecalin = 15,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stack/rods = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/reagent_containers/food/snacks/meat/slab/human = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/datum/reagent/blood = 400,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stack/sheet/mineral/silver = 1,)
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/flashlight = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/stock_parts/subspace/transmitter = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/obj/item/dice/d100 = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/datum/reagent/water/holywater = 100,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/ducttape = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/rods = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/assembly/igniter = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/sheet/mineral/plasma = 10,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/taperecorder = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/taperecorder = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +	reqs = list(/obj/item/bikehorn/golden = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/ducttape = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/ducttape = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/ducttape = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/instrument/violin = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/staples = 4,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/datum/reagent/water = 25,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/rods = 6,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/sheet/glass = 2,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/cable_coil = 5,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/sheet/plastic = 2,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/clothing/shoes = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/rods = 2,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/reagent_containers/spray = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/staples = 4,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/sheet/plasteel = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/pipe_cleaner_coil = 4,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/cable_coil = 3,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stack/rods = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/datums/components/crafting/learnedrecipes.dm
> +				/obj/item/stock_parts/capacitor = 1,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		var/list/templist = typesof(/obj/item/book/granter/crafting_recipe/)
slash then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		crafting_book_list = list()
why would you initialize the list here and not where you've declared it?

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +	if(!crafting_book_list)
you can also do `crafting_book_list.len`

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/tier1/obelisk,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/bwoinkmine,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/vuvuzela,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/statuebust,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/superbinoculars,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +
delete this comment

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		sleep(1)
try not to use sleep, you can use a timer CALLBACK instead

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/recordtape,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/mafiososuit,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/woodenstake,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/granters.dm
> +		/datum/crafting_recipe/learned/edagger,
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/implants/implantbreaker.dm
> +	activated = 0
use `FALSE` only use numbers to represent actual numerical instances not boolean variables

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/implants/implantbreaker.dm
> +	.=..()
shouldn't this be above the line ahead and dear god please format it with spaces `. = ..()`

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/storage/boxes.dm
> +	new /obj/item/inkcartridge(src)
I guess copy-pasting this 3 times works but a `for(var/i = 1 to 3)` works too

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/items/twohanded.dm
> +	return
what's the point of this `return` statement?

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/structures/obelisk.dm
> +    qdel(tool)
I believe for Destroy you want to put `return ..()` at the very end, might also not hurt to use `QDEL_NULL` just incase

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/structures/obelisk.dm
> +/obj/structure/destructible/obelisktier2
why couldn't you have just made this a subtype of obselisk??

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/structures/obelisk.dm
> +/obj/structure/destructible/obelisktier2
you just copy pasted all this code instead of overriding all the relevant variables

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/game/objects/structures/obelisk.dm
> +			return
Read what I said about using subtypes and overrides, a lot of the code in this file is taking up a lot of space that can just be replaced with a single parent and having subtypes with overriden procs and vars.

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/modules/library/lib_machines.dm
> +	var/corporations = list("Exit", "Nanotrasen Approved Books", "Syndicate nonsense books", "Wizard Federation drivel",)
comma then bracket

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/modules/library/lib_machines.dm
> +	if(icon_screen == null)
? just put `if(!icon_screen)`

2020-05-20 01:38 UTC, yoyobatty commented on hippiestation/code/modules/library/lib_machines.dm
> +		sleep(110)
no proc should EVER sleep for this long, you can literally just put a `addtimer` CALLBACK or varset callback

2020-05-20 01:40 UTC, yoyobatty commented
There's a lot of stuff in here you should probably make sure is actually fully working, I was able to find a lot of poor choppy code just skimming through

2020-05-20 01:46 UTC, carlopault commented on hippiestation/code/datums/components/crafting/curator_magic.dm
> +				/datum/reagent/blood = 200,
why do you mean by comma then bracket

2020-05-20 01:47 UTC, carlopault commented on hippiestation/code/game/objects/structures/obelisk.dm
> +/obj/structure/destructible/obelisktier2
I ran into problems if I made it a subtype of obelisk. The spawntool proc thingy wouldnt work.

2020-05-20 01:49 UTC, carlopault commented on hippiestation/code/modules/library/lib_machines.dm
> +		sleep(110)
I have no idea how to use timers, using sleep() seems easier

2020-05-20 01:50 UTC, carlopault commented
> There's a lot of stuff in here you should probably make sure is actually fully working, I was able to find a lot of poor choppy code just skimming through

When I used the stuff in-game, it seemed to work fine

2020-05-26 16:21 UTC, mkikt4743 commented
this is a certified 'comma then bracket' moment

2020-05-27 23:30 UTC, Punkinguy commented on hippiestation/code/modules/library/lib_machines.dm
> +		sleep(110)
FIGS CODE SLAVE

2020-05-30 02:55 UTC, carlopault commented
Using bolded letters in the changelog wont break it right?

2020-05-30 04:49 UTC, Zyzarda commented
+2

2020-06-06 04:37 UTC, carlopault commented
merge?

2020-06-06 04:47 UTC, yoyobatty approved these changes
Well, lets give it a go

2020-06-06 04:47 UTC, merged