The DJ
HippieStation/HippieStationdeprecated2020 pull request #12830
Opened 2020-11-22 10:34 UTC by carlopault

![image](https://user-images.githubusercontent.com/48893662/99901327-0d936200-2c84-11eb-98aa-2553bd6bc1eb.png)

## Changelog
:cl:
add: A new (non-half assed) job has been added, the DJ.
add: The Vacant Offine above Cargo has been replaced with the DJ's office.
add: 3 new machines, new clothing, new items, and additions to existing items have been added for the DJ. 
add: Bluespace radio station can play music to every headset and station-bounced radio in the game, as long as they're on a mob. 
add: Disk burner can be used to burn pre-coded or custom music onto record disks, which can be played at the bluespace radio station. This gives the DJ the power to play custom midis to people, just like an admin.
add: Unce machine plays unces over and over. 
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a bunch of new songs, expect waiting a few extra seconds to download them all
imageadd: Daft punk helmet sprites were created by INFRARED_BARON. He allowed me to use his sprites for this PR.
imageadd: All other new sprites were done by Mr. Epic Sax. Make sure to thank him.
imagedel: deleted some icons and images
spellcheck: fixed typos somewhere and made code better elsewhere
code: landmines work a bit differently now
/:cl:

## About The Pull Request
Created with the help of @Neo1w and people in coderbus. Don't merge if the changelog is still broken, I want players to see this change. Yoyobatty, tell me if there is anything wrong with my changelog that would cause it to be broke and not appear in-game.

## Why It's Good For The Game
New content good.

2020-11-22 10:37 UTC, byandaccount commented
+2 been waiting ages for this to come in, good work man

2020-11-22 12:00 UTC, MrEpicSax commented
+1 Don't thank me they're ass. 

Be sure to leave Carlos plenty of feedback in the suggestions channel when it is merged.

2020-11-24 00:50 UTC, xTrainx commented
+1, looks neat, dj needs an uzi tho

2020-11-24 07:22 UTC, SpaceLoveSs13 submitted a review, later dismissed

2020-11-24 07:24 UTC, SpaceLoveSs13 commented
Loved it. Get a maintainer to approve it and get it merged.

2020-11-24 19:51 UTC, carlopault commented
![image](https://user-images.githubusercontent.com/48893662/100144158-5dc91a80-2e64-11eb-8ec5-4fb235a0a511.png)

@AnthonyJNgo you lost the bet

2020-11-26 00:35 UTC, yoyobatty commented on code/game/objects/items/devices/PDA/PDA_types.dm
> +	..()
should be `. = ..()`

2020-11-26 00:36 UTC, carlopault commented on code/game/objects/items/devices/PDA/PDA_types.dm
> +	..()
why

2020-11-26 00:38 UTC, yoyobatty commented on code/game/objects/items/storage/fancy.dm
> +	qdel(src)
should be `return INITIALIZE_HINT_QDEL`

2020-11-26 00:38 UTC, yoyobatty commented on code/game/objects/items/storage/fancy.dm
> +	. = ..()
replace `. = ..()` with `..()`

2020-11-26 00:44 UTC, yoyobatty requested changes
Please have a look through and make sure everything works because I know you very well Carlos.

2020-11-26 02:00 UTC, carlopault commented
yes maam

2020-11-28 04:53 UTC, carlopault commented
yoyobatty can you merge this

2020-11-28 22:09 UTC, yoyobatty approved these changes

2020-11-28 22:09 UTC, merged