amourgus + xtras
HippieStation/HippieStationdeprecated2020 pull request #12844
Opened 2021-04-19 22:45 UTC by illusineer

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: amogus
add: amojoust in det office and maint
add: amojus as heirloom item for jobs not assigned heirloom 
add: amogert traitor item
fix: fixed typo in syndie surgery bag uplink item
add: robotnik mustache facial hair option
add: exclamation mohawk hair option
tweak: unce machine begins off roundstart (DAMN THAT IS ANNOYING!!)
add: 4 new fart messages
/:cl:

## About The Pull Request
![tenor (3)](https://user-images.githubusercontent.com/21048308/115312291-eacb8380-a125-11eb-836b-b8e99d40b1b6.gif)

## Why It's Good For The Game
amongos
![tenor (4)](https://user-images.githubusercontent.com/21048308/115312452-32eaa600-a126-11eb-8bd1-e647696b6613.gif)

2021-04-20 15:35 UTC, carlopault commented
+1 all of this stuff looks really neat. @yoyobatty merge dis

2021-04-20 20:59 UTC, yoyobatty commented on code/game/objects/items/plushes.dm
> +// gay ^^^
no

2021-04-20 21:00 UTC, yoyobatty commented on code/game/objects/items/plushes.dm
> +	return
should be `return BRUTE_LOSS`

2021-04-20 23:02 UTC, illusineer commented on code/game/objects/items/plushes.dm
> +	return
fixed

2021-04-26 19:09 UTC, yoyobatty requested changes

2021-04-26 19:09 UTC, yoyobatty commented on code/game/objects/items/plushes.dm
> +/obj/item/toy/plush/amongus/Initialize() //rare amojus - 2do give greentext if u escape with it
initialized twice, fix this

2021-04-26 19:29 UTC, illusineer commented on code/game/objects/items/plushes.dm
> +// gay ^^^
Yea

2021-04-26 19:59 UTC, yoyobatty approved these changes

2021-04-26 20:00 UTC, merged