Bluespace radio station fixed + improvements
HippieStation/HippieStationdeprecated2020 pull request #12858
Opened 2021-07-25 05:26 UTC by carlopault

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: record disk burner can now be used to rename record disks
add: record disk burner now displays the name of the disk at the top of its main menu
del: Removed useless "linked_RS" variable
tweak: playing record disks on your PDA is less finnicky
fix: bluespace radio station now plays music like it's supposed to
/:cl:

![image](https://user-images.githubusercontent.com/48893662/126888744-35777687-5a19-4e2d-961d-ad27ec719d8d.png)

## About The Pull Request
I have gotten around to fixing the radio station so that people can finally get the full DJ experience

## Why It's Good For The Game
DJ is cool.

2021-07-25 05:35 UTC, Zyzarda commented
improvements GOOD +1

2021-07-26 17:31 UTC, yoyobatty requested changes

2021-07-26 17:31 UTC, yoyobatty commented on code/game/objects/items/devices/radio/radio.dm
> +		radio_holder = src.loc
Bro there's way better ways to check this, you could have atleast used a loop, this is excessive. Also src. can be removed, it's redundant

2021-07-26 17:31 UTC, yoyobatty commented on hippiestation/code/modules/library/lib_machines.dm
> +		src.visible_message("<span class ='notice'>[user] loads a Spacestar-brand ink cartridge into the [src]")
Again, src. is not redundant and does nothing, I'm not sure why you added it to everything

2021-07-26 17:32 UTC, carlopault commented on code/game/objects/items/devices/radio/radio.dm
> +		radio_holder = src.loc
> Bro there's way better ways to check this, you could have atleast used a loop, this is excessive. Also src. can be removed, it's redundant

I tried making a loop but I wasnt creative enough so I brute forced it instead

2021-07-26 17:33 UTC, carlopault commented on hippiestation/code/modules/library/lib_machines.dm
> +		src.visible_message("<span class ='notice'>[user] loads a Spacestar-brand ink cartridge into the [src]")
> Again, src. is not redundant and does nothing, I'm not sure why you added it to everything

I saw src. on something somewhere else so I thought it was the right way to do it

2021-07-26 17:36 UTC, yoyobatty commented on hippiestation/code/modules/library/lib_machines.dm
> +		src.visible_message("<span class ='notice'>[user] loads a Spacestar-brand ink cartridge into the [src]")
So you just looked and went oh wow I'm not going to question it, better add it? Sir, that's hasty and shoves a big fuck you to basic troubleshooting. Clearly nothing was broken so there's no point to this.

2021-07-26 17:38 UTC, carlopault commented on hippiestation/code/modules/library/lib_machines.dm
> +		src.visible_message("<span class ='notice'>[user] loads a Spacestar-brand ink cartridge into the [src]")
> So you just looked and went oh wow I'm not going to question it, better add it? Sir, that's hasty and shoves a big fuck you to basic troubleshooting. Clearly nothing was broken so there's no point to this.

yeah

2021-07-26 17:44 UTC, carlopault commented on code/game/objects/items/devices/radio/radio.dm
> +		radio_holder = src.loc
couldnt think of any way to make a loop work

2021-07-26 22:01 UTC, carlopault commented
too easy

2021-07-28 20:12 UTC, yoyobatty approved these changes

2021-07-28 20:12 UTC, merged