Moves all ranged stuns to a stamina based system
HippieStation/HippieStationdeprecated2020 pull request #1605
Opened 2017-06-03 18:50 UTC by GuyonBroadway

:cl: Guyonbroadway
experiment: Hard ranged stuns are basically gone barring a few fringe cases.
balance: Taser bolts now deal 80 stamina damage and force people to drop items.
balance: Improvised stun prods deal 80 stamina damage that ignores armour and force people to drop items.
balance: The detectives revolver now deals 65 stamina damage, 15 brute and forces people to drop items.
balance: Taser and disabler beams have had their shot cost adjusted, with a standard taser you have 8 taser bolts or 12 disabler beams. Enough to drop four nerds if your aim is on point. 
add: Security staff now come with Krav Maga, the gloves remain in the wardens locker as a fun little prize for anyone breaking in.
balance: Syndiacte Sniper Rifles still have a stun, but it has been reduced to one tick (not that it matters when you are so slow the followup shot is both easy to land and will put you in crit anyway) 
balance: Bulldog shotguns taser rounds also match the tasers change, but they count as bullets so are better vs certain types of defences. 
experiment: Due to not having a more fun idea at the time, Ebows now gives the target 10 units of skeiwum and cause hallucinations. Sure it doesn't stun any more but the guy on the receiving end is not going to be able to do anything productive for a while.
balance: Yes I took into account the R&D guns. 
balance: Yes the mechs too
experiment: Disabler beams now travel faster so you can peg fleeing targets more easily (You can still just about outrun them on ephedrine though)

/:cl:

[why]:  Hard ranged stuns are very powerful and basically dictate the course of the game.

A stamina based system is less "one stun and done" and might provoke more firefights or more creative methods of combat besides "grab taser - go kill" The makeshift baton was also better than its sec counterpart and widely available. 

Krav Maga means sec always has tools at their disposal even if fullstripped by some greyshit and their jobs should not be that much harder as a result. 

The sec baton will remain the hard stunner that it is as it's the final means for sec to detain a perp.

There are other changes I feel could benefit this new system but I want to see how the player-base handles it first, it might just be a bad idea altogether and needs scrapping.

2017-06-03 18:51 UTC, GuyonBroadway commented
I missed out on the mechs file, hold off before merging.

2017-06-03 20:14 UTC, tortellinitony commented
You're still deleting the submodule. Fix that.

2017-06-03 20:23 UTC, tortellinitony requested changes
I also don't get why you aren't just changing the values for the actual projectiles.

2017-06-03 20:23 UTC, tortellinitony commented on hippiestation.dme
> +#include "code\modules\mob\say_readme.dm"
Why is this enabled?

2017-06-03 20:23 UTC, tortellinitony commented on hippiestation.dme
> +#include "code\__DEFINES\_readme.dm"
Why is this enabled?

2017-06-03 20:23 UTC, tortellinitony commented on hippiestation.dme
> -#include "code\modules\events\holiday\halloween.dm"
Why is this disabled?

2017-06-03 20:23 UTC, tortellinitony commented on .gitmodules
> +[submodule "tools/tgstation-server-tools"]
Delete this change.

2017-06-03 20:24 UTC, GuyonBroadway commented
And just so you know, yes it's been tested, yes it works, no there are no runtimes.

2017-06-03 20:53 UTC, JamieH commented
I want a test merge of this in a couple of days.

2017-06-03 23:52 UTC, PopNotes commented
I agree with absolutely everything here. Guy is our savior.

2017-06-04 03:35 UTC, Uqualm commented
For posterity's sake, let it be known I think this is a terrible idea. I also think that GuyonBroadway is so in love with his idea that he won't see any of the flaws in it and even if it's pure shit (like anti-stuns) it'll stay in the game. Yeah I know nobody cares what I think.

2017-06-04 14:00 UTC, lcass commented
welp hes got conflicts.

2017-06-04 15:58 UTC, tortellinitony commented
Also if this is about ranged stuns, then **everything involving the stunbatons and stunprods should aso be in its own PR if you want this to be mergeable**

2017-06-04 18:29 UTC, McBawbaggings commented
I'm for trialling this in a bit later when our population is a bit higher and I'm on. I would want to see it on a bigger player pool and see how people feel about it for a few rounds and get feedback.

While I do support these changes on the whole, they're very drastic and we should be able to revert for any reason during the testing period based on feedback and make improvements.

2017-06-04 20:58 UTC, banthebantz commented
MUH SNIPER NERF

2017-06-04 22:26 UTC, lcass commented
I think you should reduce the damage of the detectives revolver to 10 brute as it will take 2 shots minimum to down someone thats a third of their health gone, seems a bit too easy to crit with.

2017-06-09 23:29 UTC, PopNotes commented
god, please merge this already

2017-06-10 17:59 UTC, McBawbaggings commented
I'm for trialing this on a day or so I can be on for a while.

2017-06-10 18:20 UTC, banthebantz commented on hippiestation/code/game/objects/items/weapons/stunbaton.dm
> +
use a define

2017-06-10 18:21 UTC, banthebantz commented on hippiestation/code/modules/projectiles/projectile/bullets.dm
> +/obj/item/projectile/bullet/stunshot
is nerfing this necessary?

2017-06-10 18:22 UTC, banthebantz commented on hippiestation/code/modules/projectiles/projectile/energy.dm
> +	range = 8
you buffed the range

2017-06-10 18:57 UTC, GuyonBroadway commented on hippiestation/code/modules/projectiles/projectile/energy.dm
> +	range = 8
And just by one tile too... I'll remove that but they might need a range buff later down the line

2017-06-10 20:45 UTC, GuyonBroadway commented on hippiestation/code/game/objects/items/weapons/stunbaton.dm
> +
This is exactly how stunpower works for regular batons, I need to do it like this lest I need to balance different things specifically.

2017-06-10 20:45 UTC, GuyonBroadway commented on hippiestation/code/modules/projectiles/projectile/bullets.dm
> +/obj/item/projectile/bullet/stunshot
Yes, if we are changing ONE ranged stun we need to change them all.

2017-06-13 22:42 UTC, merged