Loadout system ported from paradise station
HippieStation/HippieStationdeprecated2020 pull request #2220
Opened 2017-07-02 21:38 UTC by Carbonhell

:cl: 
experiment: Adds the loadout system from paradise station, where you can choose certain fluff gear(nothing you can powergame with) to spawn with, like cosby sweaters and such
/:cl:

[why]: jamie wants it and i think it's coolio

2017-07-02 21:40 UTC, doobiedoo23 commented
snowflake bullshit

2017-07-02 21:40 UTC, Carbonhell commented
i want this to spawn with a cosby sweater and scream
*scream*

2017-07-02 23:32 UTC, QuarianCommando commented
Wouldn't be too bad if it was just simple shit like assistants being able to choose between the various colored jumpsuits you can get from the locker room, or being able to choose between different versions of your job's equipment.

Things like the cosby sweater would kind of remove the point of having them. They're little easter eggs that you have to pull out of their hidden spots in maint, and there can only be one at a time. Letting anyone spawn with it makes it less fun.

2017-07-03 00:08 UTC, JamieH commented
That's the point Quarian, simple shit

2017-07-03 07:27 UTC, ghost requested changes
Preliminary review, code smells a bit needs some more work obviously

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +	to_chat(world, "maincall")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +		to_chat(world, "secondcall")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			to_chat(world, "1")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			to_chat(world, "2")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +				to_chat(world, i)
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			to_chat(world, "3")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +				to_chat(world, "4")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +					to_chat(world, "5")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +					to_chat(world, "6")
Please remove this before removing the `DNM` tag from this PR

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences_savefile.dm
>  /datum/preferences/proc/hippie_pref_load(savefile/S)
Could we please have this renamed to `hippie_character_pref_load` because this only handles character preferences, not ckey preferences

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences_savefile.dm
>  /datum/preferences/proc/hippie_pref_save(savefile/S)
Could we please have this renamed to `hippie_character_pref_save` because this only handles character preferences, not ckey preferences

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +	for(var/i in subtypesof(/datum/gear_category))
There is no reason we need to store the `gear_categories` in each preferences datum, create a global list for this

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	var/path//item-to-spawn path
Please change this to `var/path` or `/var/item` instead of `var/path//item-to-spawn path`

2017-07-03 07:27 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +		. += "<div class='notice'>Please create an account to save your preferences</div>"
What?

2017-07-03 08:07 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	var/path//item-to-spawn path
I fucked up, the latter was meant to be a comment

2017-07-03 09:03 UTC, FuryMcFlurry commented
What items would the loadout menu offer to people? Just the general colored jumpsuit/hat/shoes?

Also cant wait for achievement items that does nothing

2017-07-03 09:10 UTC, Carbonhell commented
Pretty much,think of people like the Pink guy who would always get a pink jumpsuit at roundstart. Stuff like that. Although we're not sure wherever to keep suits or not,since they show what job you are...
It'll be up to the headmins to choose what slots to keep and what not, from the list of defines in __HELPERS

2017-07-03 23:39 UTC, Carbonhell commented
New commit fixes most of the preference menu, all what's missing is to rename the proc erik said and put the actual hookup meant to spawn the item, and remove example loadouts

2017-07-04 08:25 UTC, ghost requested changes

2017-07-04 08:25 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	for(var/i in subtypesof(/datum/gear))
This is pretty fucking awful, please look at how /tg/ does this with their uplink and do something similar, there is zero reason we need to have every category run `subtypesof` on `New()`

If you look at this, https://github.com/tgstation/tgstation/blob/master/code/modules/uplink/uplink_item.dm you can see that the following is done.

- get_uplink_items is called
- get_uplink_items calls initialize_global_uplink_items which initializes the uplink items

`one` call, versus `n` calls, I'd suggest rewriting this because the current implementation makes no sense, there is also no need to have a seperate datum per category when you could just split those off into defines.

```
/proc/initialize_global_uplink_items()
	GLOB.uplink_items = list()
	for(var/item in subtypesof(/datum/uplink_item))
		var/datum/uplink_item/I = new item()
		if(!I.item)
			continue
		if(!GLOB.uplink_items[I.category])
			GLOB.uplink_items[I.category] = list()
		GLOB.uplink_items[I.category][I.name] = I
```

2017-07-04 08:25 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	var/list/locked_to_roles // use LAZYADD in Initialize() and add the roles your item is locked to
Please rename this to `restricted_roles` to stay consistent with similar functionality

2017-07-04 08:33 UTC, ghost requested changes

2017-07-04 08:33 UTC, Chnkr commented on code/__DEFINES/hippie.dm
> +//Loadout
These are not needed either IMO, just build the interface dynamically when you build the list of loadout groups/items, look at how /tg/ handles the uplink

2017-07-04 09:42 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +		. += "<div class='notice'>Please create an account to save your preferences</div>"
i had to replace tg dat, and that's one of the things added in it, so i just copypasted it

2017-07-04 11:59 UTC, banthebantz commented
yes fifnally i can roleplay!1

2017-07-06 15:08 UTC, Carbonhell commented on code/__DEFINES/hippie.dm
> +//Loadout
yeah removed their use but i forgot to remove them as defines,will do later

2017-07-06 15:12 UTC, tortellinitony requested changes

2017-07-06 15:12 UTC, tortellinitony commented on hippiestation/code/controllers/subsystem/job.dm
> +				to_chat(world, "AAAAAAAAAAAA[M.job]")
No

2017-07-06 15:12 UTC, tortellinitony commented on hippiestation/code/controllers/subsystem/job.dm
> +				to_chat(world, "Aaaa")
No

2017-07-06 15:12 UTC, tortellinitony commented on hippiestation/code/controllers/subsystem/job.dm
> +		to_chat(world, "B")
No

2017-07-06 15:12 UTC, tortellinitony commented on hippiestation/code/controllers/subsystem/job.dm
> +			to_chat(world, "[i]")
No

2017-07-06 15:12 UTC, tortellinitony commented on hippiestation/code/modules/client/preferences_savefile.dm
> +	S["loadout"]				>> text_to_load
You don't need all of this indentation

2017-07-06 15:12 UTC, Carbonhell commented on hippiestation/code/controllers/subsystem/job.dm
> +		to_chat(world, "B")
i thought i deleted those what the fuq

2017-07-06 15:16 UTC, ghost requested changes

2017-07-06 15:16 UTC, Chnkr commented on hippiestation/changes.md
> +## Edits list
Please change this so all `dm` files actually link to the file, and all code should be encapsulated so it `looks like code`

2017-07-06 15:16 UTC, Chnkr commented on hippiestation/code/_HELPERS/mobs.dm
> +/proc/slot_to_string(slot)
Please do not use the `.` (dot) variable, it's been proven to be much much slower than using `return` so please just use `return`

2017-07-06 15:16 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	for(var/item in subtypesof(/datum/gear))
Please use a istypeless loop `for(var/A in subtypesof(/datum/gear))`

2017-07-06 15:16 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		var/datum/gear/I = new item()
why do we need to call `new` can't the list just contain type-paths of loadout items?

2017-07-06 15:16 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	category = slot_head
`slot_head` looks like a define, and defines need to be `FULLCAPS`

2017-07-06 15:16 UTC, tortellinitony commented on hippiestation/changes.md
> +## Edits list
md file

2017-07-06 15:17 UTC, Carbonhell commented on hippiestation/code/_HELPERS/mobs.dm
> +/proc/slot_to_string(slot)
didn't know that, will do

2017-07-06 15:17 UTC, tortellinitony commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	for(var/item in subtypesof(/datum/gear))
var/item is typeless

2017-07-06 15:17 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	for(var/item in subtypesof(/datum/gear))
this is a typeless loop??

2017-07-06 15:17 UTC, tortellinitony commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		var/datum/gear/I = new item()
get rid of ()

2017-07-06 15:18 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		var/datum/gear/I = new item()
i wanted to avoid using(abusing) initial even more than what i currently did, is initial actually better to use performance wise?

2017-07-06 15:18 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		var/datum/gear/I = new item()
why do you need `initial` or `new` can't the global list of loadout items just contain the paths of the items?

2017-07-06 15:19 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	category = slot_head
it's defined like this in tg files
https://github.com/tgstation/tgstation/blob/c49df85b54639d489e75eeb017d98bb00c288fc5/code/__DEFINES/inventory.dm#L44
there are two defines and i don't fuckin know why but the lowercaps one looked better

2017-07-06 15:19 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences_savefile.dm
> +	S["loadout"]				>> text_to_load
it's to keep it in line with the previous, my ocd needs to be satisfied

2017-07-06 15:35 UTC, Chnkr commented on hippiestation/code/modules/client/preferences_savefile.dm
> +	S["loadout"]				>> text_to_load
You don't need all of this indentation

2017-07-07 09:34 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences_savefile.dm
> +	S["loadout"]				>> text_to_load
my ocd needs it stfu re

2017-07-08 10:45 UTC, ghost requested changes

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/changes.md
> +## Edits list
Please remove this change from this PR and do it elsewhere

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +GLOBAL_LIST_EMPTY(loadout_items)
Please initialize this elsewhere, preferably somewhere inside the hippie init or something

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		var/datum/gear/I = new item()
get rid of () please

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	var/category = "none"
I think this should be a define to prevent people from fucking up things

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		description = initial(O.desc)
why are we using `initial()` you can just use O.desc can't you?

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/mask.dm
> +/datum/gear/clown_mask
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/mask.dm
> +/datum/gear/mime_mask
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/mask.dm
> +/datum/gear/tiki_mask
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/bluetie
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/redtie
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/blacktie
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/stethoscope
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +	restricted_roles = list("Medical Doctor", "Chief Medical Officer")
Any chance we can turn these roles into a DEFINE?

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/scarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/blackscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/redscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/greenscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/darkbluescarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/purplescarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/yellowscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/orangescarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/cyanscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/stripedredscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/stripedbluescarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/neck.dm
> +/datum/gear/stripedgreenscarf
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/shoes.dm
> +/datum/gear/laceup
These need a description and cost

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +	var/gear_tab
why are we storing this?

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			for(var/j in GLOB.loadout_items[gear_tab])
what the fuck is this, a `for` loop to determine which button is being clicked? the fuck?

2017-07-08 10:45 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +/datum/preferences/proc/is_loadout_slot_available(slot)
This entire proc seems more expensive than it needs to be

2017-07-08 11:25 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		description = initial(O.desc)
No? Path is a path, not a ref?

2017-07-08 11:26 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +GLOBAL_LIST_EMPTY(loadout_items)
All calls of this define i have seen was not under a proc, but ok i guess

2017-07-08 11:28 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +	var/category = "none"
It is a define, that is just the default value but i will remove it to prevent confusion

2017-07-08 11:29 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/neck.dm
> +	restricted_roles = list("Medical Doctor", "Chief Medical Officer")
Yeah i was thinking so too. I will check if it doesnt already exist,it should smh...

2017-07-08 11:30 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +	var/gear_tab
Hiw else would i show the right loadout category to the user?

2017-07-08 11:32 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +			for(var/j in GLOB.loadout_items[gear_tab])
How else can i get the item to spawn,safety-ized? You made me use uplink system and gear.name is not a safe way imo

2017-07-08 11:33 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +/datum/preferences/proc/is_loadout_slot_available(slot)
Well shit how would you improve it? I dont see any way to do so

2017-07-08 11:34 UTC, Carbonhell commented
All costs default to 1; description defaults to path desc

2017-07-08 12:12 UTC, Chnkr commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		description = initial(O.desc)
`var/obj/O = path`
`description =O.desc`

2017-07-08 12:13 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			for(var/j in GLOB.loadout_items[gear_tab])
Look at how the uplink system does this, I'm pretty sure the uplink system does not use a `for` loop

2017-07-08 12:41 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/loadout.dm
> +		description = initial(O.desc)
I don't get it? Path is a path,it never gets newed, so var/obj/O would be equal to something like /obj/item/bikehorn. How do you expect to access a var of a path like that without initial?

2017-07-08 12:42 UTC, Carbonhell commented on hippiestation/code/modules/client/loadout/neck.dm
> +	restricted_roles = list("Medical Doctor", "Chief Medical Officer")
Apparently there's no define for jobs, even tho strings themself are widely used... Weird. What if i replace the strings with the path of the jobs?Would you prefer that?It'd be pretty meh to make defines for each job just for this.

2017-07-08 12:43 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +			for(var/j in GLOB.loadout_items[gear_tab])
I'm dumb, i can just do var/datum/gear/G = GLOB.loadout_items[gear_tab][href_list["toggle_gear_path"]] as i just did. I was probably pretty tired, sorry

2017-07-08 16:07 UTC, Pyko1 commented
What about random outfit, that usually jsut randomizes from selectable things, but has a chance for rare things, like collectable hats and cursed rubber duck stuck in your hand.

2017-07-08 16:23 UTC, Carbonhell commented
The pr is complete in terms of feature, i wont add more to prevent waiting even more time for this thing

2017-07-08 19:21 UTC, FuryMcFlurry commented
Cant wait to see this being expanded  with achievement items. But that would be another time

2017-07-09 11:29 UTC, ghost requested changes

2017-07-09 11:29 UTC, Chnkr commented on hippiestation/code/modules/client/preferences.dm
> +			var/datum/gear/G = GLOB.loadout_items[gear_tab][href_list["toggle_gear_path"]]
This might cause runtimes, please just use `locate() in list` and call `toggle_gear_path` with a `/ref`

2017-07-09 11:33 UTC, ghost requested changes

2017-07-09 11:33 UTC, Chnkr commented on hippiestation/code/controllers/subsystem/job.dm
> +			if(!M.equip_to_slot_or_del(new G.path, G.category))
I would not `del` it, put it in their pockets, then hands, then bag, and then floor if all else fails, dont' `del` equipment

2017-07-09 17:07 UTC, Carbonhell commented on hippiestation/code/controllers/subsystem/job.dm
> +			if(!M.equip_to_slot_or_del(new G.path, G.category))
do you know of an existing proc that does it?just to make my job easier ay

2017-07-09 17:07 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences.dm
> +			var/datum/gear/G = GLOB.loadout_items[gear_tab][href_list["toggle_gear_path"]]
can you elaborate, i don't fully understand how exactly you want me to do this

2017-07-09 18:18 UTC, JamieH commented on hippiestation/code/controllers/subsystem/job.dm
> +			if(!M.equip_to_slot_or_del(new G.path, G.category))
Might be easier just to put it in their box.

2017-07-11 17:29 UTC, Carbonhell commented
Just noticed latejoiners do not get the loadout. Shit.

2017-07-11 21:17 UTC, optimumtact commented on hippiestation/code/_HELPERS/mobs.dm
> +/proc/slot_to_string(slot)
proven

posts no proof

2017-07-11 21:53 UTC, merged