Ports the NOTELEPORT disability from pre-rebase
HippieStation/HippieStationdeprecated2020 pull request #2260
Opened 2017-07-05 23:10 UTC by cacogen

:cl: cacogen
add: Ports the NOTELEPORT disability from pre-rebase and gives it back to hotel staff and the space bartender.
tweak: Hotel staff now spawn with IDs (same as pre-rebase)
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Players are getting banned for leaving the hotel which by itself is a pretty dumb thing to ban for. If it was an actual issue you'd expect the game to prevent it instead of just giving an empty IC warning.

Griefers are also using the role to metagrudge and mug people.

2017-07-05 23:15 UTC, Carbonhell commented
We cant accept it as it is now, you need to modularize it.

2017-07-06 08:04 UTC, JamieH commented
This is rad

2017-07-06 09:56 UTC, ghost requested changes
Please make your PR modular as explained in https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md

2017-07-06 17:19 UTC, cacogen commented
@Chnkr Can you explain how?

2017-07-06 17:37 UTC, tortellinitony submitted a review, later dismissed

2017-07-06 17:37 UTC, tortellinitony commented on code/modules/awaymissions/corpse.dm
> +	if(bind_to_z_level)
This will have to stay in the file

2017-07-06 17:37 UTC, tortellinitony commented on code/modules/awaymissions/corpse.dm
> +	var/bind_to_z_level = FALSE //can I leave the z level as this mob?
Create a file called `hippiestation/code/modules/awaymissions/corpse.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/game/objects/structures/ghost_role_spawners.dm
> +	bind_to_z_level = TRUE
Create a file called `hippiestation/code/game/objects/structures/ghost_role_spawners.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/game/objects/structures/ghost_role_spawners.dm
> +	id_access_list = list(GLOB.access_away_general, GLOB.access_away_maint)
Create a file called `hippiestation/code/game/objects/structures/ghost_role_spawners.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/game/objects/structures/ghost_role_spawners.dm
> +	id = /obj/item/weapon/card/id
Create a file called `hippiestation/code/game/objects/structures/ghost_role_spawners.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/game/objects/structures/ghost_role_spawners.dm
> +	flavour_text = "You are a peacekeeper assigned to this hotel to protect the interests of the company while keeping the peace between \
Create a file called `hippiestation/code/game/objects/structures/ghost_role_spawners.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/modules/mob/living/living.dm
> +	originX = x
Create a file called `hippiestation/code/modules/mob/living/living.dm` and add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/modules/mob/living/life.dm
> +	if(boundToOriginZ)
We already have a file for this, add this to it.

2017-07-06 17:37 UTC, tortellinitony commented on code/modules/mob/living/living_defines.dm
> +
Create a file called `hippiestation/code/modules/mob/living/living_defines.dm` and add this to it.

2017-07-06 20:15 UTC, cacogen commented
It's the "add this to it" part that I don't understand. You can't redefine an existing object, so you either have to copy the object over and delete the original or duplicate the entire file, add your changes and untick the original from the .dme. So which is it? Or is there another way?

2017-07-06 20:38 UTC, tortellinitony commented
yes you can

2017-07-06 21:52 UTC, cacogen commented
hopefully that's it

2017-07-07 08:33 UTC, Chnkr commented
You literally copied the entire objects, this is not needed, look at some of @tortellinitony his pullrequests to get a good example of how it should work

2017-07-08 10:08 UTC, j-mie approved these changes

2017-07-08 10:34 UTC, ghost submitted a review, later dismissed
This code is terrible, me and @JamieH went over it on discord real quick and I'd prefer if you made a new implant instead of changing the already existing ones.

The same goes for the `hippiestation/code/game/objects/structures/ghost_role_spawners.dm` file, it's literally a copy of something that already exists, you don't need to modify the description and the ghost role information, all you need to add to them is the implant

2017-07-08 10:35 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/list/whitelist = list()
Please do not initialize lists directly on the object, or in `/new` please use the `LAZY_` list helpers when working with lists.

More about that can be found [here](https://github.com/HippieStation/HippieStation13/blob/master/code/__HELPERS/lists.dm#L459)

2017-07-08 10:36 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/list/blacklist = list()
Please do not initialize lists directly on the object, or in `/new` please use the `LAZY_` list helpers when working with lists.

More about that can be found [here](https://github.com/HippieStation/HippieStation13/blob/master/code/__HELPERS/lists.dm#L459)

2017-07-08 10:36 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/on = FALSE
Implants are always on, this makes no sense

2017-07-08 10:37 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/useblacklist = TRUE
why do we need both a white and a blacklist? Just rename the implant to `bluespace destabilazation implant` and lock the `usr` his `z` to the `z` the implant was added in, this seems overly complicated

2017-07-09 08:56 UTC, Carbonhell commented on code/game/machinery/teleporter.dm
> +/obj/proc/noteleport_affect(mob/living/carbon/human/human)
Why is it an obj proc?

2017-07-09 08:56 UTC, Carbonhell commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/list/whitelist = list()
little sidenote, that "here" link is broken bruv
https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/_lists.dm#L452

2017-07-12 14:34 UTC, Chnkr commented
Zero activity in the last week, multiple merge conflicts and pending reviews. Feel free to ask for this to be reopened once you fixed those

2017-07-12 23:40 UTC, cacogen commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/useblacklist = TRUE
In case admins want to use it to blacklist or whitelist people from roles? Because I wanted to add that?

2017-07-12 23:41 UTC, cacogen commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/on = FALSE
Nope, not when you first implant someone on the station before throwing them through the teleporter. You need to exile them first before it becomes active and stops them from being on the station because it needs to know when to send someone. You should probably read the code more thoroughly in future.

2017-07-13 00:11 UTC, cacogen commented
@Chnkr, you've been creating problems with my pulls and issue reports for months now so I'm just going to go to /tg/ with this. I won't have to deal with modularisation there either.

This code would help both the players and the admins so you being so eager to find problems with it just seems like personal bias.

Hippie has about three coders so you should probably ask yourself if gatekeeping the code for personal reasons is worth it.

2017-07-13 06:39 UTC, Chnkr commented
> @Chnkr, you've been creating problems with my pulls and issue reports for months now so I'm just going to go to /tg/ with this. I won't have to deal with modularisation there either.

Correct, I've indeed been reviewing your pull requests, your code does not follow either the rules, or guidelines we put into place to make sure we still have modular and easy to manage code so we can still keep updating our server with new and fresh things from /tg/

I've also commented on some things that i personally feel are over-complicating the solution, whitelists, blacklists are all not needed in my opinion, just make an implant that when implanted starts a `x` second delay and then locks the player to their current `Z`

We already had this basic functionality trough a pullrequest @tortellinitony made, why not just (re)merge that back into the current repository? As that worked more than fine

> This code would help both the players and the admins so you being so eager to find problems with it just seems like personal bias.

I barely even play on the server these days, so that's just wrong :-)

2017-07-13 08:15 UTC, cacogen commented
@Chnkr 
please don't add noses to your emoticons if you want me to take you seriously fam

2017-07-13 09:00 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/implants/implant_exile.dm
> +	var/useblacklist = TRUE
I'd rather just keep it simple, and add subtypes if you really need specific usecases

2017-07-13 14:18 UTC, JamieH commented
I like the whitelists/blacklists, I don't mind having them. Honestly IMO all that needs to be done is to repath it from exile implant to something else

2017-07-15 13:18 UTC, JamieH commented
Sorry @cacogen I went and did the changes for you.

2017-07-15 13:27 UTC, j-mie approved these changes

2017-07-15 13:27 UTC, merged