Cat and cluwne bans
HippieStation/HippieStationdeprecated2020 pull request #234
Opened 2017-03-25 18:18 UTC by tortellinitony

Will now offer bodies to ghosts when converted to antag.

2017-03-25 19:40 UTC, ghost requested changes
We also need to make sure cat-banned players can not use ghost roles and ghost role spawners.

2017-03-25 19:40 UTC, Chnkr commented on code/controllers/subsystem/jobs.dm
> +	for(var/mob/dead/new_player/player in unassigned)
Please use _istypeless for loops_ you can find more information about this in the [contributing.md](https://github.com/HippieStation/HippieStation13/blob/master/CONTRIBUTING.md)

2017-03-25 19:40 UTC, Chnkr commented on code/controllers/subsystem/jobs.dm
> +		if(jobban_isbanned(player, "catban") || jobban_isbanned(player, "cluwneban"))
Could we turn these `"catban"` and `"cluwneban"` into defines? much like `if(jobban_isbanned(owner, ROLE_SERVANT_OF_RATVAR)`

2017-03-25 19:47 UTC, JamieH commented
build this

2017-03-26 01:55 UTC, Chnkr commented
build this

2017-04-01 18:09 UTC, j-mie approved these changes

2017-04-01 18:11 UTC, JamieH commented on hippiestation.dme
> -#include "hippiestation\code\_DEFINES\DNA.dm"
?

2017-04-01 18:12 UTC, tortellinitony commented on hippiestation.dme
> -#include "hippiestation\code\_DEFINES\DNA.dm"
moved all defines to the actual defines folder

2017-04-10 22:09 UTC, tortellinitony commented
I'll fix the conflicts later.

2017-04-11 21:22 UTC, QuarianCommando commented
Remember to put your changelog in the PR description

2017-04-13 03:07 UTC, tortellinitony commented
This PR will need to be remade since some asshole changed jobs.dm to job.dm for no reason

2017-04-13 03:34 UTC, closed without merging