Really fixes chem tanks
HippieStation/HippieStationdeprecated2020 pull request #2420
Opened 2017-07-16 19:44 UTC by GuyonBroadway

:cl: GuyonBroadway
fix: fixed Chem tanks, filling up chem tanks via beakers and filling fire extinguishers via chem tanks.
/:cl:

If yer worried about balance, chem tanks only have 300u and it just means the clown can cover the halls in carpet or make everything multicoloured.

Sure you could put some horrible stuff in there but it would be less efficent that buying the toxins kit and shooting people with initropidril syringes.

2017-07-16 19:45 UTC, PopNotes commented
can we blease get 1000u tanks back I want my memes

2017-07-16 19:46 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/extinguisher.dm
> +	if(AttemptRefill_hippie(O, user))
procnames should be `thing_thing_thing`

2017-07-16 19:46 UTC, Chnkr commented on hippiestation/code/game/objects/items/weapons/extinguisher.dm
> +/obj/item/weapon/extinguisher/proc/AttemptRefill_hippie(atom/target, mob/user)
procnames should be `thing_thing_thing`

2017-07-16 19:49 UTC, GuyonBroadway commented
thing the thinged with a thing thing

2017-07-17 01:39 UTC, tortellinitony requested changes

2017-07-17 01:39 UTC, tortellinitony commented on hippiestation/code/modules/reagents/reagent_containers/glass.dm
> +		if(target.container_type & OPENCONTAINER)
use is_open_container

2017-07-17 01:39 UTC, tortellinitony commented on hippiestation/code/modules/reagents/reagent_containers/glass.dm
> +		else if(!target.container_type & OPENCONTAINER)
use is_open_container

2017-07-17 01:39 UTC, tortellinitony commented on hippiestation/code/game/objects/items/weapons/extinguisher.dm
> +		return ..()
This will call `AttemptRefill(O, user)` and may cause issues

2017-07-17 14:54 UTC, tortellinitony requested changes

2017-07-17 14:54 UTC, tortellinitony commented on hippiestation/code/game/objects/items/weapons/extinguisher.dm
> +		..()
No... `return ..()` was better. After looking at it, I don't think it will cause issues, so leave it at that.

2017-07-17 16:40 UTC, GuyonBroadway commented
That should do it.

2017-07-17 20:51 UTC, tortellinitony approved these changes

2017-07-17 21:29 UTC, merged