fusion but modular maybe
HippieStation/HippieStationdeprecated2020 pull request #2453
Opened 2017-07-18 21:50 UTC by banthebantz

:cl: banthebantz & as334 
add: Reworked and re enabled plasmic fusion, have fun atmos techs!

/:cl:

[why]: it was a fun little project for atmos autists that got removed because it kept breaking everything or something, now it should be harder to do but more interesting when you do it and stuff.

heat a 90% pure mixture of plasma and carbon dioxide enough and you get fusionsz into nitrogen and oxygen which releases energy and radiation and looks fancy.

also pretty hard to do

2017-07-18 21:54 UTC, banthebantz commented
ahh why

2017-07-18 21:56 UTC, JamieH commented
build this

2017-07-18 21:59 UTC, banthebantz commented
builted

2017-07-18 22:14 UTC, tortellinitony requested changes

2017-07-18 22:14 UTC, tortellinitony commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
Defines go in `code/__DEFINES/hippie.dm`

2017-07-18 22:14 UTC, tortellinitony commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +#define NO_REACTION	0
Use TRUE and FALSE instead, please.

2017-07-18 22:14 UTC, tortellinitony commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "plasmafusion"
This had better be a different id from the original.

2017-07-19 12:08 UTC, banthebantz commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
so we're not maintaining the original file structure? ok but it could cause confusion later down the line

2017-07-19 12:08 UTC, banthebantz commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +#define NO_REACTION	0
using a define to define a define

ok

2017-07-19 12:08 UTC, banthebantz commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +	id = "plasmafusion"
yes yes

2017-07-19 12:45 UTC, GuyonBroadway commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +#define NO_REACTION	0
What he means is, when using boolean logic (aka 1 or 0) you should use TRUE or FALSE instead.

2017-07-19 16:03 UTC, tortellinitony commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +#define NO_REACTION	0
yes get rid of these defines

2017-07-19 16:03 UTC, tortellinitony commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
No it won't

2017-07-19 16:35 UTC, Carbonhell commented
This needs extensive testing before merging, i dont want something like atmos to break smh

2017-07-19 17:35 UTC, banthebantz commented
modularising this causes 
Runtime in gas_mixture.dm,433: Cannot execute null.Copy().
  proc name: react (/datum/gas_mixture/react) 

to be spammed repeatedly

2017-07-19 22:02 UTC, Chnkr commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
I'd suggest using `INFINITY` if you need a "big number"

2017-07-19 22:03 UTC, Chnkr commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_FUSION_ENERGY_HIPPIE             999999
Please stop spacing out all these values, just do `#define THING<space>NUMBER`

2017-07-19 22:04 UTC, Chnkr commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +		return NO_REACTION
`RETURN FALSE`

2017-07-19 22:04 UTC, Chnkr commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +		//to_chat(world, "pre [temperature, [cached_gases["plasma"][MOLES]], [cached_gases["co2"][MOLES]])
This needs to be removed before merging

2017-07-20 15:06 UTC, banthebantz commented on hippiestation/code/__DEFINES/atmospherics.dm
> +#define PLASMA_BINDING_ENERGY_HIPPIE			6000000000000//this has to be a big number
woah nelly that'd make it nearly impossible

2017-07-20 18:14 UTC, banthebantz commented
hype

2017-07-20 19:21 UTC, McBawbaggings commented
can this be used to power radiation collectors if it outputs radiation?

2017-07-20 19:22 UTC, banthebantz commented
yes

2017-07-20 19:23 UTC, Carbonhell commented
No because rad collectors get triggered by the receive_pulse() proc, called both by SM and singularity and only those

2017-07-20 19:23 UTC, banthebantz commented
i've heard that uranium walls can power them though, damm

2017-07-20 19:23 UTC, Carbonhell commented
probs a lie, the only instances of the proc used is in SM and singulo code,it doesn't even care about radiations at all sadly

2017-07-20 19:24 UTC, banthebantz commented
i should add that then

2017-07-20 21:35 UTC, McBawbaggings commented
honestly, i would fucking well support a radioactive gas provided it can be reasonably harnessed into an engine.

2017-07-20 21:36 UTC, banthebantz commented
yeah i'll do it later, i'm having problems getting it work atm

2017-07-20 22:21 UTC, Carbonhell commented
i'd say leave this pr as it is for now, and re-do rad collectors in a new one if you really want. otherwise you'll mix up feature and refactoring,which is bad

2017-07-20 22:32 UTC, GuyonBroadway commented
@McBawbaggings it will turn the turbine engine from "backup power" to **"WEW LAD!"**

2017-07-20 23:25 UTC, JamieH commented
I kinda want someone from @tgstation to look at this before we merge it.

2017-07-21 16:48 UTC, banthebantz commented
i have the power!

2017-07-21 18:32 UTC, tortellinitony submitted a review, later dismissed

2017-07-21 18:32 UTC, tortellinitony commented on hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
> +		var/moles_impurities = (cached_gases["plasma"][MOLES]+cached_gases["co2"][MOLES])/air.total_moles()//more plasma+carbon = higher chance of collision regardless of actual thermal energy
This is nitpicky, but please put a space in between variables when using math operators `* / - +`.

2017-07-21 18:43 UTC, tortellinitony commented
I think this looks like it's worth a testmerge.

2017-07-25 15:32 UTC, Carbonhell approved these changes

2017-07-25 15:33 UTC, Carbonhell commented
On a test server it worked fine. I have a few doubts on this, but if shit goes bad we'll just revert.

2017-07-25 15:34 UTC, merged