SHADOWLINGS
HippieStation/HippieStationdeprecated2020 pull request #2593
Opened 2017-07-30 03:55 UTC by MoreRobustThanYou

:cl: More Robust Than You
add: SHADOWLINGS! FOR REAL!!!
/:cl:

2017-07-30 04:01 UTC, MoreRobustThanYou commented
will test more thoroughly tomorrow

2017-07-30 04:09 UTC, MoreRobustThanYou commented
Apparently traitor panel don't work so I can't test it

_Sent from my Google Kindle Fire HDX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-07-30 11:01 UTC, MoreRobustThanYou commented
ok i got everything working

2017-07-30 11:10 UTC, MoreRobustThanYou commented
IT WORKS!!

2017-07-30 11:10 UTC, MoreRobustThanYou commented
oh crap didn't mean to click close

2017-07-30 11:17 UTC, MoreRobustThanYou commented
also for some reason, when code/__DEFINES/role_preferences.dm is moved to the hippie folder, and the hippie version is checked / normal version unchecked, everything errors

2017-07-30 11:24 UTC, ghost submitted a review, later dismissed
there is a bunch of << when we have to_chat() which should be changed.

I really don't like shadowling but I think it should exist in code at the very least so it can be run.

2017-07-30 11:24 UTC, McBawbaggings commented on code/datums/mind.dm
> +					current << "<span class='userdanger'>Your powers have been quenched! You are no longer a shadowling!</span>"
You're using << when you should use to_chat()

2017-07-30 11:24 UTC, McBawbaggings commented on hippiestation/code/game/gamemodes/shadowling/ascendant_shadowling.dm
> +		to_chat(M, "<span class='notice'><i><b>You feel a woosh as newly released energy temporarily distorts space itself...</b></i></span>")
Ellipsis should be ended with a fullstop, thus making it ....

2017-07-30 11:26 UTC, MoreRobustThanYou commented on hippiestation/code/game/gamemodes/shadowling/ascendant_shadowling.dm
> +		to_chat(M, "<span class='notice'><i><b>You feel a woosh as newly released energy temporarily distorts space itself...</b></i></span>")
Fullstop?

2017-07-30 11:30 UTC, McBawbaggings commented on hippiestation/code/game/gamemodes/shadowling/ascendant_shadowling.dm
> +		to_chat(M, "<span class='notice'><i><b>You feel a woosh as newly released energy temporarily distorts space itself...</b></i></span>")
'.' also known as a period.
If you are doing an ellipsis at the end of a sentence then basically do .... as opposed to ...

2017-07-30 11:40 UTC, MoreRobustThanYou commented on code/datums/mind.dm
> +					current << "<span class='userdanger'>Your powers have been quenched! You are no longer a shadowling!</span>"
I'm fixing the rogue <<s that escaped my spam Ctrl+F'ing

2017-07-30 11:43 UTC, MoreRobustThanYou commented
@McBawbaggings this code better now?

2017-07-30 12:48 UTC, MoreRobustThanYou commented
Would it be possible for this to be merged today?

2017-07-30 14:27 UTC, GuyonBroadway commented
Unlikely,a game-mode change this big is gonna need a +1 from two head admins and a code review by a maintainer and POSSIBLY the head coder.

And we won't see it live on the server till Jamie gets back from Las Vegas anyway as none of us can run the update script.

2017-07-31 15:20 UTC, Voratius commented
-1, advertised it in general chat on discord

2017-07-31 15:21 UTC, MoreRobustThanYou commented
nobody cares

2017-08-01 02:52 UTC, MoreRobustThanYou commented
yes i'm ```Amari Ray (thefastfoodguy)``` on discord

2017-08-01 02:54 UTC, MoreRobustThanYou commented
whoops clicked the wrong button

2017-08-03 15:43 UTC, GuyonBroadway submitted a review, later dismissed

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/datums/mind.dm
> +	remove_changeling()
Ye haven't added slings to the existing antag manipulation verbs so admins adding/removing them via verbs is not possible.

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/ascendant_shadowling.dm
> +		M << 'sound/hallucinations/wail.ogg'
use playsound.local()

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling.dm
> +				H << 'sound/weapons/sear.ogg'
Please use playsound.local()

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +						to_chat(user, "<span class='notice'>They are enslaved by Nanotrasen. You begin to shut down the nanobot implant - this will take some time.</span>")
They are called "mindshield implants" these days.

Change it to something along the lines of "They are protected by an implant. You begin to shut down the nanobots in their brain - this will take some time."

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +						to_chat(target, "<span class='boldannounce'>You feel your loyalties begin to weaken!</span>")
Change this to "You feel your mental protection faltering!"

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +						to_chat(user, "<span class='notice'>The nanobots composing the loyalty implant have been rendered inert. Now to continue.</span>")
Change loyalty to Mindshield

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +	var/obj/item/weapon/reagent_containers/glass/beaker/large/B = new /obj/item/weapon/reagent_containers/glass/beaker/large(user.loc) //hacky
There might be a better way to do this, I would have to ask Tony about it.

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +						sleep(100) //10 seconds - not spawn() so the enthralling takes longer
These sleeps will need to go if we are to port this, sleep is bad.

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +				sleep(20)
Another sleep that needs to be nipped in the bud.

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +				sleep(10)
No sleeps please.

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +	sleep(40)
This sleep too

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +			sleep(4)
This sleep too

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(50)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(100)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(90)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(80)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +			sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(50)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(100)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(90)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(40)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(1)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +				sleep(50)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling.dm
> +		sleep(10)
and this sleep

2017-08-03 15:43 UTC, GuyonBroadway commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +					sleep(20)
I really don't like this sleep here or the myraid of other times its used.

2017-08-03 15:45 UTC, GuyonBroadway commented
Sleep is a bad thing to use due to the way it interacts with the master controller, Sorry but this isn't going to be a "simple" port it's gonna need a whole lotta diddly to get working properly. 

Still, to be the person who "fixed" shadowlings would be quite the achievement.

2017-08-03 18:49 UTC, ghost requested changes
I did a quick glance over the code, i really really like the addition of shadowlings, but some of the code needs some work.

Ping me on discord if you need help

2017-08-03 18:49 UTC, Chnkr commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_SHADOWLING			"shadowling"
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on code/__DEFINES/role_preferences.dm
> +	ROLE_SHADOWLING = /datum/game_mode/shadowling
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on code/datums/mind.dm
> +	mind.special_role = ""
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on code/modules/admin/topic.dm
> +			if("shadowling")
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on code/modules/mob/living/carbon/examine.dm
> +		if(!src.wear_mask && is_thrall(src))
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on code/modules/mob/living/silicon/robot/login.dm
> +		SSticker.mode.remove_thrall(mind,0)
No code additions in the `code` folder, use the `hippiestation` folder, there is a nice readme in there, follow it.

2017-08-03 18:49 UTC, Chnkr commented on hippiestation/code/modules/mob/mob_movement.dm
> +#define MAX_SW_LUMS 0.2
Do not mirror this entire file

2017-08-03 18:49 UTC, Chnkr commented on hippiestation/code/modules/admin/verbs/one_click_antag.dm
> +/client/proc/one_click_antag()
do not mirror this entire file

2017-08-03 18:49 UTC, Chnkr commented on hippiestation/code/game/gamemodes/shadowling/special_shadowling_abilities.dm
> +var/list/possibleShadowlingNames = list("U'ruan", "Y`shej", "Nex", "Hel-uae", "Noaey'gief", "Mii`mahza", "Amerziox", "Gyrg-mylin", "Kanet'pruunance", "Vigistaezian") //Unpronouncable 2: electric boog
Use globals for this please

2017-08-03 19:25 UTC, MoreRobustThanYou commented on code/__DEFINES/role_preferences.dm
> +	ROLE_SHADOWLING = /datum/game_mode/shadowling
I tried, but for some reason, doing it in the hippie folder caused ERRORS EVERYWHERE

2017-08-03 20:20 UTC, GuyonBroadway commented on code/__DEFINES/role_preferences.dm
> +	ROLE_SHADOWLING = /datum/game_mode/shadowling
paste em in discord, we can help

2017-08-05 19:34 UTC, MoreRobustThanYou commented
I am working on these changes, over on the /tg/ shadowling branch, i'll port them over once they're finished

2017-08-05 20:16 UTC, tortellinitony commented
sleeps are fine

2017-08-05 20:19 UTC, MoreRobustThanYou commented
then why'd @GuyonBroadway flip his shit about em

2017-08-05 20:23 UTC, tortellinitony commented
i don't know

2017-08-05 20:24 UTC, MoreRobustThanYou commented
apparently because they "pause things and cause huge problems".... except MANY MANY things still use sleeps and everything works fine

2017-08-05 20:50 UTC, MoreRobustThanYou commented
Wait what
why does it change tgstation.dme

2017-08-05 22:04 UTC, GuyonBroadway commented
Erik says to avoid sleeps like the plauge and erik is better ar code than me so...

2017-08-05 22:13 UTC, MoreRobustThanYou commented
@GuyonBroadway the only viable alternative is Spawn, and, well

> spawned off code is about 30x the cost of a proc call

2017-08-05 22:15 UTC, MoreRobustThanYou commented on code/modules/admin/topic.dm
> +			if("shadowling")
i fixed this one by keeping the if("shadowling") but making it use a hook proc

2017-08-05 22:15 UTC, MoreRobustThanYou commented on hippiestation/code/modules/mob/mob_movement.dm
> +#define MAX_SW_LUMS 0.2
fixed

2017-08-05 22:16 UTC, MoreRobustThanYou commented on code/__DEFINES/role_preferences.dm
> +	ROLE_SHADOWLING = /datum/game_mode/shadowling
i'll try again, but this file will NEED to be mirrored due to it's nature

2017-08-05 22:19 UTC, MoreRobustThanYou commented on code/modules/mob/living/carbon/examine.dm
> +		if(!src.wear_mask && is_thrall(src))
Fixed with a hook proc

2017-08-05 22:19 UTC, MoreRobustThanYou commented on code/__DEFINES/role_preferences.dm
> +	ROLE_SHADOWLING = /datum/game_mode/shadowling
https://pastebin.com/qUddfWig

2017-08-05 22:19 UTC, MoreRobustThanYou commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_SHADOWLING			"shadowling"
https://pastebin.com/qUddfWig

2017-08-05 22:20 UTC, MoreRobustThanYou commented on code/datums/mind.dm
> +	mind.special_role = ""
Some parts of this file are near-impossible to modularize, but I did what I could.

2017-08-05 22:23 UTC, MoreRobustThanYou commented
@Chnkr please re-review, I modularized mostly everything and used hook procs for the rest

2017-08-06 09:36 UTC, Chnkr commented
@MoreRobustThanYou reviewing now

2017-08-06 09:38 UTC, Chnkr commented on code/modules/admin/topic.dm
> +			if("shadowling")
👍

2017-08-06 09:38 UTC, Chnkr commented on tgstation.dme
> -#include "code\game\gamemodes\clock_cult\clock_structures\interdiction_lens.dm"
where did this go?

2017-08-06 09:39 UTC, ghost approved these changes
The code is fine with me, i think we can merge this as a test

2017-08-06 09:41 UTC, GuyonBroadway commented on tgstation.dme
> -#include "code\game\gamemodes\clock_cult\clock_structures\interdiction_lens.dm"
This is the result of them having an outdated local repo. A recent /tg/change removed the interdiction lens and merged its functionality with the sigil of power or whatever.

2017-08-06 11:45 UTC, GuyonBroadway commented
If Erik approves then so do I. 

Needs the ok from a head or two before we press the go button but code is good to go.

2017-08-06 21:58 UTC, canigetuhhhh commented
yeah uhhh lemme hit this up with a +1 from me if everything is good to go.

note: this is tfw the most mediocre gm of all time.

2017-08-06 22:58 UTC, bardofrage commented
Code approved? Smash that mf +1 button

2017-08-06 23:01 UTC, Dudeinyourbackyard commented
+1 yes

2017-08-06 23:01 UTC, DinduStuffin commented
+1 yes do it now

2017-08-06 23:02 UTC, merged

2017-08-06 23:04 UTC, MoreRobustThanYou commented
Yes i'm @Chervilpaw#0856 or "Amari Ray (thefastfoodguy)" on discord