Blob snuggling
HippieStation/HippieStationdeprecated2020 pull request #3005
Opened 2017-08-30 18:59 UTC by MoreRobustThanYou

:cl: Thefastfoodguys
add: you can now erp with blobs
/:cl:

2017-08-30 19:00 UTC, banthebantz commented
sticks ze benizz in de blob ;B

2017-08-30 19:00 UTC, MoreRobustThanYou commented
also wtf travis ci is drunk

2017-08-30 19:01 UTC, McBawbaggings commented on code/game/gamemodes/blob/theblob.dm
> +/obj/structure/blob/attack_hand(mob/M)
does this only work on help intent?

2017-08-30 20:25 UTC, MoreRobustThanYou commented on code/game/gamemodes/blob/theblob.dm
> +/obj/structure/blob/attack_hand(mob/M)
now it does

2017-08-30 20:31 UTC, JamieH commented
build this

2017-08-30 20:37 UTC, MoreRobustThanYou commented
It compiles

2017-08-30 21:53 UTC, DinduStuffin commented
-1
/tg/ removed this for an incredibly valid reason. All it does is encourage people to be friendly to blobs, and blobs to be friendly to players. There's three possibilities from this then:

1) The blob just kills the guy, and he's dead weight because he isn't fighting the blob like he should be
2) The blob doesn't kill the guy (or any guy) because he too wants to be 'friendly' and get ERPd.
3) neither side does anything and the round either stagnates or the blob wins.

This is the kind of feature that I think that, despite adding something to the game from a code perspective, takes away from it from a design perspective.

2017-08-30 21:57 UTC, MoreRobustThanYou commented
blobs have feelings too

2017-08-30 22:00 UTC, DinduStuffin commented
it's going to turn it either into TF2 friendly heavy bullshit that no one wants, or become a literally useless feature when anyone who tries to hug a blob gets killed instantly

2017-08-31 08:10 UTC, JamieH commented
build this

2017-08-31 09:23 UTC, JamieH commented
build this

2017-08-31 09:29 UTC, JamieH commented
build this

2017-08-31 09:40 UTC, JamieH commented
-1, I agree with the reasoning of Dindu

2017-08-31 10:43 UTC, Arzion5 commented
I like the idea. Let people be friendly with the risk of ending up on darwin awards. In an extremely populated round, there'd be at most 2-3 friendlies out of about 50. Everyone on Hippie demands their valids for dinner

2017-08-31 15:02 UTC, DinduStuffin commented
I'd rather have 0 people doing it than 2-3 people doing it. It's an addition that adds nothing to the game, because it's either going to not be used, or used and immediately killed for it, because instead of fighting the blob, they're just going to try and ERP with it. This was removed from /tg/ for a reason, and robust is just trying to push it here.

2017-08-31 15:16 UTC, JamieH commented
I'd like to see this more modular too

2017-08-31 17:42 UTC, DinduStuffin commented
Also I'd like to note that a lot of blob rounds have the problem of people either griefing, or not fighting the blob at all. I think we shouldn't add shit that will encourage that.

2017-09-02 14:17 UTC, ghost requested changes

2017-09-02 14:17 UTC, Chnkr commented on code/game/gamemodes/blob/overmind.dm
> +	var/acceptLove = FALSE
Please put this in the `hippie` subfolder and for the love of god name it `accept_love`

2017-09-02 14:17 UTC, Chnkr commented on code/game/gamemodes/blob/powers.dm
> +/mob/camera/blob/verb/toggle_cuddles()
See above.

2017-09-02 14:17 UTC, Chnkr commented on code/game/gamemodes/blob/theblob.dm
> +/obj/structure/blob/attack_hand(mob/M)
See above

2017-09-02 14:17 UTC, closed without merging