Nations gamemode
HippieStation/HippieStationdeprecated2020 pull request #3065
Opened 2017-09-03 16:42 UTC by tortellinitony

:cl: Tortellini Tony
add: Nations gamemode ported from Paradise. Admin only
/:cl:

2017-09-03 18:06 UTC, McBawbaggings commented
i'm really not big into nations but i know others like it

i think some supporting code to help people run it more efficiently is better than just me saying "no i dislike the nations mode" but allowing people to run it anyway.

2017-09-03 20:47 UTC, ghost requested changes

2017-09-03 20:47 UTC, Chnkr commented on code/__DEFINES/atom_hud.dm
> +#define ANTAG_HUD_NATIONS		19
This can be done inside the `hippiestation` folder

2017-09-03 20:47 UTC, Chnkr commented on code/modules/mob/mob.dm
> +		var/image/I = image('hippiestation/icons/mob/hud.dmi', src, "")
might just want to do a IF here to only pull our huds out of our folder

2017-09-04 02:01 UTC, tortellinitony commented
OK it should actually work now

2017-09-04 11:42 UTC, JamieH commented on code/modules/mob/mob.dm
> +		var/image/I = image('hippiestation/icons/mob/hud.dmi', src, "")
I'm going to be putting a hook proc here for gang anyway, so he should put my hook in

2017-09-04 11:42 UTC, JamieH commented
@tortellinitony You should wait for Gang to be merged, since I'll be adding a fuck tonn of hooks.

2017-09-18 04:48 UTC, tortellinitony commented
So I've decided I'm not gonna take up adding war and peace initially, but I'll probably jam it in as a later update, same deal with nations chat. I'll get the verbs working, make them action buttons, and then this should be good to go

2017-10-20 22:10 UTC, closed without merging