Hippie Station three: the reckoning, the return of the gangs
HippieStation/HippieStationdeprecated2020 pull request #3072
Opened 2017-09-03 22:02 UTC by JamieH

:cl: Jambread
add: Add back gangs
/:cl:

This needs to be better modualised but it's shit code, so if you can give me suggestions on what to modualise then that'd be 👍

2017-09-03 22:11 UTC, Arzion5 commented
The implant system is overpowered but it does not allow lieutenant promotion. Old gangs were nicer but you had to suck the gang leader's cock for base-line gang equipment. Removing the implant system but automatically giving gang members sprays and a switchblade upon converting would be an interesting idea, though it will blow over the gang's cover if the target has full inventory

2017-09-03 23:11 UTC, GuyonBroadway requested changes

2017-09-03 23:11 UTC, GuyonBroadway commented on code/datums/mind.dm
> +/datum/mind/proc/make_Gang(datum/gang/G)
As its a datum this could go in its own file

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/antag_hud.dm
> +/datum/atom_hud/antag/gang
All these datums could go in their own file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/gang/dominator.dm
> +#define DOM_BLOCKED_SPAM_CAP 6
this whole file could go in the hippie folder, but as its a whole file it's not that important.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/gang/gang_datum.dm
> +//gang_datum.dm
This whole file can go in the hippie folder

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/gang/gang_items.dm
> +/datum/gang_item
This file could go in the hippie folder

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/gang/gang_pen.dm
> +/*
This file could go in the Hippie folder

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/gang/recaller.dm
> +//gangtool device
This could go in the hippie file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
> +/obj/effect/decal/cleanable/crayon/gang/swarmer_act(mob/living/simple_animal/hostile/swarmer/S)
this could be moved to a separate file

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/countdown.dm
> +/obj/effect/countdown/dominator
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/countdown.dm
> +/obj/effect/countdown/dominator/get_value()
This could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/decals/crayon.dm
> +/obj/effect/decal/cleanable/crayon/gang
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/decals/crayon.dm
> +/obj/effect/decal/cleanable/crayon/gang/Initialize(mapload, var/datum/gang/G, var/e_name = "gang tag", var/rotation = 0,  var/mob/user)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/decals/crayon.dm
> +/obj/effect/decal/cleanable/crayon/gang/proc/set_mind_owner(datum/mind/mind)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/effects/decals/crayon.dm
> +/obj/effect/decal/cleanable/crayon/gang/Destroy()
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/proc/can_claim_for_gang(mob/user, atom/target)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/proc/territory_claimed(area/territory, mob/user)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/proc/tag_for_gang(mob/user, atom/target)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/spraycan/gang
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/spraycan/gang/New(loc, datum/gang/G)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/crayons.dm
> +/obj/item/toy/crayon/spraycan/gang/examine(mob/user)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/game/objects/items/implants/implant_gang.dm
> +/obj/item/implant/gang
This whole file could be moved to the hippie folder.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/admin/verbs/one_click_antag.dm
> +/datum/admins/proc/makeGangsters()
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/clothing/neck/neck.dm
> +/obj/item/clothing/neck/necklace/dope/gang_contraband_value()
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/jobs/job_exp.dm
> +/proc/lookforgangrole(rolecheck)
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +/datum/uplink_item/dangerous/smg/unrestricted
this could be moved to a separate file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
To modularize this you could  put 

` 
/datum/uplink_item/dangerous/crossbow
	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)` In our uplink datums file.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list()
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	include_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Same goes for here.

2017-09-03 23:11 UTC, GuyonBroadway commented on tgstation.dme
> +#include "code\game\gamemodes\gang\dominator.dm"
Make sure to unstage these changes from tgstation.dme

2017-09-04 08:23 UTC, ghost requested changes
I stopped reviewing halfway trough, this needs more work.

- The code *needs* to be modularized, most if not all of the existing procs can call hippie specific versions and have them return/handle the hippie specific code there.

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/misc.dm
> +#define GANGSTER_BOSS_STARTING_INFLUENCE 20
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/misc.dm
> +#define GANGSTER_SOLDIER_STARTING_INFLUENCE 5
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/misc.dm
> +#define GANG_TAKEOVER 7
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/misc.dm
> +#define GANG_LOSS 6
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_GANG				"gangster"
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/__DEFINES/role_preferences.dm
> +	ROLE_GANG = /datum/game_mode/gang,
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

Now since `special_roles` is a list, you an just `add` to this list in a hippie-specific init proc

2017-09-04 08:23 UTC, Chnkr commented on code/controllers/subsystem/ticker.dm
> +				if("gang war") //Gang Domination (just show the override screen)
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

It'd be best to just create a `hippie` specific call in the `ticker` that handles this

2017-09-04 08:23 UTC, Chnkr commented on code/controllers/subsystem/ticker.dm
> +		if(GANG_LOSS)
and this

2017-09-04 08:23 UTC, Chnkr commented on code/controllers/subsystem/ticker.dm
> +		if(GANG_TAKEOVER)
and this

2017-09-04 08:23 UTC, Chnkr commented on code/datums/hud.dm
> +	var/gang_huds = list()
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

You could handle this by making `reload_huds()` call a hippie specific proc for the hippie specific huds

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	var/datum/gang/gang_datum //Which gang this mind belongs to, if any
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +/datum/mind/proc/remove_gang()
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	if(gang_datum)
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	remove_gang()
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +		gang_datum.remove_gang_hud(src)
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	else if(is_gangster(creator))
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

This should be a hippie specific call ( e.g. `hippie_equip_traitor` )

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	remove_gang()
This can all go into a hippie specific call ( e.g. `hippie_remove_antag_equip` )

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +	if(gang_datum)
This can all go into a hippie specific call ( e.g. `hippie_remove_antag_equip` )

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +		"gang",
See above

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +		/** GANG ***/
See above, all of the below can be pulled from a hippie proc

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +//////////////////// GANG MODE
See above

2017-09-04 08:23 UTC, Chnkr commented on code/datums/mind.dm
> +/datum/mind/proc/make_Gang(datum/gang/G)
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/game/gamemodes/antag_hud.dm
> +/datum/atom_hud/antag/gang
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/game/gamemodes/game_mode.dm
> +	possible_modes.Add("blob", "changeling", "clock_cult", "cult", "extended", "gang", "malf", "nuclear", "revolution", "traitor", "wizard", "shadowling")
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-04 08:23 UTC, Chnkr commented on code/game/gamemodes/game_mode.dm
> +	possible_modes.Add("blob", "changeling", "clock_cult", "cult", "extended", "gang", "malf", "nuclear", "revolution", "traitor", "wizard", "shadowling")
This can be done by adding a hippie specific call ( e.g. `hippie_get_possible_modes` ) that is added to `Add()`

2017-09-04 08:23 UTC, Chnkr commented on code/game/gamemodes/game_mode.dm
> +	SSticker.mode.remove_gangster(newborgie, 0, remove_bosses=1)
See above, above and above. Create a hippie specific version of this proc and call it. `hippie_remove_antag_for_borging`

2017-09-04 08:23 UTC, Chnkr commented on code/game/gamemodes/gang/dominator.dm
> +#define DOM_BLOCKED_SPAM_CAP 6
To make sure we can easily merge upstream changes from /tg/station back into our repo you need to place new content in the correct folders, this will also make it easier to rebase if we ever need to do so in the future.

- All new code should go into `/code/modules/hippie`
- All new icons should go into `/icons/hippie`
- All new sounds should go into `/sounds /hippie`

2017-09-24 17:32 UTC, closed without merging