localised mentally unwell male adds turfchems
HippieStation/HippieStationdeprecated2020 pull request #3083
Opened 2017-09-04 14:14 UTC by banthebantz

:cl: banthebantz
experiment: Chemicals can now be applied to turfs directly goonstation style via splashing/smoke/foam
/:cl:

[why]: It can allow for a hell of a lot of fun experimentation with chem mixes.

I've added sanity checks for explosions and such but this still has runtimes with explosive smoke that I am yet to figure out

[14:50:54] Runtime in LINDA_system.dm,97: Cannot execute null.air update turf().
  proc name: air update turf (/atom/proc/air_update_turf)

[14:50:54] Runtime in reagents.dm,17: Cannot read null.total_volume
  proc name: reaction turf (/datum/reagent/proc/reaction_turf)

[14:50:55] Runtime in reagent_containers.dm,72: Cannot read null.chem_temp

these 3 fuckers are an issue

2017-09-04 14:28 UTC, ghost submitted a review, later dismissed

2017-09-04 14:28 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
> +	if(reagents)
```if(reagents && reagents.total_volume)```

2017-09-04 14:28 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
> +	if(reagents)
```if(reagents && reagents.chem_temp)```

2017-09-04 14:49 UTC, JamieH commented
https://share.jamiehankins.co.uk/ShareX/2017/09/2017-09-04_15-43-01.mp4

2017-09-04 14:57 UTC, ghost requested changes
Something needs to be done about the spam

2017-09-04 15:27 UTC, ghost requested changes

2017-09-04 15:27 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
> +			reagents.trans_to(M, rand(1,5)* M.get_permeability_protection())
```CHECK_TICK```

2017-09-04 15:27 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
> +		reagents.handle_reactions()
```CHECK_TICK```

2017-09-04 15:27 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/effects/effect_system/effects_smoke.dm
> +		reagents.reaction(T, TOUCH, fraction)
```CHECK_TICK```

2017-09-04 15:30 UTC, ghost submitted a review, later dismissed

2017-09-04 15:30 UTC, Chnkr commented on hippiestation/code/modules/reagents/chemistry/reagents.dm
> +	for(var/obj/effect/decal/cleanable/chempile/c in T.contents)//handles merging existing chempiles
Please use _istypeless for loops_ you can find more information about this in the [contributing.md](https://github.com/HippieStation/HippieStation13/blob/master/CONTRIBUTING.md)

2017-09-04 15:30 UTC, Chnkr commented on hippiestation/code/game/objects/effects/effect_system/effects_smoke.dm
> +		for(var/atom/movable/AM in T)
Please use _istypeless for loops_ you can find more information about this in the [contributing.md](https://github.com/HippieStation/HippieStation13/blob/master/CONTRIBUTING.md)

2017-09-04 15:37 UTC, banthebantz commented on hippiestation/code/game/objects/effects/effect_system/effects_smoke.dm
> +		for(var/atom/movable/AM in T)
"Of course, if the list contains data of a mixed type then the above optimisation is DANGEROUS, as it will blindly typecast all data in the list as the specified type, even if it isn't really that type! which will cause runtime errors."

2017-09-04 15:37 UTC, banthebantz commented on hippiestation/code/modules/reagents/chemistry/reagents.dm
> +	for(var/obj/effect/decal/cleanable/chempile/c in T.contents)//handles merging existing chempiles
"Of course, if the list contains data of a mixed type then the above optimisation is DANGEROUS, as it will blindly typecast all data in the list as the specified type, even if it isn't really that type! which will cause runtime errors."

2017-09-04 17:09 UTC, banthebantz commented
log spam fixed

2017-09-04 17:26 UTC, ghost submitted a review, later dismissed

2017-09-04 17:27 UTC, ghost approved these changes
woops didnt mean to dismiss my approval

2017-09-04 17:30 UTC, McBawbaggings commented
I worry shit like teslium will be potent as fuck and other things like unstable mutagen piles for mutagen powers a-la vaping.

2017-09-04 17:31 UTC, banthebantz commented
mutagen vaping was changed ages ago.

as for explosive smoke from what i've seen it's a lot more effective at destroying tiles but the actual radius is terrible because it's lots of small explosions rather tahn one big one

2017-09-04 17:32 UTC, MoreRobustThanYou commented
@McBawbaggings chempiles ARE visible.

2017-09-04 17:32 UTC, bardofrage commented
Seems really cool and I'd like to see it, Definitely some balance concerns with it though.

2017-09-04 17:32 UTC, banthebantz commented
currently they apply at 25% effectiveness, this number can be tweaked later if it's too strong, also take note of the special verb to remove all chem piles if someone manages to make some horrible lagnade

2017-09-04 17:34 UTC, McBawbaggings commented
yeah sure, i'd like to see this trialed?
+1

2017-09-04 20:18 UTC, tortellinitony commented
this is one of those things that can cause a lot of problems that nobody will figure out until it fucks stuff up on the live server, so I dunno...

2017-09-04 21:50 UTC, banthebantz commented
it seems fine so far

2017-09-05 21:28 UTC, banthebantz commented
i pushed a fix to the slime bug

2017-09-06 23:09 UTC, MoreRobustThanYou commented
nice try, sneaking top-tier parts into hippiestation/code/game/objects/items/circuitboards/machine_circuitboards.dm

2017-09-07 03:23 UTC, merged

2017-09-07 15:29 UTC, banthebantz commented
the fuck are you on about?