Fixes hydropnics trays taking double chems.
HippieStation/HippieStationdeprecated2020 pull request #3117
Opened 2017-09-05 20:58 UTC by GuyonBroadway

Turns out we modified hydroponics.dm ages ago before tg removed ambrosia gaia and never changed it back when they readded it, as a result we had a second reagents transfer call and hey ho there you go.

:cl: GuyonBroadway
fix: fixed the bug where hydroponics trays were taking more reagents than they should. 
/:cl:

2017-09-05 22:21 UTC, tortellinitony requested changes

2017-09-05 22:21 UTC, tortellinitony commented on code/modules/hydroponics/hydroponics.dm
> +			overlays += mutable_appearance('icons/obj/hydroponics/equipment.dmi', "gaia_blessing")
NO!

2017-09-05 22:21 UTC, tortellinitony commented on code/modules/hydroponics/hydroponics.dm
> +			add_atom_colour(rgb(255, 175, 0), FIXED_COLOUR_PRIORITY)
what does this have to do with it?

2017-09-05 22:21 UTC, GuyonBroadway commented on code/modules/hydroponics/hydroponics.dm
> +			overlays += mutable_appearance('icons/obj/hydroponics/equipment.dmi', "gaia_blessing")
this is the file exactly as is from /tg/

2017-09-05 22:21 UTC, GuyonBroadway commented on code/modules/hydroponics/hydroponics.dm
> +			add_atom_colour(rgb(255, 175, 0), FIXED_COLOUR_PRIORITY)
this is the file exactly as is from /tg/

2017-09-06 00:42 UTC, tortellinitony approved these changes

2017-09-06 00:42 UTC, merged