Pools now change color with reagents!
HippieStation/HippieStationdeprecated2020 pull request #3286
Opened 2017-09-13 19:04 UTC by MoreRobustThanYou

:cl: Thefastfoodguy
add: Pools now change color with reagents!
/:cl:

2017-09-13 19:05 UTC, banthebantz commented on hippiestation/code/modules/pool/pool_controller.dm
> +		if(LAZYLEN(beaker.reagents.reagent_list))
lazylen isn't needed

2017-09-13 19:06 UTC, MoreRobustThanYou commented on hippiestation/code/modules/pool/pool_controller.dm
> +		if(LAZYLEN(beaker.reagents.reagent_list))
what if there's no reagents?

2017-09-13 19:07 UTC, banthebantz commented on hippiestation/code/modules/pool/pool_controller.dm
> +		if(LAZYLEN(beaker.reagents.reagent_list))
then it checks the list regardless???

2017-09-13 19:08 UTC, MoreRobustThanYou commented on hippiestation/code/modules/pool/pool_controller.dm
> +		if(LAZYLEN(beaker.reagents.reagent_list))
also, it's to set the color back to normal if there's no reagents

2017-09-13 19:08 UTC, banthebantz commented on hippiestation/code/modules/pool/pool_controller.dm
> +		if(LAZYLEN(beaker.reagents.reagent_list))
nevermind

2017-09-13 19:39 UTC, GuyonBroadway commented
Approval subject to successful code test.

2017-09-13 20:25 UTC, tortellinitony commented
fix the pool blood while you're at it

2017-09-13 20:26 UTC, MoreRobustThanYou commented
pool blood? wut?

2017-09-13 20:29 UTC, tortellinitony requested changes

2017-09-13 20:29 UTC, tortellinitony commented on hippiestation/code/modules/pool/pool_controller.dm
> +/obj/machinery/poolcontroller/proc/update_color()
make this a proc for each turf please

2017-09-13 20:33 UTC, MoreRobustThanYou commented on hippiestation/code/modules/pool/pool_controller.dm
> +/obj/machinery/poolcontroller/proc/update_color()
done

2017-09-13 20:35 UTC, tortellinitony submitted a review, later dismissed

2017-09-13 20:35 UTC, tortellinitony commented on hippiestation/code/modules/pool/pool_controller.dm
> +			update_color(W)
you shouldn't have to call it here

2017-09-13 20:38 UTC, MoreRobustThanYou commented on hippiestation/code/modules/pool/pool_controller.dm
> +			update_color(W)
this was because i found out the colors didnt update until i got in the pool and swalloed water

2017-09-13 21:08 UTC, tortellinitony commented on hippiestation/code/modules/pool/pool_controller.dm
> +			update_color(W)
no they update as soon as reagenttimer = 0

2017-09-13 22:27 UTC, tortellinitony commented
there's still the blood stuff figure it out

2017-09-14 09:57 UTC, McBawbaggings commented
good change +1

2017-09-14 17:55 UTC, Super3222 commented
Here comes poo water

2017-09-14 17:59 UTC, McBawbaggings commented
D E S I G N A T E D
S H I T T I N G
P O O L S

2017-09-14 20:42 UTC, j-mie approved these changes

2017-09-14 20:42 UTC, merged