Fixes various icons
HippieStation/HippieStationdeprecated2020 pull request #3441
Opened 2017-09-20 23:05 UTC by tortellinitony

:cl: Tortellini Tony
add: Old box, power generator, and cell-charger icons are back!
/:cl:

2017-09-20 23:06 UTC, ghost submitted a review, later dismissed
gay but code is fine

2017-09-21 20:36 UTC, PopNotes commented
images needed

2017-09-21 22:33 UTC, j-mie requested changes

2017-09-21 22:33 UTC, JamieH commented on hippiestation/code/game/objects/items/weapons/storage/boxes.dm
>  /obj/item/storage/box
Nah, don't do this, our icons are out of date and it was breaking the chefs boxes. Either document the DMIs we have completely mirrored or only overwrite the paths we need too.

2017-10-01 16:28 UTC, j-mie approved these changes

2017-10-01 16:28 UTC, merged