Adds the alternate_farts var to mobs
HippieStation/HippieStationdeprecated2020 pull request #3508
Opened 2017-09-24 18:19 UTC by MoreRobustThanYou

Now admemes can varedit your farts, too!

:cl: Thefastfoodgu
admin: Adds the alternate_farts var to mobs
/:cl:

2017-09-24 18:56 UTC, banthebantz commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +	var/list/alternate_farts
shouldn't you init this list?

2017-09-24 18:56 UTC, Arzion5 commented
What a time to be alive +1

2017-09-24 18:58 UTC, MoreRobustThanYou commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +	var/list/alternate_farts
done (it's done as a LAZYINITLIST in the code)

2017-09-25 22:44 UTC, mlgdatboi commented
+1 not exploitable in any way as only admins can add them

2017-09-27 17:13 UTC, GuyonBroadway submitted a review, later dismissed
Yeah i guess this looks good.

2017-09-28 20:39 UTC, GuyonBroadway commented
build this

2017-09-28 21:46 UTC, tortellinitony requested changes
Integrate alien fart sound with this system.

2017-10-01 18:30 UTC, tortellinitony commented
Set alien mobs `alternate_farts = list('hippiestation/sound/effects/alienfart.ogg')`

2017-10-01 18:31 UTC, tortellinitony submitted a review, later dismissed

2017-10-01 18:31 UTC, tortellinitony commented on hippiestation/code/modules/mob/living/carbon/human/emote.dm
> +		if(!LAZYLEN(user.alternate_farts))
Remove this bit here

2017-10-01 21:24 UTC, j-mie approved these changes

2017-10-01 21:29 UTC, merged