Added 3 new uplink items.
HippieStation/HippieStationdeprecated2020 pull request #3631
Opened 2017-09-30 16:37 UTC by Arzion5

:cl:
add: Added instant bear, banhammer and instakill gun to traitor uplink.
/:cl:
Just simple additions to the uplink. The instant bear is useful for when you are chased, the banhammer is a fun toy, and you require the aid of 4 other traitors along with yourself to acquire it. If you somehow managed the gargantuan task of convincing people to give you TC without having the instakill gun be theirs, then you probably deserve the right to kill everyone on the station.

2017-09-30 16:46 UTC, McBawbaggings commented
i uh, really don't know about the instant kill gun

i really don't think co-operation like that will ever happen but the idea of an instant kill weapon existing is bad.

but i do also really appreciate the fact there will only be 1 gun and ultimately, only 1 traitor can have it.

2017-09-30 18:50 UTC, Pyko1 commented
So basically its nuke op leader swindling all the tc or someone exploiting.

Do we really want to encourage either one?

2017-09-30 18:54 UTC, Arzion5 commented
I've already added an exclusion from nuke ops. The items under the "Collaborative" category will not appear in Nuclear Emergency, and also cannot be discounted unless specified otherwise.

2017-10-01 00:20 UTC, tortellinitony commented
Seems like a pointless addition

2017-10-01 01:10 UTC, DinduStuffin commented
better idea, retool this to work like some of the weapons in Metal Gear Solid: Peace Walker.
The Human Slingshot is an excellent example. Get the traitors to pool their TC together, and buy the slingshot kit. Two people get posts, one gets a rubber thing, and one human becomes the ammo.

Instant kill weapons like the proposed banhammer basically encourage people to go around killing other antags as fast as they can so they can murderbone as much as they can. I'd rather have a band of retards using gimmicky human slingshots to kill each other than people fighting over TC to get a super broken weapon.

I love the idea of collaboration focused items and gimmicks though. That's a damn good idea imo.

2017-10-01 06:39 UTC, Arzion5 commented
Actually, traitors do not know the uplink codes of other players. They will lose the potential amount of TC if they kill their fellow agents. The banhammer is just the toy version, which is why it's listed under the "Badass" category. I wish I knew coding well enough to add a human slingshot though

2017-10-02 13:26 UTC, McBawbaggings commented
@DinduStuffin Banhammer isn't instant kill. It just gives a fake "U HAVE BEEN BANNED FOR NO RAISINS BY USER" it's a toy item.

2017-10-07 22:52 UTC, JamieH commented
[11:51 PM] Jambread: @Arzion ATOMIC PRS
[11:51 PM] Jambread: 1 change per a PR
[11:51 PM] Banthebantz: nukes
[11:51 PM] Jambread: don't edit the health of a rando mob and edit the uplink? wat
NEW MESSAGES
[11:51 PM] Banthebantz: makes it more awkward for admins to come to a decision yes

2017-10-08 03:32 UTC, GuyonBroadway commented
Keep your pr changes limited to one subject at a time. Put the watcher hp nerf in a different pr please m

2017-10-08 05:28 UTC, tortellinitony commented
I might be the only one, but I'm not a big fan of adding all of this pointless gimmicky trash to the traitor uplink

2017-10-08 09:32 UTC, KayeArray submitted a review, later dismissed
provided it's been tested, the code looks fine

2017-10-10 09:38 UTC, McBawbaggings commented
fixed merge conflicts

2017-10-10 21:18 UTC, ghost requested changes

2017-10-10 21:18 UTC, MoreRobustThanYou commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/traitor)
```category = "Collaborative Gear"```

2017-10-10 22:53 UTC, McBawbaggings commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/traitor)
He's overriding it to disable that version of the uplink item.

He redefines a colab based version below this.

2017-10-10 23:00 UTC, MoreRobustThanYou commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/traitor)
oh

2017-10-16 15:05 UTC, Arzion5 commented
It's been too long and I have plans on adding HUD buttons to Sleeping Carp. Closing, moving collaborative gear to new PR

2017-10-16 15:05 UTC, closed without merging