Alt clicking on doors sends the AI a request link to open it
HippieStation/HippieStationdeprecated2020 pull request #3898
Opened 2017-10-10 09:32 UTC by MoreRobustThanYou

🆑 Kor/Thefastfoodguy
rscadd: Alt+clicking on an airlock will now send a request to the AI to open it. The door must be on camera for this to work.
/🆑

Alt+click on a door will send the AI a notice with the doors name, and the name (not real name, so disguises will work here) of the person requesting the door. Clicking the link will open the door.

There is a 10 second cooldown on each door to stop request spam.

The door must be near cameras, or the AI can not open it.

Reasoning: Opening doors is annoying busy work, it tends to generate a bunch of complaints when an AI is swamped (its not listening to me!), etc, and it'd be nice if you could let the clown into EVA and the scientist into tech storage without taking your eyes away from the murder.

2017-10-10 09:46 UTC, ghost commented
I echo what tee gee said.
It being on alt click is bad.

2017-10-10 12:32 UTC, JamieH commented
I'm ok with AltClick

2017-10-10 14:18 UTC, tortellinitony commented
how do people have some magic super power to telepathically tell the AI to open doors. I like how you have to spam AI OPEN

2017-10-10 14:21 UTC, JohnGinnane commented
neat idea, but what about making adding a "jump to location" thing so AIs can see who wants to go where specifically?

2017-10-10 14:21 UTC, Pyko1 commented
Maybe the door has a magic super power doorbell to AI

2017-10-10 14:35 UTC, KayeArray requested changes

2017-10-10 14:35 UTC, banthebantz commented on hippiestation/code/game/machinery/doors/airlock.dm
> +		to_chat(user, "<span class='info'>Nice try, ghosts.</span>")
no need for this

2017-10-10 14:35 UTC, banthebantz commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	request_cooldown = world.time + 100
magic number

2017-10-10 14:35 UTC, banthebantz commented on hippiestation/code/game/machinery/doors/airlock.dm
> +/obj/machinery/door/airlock/AltClick(mob/living/user)
please make it a right click option or something instead

2017-10-10 23:52 UTC, MoreRobustThanYou commented on hippiestation/code/game/machinery/doors/airlock.dm
> +/obj/machinery/door/airlock/AltClick(mob/living/user)
gross

2017-10-10 23:53 UTC, MoreRobustThanYou commented
@JohnGinnane i made it so it tracks the user if you click on their name

2017-10-11 09:58 UTC, Pyko1 commented
time to rename ai upload to clown office and break bridge camera as a clown?

2017-10-11 12:23 UTC, banthebantz commented on hippiestation/code/game/machinery/doors/airlock.dm
> +/obj/machinery/door/airlock/AltClick(mob/living/user)
alt click is gross

2017-10-15 20:46 UTC, KayeArray approved these changes
Looks fine, merging

2017-10-15 20:46 UTC, merged