Stronger Improvised Firebombs
HippieStation/HippieStationdeprecated2020 pull request #4076
Opened 2017-10-16 01:31 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: optional name here
add: Slightly stronger fire bomb you can craft with 100 fuel instead of 50.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

2017-10-16 01:32 UTC, ghost requested changes
Change the changelog to include your name instead of "Optional Name Here"

2017-10-16 01:35 UTC, ghost submitted a review, later dismissed

2017-10-16 01:35 UTC, McBawbaggings commented on code/game/objects/items/grenades/ghettobomb.dm
> +/obj/item/grenade/iedcasing/upgrade
not moduralised!
take all the changes in ghettobomb.dm
make a new file as so
hippiestation/code/game/objects/items/grenandes/ghettobomb.dm
past all the new code you made here.

there should be no changes in this ghettobomb.dm

2017-10-16 01:59 UTC, ghost requested changes
Changelog will print the change log author as IED grenades when it should be YoYoBatty

2017-10-16 10:54 UTC, GuyonBroadway requested changes

2017-10-16 10:54 UTC, GuyonBroadway commented on hippiestation/code/game/objects/items/grenades/ghettobombupgrade.dm
> +	desc = "A stringer, improvised incendiary device."
Did you not mean to put "Stronger" instead of "Stringer"

2017-10-16 12:31 UTC, zamolxius commented
Yes please

2017-10-16 12:36 UTC, McBawbaggings commented
I don't really like the idea of a bigger explosion since blowing things up is already nasty.
Why not make it like 50 Fuel, 50 ethanol for a bigger fire based explosion? Perhaps a little less boom and more fire. Otherwise this is a straight upgrade to the normal version and it won't ever be crafted again.

2017-10-20 22:11 UTC, tortellinitony commented
Why? We really don't need this...

2017-10-21 00:39 UTC, Swagile commented
what mcbawg said

2017-10-23 20:21 UTC, praisenarsie commented
what the pasta man said

2017-10-24 09:45 UTC, banthebantz commented
-1 from me because it's a boring way to buff greytide imo

2017-10-27 16:30 UTC, dreamcrab commented
i like the idea of making it have more fire and burning for longer, but big explosions for greytide seems gay

PLEASE REVISE

2017-10-27 16:31 UTC, banthebantz commented
I actually have my own idea for a revised reagent fireball system at some point.
Judging  by the negative input I will be closing this.

2017-10-27 16:31 UTC, closed without merging