[DNM] Garrotes
HippieStation/HippieStationdeprecated2020 pull request #4084
Opened 2017-10-16 11:03 UTC by JamieH

:cl: Jambread/Crystalwarrior
add: Adds garrots into the game! They are similar to damp rags in functionalty, but have a different purpose. It''s MUCH faster to choke someone out with a garrot.  There are two ways to craft it:  Using table, put a single rod, 15 cables and have a welding tool in-hand. Drag&Drop the table on yourself and select ''Garrote Handles''. Apply 20 cables on the created garrot handles.  Doing it the old-fashioned way, you need to make a wire rod, apply welder on it and then apply 20 cables on the created garrot handles.
rscadd: 'HOW TO USE GARROTS:
Step 1. Make sure you have grab intent AND are aiming for head.
Step 2. Click on target, switch hands, reinforce grab.
Step 3. Reinforce up to neckgrab if you want choking to start, reinforcing into KILL grab will kill your target much faster!  You can use the garrot in-hand if you already have a grab to garrot or stop garroting.'
/:cl:

2017-10-16 12:03 UTC, Arzion5 commented
What makes garrotes so useless is that they do not work if the person has a mask. Everyone starts with a mask and there is no disadvantage to wearing one

2017-10-16 12:26 UTC, zamolxius commented
make it work with a mask but the added neck protection makes people allowed to speak,  otherwise it gags them. 
Or simply make the only protection facehugger immune headwear.  And maybe make the garotte one-1-3 use since it's low quality Nanotrasen wire fabricated in sweatshops by clowns

2017-10-16 13:02 UTC, GuyonBroadway submitted a review, later dismissed

2017-10-16 13:02 UTC, GuyonBroadway commented on hippiestation/code/modules/crafting/recipies.dm
> +/datum/table_recipe/garrote_handles //Still need to apply some wires to finish it
it's `crafting_recipe` not `table_recipe`

2017-10-16 16:51 UTC, PopNotes commented
inconsistent spelling, blease fix

2017-10-16 16:53 UTC, PopNotes commented on hippiestation.dme
> +#include "hippiestation\code\game\objects\items\garrot.dm"
garrote

2017-10-16 16:53 UTC, PopNotes commented on hippiestation/code/game/objects/items/garrot.dm
> +	icon_state = "garrothandles"
garrote

2017-10-16 16:53 UTC, PopNotes commented on hippiestation/code/game/objects/items/garrot.dm
> +	icon_state = "garrot"
garrote

2017-10-16 16:54 UTC, PopNotes commented on hippiestation/code/game/objects/items/garrot.dm
> +	var/next_garrot = 0
garrote

2017-10-16 16:54 UTC, PopNotes commented on hippiestation/code/game/objects/items/garrot.dm
> +	icon_state = "garrot[garroting ? "_w" : ""][item_color ? "_[item_color]" : ""]"
garrote

2017-10-16 16:54 UTC, PopNotes commented on hippiestation/code/game/objects/items/garrot.dm
> +	if(world.time <= next_garrot) return
guess what

2017-10-16 16:57 UTC, PopNotes commented
(edited description for great engrish)

2017-10-16 17:05 UTC, KayeArray requested changes
To be frank: this code is awful and you'd be better off rewriting it up to modern standards

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +/obj/item/garrotehandles/attackby(obj/item/I, mob/user, params)
honestly it'd be better if you just removed the 'attach to handles' system and added the cables to the crafting recipe

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +/obj/item/garrote/New()
Initialize

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +	SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +		SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +		garroting = 0
FALSE

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +	var/garroting = 0
FALSE

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +			user << "<span class='warning'>You need 20 cables to make a garrote!</span>"
to_chat

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +			user << "<span class='notice'>You attach the cable to the handles and pull on them tightly, creating a garrote.</span>"
to_chat

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +	if(world.time <= next_garrot) return
eww single line if

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +	//to_chat(user, "ayylmao")
remove these fucking comments

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +		SSobj.processing.Add(src)
START_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +/obj/item/garrote/afterattack(atom/A, mob/living/user as mob, proximity, click_parameters)
no need for 'as mob'

2017-10-16 17:05 UTC, KayeArray commented on hippiestation/code/game/objects/items/garrot.dm
> +			//to_chat(user, "ayylmao3")
REMOVE THIS FUCKING BULLSHIT

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			if(user.zone_selected != "mouth" && user.zone_selected != "eyes" && user.zone_selected != "head")
surely OR instead of AND

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				//Autograb. The trick is to switch to grab intent and reinforce it for quick chokehold.
make these comments not BREAK UP THE FUCKIGN CODE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				garroting = 1
TRUE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				SSobj.processing.Add(src)
START_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				user.visible_message(
fuck this multi line shit

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +					return 0
FALSE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +						visible_message("<span class='danger'>[user] has tightend the garrote around [src]!</span>", \
tightened

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +/obj/item/garrote/process()
this is fucking horrible and stupid and it can be done better

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			//to_chat(C, "not holding")
FUCK
OFF
WITH
THESE
RANDOM
BULLSHIT
COMMENTS

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			garroting = 0
FALSE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			garroting = 0
FALSE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +			SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				garroting = 0
FALSE

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +				SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +		if(C.grab_state >= GRAB_NECK) //Only do oxyloss if in neck grab to prevent passive grab choking or something.
space this shit out a bit

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +		SSobj.processing.Remove(src)
STOP_PROCESSING(SSobj, src)

2017-10-16 17:05 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrot.dm
> +		garroting = 0
FALSE

2017-10-16 17:22 UTC, KayeArray reviewed
Well it's somewhat better, I hope you tested it. Now clean up the crafting code

2017-10-16 17:22 UTC, banthebantz commented on hippiestation/code/game/objects/items/garrote.dm
> +	playsound(C.loc, 'hippiestation/sound/weapons/grapple.ogg', 40, 1, -4)
and is C defined and typechecked?

2017-10-16 21:18 UTC, JamieH commented
build this

2017-10-17 14:08 UTC, KayeArray approved these changes
Eugh well if it's tested then I guess it's alright

2017-10-17 14:11 UTC, merged

2017-10-17 14:16 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/garrote.dm
> +		if (R.use(20))
The handles require 20 coil here, but below it's only 15 in the recipe. Could this also be seen as magic number?

2017-10-17 14:16 UTC, JohnGinnane commented on hippiestation/code/modules/crafting/recipies.dm
> +	reqs = list(/obj/item/stack/cable_coil = 15,
See above comment, this doesn't match if you assemble using coils onto handles

2017-10-17 14:16 UTC, JohnGinnane commented on hippiestation/code/modules/crafting/recipies.dm
> +	tools = list(/obj/item/weldingtool)
Not a show stopper but you need a welding tool to make a garrote?