Stop shitlording with spesslube plz
HippieStation/HippieStationdeprecated2020 pull request #4356
Opened 2017-10-28 05:12 UTC by Shdorsh

A little surprise to everyone who tries to get cancerous.

[Changelogs]: # Changes how the smonk machine vapes dankly with spess lube. One way to stop from having all the halls  lubed. You could also change the pull request to only apply after a certain amount has been chosen for the smoke machine if you want to nerf that, but honestly, I feel it is an okay punishment

:cl: Anti-shitlord smoke machine
balance: Made mass lubing via smoke machine impossible.
/:cl:

[why]: # (looks at newfags trying le chem memes for the first time) Does this really need any explanation?

2017-10-28 05:15 UTC, Spacedong commented
this doesn't look good and the comment looks obnoxious, I'm not too smart when it comes to code standards, or coding in general though

2017-10-28 09:35 UTC, ghost requested changes
Not modular

2017-10-28 10:08 UTC, banthebantz commented
no -1

2017-10-28 13:42 UTC, praisenarsie commented
or just remove smoke machine because smonk machine is just a very stupid qol improvement to smoke grenades

2017-10-28 18:24 UTC, Spacedong commented
https://github.com/HippieStation/HippieStation/pull/4367

2017-10-30 01:24 UTC, MoreRobustThanYou commented
fixed by #4268

2017-10-30 01:24 UTC, closed without merging