Gives mindshield implants to hotel security staff
HippieStation/HippieStationdeprecated2020 pull request #4359
Opened 2017-10-28 07:58 UTC by xTrainx

[Changelogs]: # mindshields security staff
tweak: hotel security staff are now mindshielded
/:cl:

[why]: # this would allow them to use the energy shotgun, also, for some reason, normal hotel staff are alredy mindshielded

2017-10-28 09:39 UTC, ghost requested changes
Needs to be made modular

2017-10-28 13:13 UTC, xTrainx commented
done

2017-10-28 13:41 UTC, ghost approved these changes
Code OK. Needs @HippieStation/head approval now

2017-10-29 12:31 UTC, banthebantz commented
+1

2017-10-29 14:38 UTC, McBawbaggings commented
okay

2017-10-29 21:41 UTC, dreamcrab commented
idk what this does but whatever it seems good +790

2017-10-29 23:02 UTC, merged