Carbon's Power Laser (WIP)
HippieStation/HippieStationdeprecated2020 pull request #4365
Opened 2017-10-28 17:29 UTC by banthebantz

Unfinished, we need his sprites and needs a full review.

2017-10-28 17:30 UTC, ghost requested changes

2017-10-28 17:30 UTC, MoreRobustThanYou commented on hippiestation/code/modules/power/power_laser.dm
> +	..()
. = ..()

2017-10-28 17:47 UTC, Chnkr commented on hippiestation/code/modules/power/power_laser.dm
> +#define LOW_ENERGY 10000
Put the beam in it's own file

2017-10-29 16:13 UTC, Cyberboss commented
PR this upstream!!

2017-10-29 21:25 UTC, GuyonBroadway requested changes
this is what jenkins is crying about.

2017-10-29 21:25 UTC, GuyonBroadway commented on hippiestation/code/modules/power/power_laser.dm
> +	stat = POWEROFF // starts offline
this needs to be defined.... as to where carbon defined it last time I dunno.

2017-10-29 21:25 UTC, GuyonBroadway commented on hippiestation/code/modules/power/power_laser.dm
> +	icon = 'hippiestation/goon/icons/pt_laser.dmi' // huge thanks to goon for the sprite!
This does not exist.

2017-10-29 21:25 UTC, GuyonBroadway commented on hippiestation/code/modules/power/power_laser.dm
> +	icon = 'hippiestation/goon/icons/ptlbeam.dmi'
this also does not exist.

2017-10-29 23:04 UTC, MoreRobustThanYou commented on hippiestation/code/modules/power/power_laser.dm
> +	icon = 'hippiestation/goon/icons/pt_laser.dmi' // huge thanks to goon for the sprite!
You forgot to read

```Unfinished, we need his sprites and needs a full review.```

2017-11-03 10:13 UTC, Carbonhell commented on hippiestation/code/modules/power/power_laser.dm
> +	stat = POWEROFF // starts offline
it's a tg define if i remember correctly, machinery to be exact

2017-11-11 12:26 UTC, Chnkr commented
Stale PR, reopen whenever you feel like this is ready for review

2017-11-11 12:26 UTC, closed without merging