Tones down le solid chems
HippieStation/HippieStationdeprecated2020 pull request #4436
Opened 2017-10-30 23:00 UTC by banthebantz

:cl: banthebantz
balance: Solid chem and chempile grenade duping toned down significantly, vapour duping slightly buffed
refactor: Vapour runtime caused by reagent ref being GC'd fixed. General refactor to state change multipliers.
/:cl:

Please take note of the now commented out and mirrored reagent splash proc. It was snowflakey bullshit so I had to change it significantly for this to work.

2017-10-30 23:55 UTC, PopNotes commented
it was a good run

thanks for still keeping it to some degree tho

2017-10-31 00:04 UTC, GuyonBroadway commented
THis does mean you need to invest some time for a return which I like.

2017-10-31 08:17 UTC, Chnkr commented on code/modules/reagents/chem_splash.dm
>  /proc/chem_splash(turf/epicenter, affected_range = 3, list/datum/reagents/reactants = list(), extra_heat = 0, threatscale = 1, adminlog = 1)
Suggestion: Can we, going forward annotate all hippie changes in /tg/ code with something like this?

```
// HIPPIESTART: Mirrored this function in <file> for <reason>
bunch of shitcode here
// HIPPIESTOP
```

@HippieStation/coders @HippieStation/maintainers what do you guys think?

2017-10-31 08:22 UTC, Chnkr commented on hippiestation/code/modules/reagents/chem_splash.dm
> +/proc/chem_splash(turf/epicenter, affected_range = 3, list/datum/reagents/reactants = list(), extra_heat = 0, threatscale = 1, adminlog = 1)
See my previous comment, any chance you can document the changes done in this function?

2017-10-31 08:23 UTC, ghost submitted a review, later dismissed
Code looks OK, if you can please address the above comments so that we can actually maintain this.

2017-10-31 13:07 UTC, banthebantz commented
Good idea

2017-10-31 13:15 UTC, Chnkr commented on hippiestation/code/modules/reagents/chem_splash.dm
> +/proc/chem_splash(turf/epicenter, affected_range = 3, list/datum/reagents/reactants = list(), extra_heat = 0, threatscale = 1, adminlog = 1)
@banthebantz

2017-10-31 14:19 UTC, ghost submitted a review, later dismissed
Code OK

2017-10-31 22:51 UTC, ghost requested changes

2017-10-31 22:51 UTC, Chnkr commented on code/modules/reagents/chem_splash.dm
> +// HIPPIESTART: Mirrored this function in <hippiestation\code\modules\reagents\chem_splash.dm> for <reducing the duplication of solid and turchchems by refactoring chem splash code to use a particle_
You've made changes to /tg/ files, please mark these changes.

**All modifications to non-hippie files should be marked.**

- Multi line changes start with `// hippie start` and end with `// hippie end`
- You can put a messages with a change if it isn't obvious, like this: `// hippie start - reason`
  - Should generally be about the reason the change was made, what it was before, or what the change is
  - Multi-line messages should start with `// hippie start` and use `/* Multi line message here */` for the message itself
- Single line changes should have `// hippie` or `// hippie - reason`

If you need to mirror a file, or function into a hippie-specific file, please leave behind a comment stating where it went.

```
// hippie start - Mirrored this function in <file> for <reason>
bunch of shitcode here
// hippie stop
```

Once you mirror a file, please follow the above for marking your changes, this way we know what needs to be updated when a file has been mirrored.

2017-11-02 13:23 UTC, dreamcrab commented
cool +7685

2017-11-06 10:13 UTC, MoreRobustThanYou commented on code/modules/reagents/chem_splash.dm
>  /proc/chem_splash(turf/epicenter, affected_range = 3, list/datum/reagents/reactants = list(), extra_heat = 0, threatscale = 1, adminlog = 1)
i think DON'T PING ME

2017-11-06 11:42 UTC, ghost approved these changes
Code OK

2017-11-06 19:40 UTC, McBawbaggings commented
ok

2017-11-07 02:53 UTC, Dudeinyourbackyard commented
GO FUCKO DO IT +1

2017-11-07 10:04 UTC, GuyonBroadway commented
Thats a good review, a +3 and nearly a weeks worth of waiting. Merger a gogo

2017-11-07 10:04 UTC, merged