Lean's effects now take a minute or two to start
HippieStation/HippieStationdeprecated2020 pull request #4586
Opened 2017-11-04 18:53 UTC by MoreRobustThanYou

:cl: Thefastfoodguy
fix: Lean's effects now take a minute or two to start
/:cl:

1 current_cycle = APPROX 2 seconds

2017-11-04 18:54 UTC, Arzion5 commented
Omae wa mou shindeiru

2017-11-04 18:55 UTC, KayeArray requested changes

2017-11-04 18:55 UTC, banthebantz commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		if(prob(3) && current_cycle >= 65) //easily a minute or two to get the lean out
This will take a very long time to take effect.

2017-11-04 18:55 UTC, banthebantz commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
>  		H.adjust_drugginess(5)
You still need to cap this

2017-11-04 18:57 UTC, MoreRobustThanYou commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		if(prob(3) && current_cycle >= 65) //easily a minute or two to get the lean out
Approx 2 minutes

2017-11-04 18:57 UTC, MoreRobustThanYou commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
>  		H.adjust_drugginess(5)
To what?

2017-11-04 18:58 UTC, banthebantz commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
>  		H.adjust_drugginess(5)
I don't know, just make sure it doesn't leave you druggy for the entire fucking round.

2017-11-04 18:59 UTC, banthebantz commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		if(prob(3) && current_cycle >= 65) //easily a minute or two to get the lean out
No because it's only a 3% chance, it's actually a lot longer.

2017-11-04 19:00 UTC, MoreRobustThanYou commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +		if(prob(3) && current_cycle >= 65) //easily a minute or two to get the lean out
I'll change it to 25

2017-11-06 11:40 UTC, Chnkr commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
>  		H.adjust_drugginess(5)
Agreed, cap it

2017-11-09 21:14 UTC, closed without merging