Reagent materials [WIP]
HippieStation/HippieStationdeprecated2020 pull request #4622
Opened 2017-11-05 23:02 UTC by banthebantz

:cl: banthebantz
/:cl:

Needs polishing, mapping, sprites and balancing
Adds reagent ingots, a forge and sheet processor to obtain and forge them into custom weapons and ammo.

2017-11-05 23:10 UTC, PopNotes commented
oh fuck

OH FUCK

FILL THE ARMORY WITH MACES

2017-11-05 23:15 UTC, PopNotes commented on hippiestation/code/game/machinery/reagent_forge.dm
> +	var/recipe//currently 6 types of weapon can be forged
hmmm

2017-11-05 23:15 UTC, PopNotes commented on hippiestation/code/game/machinery/reagent_forge.dm
> +	var/datum/reagent/currently_forging//forge one mat at a time
hhhhmmmm

2017-11-06 10:50 UTC, MoreRobustThanYou commented
SYNTHFLESH SHOVELS!

2017-11-06 10:51 UTC, MoreRobustThanYou commented
CYANIDE SWORDS!

2017-11-06 11:37 UTC, ghost requested changes
Needs some work, cool feature

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +	if(user.a_intent == INTENT_HARM)
I'd check for the intent first, before calling `check_cost()`

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/Topic(href, href_list)
I'd prefer if we'd use TGUI for this UI

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/interact(mob/user)
I'd prefer if we'd use TGUI for this UI

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_sheet.dm
> +/obj/machinery/reagent_sheet/proc/Create_Sheets(amount, R)
Please use `snake_case` for procs

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/objects/items/forged_weapons.dm
> +/obj/item/forged/proc/Assign_Properties()
Please use `snake_case` for procs

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/objects/items/forged_weapons.dm
> +/obj/item/twohanded/forged/proc/Assign_Properties()
Please use `snake_case` for procs

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/objects/items/stacks/sheets/sheet_types.dm
> +/obj/item/stack/sheet/mineral/reagent/merge(obj/item/stack/S) //Merge src into S, as much as possible
This needs some logging for the potential reactions it can make

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/objects/items/forged_weapons.dm
> +/obj/item/projectile/bullet/forged/proc/Assign_Properties(datum/reagent/reagent_type, caliber_multiplier)
Please use `snake_case` for procs

2017-11-06 11:37 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +				else if(D.id == "fgsword" || D.id == "fwhammer")
These checks are pretty snowflake, can't we handle this more dynamically? This way we'd have to update this proc when we create a new item that can be forged, would be nice to keep it simple.

2017-11-06 15:22 UTC, PopNotes commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/Topic(href, href_list)
TGUI is fucking awful and we should avoid it whenever possible

2017-11-06 15:59 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/Topic(href, href_list)
There is no reason to not use TGUI

* centralised topic checks for distance and visibility
* easy to manage streaming data updates

Your statement is invalid, TGUI works, and does what it needs to do.

2017-11-06 16:07 UTC, banthebantz commented on hippiestation/code/game/objects/items/stacks/sheets/sheet_types.dm
> +/obj/item/stack/sheet/mineral/reagent/merge(obj/item/stack/S) //Merge src into S, as much as possible
Not sure what you mean. These is just an overidden version of the normal stack merge proc to prevent different types of stacks from merging. Reagent materials are completely inert.

2017-11-06 16:25 UTC, Chnkr commented on hippiestation/code/game/objects/items/stacks/sheets/sheet_types.dm
> +/obj/item/stack/sheet/mineral/reagent/merge(obj/item/stack/S) //Merge src into S, as much as possible
I thought it mixed reagents, my bad

2017-11-06 19:28 UTC, closed without merging

2017-11-06 20:34 UTC, MoreRobustThanYou commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/Topic(href, href_list)
The syntax is horseshit, and doesn't it cause people to crash