Reagent materials [WIP]
HippieStation/HippieStationdeprecated2020 pull request #4629
Opened 2017-11-06 19:30 UTC by banthebantz

:cl: banthebantz
/:cl:

Needs polishing, mapping, sprites and balancing.

Remade because fuck git.

2017-11-06 20:15 UTC, ghost requested changes

2017-11-06 20:15 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/interact(mob/user)
I'd prefer if this would've been using TGUI instead of the terrifying old UI system that has a shitload of issues

2017-11-06 20:23 UTC, praisenarsie commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/interact(mob/user)
tgui is equally as shit

2017-11-06 20:33 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge/interact(mob/user)
@praisenarsie TGUI is fine, if you have any issues with TGUI report them upstream

2017-11-07 10:42 UTC, ghost requested changes
beep boop

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +	var/list/show_categories = list("Weaponry")
Please do not initialize lists directly on the object, or in `/new` put them in `Initialize()` doing so adds a hidden init proc that slows down `world/New()`

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +		if(!in_range(src, R) || !user.Adjacent(src))
Shouldn't the range check come before the panel check?

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +	var/menustat = "menu"
Please change this into bitflags instead of string fuckery

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +		var/datum/design/D = locate(href_list["create"])
This `locate` call should be a `locate in <list>` **_or_** you should verify if the `design` is a valid `design` before even passing is to the `create_product` proc, because in there you only accept `/datum/design/forge`

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/machinery/reagent_forge.dm
> +		if(isliving(usr))
You should move this check to the top of `Topic` only living people should be allowed to use the machine anyway

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/objects/items/forged_weapons.dm
> +	var/stabby = 0 //affects reagent transfer 1 is sharp, 1.5 is extremely sharp, anything below 1 is partially or completely blunt
Please turn this into a `DEFINE` instead of a comment somewhere hidden

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/game/objects/items/forged_weapons.dm
> +		radiation_pulse(src, 300)
a rad pulse on every `Move()` seems overkill

2017-11-07 10:42 UTC, ghost commented on hippiestation/code/modules/research/research.dm
> +		if((D.build_type & REAGENT_FORGE) && ("initial" in D.category))  //ATMOSLATHE starts without hacked designs
`//ATMOSLATHE` ?

2017-11-07 21:27 UTC, ghost submitted a review, later dismissed
Looks good 👍

2017-11-08 00:14 UTC, Blute1 commented
this adds a fucking forge, why isnt that in the PR name

2017-11-08 00:32 UTC, Dudeinyourbackyard commented
Local Man Sneaks In An Entire Forge

2017-11-08 14:11 UTC, GuyonBroadway commented
> Local Man Sneaks In An Entire Forge

Just the idea of sec turning out some greytards pockets.

"Excuse me sir why do you have an entire matter forge on your person?"

_"FUCK YOU SHITCUTIRTY!!"_

2017-11-08 18:06 UTC, dreamcrab commented
yea wtf does this do

2017-11-08 18:06 UTC, praisenarsie commented
yea wtf does this do

2017-11-08 18:06 UTC, banthebantz commented
It's not finished so I'm not doing a changelog yet, ignore it.

2017-11-09 01:35 UTC, Blute1 commented
wtf

2017-11-09 13:02 UTC, GuyonBroadway commented
Be sure to include material toolboxes too.  Look me in the eye and say you don't want to pimp someone over the head with a solid gold/diamond toolbox.

2017-11-09 14:33 UTC, Chnkr commented
glass toolboxes

2017-11-11 15:11 UTC, tortellinitony commented
Do walls work?

2017-11-11 15:13 UTC, banthebantz commented
That's on my list of things to add don't worry

2017-11-12 11:21 UTC, ghost requested changes

2017-11-12 11:21 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +/obj/machinery/reagent_forge
There is a bunch of excessive whitespace in this file

2017-11-12 11:21 UTC, Chnkr commented on hippiestation/code/game/machinery/reagent_forge.dm
> +				if(R.amount <= 0)//this shouldn't exist
I'd suggest giving the user some feedback if this happens e.g. `the sheet crumbles apart into a useless mass of nothingness, maybe the sheet was a fake one?` this can happen quite a lot if people forcefully eject sheets from the mining thing

2017-11-13 19:48 UTC, PopNotes commented
still hype for this

2017-11-13 21:52 UTC, bardofrage commented
Really cool concept, all for it. Forge sprite might be a little over the top to be on the station.

2017-11-13 22:03 UTC, dreamcrab commented
i like it +420

2017-11-18 19:49 UTC, ghost commented
Build triggered. sha1 is original commit.

2017-11-19 20:07 UTC, zamolxius commented
this is the  masterwork teslium *toolbox* clown bashing of Zeus' Wrath

2017-11-20 16:59 UTC, Arzion5 commented
Neat. +1

2017-11-23 16:06 UTC, 2Dollarbill commented
+1, this all seems excellent and definitely something unique. Seems like you spent quite some time on it, so let's fair to see how it goes.

2017-11-24 09:37 UTC, Chnkr commented
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

2017-12-09 11:55 UTC, banthebantz commented
weird how a pr can be open for a branch that no longer exists

2017-12-09 11:56 UTC, closed without merging