Reduces Tourette Stun Time
HippieStation/HippieStationdeprecated2020 pull request #4714
Opened 2017-11-11 09:19 UTC by Arzion5

:cl:
tweak: Tourette's stun time has been reduced from 20 seconds to 5 seconds.
/:cl:

Tourette is extremely annoying and has a relatively high chance of appearing in just 30 seconds, because each roll is made per tick. This means you can repeatedly get stunlocked for more than 2 minutes if you're unlucky, completely helpless as you automatically swear on the radio.

2017-11-11 09:23 UTC, Dudeinyourbackyard commented
lets make a compromise with the current time and make it 10 seconds to make it require some sort of external help instead of powering through it unlike autism

2017-11-11 09:26 UTC, Arzion5 commented
Sure

2017-11-11 09:27 UTC, Dudeinyourbackyard commented
sweet you got my +1

2017-11-11 10:20 UTC, JohnGinnane requested changes

2017-11-11 10:20 UTC, JohnGinnane commented on hippiestation/code/datums/mutations.dm
> +/datum/mutation/human/tourettes/on_life(mob/living/carbon/human/owner)
This only stuns and doesn't do any of the following: https://github.com/HippieStation/HippieStation/blob/229f7c8efab323a4b69e58233e16d75aa75cce2d/code/datums/mutations.dm#L322

2017-11-11 12:42 UTC, JohnGinnane approved these changes
Code is fine, but I still think 10 seconds is fucking extreme

2017-11-11 12:48 UTC, JohnGinnane commented
Oh, I think you should include your name after the first :cl: so it appears in the change log

2017-11-11 12:54 UTC, Arzion5 commented
The name of the coder automatically appears in a changelog

2017-11-11 12:55 UTC, JohnGinnane commented
Oh cool, wasn't sure

2017-11-11 15:41 UTC, dreamcrab commented
was it always like this? this seems like a wild stun at 20 seconds jfc

+31412

2017-11-11 18:25 UTC, PopNotes commented
I think it'd be better if the stun time was only five seconds to make epilepsy even scarier by comparison.

2017-11-12 17:54 UTC, banthebantz commented
yeah it's pretty gay +1

2017-11-12 17:54 UTC, merged