Adds Man Of Steel genetic mutation
HippieStation/HippieStationdeprecated2020 pull request #4716
Opened 2017-11-11 10:18 UTC by Arzion5

:cl:
add: Added Man Of Steel, a genetic superpower that reduces damage done to you by a little bit. Good enough to yawn punches off but not good enough to protect against armor-piercing attacks or much stronger weapons effectively.
/:cl:

Genetics variety, this is the first defense-oriented genetic power. Added mostly for fun value.

2017-11-11 15:25 UTC, ghost requested changes
You WILL need to change a /tg/ file for this --- change DNA_STRUC_ENZYMES_BLOCKS to 20 in __DEFINES/DNA.dm

2017-11-11 21:08 UTC, tortellinitony commented
no you can just redefine it

2017-11-14 18:47 UTC, Arzion5 commented
Maybe later. I will do it in a respectable time-frame

2017-11-15 19:12 UTC, banthebantz commented
+1

2017-11-15 22:47 UTC, Dudeinyourbackyard commented
sounds cool
+1

2017-11-16 09:15 UTC, McBawbaggings commented on hippiestation/code/datums/mutations.dm
> +	S.armor = 0 //You're no longer resistant to punches. Do not combine with DNA Vault.
S.armor = initial(S.armor)

2017-11-16 09:15 UTC, McBawbaggings commented on hippiestation/code/datums/mutations.dm
> +	S.armor = 5 // You're resistant to punches.
S.armor = initial(S.armor + 5)

2017-11-16 15:51 UTC, banthebantz commented on hippiestation/code/datums/mutations.dm
> +	S.armor = 5 // You're resistant to punches.
No, do S.armor += 5

2017-11-18 13:48 UTC, zamolxius commented
rename to Subdermal Matrix/Keratin Skin/Light Carapace/Severe Psoriasis/Tough Epidermis/Bone Plates etc.  Man of steel sounds like shit tbh if it's not actually steel.

2017-11-19 11:55 UTC, banthebantz commented on hippiestation/code/datums/mutations.dm
> +	S.armor = initial(S.armor) //You're no longer resistant to punches. Do not combine with DNA Vault.
S.armor -= 5

Now it won't remove DNA vault armour

2017-11-20 17:30 UTC, WallaceShark commented
Cool concept! +1

2017-11-23 16:02 UTC, 2Dollarbill commented
Interesting concept, honestly more balanced than a hulk mutation but that's the fun of hulk.
+1

2017-11-24 09:38 UTC, Chnkr commented
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

2017-11-24 09:38 UTC, closed without merging