Adds wizard healing spell for 1 spell point
HippieStation/HippieStationdeprecated2020 pull request #4805
Opened 2017-11-14 18:57 UTC by Arzion5

:cl:
add: Added "Lesser Heal" to the wizard spellbook. It heals you for 10 brute and burn damage and has a 10-second cooldown, which can go as low as 5 seconds. Be aware that it does not work for non-humans!
/:cl:

Fun, gimmicky item. A cheaper heal wand + recharge combo.

2017-11-14 18:58 UTC, JohnGinnane commented
Did you test this?

2017-11-14 19:00 UTC, JohnGinnane requested changes

2017-11-14 19:00 UTC, JohnGinnane commented on hippiestation/code/game/gamemodes/wizard/spellbook.dm
> +	name "Lesser Heal"
Missing an "=" homey

2017-11-14 19:01 UTC, Arzion5 commented
Absolutely not. Re-trying

2017-11-15 14:03 UTC, banthebantz commented
It's too weak

2017-11-15 14:26 UTC, Arzion5 commented
You're weak >:^)

2017-11-15 14:27 UTC, banthebantz commented
Don't kill me, please!

2017-11-15 23:28 UTC, Dudeinyourbackyard commented
ehh why not
if its too powerful or too weak it can be tweaked later
+1

2017-11-16 12:47 UTC, McBawbaggings commented
Make it stronger but it applies an AoE effect.
Having yet another fleshmend tier ability isn't fun, having something that will save you inbetween fights is fine though.

2017-11-16 12:48 UTC, Arzion5 commented
I have absolutely no idea how to make it AoE

2017-11-16 13:09 UTC, JohnGinnane commented
@McBawbaggings I think making it AoE defeats the purpose. I imagine the whole point of the lesser heal is a single target tiny heal with low CD, nothing fancy, nothing too powerful, just a basic little spell that can't really go wrong

2017-11-19 20:03 UTC, zamolxius commented
Nice

2017-11-23 15:58 UTC, 2Dollarbill commented
A little too hesitant on having this pass, Wizards have good mobility, adding healing to the mix might break him.

2017-11-24 09:39 UTC, Chnkr commented
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

2017-11-24 09:39 UTC, closed without merging