Adds gloves of the north star.
HippieStation/HippieStationdeprecated2020 pull request #4808
Opened 2017-11-14 19:09 UTC by GuyonBroadway

:cl: GuyonBroadway
add: Added a nice pair of gloves to the traitor uplink that let you punch people very fast. costs 10tc. 
/:cl:

[why]: Erik wanted me to...
![image](https://user-images.githubusercontent.com/22083966/32799000-42f204f0-c96e-11e7-808d-b0c3951ee894.png)

Also these gloves use the touch() proc which is only called on an unarmed attack by their wearer, due to it working off the unarmedattack() proc it is incompatible with hulk because hulk calls hulk_attack and will not work with ANY weapons. 

It IS compatible with the bonus damage from sleeping carp but that shits 17tc and if you manage to win the uplink discount lottery then go nuts kiddo.

2017-11-14 19:11 UTC, bardofrage commented
+1

2017-11-14 19:12 UTC, KayeArray requested changes

2017-11-14 19:12 UTC, banthebantz commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +/obj/item/clothing/gloves/color/white/rapid/Touch(mob/living/target,proximity = 1)
proximity = TRUE

2017-11-14 19:12 UTC, banthebantz commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	var/mob/living/M = loc
why is a loc being assigned to a mob?

2017-11-14 19:12 UTC, banthebantz commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	else
this is pointless, just stick .=FALSE at the end

2017-11-14 19:12 UTC, banthebantz commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 10
Probably not worth 10TC, aside from knockdown chance this is basically just a weaker esword with no block chance.

2017-11-14 19:13 UTC, banthebantz commented
+1

2017-11-14 19:16 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	else
TRUE... geddit... true?

2017-11-14 19:17 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	var/mob/living/M = loc
its the funny way tocuh works, there might be a better way to to it but this is tested and works.

2017-11-14 19:18 UTC, banthebantz commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	var/mob/living/M = loc
and this doesn't runtime when you touch something else?

2017-11-14 19:26 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	var/mob/living/M = loc
Nope no runtimes, also it works because the gloves location is the mob they are being worn on. That's how clothing works when worn.

2017-11-14 19:32 UTC, GuyonBroadway commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 10
I'd rather highball it for a day or two and then buff it.

2017-11-14 19:57 UTC, dreamcrab commented
+7 star dipper formation

2017-11-14 20:08 UTC, PopNotes commented
I'd suggest lowering the price to 8TC for extra combo potential.

2017-11-14 20:10 UTC, PopNotes commented
Also, Kenshiro used a single fingerless biker glove, going off what little weeb knowledge I have. Make it a child of roboticist's fingerless gloves for accuracy.

2017-11-14 20:11 UTC, dreamcrab commented
he just had leather bracers or wrapped his wrists, i dont recall any gloves and im a huge hnk nerd

2017-11-14 20:17 UTC, PopNotes commented
I think his appearance changed at some point, there's depictions of him with a biker glove and depictions of a manchette, always with the bandage wrap around the other arm tho

2017-11-14 22:26 UTC, GuyonBroadway commented
side note imagine how amazing these will be once this gets added too https://github.com/HippieStation/HippieStation/pull/4776

2017-11-14 22:27 UTC, ghost commented on hippiestation/code/modules/clothing/gloves/rapidgloves.dm
> +	name = "Gloves of the north star"
Gloves of the North Star.

2017-11-14 23:28 UTC, Dudeinyourbackyard commented
omae wa mou dooteiru
+1

2017-11-15 01:23 UTC, GuyonBroadway commented
This has a +3, needs 18 more hours and bantz to sign everything off.

2017-11-15 14:01 UTC, KayeArray approved these changes

2017-11-15 19:13 UTC, merged