You can no longer drop the clown shoes once you put them on your feet.
HippieStation/HippieStationdeprecated2020 pull request #4914
Opened 2017-11-19 11:35 UTC by Arzion5

:cl:
tweak: The clown shoes can no longer be taken off your feet.
/:cl:

Once a clown, always a clown. I dislike seeing clowns taking a metaphorical dump on the nature of clowns by taking off their shoes and taking mutadone, as the "strategy" is as of more recently. When you pick a clown, you willingly acknowledge the clown's upsides and downsides. People shouldn't pick clown only for the free slips.

2017-11-19 11:40 UTC, zamolxius commented
yes

2017-11-19 11:42 UTC, banthebantz commented
no

2017-11-19 12:45 UTC, McBawbaggings commented
also sinful but not as sinful

2017-11-19 16:52 UTC, MoreRobustThanYou commented
basically clowns are cursed from roundstart.

-1

2017-11-19 16:53 UTC, fluxcapacitor1337 commented
YES

if you're going CLOWN you need to COMMIT

+100000000

2017-11-19 16:54 UTC, dreamcrab commented
https://en.wikipedia.org/wiki/Clown_(film)

reminds me of this movie

2017-11-19 16:54 UTC, MoreRobustThanYou commented
new strategy as clown: cutting legs off then getting robotic legs

2017-11-19 17:03 UTC, GuyonBroadway commented
This will mean its impossible to build a HONK as the moment you pick up any clown shoes you cannot drop or use them.

2017-11-19 17:21 UTC, GuyonBroadway requested changes

2017-11-19 17:21 UTC, GuyonBroadway commented on hippiestation/code/game/objects/items/clown_items.dm
>  #undef HORN_BRAIN_DAMAGE
undefs need to go at the very bottom of a file please place your code ABOVE any undefs

2017-11-19 17:34 UTC, GuyonBroadway approved these changes

2017-11-19 17:35 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/shoes/miscellaneous.dm
> +/obj/item/clothing/shoes/clown_shoes/equipped/equipped(mob/user, slot)
Now this means that if you cut a clowns legs off and picked his shoes up they would get stuck to your hand.

Might wanna make it so they get undone on an unequip.

2017-11-19 17:57 UTC, tortellinitony commented
stupid

2017-11-19 18:41 UTC, zamolxius commented
Potential change: give clowns clown slowdown by nature,  or even slower, and clownshoes give them normal clownshoe slowdown. If they wanna go fast they gotta get nuka cola,  or ephedrine.  Traitor clowns are excused.  Oooor....  Traitor clowns get 25 tc to compensate slower movespeed

2017-11-19 18:42 UTC, McBawbaggings commented
forcing a particular playstyle is kinda shit though
even if these "clowns" are only in name related.

if clowns take their shoes off then the IC ire they get is justified, coding against it is bad though

2017-11-19 18:44 UTC, zamolxius commented
how about giving clowns with clownshoes on a special asskick attack.  It only knocks people back   baseball bat style.  Hey,  mime has free forcewall so why not

2017-11-20 05:19 UTC, Arzion5 commented
I didn't actually take into account traitor clowns.

...shit.

2017-11-20 05:19 UTC, closed without merging