Fuck circuits
HippieStation/HippieStationdeprecated2020 pull request #5078
Opened 2017-11-27 01:17 UTC by TDcoolguy300

:cl: TDcoolguy300 AKA Gregg
del: Disabled Integrated Circuits codewise, if this was merged then nobody was on to fix the fucking config.
/:cl:

2017-11-27 01:21 UTC, Sarcalogo commented
Why would you remove circuits?

2017-11-27 01:21 UTC, ghost submitted a review, later dismissed

2017-11-27 01:22 UTC, McBawbaggings commented
merging due to the high CPU load it puts the server under

we can reevaluate adding them once the problem is identified

2017-11-27 01:27 UTC, GuyonBroadway commented
this is also something to send upstream.

2017-11-27 01:29 UTC, ghost requested changes

2017-11-27 01:29 UTC, Chnkr commented on code/modules/integrated_electronics/core/printer.dm
> +	var/enabled = 0
You've made changes to /tg/ files, please mark these changes.

**All modifications to non-hippie files should be marked.**

- Multi line changes start with `// hippie start` and end with `// hippie end`
- You can put a messages with a change if it isn't obvious, like this: `// hippie start - reason`
  - Should generally be about the reason the change was made, what it was before, or what the change is
  - Multi-line messages should start with `// hippie start` and use `/* Multi line message here */` for the message itself
- Single line changes should have `// hippie` or `// hippie - reason`

If you need to mirror a file, or function into a hippie-specific file, please leave behind a comment stating where it went.

```
// hippie start - Mirrored this function in <file> for <reason>
bunch of shitcode here
// hippie stop
```

Once you mirror a file, please follow the above for marking your changes, this way we know what needs to be updated when a file has been mirrored.

2017-11-27 01:29 UTC, Chnkr commented on code/modules/integrated_electronics/core/printer.dm
> +		if(!CONFIG_GET(flag/ic_printing) || !enabled)
You've made changes to /tg/ files, please mark these changes.

**All modifications to non-hippie files should be marked.**

- Multi line changes start with `// hippie start` and end with `// hippie end`
- You can put a messages with a change if it isn't obvious, like this: `// hippie start - reason`
  - Should generally be about the reason the change was made, what it was before, or what the change is
  - Multi-line messages should start with `// hippie start` and use `/* Multi line message here */` for the message itself
- Single line changes should have `// hippie` or `// hippie - reason`

If you need to mirror a file, or function into a hippie-specific file, please leave behind a comment stating where it went.

```
// hippie start - Mirrored this function in <file> for <reason>
bunch of shitcode here
// hippie stop
```

Once you mirror a file, please follow the above for marking your changes, this way we know what needs to be updated when a file has been mirrored.

2017-11-27 10:27 UTC, MoreRobustThanYou commented
Perhaps someone making shittons of circuits is the problem, and said people need to be warmed?

2017-11-28 03:41 UTC, Iamgoofball commented
you're a retard if you think this prevents circuits lmao

2017-11-28 19:18 UTC, zamolxius commented
Do it.  And switch host box to EU faggots

2017-11-29 17:41 UTC, zamolxius commented
MERGE

2017-11-30 08:41 UTC, Chnkr commented
Closing this PR as it literally does nothing

2017-11-30 08:41 UTC, closed without merging