Grudgecodes Nuka Cola into uselessness
HippieStation/HippieStationdeprecated2020 pull request #5127
Opened 2017-12-01 15:27 UTC by Arzion5

:cl: Salty Traitor
del: Nuka Cola no longer makes you go fast
/:cl:

I died from a person who killed me using the speed from nuka cola, please delet everything I don't like

2017-12-01 15:27 UTC, Blute1 commented
lol

2017-12-01 15:28 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	M.status_flags |=
this doesn't even work

merge right now

2017-12-02 11:31 UTC, JohnGinnane commented
Because it isn't abundantly clear what's different, here's the current proc:

![image](https://user-images.githubusercontent.com/3355198/33514986-64e6a23e-d754-11e7-8ca3-705e9deb16a7.png)

2017-12-02 11:43 UTC, JohnGinnane requested changes
Honestly I think you should just remove the line from the original file and put in a comment say `// Hippie - Removed fast because it's OP` or something, rather than copying the entire proc

2017-12-02 11:43 UTC, JohnGinnane commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +. = 1
Missing indentation

2017-12-02 15:22 UTC, JohnGinnane requested changes

2017-12-02 15:22 UTC, JohnGinnane commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	M.status.flags |= NONE
Homey this is even worse, it won't do any of the things it should :(

2017-12-02 15:23 UTC, JohnGinnane commented on hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	M.status.flags |= NONE
I think you should go to here

https://github.com/HippieStation/HippieStation/blob/bb368d910f501154d54129f09d1bf27fd3a7162b/code/modules/reagents/chemistry/reagents/drink_reagents.dm#L389

And replace that line with a commenting saying it was removed or something, and then get ride of the override in the new file altogether

2017-12-03 21:00 UTC, McBawbaggings commented
broken code and stale

2017-12-03 21:00 UTC, closed without merging