Potted Plant Update - Emag Potted Plants, Attach Knives to Potted Plants, Potted Plants Antagonist (protagonist??)
HippieStation/HippieStationdeprecated2020 pull request #5155
Opened 2017-12-02 12:10 UTC by Spankmaster1066

:cl: Spankmaster

add:ability for potted plant to be emagged (RISKY)
add:ability to screwdrive open potted plant to insert sharp items into the plant
add:potted lean mob
/:cl:

2017-12-02 12:20 UTC, KayeArray requested changes

2017-12-02 12:20 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +	if (istype(W, /obj/item/screwdriver)) //If you screwdrive it, it is attachable
please space ifs consistently like this :
if(thing)
instead of
if (thing)

2017-12-02 12:20 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +		src.disable = !src.disable
remove src

2017-12-02 12:20 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +	if (W.is_sharp() && disable == 1)  //If screwdriven and the item is sharp, it creates sharp plant
remove == 1

2017-12-02 12:20 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(emagged)
if(emagged && wielded)

2017-12-02 12:20 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +	var/sharp_desc_add = "This one appears to have a bunch of sharp edges peeking out from under its leaves."
make these two vars defines

2017-12-02 12:49 UTC, JohnGinnane commented on hippiestation/code/game/objects/structures/flora.dm
> +#define EMAG_DESC_ADD = "This plant appears to have been illegally modified. //typically we write 'define' in lowercase -- Spankmaster, Dec 2017
Missing an ending quotation

2017-12-02 12:49 UTC, JohnGinnane commented on hippiestation/code/game/objects/structures/flora.dm
> +#define EMAG_DESC_ADD = "This plant appears to have been illegally modified. //typically we write 'define' in lowercase -- Spankmaster, Dec 2017
I think

2017-12-02 12:50 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +#define EMAG_DESC_ADD = "This plant appears to have been illegally modified. //typically we write 'define' in lowercase -- Spankmaster, Dec 2017
it is

2017-12-02 12:50 UTC, banthebantz commented on hippiestation/code/game/objects/structures/flora.dm
> +#define EMAG_DESC_ADD = "This plant appears to have been illegally modified. //typically we write 'define' in lowercase -- Spankmaster, Dec 2017
also remove the comment

2017-12-02 17:57 UTC, zamolxius commented
Banthebantz reviewed this PR.
        Accepted my lad

2017-12-02 17:57 UTC, Spankmaster1066 commented
OK, should be good now.

2017-12-02 18:02 UTC, ghost requested changes

2017-12-02 18:02 UTC, MoreRobustThanYou commented on hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
> +
finish this

2017-12-02 18:05 UTC, ghost requested changes
it's pretty much ok

2017-12-02 18:05 UTC, MoreRobustThanYou commented on hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
> +/mob/living/simple_animal/hostile/retaliate/frog/Initialize()
frog? what? Also no need to specify Initialize if you're not gonna do anything other than ```. = ..()```

2017-12-02 18:05 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(istype(W, /obj/item/reagent_containers))
why not add dumping liquids in it?

2017-12-02 18:09 UTC, MoreRobustThanYou commented
don't do this shit in the webeditor, just get Sourcetree or someshit

2017-12-02 18:10 UTC, Spankmaster1066 commented on hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
> +/mob/living/simple_animal/hostile/retaliate/frog/Initialize()
Good catch ty

2017-12-02 18:11 UTC, Spankmaster1066 commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(istype(W, /obj/item/reagent_containers))
What is the proc for that? How do I writei t?

2017-12-02 18:12 UTC, MoreRobustThanYou commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(istype(W, /obj/item/reagent_containers))
nevermind

2017-12-02 18:15 UTC, doobiedoo23 commented
+1

2017-12-02 18:16 UTC, HippieBartels commented
This is unrealistic. There are no electronics in plants.

2017-12-02 18:16 UTC, fluxcapacitor1337 commented
+1

2017-12-02 18:17 UTC, Spankmaster1066 commented
Bartels, it isn't realistic. The plants have hardware in the pots which artifically weigh them down to prevent shenanigans being carried out with the plants, the emag disables this mechanism and allows the plants to move freely.

2017-12-02 18:19 UTC, ghost submitted a review, later dismissed
I'd suggest you change this to be less hacky

Create a new `/obj/item/kirbyplant` that does what the emagged plant should do.

Then, when the original plant is emagged, spawn the `/obj/item/kirbyplant` and put the original plant inside of the new plant, and qdel it

makes it less hacky

2017-12-02 18:21 UTC, Blute1 commented
holy fuck yes

2017-12-02 18:59 UTC, banthebantz commented
+1

2017-12-02 19:16 UTC, McBawbaggings commented
this isn't even tested

you haven't added it to hippiestation.dmb and committed that.

2017-12-02 19:16 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/flora.dm
> +#define SHARP_DESC_ADD = "This one appears to have a bunch of sharp edges peeking out from under its leaves."
Remove the "="
Defines don't work like that
It's
#DEFINE MY_CONSTANT number

2017-12-02 19:19 UTC, Spankmaster1066 commented
I didn't have to do that with my lean PR.. it's tested locally. What do I need to do with the .dmb?

2017-12-02 19:25 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/flora.dm
> +		desc = "[desc] [SHARP_DESC_ADD]"
SHARP_DESC_ADD is not a var, it's a DEFINE
This might work still but it should be  desc = "[desc] " + SHARP_DESC_ADD

2017-12-02 19:26 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/flora.dm
> +	desc = "[desc] [EMAG_DESC_ADD]"
Same as above about SHARP_DESC_ADD

2017-12-02 19:59 UTC, McBawbaggings commented on hippiestation.dme
> +#include "hippiestation\icons\mob\animal.dmi"
did you just add the icon.dmi manually

2017-12-02 20:09 UTC, bardofrage commented
+1, duh.

2017-12-02 20:53 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(W.is_sharp() && disable)  //If screwdriven and the item is sharp, it creates sharp plant
you can just keep adding sharp stuff and the desc can go on infinitely can it not?

2017-12-02 21:38 UTC, McBawbaggings commented
i like it but there's a few things to fix codewise
+1

2017-12-02 21:41 UTC, Spankmaster1066 commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(W.is_sharp() && disable)  //If screwdriven and the item is sharp, it creates sharp plant
I am testing that right now

2017-12-02 22:24 UTC, Spankmaster1066 reviewed
Hotdogs hot tangle dog

2017-12-02 22:24 UTC, Spankmaster1066 commented on hippiestation/code/game/objects/structures/flora.dm
> +	if(W.is_sharp() && disable)  //If screwdriven and the item is sharp, it creates sharp plant
Ye, it did but is now fixed.

2017-12-02 22:31 UTC, Dudeinyourbackyard commented
+1 i love the plants and getting to do more with them is great
do fix your code though

2017-12-02 22:39 UTC, Spankmaster1066 commented
Unless I am missing something, all code requests have now been met. The issue mcbaw mentioned about you being able to infinitely sharpen the bushes is also resolved. I agree with Erik about his thing but I'd really like to see this merged so we can just test it out in-game to see if it's fun, and if it is I'll go back through and make the new single handed plant item that the emagged one becomes. 

If it's not a good feature, it's not worth doing that work anyways. Right now as it stands it's entirely functional except you have to pick up the plant BEFORE picking up another item, if that's what you wanna do.

2017-12-02 23:32 UTC, JohnGinnane approved these changes

2017-12-02 23:32 UTC, JohnGinnane commented
original hippie content please add)

2017-12-03 00:39 UTC, Spankmaster1066 commented
Thank you for the kind comments Jonathan, whenever THE OTHER HEAD ADMINS AND MAINTAINERS DECIDE TO MERGE THIS INTO THE REAL GAME we can test it out =)

2017-12-03 01:00 UTC, Spankmaster1066 commented
prease merge this

2017-12-03 05:24 UTC, Spankmaster1066 commented
ayo dog.. mane

2017-12-03 20:56 UTC, Spankmaster1066 commented
WHAT REVIEWS HAVE NOT BEEN ADDRESSED? DO I HAVE TO DO ERIK'S THING BEFORE YOU'RE WILLING TO MERGE THIS? IT LITERALLY WORKS 100% FINE. I HAVE FIXED ALL ISSUES WITH IT. THE ONLY PROBLEM IS THIS:
1. PICKING UP PLANT WITH ITEM IN HAND WILL SAY "YOUR HANDS ARE TOO FULL" SO YOU HAVE TO PICK UP THE PLANT FIRST



IF THE FEATURE IS GOOD I WILL WRITE A FIX FOR THIS BUT CAN WE PLEASE TEST IT IN GAME TO SEE HOW PEOPLE LIKE IT? PLS?

2017-12-03 20:57 UTC, KayeArray approved these changes

2017-12-03 20:57 UTC, merged