Plant Expansion Beta: V.02
HippieStation/HippieStationdeprecated2020 pull request #5186
Opened 2017-12-04 07:01 UTC by Spankmaster1066

[Changelogs]: 

:cl: Spankmaster
tweak: Potted Lean behavior, adds chance to inject a variable amount of lean, tweaks some of the speech verbs and stuff
fix: Fixed a bug where you could infinitely sharpen a potted plant. 
tweak: Potted Plants now inherit the force of the item inserted into them. Fixed some of the outputted messages as well for performing actions on plants.
/:cl:

[why]: # Makes the experience of working with potted plants more fun and realistic.

2017-12-04 09:31 UTC, JohnGinnane commented on hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
> +	var/attackInject = "lean"
Kinda nitpicky but could this be changed to `attack_inject` to be consistent with the rest of the vars?

2017-12-04 10:13 UTC, JohnGinnane commented
Code is 🆗 but will wait for any other changes before approving because it'll be dismissed anyway

2017-12-04 18:20 UTC, ghost requested changes
No.

Please refactor your plants as was requested in the previous PR.

I'd suggest you create a new `/obj` for your one-handed-plant that is created when emagging a two handed plant, should be super simple and easy to do, and is less hacky than your current implementation

2017-12-04 20:15 UTC, Spankmaster1066 commented on hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
> +	var/attackInject = "lean"
Sure thing, I am still learning the little standards we use on here.

2017-12-04 20:17 UTC, Spankmaster1066 commented
Alright alright CHNKR I will set that up tonight, this still is kinda seperate. It just fixes the functionality we have on the server currently but alright gimme a sec

2017-12-04 21:58 UTC, Chnkr commented
@Spankmaster1066 Thanks dude, because when you do that you'll fix the issue with picking it up as well 👍

2017-12-04 23:31 UTC, Spankmaster1066 commented
I hear ya bro, the only thing is I have a fuckton of real life android coding assignments to work on right now so I can't go in and tweak this. So I will write it in a day or two and merge it to this.

That aside though, if this is merged now it will solve all the issues for the currently implemented potted plants besides the one-handed thing. They're a tad broken right now but it isn't game-breaking.

2017-12-06 06:49 UTC, Spankmaster1066 commented
OK Chnkr your request is met and this PR is 100% fully functional, no bugs at all as far as I can tell.

2017-12-06 07:39 UTC, ghost submitted a review, later dismissed
Just a small few things, rest is good

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/items/dildo.dm
> -//Coded by Nexendia~ :)
No.

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/structures/flora.dm
> +obj/item/kirbyplants_onehanded/equipped(mob/living/user)
Missing `/`

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/structures/flora.dm
> +obj/item/kirbyplants_onehanded/dropped(mob/living/user)
Missing `/`

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/structures/flora.dm
> +obj/item/kirbyplants_onehanded/random
Missing `/` and the `random` path is not needed, since these will never be dropped as a random plant

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/structures/flora.dm
> +obj/item/kirbyplants_onehanded/random/Initialize()
Missing `/` and the `random` path is not needed, since these will never be dropped as a random plant

2017-12-06 07:39 UTC, Chnkr commented on hippiestation/code/game/objects/structures/flora.dm
> +obj/item/kirbyplants_onehanded/random/proc/generate_states()
Missing `/` and the `random` path is not needed, since these will never be dropped as a random plant

2017-12-06 08:41 UTC, bardofrage commented
add this fix to our great station +1

2017-12-06 08:52 UTC, JohnMcLaime commented
This makes chameleon device pointless, with emag you basically get its a bit weaker (to thermals/sechud) version.

2017-12-06 15:20 UTC, fluxcapacitor1337 commented
+1

2017-12-06 15:21 UTC, McBawbaggings commented
we need 2 sell this as DLC under hippiecoin cryptocurrency
+1

2017-12-06 15:32 UTC, JohnGinnane commented
@McBawbaggings does this even need votes if it's bugfixing on already-approved stuff?

2017-12-06 15:53 UTC, Pyko1 commented
Undocumented code changes, this removes code that is not listed on initial pr or changes.

2017-12-06 15:57 UTC, KayeArray requested changes
>unatomic pr
>sneaking in changes
>not even removing the file correctly

2017-12-06 16:03 UTC, McBawbaggings commented
HOLY SHIT I DIDN'T EVEN NOTICE LMAO

spankmonkey ur gonna meet me behind mcdonalds and we're gonna fight 2 the death now

2017-12-06 16:07 UTC, JohnGinnane commented
Whoops, didn't even realise other commits were done

2017-12-06 19:14 UTC, Spankmaster1066 commented
I deleted Dildo's on my own Repo and forgot it would transfer over here. Let me fix that. I'm sorry I deleted dildos everyone.


To Roma, what you say is half true. The Chameleon Projector has the utility of being able to assume the form of ANY item, whereas this only lets you hide in a bush. Anyone who is aware of you using this strategy will instantly key in on bushes. a chameleon projector allows you to do plays like shooting someone then bolting into maint and transforming into a TINY and boring object, like a wire clipping.

2017-12-06 19:37 UTC, Spankmaster1066 commented
OK, all checks passed, Dildo stuff is fixed. Admins let's do this.

2017-12-06 19:39 UTC, KayeArray approved these changes

2017-12-06 19:40 UTC, banthebantz commented
+1

2017-12-06 19:40 UTC, merged