Mass Lavaland Nerfing : No Mercy Edition
HippieStation/HippieStationdeprecated2020 pull request #5566
Opened 2017-12-24 17:05 UTC by Arzion5

:cl: Arzion
tweak: Lavaland has been nerfed in multiple aspects, mostly regarding the creatures. No more "M-MUH D-DIFFICULTY!!!" for you.
tweak: Meat hook damage reduced to 10 from 25. Meat hook stun reduced to 1 second from 3.
balance: You can no longer transform into an inferior ashwalker when drinking the Dragon's Blood potion anymore.
tweak: Lava Staff damage reduced to 15 from 25. Cooldown for creating lava tiles has been increased to 60 seconds from 10 seconds.
tweak: The gods have realized that the blood-drunk miner is still really just a human, but still felt generous enough to reduce its health to 400 from 900, double the amount of health that a regular human has.
tweak: The nerf hammer has finally come crashing down on megafauna, reducing their health to 1500 from 2500 and damage reductions to their melee attacks (not their special abilities!) and in the case of Colossus and Hierophant, their projectile attacks too. Legion (the megafauna) had its health reduced to 550 from 800.
tweak: The nerf hammer has no mercy. Regular fauna is affected too. Goliath health has been reduced to 200 from 300, along with its unique ancient variant having its health reduced to 300 from 400. Goliath damage reduced to 20 from 25. Tentacle stun reduced to 5 seconds from 10.
tweak: Legion (the mob) had its health slightly reduced to 60 from 75, while legion skull damage has been reduced to 8 from 15 (the skulls bite only). The unique variant of the Legion had its health reduced to 100 from 120. Legion's skull spawn delay has been increased, which means you should be able to fight more Legions at a time without being overwhelmed by skulls.
tweak: Watcher's health has been halved to 100 from 200.  Damage reduced to 12 from 15. Magmawing health reduced to 140 from 215. Icewing health reduced to 120 from 170. 
tweak: The tendrils are not safe either. Necropolis tendril health has been reduced to 175 from 250, and the rate at which fauna is spawned from the tendrils has been reduced, taking 60 seconds to spawn a creature instead of 30.
/:cl:

Beg me for mercy.

2017-12-24 17:09 UTC, zamolxius commented
fast merge -head maintainer

2017-12-24 17:16 UTC, GuyonBroadway commented on hippiestation/code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/dragons_blood/attack_self(mob/living/carbon/human/user)
Excuse me sir but you forgot to put this in the changelog.

2017-12-24 17:16 UTC, Arzion5 commented on hippiestation/code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/dragons_blood/attack_self(mob/living/carbon/human/user)
Already there. "tweak: Meat hook damage reduced to 10 from 25. Meat hook stun reduced to 1 second from 3."

2017-12-24 17:17 UTC, GuyonBroadway commented on hippiestation/code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/dragons_blood/attack_self(mob/living/carbon/human/user)
No the dragons blood changes you Nimby!! You read from the commented line downwards you blithering chunderbucket!

2017-12-24 17:20 UTC, Arzion5 commented on hippiestation/code/modules/mining/lavaland/necropolis_chests.dm
> +/obj/item/dragons_blood/attack_self(mob/living/carbon/human/user)
"balance: You can no longer transform into an inferior ashwalker when drinking the Dragon's Blood potion anymore."

2017-12-24 17:21 UTC, GuyonBroadway requested changes
AND FOR CRYING OUT LOUD, TEST ALL THIS SHIT!!

2017-12-24 17:21 UTC, GuyonBroadway commented on hippiestation/code/modules/mining/lavaland/necropolis_chests.dm
> +	var/create_cooldown = 600 //Jesus Christ, why would you give a miner such a powerful tool that allows you to create impassable lava floors that deal massive burn damage?
remove the var/

2017-12-24 17:21 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	var/damage = 7
remove the var/

2017-12-24 17:21 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
> +	var/damage = 7
remove the var/

2017-12-24 17:21 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +/obj/effect/temp_visual/goliath_tentacle/proc/trip()
remove /proc

2017-12-24 17:53 UTC, Dudeinyourbackyard commented
Test it all out.
I like the nerfs though.
+1

2017-12-24 17:58 UTC, Jujumatic commented
Tentacle stun reduced to 5 seconds from 10.

YOU ARE GREATER THAN JESUS THANK YOU FINALLY

2017-12-24 18:02 UTC, Carbonhell commented
>nerfing normal enemies
git gud

2017-12-24 18:05 UTC, Arzion5 commented
@Carbonhell No u >:(

2017-12-24 21:18 UTC, Arzion5 commented
All tested, it's all okay, good, comfy and kosher

2017-12-24 22:21 UTC, xTrainx commented
the absolute state of hippiestation

2017-12-24 22:27 UTC, Arzion5 commented
Beg for mercy @xTrainx

2017-12-24 23:35 UTC, banthebantz commented
yeah halo 2 brutes were cooler anyway

2017-12-25 00:45 UTC, GuyonBroadway submitted a review, later dismissed

2017-12-25 08:46 UTC, Jujumatic commented
"from Arzion5:Probably-makes-Lavaland-not-be-such-a-piece-of-shit-gamebreaker-holy-fuck"

I agree also can we pls merge now before someone comes and says NO and codegrudges insane buffs into the lavaland mobs :(

2017-12-25 10:30 UTC, Carbonhell commented
So basically even an armless dude can mine safely
-1
***-1***

2017-12-25 10:32 UTC, GuyonBroadway commented
Your -1 lost its power when u quit being headcoder.

2017-12-25 10:34 UTC, Pyko1 commented
NO, time to grudgecode lavaland mobs attack and move 10 times faster for balance.

2017-12-25 10:38 UTC, Jujumatic commented
Balance: Goliaths have had their stun-time increased to 5 minutes, up from 10 seconds.
Tweak: All mobs can now move 50 tiles per tick
Tweak: All mobs have had their health increased by 500% for "balancing" reasons

REEEEEEEEEEEEEEEEEEEEEE

2017-12-25 13:11 UTC, Carbonhell commented
Time to become headcoder again just to -1 this pr

2017-12-25 15:59 UTC, Chnkr commented
-1 stop being shit

2017-12-25 20:01 UTC, Jujumatic commented
+1 fix the server lag and maybe we can stop being shit

2017-12-25 20:26 UTC, praisenarsie commented
no one saw that

2017-12-26 01:07 UTC, doobiedoo23 commented
@Carbonhell that wud imply u  have the ability to get headcoder again
BOO MBTFO

2017-12-26 01:23 UTC, doobiedoo23 commented
also youre actually limp dicked fuckers just remoev lavaland entirely lol

2017-12-26 01:39 UTC, JohnMcLaime commented
Since you are moving to new box, up lavaland bombcap, it is just 15 30 60 currently.

2017-12-26 01:40 UTC, GuyonBroadway commented
That'd be outside the pr scope John

2017-12-26 13:14 UTC, Pyko1 commented
So basically every lavaland mob nerfed in multiple ways, I really fail to see the point.
Lavashit is only really challenging to lavaliggers anyways, and this will just prolly make them die even faster since bored miners will be knocking their front door and face even faster with kinetic accelerators.

I mean this PR and the roundstart plasma cutter for ripley with voucher PR combined, why not just spawn all the lavaland ore at mining room aboard the station on round start?

2017-12-28 12:32 UTC, Arzion5 commented
Lavaland, as of currently, is a mess where people think that if you get tendril stunned for 10 seconds and subsequently mauled, or instantly disappearing for accidentally stepping into a chasm, or being turned to ash or gibbed by megafauna (while since the tech webs rework, you have to wait for some time to produce t4 components to upgrade cloners so that you can be auto-cloned after dying, while at the same time it is unlikely that you'll have your brain recovered by anyone in the case you're gibbed), is challenging, in spirit with the "MOST HOSTILEST PLACE IN THE GAME" and not just extremely annoying. Rewards are completely based on RNG and range from useful and neat (things like the god eye [X-ray and night vision, essentialy complete 7-tile vision, but makes you permanently vulnerable to flashes], the hardsuits, tarot cards) to very shitty (things like soulstones [you aren't given constructs with it], cursed katana, diamond pickaxe). However, I can compromise so that no mob damages will be reduced (except for colossus death bolts), but health reductions will still stay as they are, seeing as fauna and megafauna turn from challenging to very annoying as you become more skilled at surviving in Lavaland, and the megafauna are really just damage sponges.

2017-12-28 12:35 UTC, praisenarsie commented
bro are you retarded, just fucking use your arrowkeys to move like lmao 😂 just move away 🚶 just walk away from the tendril ⛺️ bro just smash that arrowkey button 👉  💥 ▶️ like real shit!?

2017-12-28 12:53 UTC, geylard commented
first the R&D change to make it built for retards and now mining too? kill all coders before ss13 devolves into a game of pong.

2017-12-28 15:52 UTC, JohnMcLaime commented
There is no point to "farm" megafauna if you have a mech, if you have a mech you have basically all you need for station wide genocide/protecting the disk and being unstunnable.
The loot they drop isnt worth wasting 20 mins (if you are fast/lucky with miners/ore placement) to get mech and then waste extra 5-10 mins getting to the boss and combat mechs cant have plasma cutter (can have rocket launcher but not shitty mining laser?) and luring it to open area to kill it. It isnt worth spending time to order autorifles with trashbags and getting ballistic weapon research for cheap mags. It isnt worth the time getting points to upgrade your KA, same with stock KA.

And they have been balanced by tg, where they still have plenty of 1 hit gg no re weapons, where you can make maxcaps out of all stock ttvs in 5 mins. Combat oriented loot isnt much better than onstation one (thermal eye is bugged and even if it wasnt, it would be still tied to rng drop) and generally, counters to the loot you spent shitton of time getting, can be aqquired in less than 5 mins. As for meme loot, is it worth the time getting to it?

2017-12-28 16:16 UTC, geylard commented
maybe if the coders added lavaland mechanics and items instead of trying to take it away. GIVE ME MY CHAOS EMERALDS. GIVE ME MY DORFS.

2017-12-30 09:18 UTC, Jujumatic commented
With the way lavaland is there's no point in even going there as you can get better items from the station in half the time, you're guaranteed to get them and you don't have the stupid retard danger of ooh muh random instant death penalty for teh lulz ecks dee xxddddD. If you really want that to stay in lavaland then nobody is even going to even work on it anymore because nobody is going to use lavaland anymore. It's supposed to be high risk = high reward not super high risk = most likely shit rng reward and if you're lucky maybe an ok reward at best but still nothing compared to the god tier shit you can get on the station in the same amount of time.

2017-12-30 09:21 UTC, Jujumatic commented
This comments section needs to be locked so only people who've had some time on lavaland can comment on this PR, fuck.

2017-12-30 10:59 UTC, geylard commented
"FUCK RNG"

I almost always see a miner on lavaland. There's literally never a, "lol random death xdddD" thing on lavaland, megafauna can be tracked through the GPS and tentacles have a couple second delay for you to get away from them. Instead of making lavaland boring/easy as fuck for players who haven't done lavaland a million times to the point of it only being used as a potential way to get items, how about you FILTHY, DISGUSTING CODERS add more features/items instead of removing the risks of lavaland and nerfing the items as mentioned in the PR? All these nerfs will do is make it appealing to A. Unrobust turbo nerds and B. People trying to farm items so they can kill tendrils then run back to the station as fast as possible to show off their goods. Also as long as lavaland has unique cool items, then it's worth going to. The appeal of lavaland is the challenge and the unique loot that can be gained through COMBAT, not "GET THE "BEST" MOST POWERFUL ITEM IN THE SHORTEST AMOUNT OF TIME" because by that theory, why the fuck isn't R&D, xenobiologist, toxins, cargo technician and warden more popular jobs than mining? 

I think you're all just fucking scrubs too. Even as "COMPLETELY BULLSHIT" as lavaland is currently, it's still completely viable to go to lavaland, kill a few tendrils then get back within 15 minutes if you're truly as not shit as you say. I also think the current difficulty is important to lavaland spawns and without the difficulty some of those roles will become increasingly gay.

The only thing that can be improved upon by simply removing/nerfing shit is removing KA upgrade disks from lavaland chests.

 Literally kill everyone in this PR.

2017-12-31 19:54 UTC, Arzion5 commented
If the PR gets merged but it turns out that it has negative consequences on Lavaland gameplay as a whole, then I will revert the changes myself

2017-12-31 19:55 UTC, Swagile commented
- 1

nothing in lavaland has to be fixed because its extremely rare, due to how shit the rng is and how fast the rounds go, for anything in lavaland to ruin the round

2017-12-31 19:56 UTC, tortellinitony commented
\-1 Lavaland isn't meant to be easy!

2018-01-01 00:09 UTC, Iamgoofball commented
if tg players can handle this you dipshits can too

git gud

2018-01-01 00:09 UTC, Iamgoofball commented
ps.

this PR is hippie admitting it's less robust than /tg/

2018-01-01 00:26 UTC, Kawaii-Big-Boss commented
-1
Lavaland items like the meathook probably should get a nerf, but you made some good decisions and them some hilariously poor ones.
How about you speed up mining instead of making mining worse?

2018-01-01 01:42 UTC, praisenarsie commented
yeah i knew this was going to be disliked

arzion, git gud B)

2018-01-01 01:42 UTC, closed without merging