Dental Implant Activates in Softcrit
HippieStation/HippieStationdeprecated2020 pull request #5597
Opened 2017-12-27 01:56 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: The ability to use dental implants in soft crit (-30 hp and above)
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I think it's ridiculously silly that you can crawl, whisper and superfart while in softcrit but can't simply bite down to activate something in your mouth. Hopefully you guys will like this.

2017-12-27 11:57 UTC, JohnGinnane commented
I'm against this because I think it encourages powergaming

2017-12-27 12:07 UTC, JohnGinnane requested changes
technically works but would rather it's changed

2017-12-27 12:07 UTC, JohnGinnane commented on code/modules/surgery/dental_implant.dm
> +	if(owner.stat != CONSCIOUS && owner.stat != SOFT_CRIT )
By removing the check for `..()` you're missing this (action.dm):

![image](https://user-images.githubusercontent.com/3355198/34380995-8dd1aaba-eafd-11e7-9aba-e31e94663441.png)

I think you might want to adjust the flags (and maybe add a new one for soft crit) for the implants. As you can see below these are the flags being using by implants (also action.dm):

![image](https://user-images.githubusercontent.com/3355198/34381110-50f59600-eafe-11e7-8725-d4fb7228fc81.png)

By using flags it just makes it more consistent with the rest of the code. Also you're missing the usual `// Hippie Code - Erik is lame` stuff

2017-12-28 06:21 UTC, yoyobatty commented on code/modules/surgery/dental_implant.dm
> +	if(owner.stat != CONSCIOUS && owner.stat != SOFT_CRIT )
Will do it

2017-12-28 07:28 UTC, yoyobatty commented on code/modules/surgery/dental_implant.dm
> +	if(owner.stat != CONSCIOUS && owner.stat != SOFT_CRIT )
Okay, so this actually just makes things a lot more complicated, the single line with the comment is more than perfect, but

2017-12-28 15:43 UTC, FantasticFwoosh commented
Limit it to 1 dental implant or implant (EI - nuclear operative explosive implant or adrenals) in general at a time and it wouldn't be as overpowered.

2017-12-28 15:45 UTC, McBawbaggings commented
bad but also bad

this will only benefit non-antag crew who powergame further and it's already a problem

2017-12-28 15:50 UTC, FantasticFwoosh commented
Then the issue in subject is that a unlimited amount of these can be used whilst awake with a minimal amount of preparation for a non-complex procedure.

Protocol normally would be to probe & operate upon captured criminals for implants like these, if they dupe you with ephedrine & zombie powder for a fake death while the drugs stabilise & bring them round it would be your own fault.

2017-12-28 16:10 UTC, Dudeinyourbackyard commented
Don't like it.

2017-12-28 16:11 UTC, Chnkr commented
bad bad bad

2017-12-28 17:01 UTC, JohnGinnane approved these changes
Code looks good now

2017-12-28 17:05 UTC, JohnGinnane commented
The problem with implants is there's no counter play to them with this change. Perhaps implants might only work if you're not stunned. Being in soft crit, sure it makes sense you can move around and whisper. However when stunned, you can't move, and that's really why they're used - To remove any stun and then run away. They were abused as antistuns (when stuns were really popular) and because literally anyone can make them really quickly with no downsides.

With this change, why would any tator buy stims/implants when you can make them for free on the station?

2017-12-28 17:22 UTC, Chnkr commented
I'd suggest changing it, to where you have a percentage chance to activate it successfully, a non-successful activation would lead to

- a chance to break your teeth
- a chance to bite your tongue, and be unable to speak for a while

if the entire mechanism is RNG based, and the effectiveness is based on your current HP it effectively makes it less useful for powergamers, and traitors

2017-12-28 17:23 UTC, Pyko1 commented
Also brute attacks on mouth should have a high chance of activating dental implants.

2017-12-28 17:25 UTC, JohnGinnane commented
@Chnkr no please no RNG for the love of God

2017-12-28 17:29 UTC, JohnGinnane commented
Because RNG is the aboslute worst, here's some alternatives:

* Delays to bite down on the implant - Even something like a 1 second delay, and make it visible to nearby players so they know what's happening
* Can't use it when stunned - This completely negates anti-stun implants which are the biggest culprit
* I think implants were limited to 1 already? If not, then max 1 implant whose total volume would only be 5 units or something
* As Pyko suggested, being hit the mouth can either activate it or just knock it out even

@yoyobatty I know this is a lot more than what your PR is about but we don't to fall back to powergamers just gaming every mechanic to ensure they're almost invincible

2017-12-28 17:35 UTC, yoyobatty commented
I absolutely love your guys suggestions. Even though antistuns aren't a thing any more, the only advantage I can see this offering is for implenting a combination of healing chems to revive you in emergencies or implanting morphine pills to let you run at full speed despite being cold/disabled/wearing a hardsuit. I like the idea of the stun preventing use as well as the delay and knockout from brute to the mouth, but I think it's not really fair to limit its potential that severely.

2017-12-28 17:54 UTC, JohnGinnane commented
What about not being to use implants while stunned? Does that nerf them into non-existence?

2017-12-28 22:51 UTC, FantasticFwoosh commented
Well technically if you're going to deposit drugs inside yourself you are entitled to use them and drugs like methamphetamine and other anti stun reagents can be activated conveniently before the stun is applied when the perp sees a taser bolt heading towards them.

There are plenty of solutions in /tg/ code to stopping anti-stun or speedy opponents, a typical e-bola to limit speed & anti-stamina shots will keep a perp down, until they are managable enough to be contained & the source (adrenals or teeth implants) located & removed in custody.

2018-01-05 02:01 UTC, Kawaii-Big-Boss commented
Dental implants were the most obnoxious shit on the planet thanks to antistuns. The only reason anyone would use this is to cheese omnizine or other chems through crit.
Crit is supposed to make you helpless. Unless you took chems or an epi-pen before you entered crit, you're pretty much screwed unless someone comes to help you. Considering what we saw in the past with the use of dentals in crit (omnizine and cryo-chems) I can only imagine how much this would make chemisty even more obnoxious.
There's a reason why Chemistry has been getting hit with so many nerfs lately. It's too easy to make, too easy to abuse, and has no downside what-so-ever for the most part. Powergamers eat this shit up and then head of validhunting before you even know it.
Even if this is just a small change that won't really give powergamers too much of an edge over the average player, it's still something the powergamers would inevitably exploit. Don't give them an inch.

tl;dr No, no, no.

2018-01-05 22:20 UTC, Chnkr commented
No

2018-01-05 22:32 UTC, praisenarsie commented
no headmin or headcoder likes it, looks like it's going into the bin. 🗑

2018-01-05 22:32 UTC, closed without merging