Ports Lawnmowers
HippieStation/HippieStationdeprecated2020 pull request #579
Opened 2017-04-12 19:30 UTC by Memendia

Ports Hippie lawnmowers

:cl: Nexendia
add: Added Hippie Lawnmowers
add: They can be purchased by traitor botanists.
/:cl:

2017-04-12 19:55 UTC, Chnkr commented
needs `to_chat()`

2017-04-12 19:58 UTC, tortellinitony requested changes

2017-04-12 19:58 UTC, tortellinitony commented on hippiestation/code/modules/vehicles/pimpin_ride.dm
> +	user << "<span class='warning'>You disable the safety mechanisms on \the [src].</span>"
to chat

2017-04-12 19:58 UTC, tortellinitony commented on hippiestation/code/modules/vehicles/pimpin_ride.dm
> +		user << "<span class='warning'>The safety mechanisms on \the [src] are already disabled!</span>"
to chat

2017-04-12 20:28 UTC, Memendia commented
@tortellinitony done

2017-04-13 02:46 UTC, tortellinitony approved these changes

2017-04-13 02:46 UTC, merged