STOP RIGHT THERE CRIMINAL SCUM
HippieStation/HippieStationdeprecated2020 pull request #5998
Opened 2018-01-17 19:46 UTC by Kawaii-Big-Boss

[Changelogs]:

:cl: KawaiiBigBoss
add: Added a new box to the SecTech containing special armor.
add: Has its own custom scream sound.
admin: Was originally an attempt at creating a new DS that didn't end well. Nothing should be damaged.
/:cl:

Nanotrasen belongs to the Nords!
Adds a box to the SecTech at Security containing a reskin of the standard officer gear, which looks similar to that of a Whiterun Guard.
The helmet applies special scream sounds.

2018-01-17 19:49 UTC, ghost requested changes
Resupply packs won't work as intended and I have no idea if it will properly stocked on roundstart.

2018-01-17 19:49 UTC, McBawbaggings commented on code/game/machinery/vending.dm
> +					/obj/item/reagent_containers/food/snacks/donut = 12, /obj/item/storage/box/evidence = 6, /obj/item/device/flashlight/seclite = 4, /obj/item/restraints/legcuffs/bola/energy = 7, /* hippie edit */
IF YOU MODIFY THE PRODUCTS LIST OF A MACHINE, MAKE SURE TO UPDATE ITS RESUPPLY CANISTER CHARGES in vending_items.dm
https://github.com/HippieStation/HippieStation/pull/5998/files#diff-be8fc4ef536d83a7c390019dd59d14efL623

2018-01-17 19:50 UTC, Kawaii-Big-Boss commented on code/game/machinery/vending.dm
> +					/obj/item/reagent_containers/food/snacks/donut = 12, /obj/item/storage/box/evidence = 6, /obj/item/device/flashlight/seclite = 4, /obj/item/restraints/legcuffs/bola/energy = 7, /* hippie edit */
The SecTech does not use resupply. I tested it, it spawns properly stocked on roundstart.

2018-01-17 19:51 UTC, McBawbaggings commented on code/game/machinery/vending.dm
> +					/obj/item/reagent_containers/food/snacks/donut = 12, /obj/item/storage/box/evidence = 6, /obj/item/device/flashlight/seclite = 4, /obj/item/restraints/legcuffs/bola/energy = 7, /* hippie edit */
My bad, most issues I've had with vending machine stuff has stemmed from that.

2018-01-17 19:59 UTC, Kawaii-Big-Boss commented
+1
+1
+1
ok we can merge now

2018-01-17 20:17 UTC, Carbonhell commented
1) why did you put this in the sectech vendor?if it's literally clothing, sec has a special locker containing their clothings in checkpoints and brig
2) put some pics of the sprites in the desc please

2018-01-17 20:18 UTC, Kawaii-Big-Boss commented
Put it in the sectech vendor because I dinnae know how to map. It's also armor, meaning that if I just put it in the "special locker" greyshirts could just bust into arrivals and get sec gear.

2018-01-17 20:19 UTC, praisenarsie commented
> put some pics of the sprites in the desc please

![2018-01-17_20-18-05](https://user-images.githubusercontent.com/31222036/35064952-9576b4b4-fbc3-11e7-9159-7f374e94bd11.png)

![image](https://user-images.githubusercontent.com/31222036/35065014-c3b368f4-fbc3-11e7-8948-cf9383aad891.png)

2018-01-17 20:21 UTC, Carbonhell commented
you don't need to map, there are preset closets with a special proc, populatecontents, which i just noticed you used aswell. Just find the path to said locker, edit the proc,call ..() at the start and add your items,done

also if it is like armor,perhaps add it to the red lockers then?armor in dispensers sounds..ehh

2018-01-17 20:22 UTC, Kawaii-Big-Boss commented
Why have the medieval armor also crowd the red lockers? If you insist then I'll do it, but the point of adding it to the SecTech was to stop crowding, not do mapping stuff, and keep it out of hands of the greyshirts.

2018-01-17 20:25 UTC, Carbonhell commented
normal armor vest and helmet is in the red locker,so it makes sense for a resprited item to be in the same place, but it's just minor shit,doesn't matter much, +1

2018-01-17 20:25 UTC, Carbonhell commented on code/modules/admin/verbs/one_click_antag.dm
> +
remove this?

2018-01-17 20:26 UTC, Carbonhell commented on hippiestation/code/modules/clothing/head/helmet.dm
> +	dynamic_hair_suffix = ""
are those two vars actually needed?

2018-01-17 20:26 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/clothing/head/helmet.dm
> +	dynamic_hair_suffix = ""
Yes. They properly hide the head. Without them you get a janky ass look.

2018-01-17 23:09 UTC, 2Dollarbill commented
+1 m8, merge this shit now.

2018-01-17 23:45 UTC, Kawaii-Big-Boss commented
merge dis

2018-01-18 00:29 UTC, TrickyDickRichard commented
merge            this

2018-01-18 00:31 UTC, t-f-w commented
+1!!!

2018-01-18 00:50 UTC, Kawaii-Big-Boss commented
Hello yes it is me Maintainer Big Boss.
I can verify that the code looks fine.
You may merge this now.
:smug:

2018-01-18 02:57 UTC, Dudeinyourbackyard commented
has a plus two and some reviews by cabroni, should be ok to merge

2018-01-18 02:58 UTC, ghost approved these changes

2018-01-18 02:58 UTC, merged

2018-01-18 08:05 UTC, Pyko1 commented
Then again didn't pass the 24 hour mark, which all non mirror, non fix PR's should be delayed.

2018-01-18 08:09 UTC, Pyko1 commented
also this should be really be a cargo pack like the crusadier set.

2018-01-18 12:52 UTC, Carbonhell commented
@pyko1 what do you mean,the 24 hour mark is a tg thing,if a pr has the +2s and a codecheck it can be merged
Although my +1 was an head one,i didnt actually codecheck this carefully but it looks modular enough to me?

2018-01-18 13:13 UTC, Pyko1 commented
![24hour](https://user-images.githubusercontent.com/12048747/35099811-12d83c54-fc62-11e7-8445-f4e3fd5cab44.JPG)

2018-01-18 13:14 UTC, Pyko1 commented
the vending machine change was not modular, only the new items.

2018-01-19 19:13 UTC, Kawaii-Big-Boss commented
@Pyko1 The hell do you even mean by "modular?" We don't have a mirror for vending machines on our side, you have to edit them on the /tg/ side.
If adding a single line alongside "this is a hippie edit" is not okay, then suck it up. It's the only thing you can do.

2018-01-19 19:48 UTC, Carbonhell commented
That single line could have been avoided,pyko is right once again

2018-01-19 19:49 UTC, Kawaii-Big-Boss commented
And nobody told me this.