[MIRROR] Moths, except I have stolen them and they no longer conflict
HippieStation/HippieStationdeprecated2020 pull request #6061
Opened 2018-01-19 15:32 UTC by HonkBot

Original PR: https://github.com/tgstation/tgstation/pull/34498
--------------------
:cl: Joan and More Robust Than You
add: Adds moths! They're a new species that is able to fly in pressurized areas provided gravity is off... and that they still have wings.
/:cl:

![](https://i.imgur.com/ktRc4p8.png)

**CREDITS TO @ tortellinitony, @ FuryMcFlurry, and @ TDcoolguy300 for their original work on moths.**

2018-01-19 22:13 UTC, Carbonhell commented
Needs all those retarded advantages to be disabled before going in
Or just disable them completely and leave ours in

2018-01-19 22:16 UTC, Carbonhell commented
With a quick glance at the code i think we can merge everything and only keep our moth.dm specie file to make everything work as desired,and better. The language could be kept,doesnt seems like a big issue.

2018-01-21 11:21 UTC, GuyonBroadway commented on code/_globalvars/lists/names.dm
> +GLOBAL_LIST_INIT(moth_names, world.file2list("strings/names/moth.txt"))
Reccomend we replace our local version of this file with as many variations of the work cuck as we possibly can.

2018-01-21 15:43 UTC, Pyko1 commented
merge https://github.com/HippieStation/HippieStation/pull/6089 after this

2018-01-21 15:56 UTC, Pyko1 commented
also pretty sure we don't actually need the config update.
due to hippie mothshit module overwriting the config check.

2018-01-21 19:01 UTC, Pyko1 commented
added https://github.com/HippieStation/HippieStation/pull/6116#issuecomment-359271387 fix to the code that goes in to hippie folder

2018-01-22 13:49 UTC, Pyko1 commented
added the contents of open moth fix mirrors to this PR, as merging this would had just those conflict.

2018-01-23 15:52 UTC, Pyko1 commented
fixed once again, and added changes from moth mirrors that are bound to conflict.

2018-01-25 18:41 UTC, tortellinitony requested changes

2018-01-25 18:41 UTC, tortellinitony commented on code/modules/mob/living/carbon/human/species_types/mothmen.dm
> +Pull requests
fix this file

2018-01-25 18:41 UTC, tortellinitony commented on tgstation.dme
> +#include "code\modules\language\moth.dm"
add files to hippiestation.dme

2018-01-25 18:42 UTC, Pyko1 commented on tgstation.dme
> +#include "code\modules\language\moth.dm"
actually is ok, tg removed the file on moth fix, but diditn undefine it

2018-01-25 18:47 UTC, Pyko1 commented on code/modules/mob/living/carbon/human/species_types/mothmen.dm
> +Pull requests
wow, no idea how it even checked out with those copy paste issues,

2018-01-26 04:09 UTC, tortellinitony submitted a review, later dismissed

2018-01-26 04:09 UTC, tortellinitony commented on code/modules/mob/living/carbon/human/species_types/mothmen.dm
> +Contact GitHub
there is more

2018-01-26 11:39 UTC, Carbonhell submitted a review, later dismissed

2018-01-26 13:29 UTC, Carbonhell approved these changes

2018-01-26 13:29 UTC, Carbonhell commented
@Pyko1 merge it,i approve

2018-01-26 13:31 UTC, merged