let's you replace your arm with an energy chainsaw without it being shit
HippieStation/HippieStationdeprecated2020 pull request #6079
Opened 2018-01-20 20:34 UTC by xTrainx

[Changelogs]: # 
:cl: xTrainx
add: Added mounted energy chainsaw
tweak: putting a chainsaw in your arm now distinguish betwen energy chainsaw and normie chainsaw
/:cl:

[why]: # fixes issue #4510

2018-01-20 20:36 UTC, ghost requested changes
Indent everything under line 50 in weaponry.dm

2018-01-20 20:36 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/weaponry.dm
> +/obj/item/mounted_energy_chainsaw
Code doesn't work, not properly indented.

2018-01-20 20:36 UTC, McBawbaggings commented on code/modules/surgery/prosthetic_replacement.dm
> +			if(istype(tool, /obj/item/twohanded/required/chainsaw/energy))
You are adding new code to /tg/ code file
Either mirror and update the proc in the hippiestation subfolder or add a comment saying the start and end of hippiecode if that is not feasible.

2018-01-20 20:49 UTC, xTrainx commented on hippiestation/code/game/objects/items/weaponry.dm
> +/obj/item/mounted_energy_chainsaw
Sorry, i have autism

2018-01-20 21:29 UTC, xTrainx commented
and it only took me 6 commits

2018-01-21 03:35 UTC, 2Dollarbill commented
Why not, I think it'd be fine, more toys for the boys. +1

2018-01-21 03:42 UTC, GuyonBroadway commented
reminder that you need two hands just to hold a chainsaw so without a willing helper this is impossible to do yourself... and that's fine IMO.

2018-01-21 11:24 UTC, Carbonhell requested changes

2018-01-21 11:24 UTC, Carbonhell commented on code/modules/surgery/prosthetic_replacement.dm
> -			var/obj/item/mounted_chainsaw/new_arm = new(target)
Why not just change this from new(src) to new tool(src)?

2018-01-21 11:24 UTC, Carbonhell commented on hippiestation/code/game/objects/items/weaponry.dm
> +/obj/item/mounted_energy_chainsaw
Maybe make it a child of the normal mounted chainsaw?

2018-01-21 13:54 UTC, Carbonhell commented
This isnt really a feature but a bugfix. Its passable since the system beneath it is shitty. A rework in future could be wise. Merging

2018-01-21 13:54 UTC, Carbonhell approved these changes

2018-01-21 13:54 UTC, merged