Dufflebag buff
HippieStation/HippieStationdeprecated2020 pull request #6250
Opened 2018-01-26 12:07 UTC by xTrainx

[Changelogs]:

:cl: xTrainx
tweak: Duffle bag will no longer slow you down
/:cl:

[why]: # https://hippiestation.com/threads/remove-dufflebag-encumbrance-2017.5956/ left the duffle bag weight capacity as it is to avoid problem with preloaded duffle bag and because the difference is not so big that would be game breaking

2018-01-26 12:09 UTC, McBawbaggings commented
why would you ever use the regular backpack over a duffel then?
might as well make it a cosmetic change (LIKE HOW IT USED TO BE)

2018-01-26 12:10 UTC, Pyko1 commented
should be the same size as all the other roundstart bags if it does not slow down.

2018-01-26 12:10 UTC, Carbonhell commented
As baw said. Also you need to modularize it, just make a file with the same filepath in hippiestation folder, and "overwrite" the var aka /path/of/the/item
var=newvalue

it'll take precedence over tg one

2018-01-26 12:10 UTC, McBawbaggings commented
https://github.com/HippieStation/HippieStation/search?utf8=%E2%9C%93&q=duffelbag+PopulateContents&type=

All instances to replace.

2018-01-26 13:13 UTC, Pyko1 commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +	name = "duffel bag"
no need to redifine these lines.
name = "duffel bag"
desc = "A large duffel bag for holding extra things."
icon_state = "duffel"
item_state = "duffel"

2018-01-26 13:18 UTC, Pyko1 commented
Also +1 when the code changes are completed to make it only visual.

2018-01-26 15:35 UTC, tortellinitony submitted a review, later dismissed
Remove excess variables

2018-01-26 20:00 UTC, xTrainx commented
changes acknowledged and aplied

2018-01-26 20:09 UTC, tortellinitony submitted a review, later dismissed

2018-01-27 07:54 UTC, Pyko1 commented
now we just play the waiting game of someone wandering in with their thumb up, and him actually counting for approval purposes.

2018-01-27 11:48 UTC, Chnkr commented
This is a dumb change

2018-01-27 11:54 UTC, Carbonhell commented
It isnt dumb. Making it visual only is how it was pre rebase and people liked it that way. Pr seems ok, it has my +1

2018-01-27 12:32 UTC, Chnkr commented
Dufflebags offer more storage space, so to compensate for the balance implications they slow you down

2018-01-27 13:05 UTC, GuyonBroadway commented
They used to just be a cosmetic roundstart option for fasionstation13.

2018-01-27 13:30 UTC, Chnkr commented
Then just add a new sub item that is cosmetic only?

2018-01-27 13:37 UTC, Carbonhell commented
Who even uses the slow version? I have never seen anyone using it..

2018-01-27 14:28 UTC, xTrainx commented
How about making it slow down only after getting more than 21 weight class?

2018-01-27 15:52 UTC, JohnMcLaime commented
Make sure to leave syndie duffel bags as they are currently.

2018-01-27 15:57 UTC, Carbonhell commented
Why use normal backpacks and satchels at all then if they are a straight nerf

2018-01-27 16:07 UTC, fluxcapacitor1337 commented
+1

2018-01-27 16:22 UTC, Chnkr commented
This change will break existing functionality, please rework your PR to keep existing dufflebags working, I'd suggest you add an action button that allows you to switch from a cosmetic to a working dufflebag.

2018-01-27 16:23 UTC, Carbonhell commented
What chnkr said, if you do that you got my +1

2018-01-27 19:30 UTC, xTrainx commented
i think i did a thig

2018-01-27 20:50 UTC, tortellinitony commented
-1

Not worth the change for some weird hacky system where you can switch between

2018-01-27 20:50 UTC, tortellinitony commented
This makes them not cosmetic only and also objectively superior to all other bags since you can toggle between

2018-01-27 21:31 UTC, xTrainx commented
This just needs testing now, there should be an option for adjust bag on the object tab

2018-01-27 22:06 UTC, JohnMcLaime commented
Regular duffelbags arent worth it due to slowdown, syndie duffels got no slowdown but make you valid/give you out and usually cost tc.

2018-01-27 23:05 UTC, xTrainx commented
pelase dont axe me, i have a family to feed

2018-01-27 23:18 UTC, Chnkr commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +/obj/item/storage/backpack/duffelbag/verb/adjust_bag(mob/living/user)
You should only be able to do this if it's in your hand, and it needs a delay

2018-01-28 03:47 UTC, xTrainx commented
after about 4 hours of understanding how variables work, i managed to only allow it to  be used on hand and gave it a delay, while making it compile, now someone needs to test this, also, i would like to thank carbonara, macbwing, tg and bane for allowing me to let thi pr coem this far

2018-01-29 13:42 UTC, JohnMcLaime commented
What if you try to switch modes while it has items in it?

2018-01-29 21:08 UTC, xTrainx commented
If you have more item than the max capacity while adjusted, it wont let you toggle it

2018-01-30 15:16 UTC, Pyko1 commented
to be honest i don't care eitherway.

2018-02-01 00:10 UTC, t-f-w commented
would just prefer old dufflebags and them being solely cosmetic. +1 if they become solely cosmetic. -1 if they arent only cosmetic for the reason that tony of a toggle-able bag being just better than an 
untoggle-able one.
basically just bring old dufflebags bag 2k18.

2018-02-02 00:01 UTC, 2Dollarbill commented
I agree with tfw. Dufflebags were mostly cosmetics, the traitor one should remain in tact but I'd rather just remove the weight-down with current dufflebags.

2018-02-03 18:26 UTC, Dudeinyourbackyard commented
+1

2018-02-03 18:26 UTC, dreamcrab commented
+69

2018-02-08 22:43 UTC, Carbonhell requested changes

2018-02-08 22:43 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			for(var/Objs in src.contents)
src. is not required

2018-02-08 22:43 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		adjust_bag()
you made a proc with certain args, then call it with no args?what will you actually use in the proc itself then?

2018-02-08 22:43 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +/obj/item/storage/backpack/duffelbag/proc/adjust_bag(obj/item/W, stop_messages = 0, mob/user)
why do you even need those args?

2018-02-08 22:43 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			if( sum_w_class > max_combined_w_class)
no need for that space between if( and sum_w_class

2018-02-08 22:43 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +				return 0
why are you returning a value if you don't need it, just return

2018-02-13 10:27 UTC, Carbonhell submitted a review, later dismissed

2018-02-13 14:20 UTC, JohnGinnane submitted a review, later dismissed

2018-02-13 14:20 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
If this goes through it doesn't actually adjust the bag?

2018-02-14 11:35 UTC, xTrainx commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
not sure what you mean, it checks if the bag is alredy adjusted, then check if you have enough space inside for it to adjust itself, and if it has, it adjust the bag. In this case, adjusted is a variable

2018-02-14 11:39 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
in that case your indentation looks wrong. The "else" needs to be indented one more tab so that it's related to the "if sum w class..." not the "if not adjusted"

2018-02-14 11:40 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
![image](https://user-images.githubusercontent.com/3355198/36202473-db2a7f68-117b-11e8-9651-cfc84d5b13d3.png)

2018-02-14 12:54 UTC, JohnGinnane commented
@xTrainx did you test this?

2018-02-14 14:02 UTC, Carbonhell submitted a review, later dismissed

2018-02-14 14:02 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
if adjusted = TRUE, this won't run,so you'll never be able to toggle it back.

2018-02-14 14:08 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		if (!adjusted)
move the adjusted = !adjusted out of the else block and after the if/else statement like so:
```
/obj/item/storage/backpack/duffelbag/proc/adjust_bag(mob/user)
	set name = "Adjust Duffel Bag"
	if(do_after(user, 40, target = src))
		if (!adjusted)
			var/sum_w_class = 0
			for(var/Objs in contents)
				var/obj/item/O = Objs
				sum_w_class += O.w_class
			if(sum_w_class > max_combined_w_class)
				to_chat(usr, "<span class='warning'>There are too many things in there to properly adjust the [src]!</span>")
				return
			else
				to_chat(user, "You adjust the [src], [adjusted ? "leaving less space, but making it easier to carry around" : "allowing you to carry more stuff, but slowing you down"]")
				slowdown = adjusted ? adjusted_slowdown : initial(slowdown)
max_combined_w_class = adjusted ? adjusted_max_combined_w_class : initial(max_combined_w_class)
	adjusted = !adjusted
```

2018-02-14 14:17 UTC, Carbonhell commented
doesn't work

2018-02-17 13:34 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			else
I think the flow here will mean this will only trigger when the item isn't adjusted and you are trying to adjust it:

```
if item is NOT adjusted
    if there is not enough space to adjust it
        say can't adjust and return
    else
        say which way you adjust it // You will only ever adjust it in one direction because of the first if statement
```

2018-02-17 13:35 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			else
I think what you need to do is remove this "else" line and then move the following 3 lines down to be beside the `adjusted = !adjusted` so that the code will get to that point regardless of which way you're adjusting it

2018-02-23 12:18 UTC, Carbonhell commented
I think it is better if we close it. If you cannot test your PRs, it is an unnecessary danger on our side to merge it. Try to find a way to test your PRs, i am giving this a deadline set to 10 hours and 42 mins from now, after that it will be denied if not ready and tested

2018-02-23 13:05 UTC, JohnGinnane commented
I'll test this later

2018-02-23 22:46 UTC, Dudeinyourbackyard commented
and so he went on  a quest to test

2018-02-24 13:27 UTC, Pyko1 commented
lets hope the dragons wont eat him

2018-02-24 23:18 UTC, xTrainx commented
sorry for wasting everyone's time,  i have no way to test this, as git wont clone the repo and i have no way to download the folder, so i will process to close this for now

2018-02-24 23:29 UTC, Dudeinyourbackyard commented
the dragons ate him pyko

2018-02-25 11:26 UTC, JohnGinnane commented
i fix))

2018-03-03 18:45 UTC, JohnGinnane commented
@Carbonhell @JohnGinnane this ready

2018-03-03 18:46 UTC, JohnGinnane commented
I've added some videos to the OP so you can see it in action

2018-03-04 05:47 UTC, Dudeinyourbackyard commented
he ficcs

2018-03-05 21:22 UTC, Carbonhell requested changes

2018-03-05 21:22 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			to_chat(usr, "<span class='warning'>There are too many things in the [src] to adjust it, trying removing some!</span>")
try removing some*

2018-03-05 21:22 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		return 1
return TRUE

2018-03-05 21:26 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +			to_chat(usr, "<span class='warning'>There are too many things in the [src] to adjust it, trying removing some!</span>")
🆗

2018-03-05 21:26 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/storage/backpack.dm
> +		return 1
🆗

2018-03-11 11:45 UTC, JohnGinnane commented
@Carbonhell this is ready

2018-03-11 16:27 UTC, Carbonhell approved these changes

2018-03-11 16:27 UTC, merged

2018-03-11 16:27 UTC, Carbonhell commented
41 commits holy fuck

2018-03-11 16:29 UTC, banthebantz commented
how

2018-03-11 16:30 UTC, JohnGinnane commented
Probably because lots of revisions

2018-03-11 16:41 UTC, tortellinitony commented
-1 this makes duffle bags 100% better than every other bag

This is even worse balance.

2018-03-11 16:43 UTC, JohnGinnane commented
too late fam

also technically yes but only because you can change between normal bag capabilities and duffelbag

By default duffelbags have the slow but you can adjust to make the capacity smaller and remove the slow