Spiked bats
HippieStation/HippieStationdeprecated2020 pull request #6545
Opened 2018-02-10 05:19 UTC by asskek

Adds spiked baseball bats.

2018-02-10 07:15 UTC, Carbonhell requested changes

2018-02-10 07:15 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/uplink_kits.dm
> +
?

2018-02-10 07:15 UTC, Carbonhell commented on hippiestation/code/game/objects/items/weaponry.dm
> +		qdel(src)
If you qdel src,the proc will stop running. You must do this at the end, as if it was a return

2018-02-10 07:15 UTC, Carbonhell commented on hippiestation/code/modules/crafting/recipies.dm
> +	subcategory = CAT_WEAPON
?

2018-02-10 16:43 UTC, asskek commented on hippiestation/code/modules/crafting/recipies.dm
> +	subcategory = CAT_WEAPON
Oh, this is a leftover from when I was trying to make it a tablecrafting item. Forgot to remove that.

2018-02-10 16:44 UTC, asskek commented on hippiestation/code/game/objects/items/storage/uplink_kits.dm
> +
Not sure what's happening here, did I delete something on accident?

2018-02-10 16:45 UTC, asskek commented on hippiestation/code/game/objects/items/weaponry.dm
> +		qdel(src)
Alright, I'll do that when I get home from work. Thanks man.

2018-02-11 06:19 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/weaponry.dm
> +		qdel(src)
Pretty sure this is just copy+pasted Spear Code, you nimmy.

2018-02-11 09:08 UTC, Pyko1 commented
would be neat if you could use chem rods, to give the bat a chem inject trait.

2018-02-13 00:01 UTC, Carbonhell requested changes

2018-02-13 00:01 UTC, Carbonhell commented on hippiestation/code/game/objects/items/storage/uplink_kits.dm
> +
no, you added a lot of new lines 4noraisin, delete them and make the file not show here

2018-02-13 00:01 UTC, Carbonhell commented on hippiestation/code/game/objects/items/weaponry.dm
> +		qdel(src)
just doublechecked,i confirm it's potentially buggy behaviour. fix

2018-02-15 11:09 UTC, fluxcapacitor1337 commented
+1

2018-02-15 13:42 UTC, GuyonBroadway commented
>GA's still think thier +1s count here

2018-02-15 17:04 UTC, Pyko1 commented
+1

2018-02-17 13:51 UTC, JohnGinnane commented
@asskek pls

2018-02-20 11:55 UTC, Carbonhell commented
@asskek wake up nerd

2018-02-21 17:05 UTC, bardofrage commented
+1

2018-03-03 21:07 UTC, praisenarsie commented
stale, ping for reopen

2018-03-03 21:48 UTC, Carbonhell commented
Since asskek went MIA i will complete the pr later once i get home

2018-03-04 01:20 UTC, Carbonhell commented
Will fix tomorrow cause web editor bugs out on mobile, i spotted another issue aswell(rods shouldn't be qdelled, they should use use())

2018-03-05 21:20 UTC, Carbonhell commented
Pr cannot be merged due to a conflict we cannot resolve, someone please remake this

2018-03-05 21:20 UTC, closed without merging

2018-03-05 21:29 UTC, JohnGinnane commented
🆗