Armstrong Style
HippieStation/HippieStationdeprecated2020 pull request #6679
Opened 2018-02-17 12:51 UTC by Kawaii-Big-Boss

[Changelogs]: # 
:cl: KawaiiBigBoss
add: Adds Armstrong Style, a new traitor scroll for 14 TC!
fix: Martial Arts code can now actually check for help intent.
soundadd: Added some LISA sound effects
/:cl:

[why]: [Suggested by ExpensiveAntique](https://hippiestation.com/threads/add-armstrong-style.8241/)

Armstrong Style is the more "offensive" counterpart to Sleeping Carp, starting off rather weak but rapidly leveling up the more you use it - to the point to where you have an unbelievably powerful Martial Arts type on your hands.
It does have a few weaknesses. While using Armstrong Style, you lose the ability to pull people entirely - as well as being unable to use guns. You must fight wherever the enemy happens to end up.

Some of the code is taken from the currently test-merged Monk martial art from /tg/station. If this causes merge conflicts, yell at me and I'll see about fixing them.

**Please review this**

2018-02-17 13:20 UTC, Carbonhell commented on code/datums/martial.dm
> +//hippie end
Why dont you just modularize this? It doesnt have to be in this file

2018-02-17 13:20 UTC, Carbonhell commented on code/datums/martial.dm
> +	owner = null // hippie edit: monk code
Monk code? Can you explain

2018-02-17 13:22 UTC, Manly-Dwarf commented on code/datums/martial.dm
> +//hippie end
Have no idea how to do that. Do you mean add it to the armstrong file? (i.e datum/martial_art/armstrong/proc/help_act)

2018-02-17 13:22 UTC, Kawaii-Big-Boss commented on code/datums/martial.dm
> +	owner = null // hippie edit: monk code
Monk code used as a check for ownership. Necessary for the EXP system and whatnot.

2018-02-17 13:24 UTC, Carbonhell commented on code/datums/martial.dm
> +//hippie end
Literally move this code in the hippie file, proc can be moved as it is, the var just do
Your/obj/path
    var/yourvar

2018-02-17 13:27 UTC, Carbonhell commented
Instead of using that owner var that breaks modularity a bit can't you just always pass the mob to your procs as an arg?

2018-02-17 13:28 UTC, Carbonhell requested changes

2018-02-17 13:28 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
So many magic numbers, could you perhaps use defines? #define EXPSLOPPY 4

2018-02-17 13:29 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
Why would spamming defines help? add_exp is pretty straightforward. Besides there's already like 15 defines.

2018-02-17 13:30 UTC, Kawaii-Big-Boss commented on code/datums/martial.dm
> +//hippie end
The var is going to be added by monk code regardless, are you certain you want me to modularize a part that's just going to be moved in later?

2018-02-17 13:30 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
Having a lot of defines does not hurt. In future if the exp gained needs to be changed, it will be very easy

2018-02-17 13:31 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
But it's easy now any way, just change a number. I'm not making a bunch of defines for the applied brute damage, either, that would just be silly.

2018-02-17 13:36 UTC, JohnGinnane commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
Having defines makes it easier to maintain and understand, nobody will be "accidentally changing" anything because it should be caught in code reviews..

2018-02-17 13:48 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +		add_exp(4)
add_exp(4, A)

2018-02-17 13:50 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +/datum/martial_art/armstrong/proc/add_exp(amt)
(amt, mob/owner)

2018-02-17 23:12 UTC, Kawaii-Big-Boss commented
Gonna have to rework Headslide into an actual spell or something, because unfortunately action code is hot garbage.

Besides that I made a couple of changes, fixed some typos and whatnot.

2018-02-17 23:17 UTC, Carbonhell commented on code/datums/martial.dm
> +	owner = null // hippie edit: monk code
yes but when the mirror arrives it wont be mergeable due to this

2018-02-17 23:19 UTC, Carbonhell commented on code/modules/mob/living/carbon/human/species.dm
>  /datum/species/proc/help(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
You may be able to modularize this by doing
/datum/species/help(those args)
Yourcheck
..()

2018-02-17 23:19 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +	set waitfor = FALSE
Why this

2018-02-17 23:21 UTC, Kawaii-Big-Boss commented on code/datums/martial.dm
> +	owner = null // hippie edit: monk code
Want me to mirror the teach/remove proc to the armstrong file, then?

2018-02-17 23:21 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	set waitfor = FALSE
Recycled Plasma Fist code.

2018-02-17 23:22 UTC, Kawaii-Big-Boss commented on code/modules/mob/living/carbon/human/species.dm
>  /datum/species/proc/help(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
Will try immediately, thanks.

2018-02-18 16:31 UTC, Carbonhell submitted a review, later dismissed

2018-02-18 16:31 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
You forgot to give exp for this?

2018-02-18 16:31 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +	add_exp(rand(1,3))
You forgot the second arg dude

2018-02-18 16:31 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +	add_exp(rand(1,3))
Second arg

2018-02-18 16:31 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +	add_exp(rand(2,4))
Second arg

2018-02-18 16:31 UTC, Carbonhell commented on hippiestation/code/datums/martial/armstrong.dm
> +	add_exp(rand(2,4))
Second arg

2018-02-18 16:33 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
What? I changed that up a while ago. It probably got reverted when I tried to add some stuff and suddenly BYOND crashed, so I undid a bunch of changes. Will fix.

2018-02-18 17:49 UTC, Kawaii-Big-Boss commented
Made a bunch of changes. Check the OP for details.

2018-02-19 16:36 UTC, zamolxius commented
awesome

2018-02-19 16:37 UTC, DaydreamPuppeh commented
+1, also add dynamite for this style.

2018-02-19 18:22 UTC, Manly-Dwarf commented on code/modules/mob/living/carbon/human/species.dm
>  /datum/species/proc/help(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
Nope. Doesn't work.
Looks like it'll have to be unmodularized FOREVER

2018-02-19 19:56 UTC, ghost requested changes
Ask for more detail if not clear please.

2018-02-19 19:56 UTC, McBawbaggings commented on code/modules/mob/living/carbon/human/species.dm
> +//hippie edit - martial arts check because this was never implemented. sorry not sorry
@Pyko1 do we enforce the `// hippie edit - reason` standard now or grep replace later?

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(findtext(streak,BUSTER_COMBO))
make these if/else if/else statements
i'd say switch but you comparing strings of different lengths so you'd have to nest them

idea is as follows:
```
if(COMBO_1)
    combo_1(A, D)
else if(COMBO_2)
    combo_2(A, D)
...
else
    return 0
streak = ""
A.hud_used.combo_object.update_icon(streak)
return 1
```

UPDATE: Talked about this in DMs but just putting it here so it's a change I asked for other maintainers to see

Saves a lot of copy pasted code.

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.setDir(i)
https://github.com/HippieStation/HippieStation/blob/27e4596befb785dd2db7f75a7cd2a28f91cd8b68/code/__HELPERS/matrices.dm#L5
Here is a function dedicated to spinning an atom.
This same function is used in the *spin emote.

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 2) // Checks Armstrong's current level.
intentional for nothing to happen, or feedback to occur when you don't meet the requirement?

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
if so, this return is useless

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 5) // Checks Armstrong's current level.
same as above

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
again same as above

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 6 && !D.stat && !D.IsKnockdown())
you get the idea

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/effects/fart.ogg', 100, FALSE, pressure_affected = FALSE)
`playsound()` is local, don't need to run this version?

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
unneeded return

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
unneeded return

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/misc/oof.ogg', 100, FALSE, pressure_affected = FALSE)
`playsound()` is local, don't need to run this version?

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
shouldn't this return the regular version rather than just terminate code?

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(D.stat != DEAD) // Checks if they're dead.
you're copy pasting this code 4 times
make it a proc and call it within all the `act` procs
then handle each action in each act as you would normally

like so:
```
/datum/martial_art/armstrong/help_act(mob/living/carbon/human/A, mob/living/carbon/human/D)
	if(D.stat != DEAD) // Checks if they're dead.
		add_to_streak("E",D)
		return do_regular_act_interaction(A, D)
	else
		//Do the help intent regular action here? is that intended?
```

2018-02-19 19:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +				owner.facial_hair_style = "Broken Man"
what happens if you're female who don't have access to facial hair?

2018-02-19 19:58 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
No. It already returns the regular version.

2018-02-19 19:58 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
:ok_hand:

2018-02-19 19:59 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +				owner.facial_hair_style = "Broken Man"
If I recall, women can still have facial hair forced onto them. Will check later.

2018-02-19 19:59 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +				owner.facial_hair_style = "Broken Man"
if so that's fine, i don't think it's a huge issue because either they can't display or they can and i don't think it'll shit out errors for it

2018-02-19 20:00 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/misc/oof.ogg', 100, FALSE, pressure_affected = FALSE)
It's the same code that's used for antagonist sounds. It's this way so only Armstrong hears this.

2018-02-19 20:00 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/effects/fart.ogg', 100, FALSE, pressure_affected = FALSE)
It's the same code that's used for antagonist sounds. It's this way so only Armstrong hears this.

2018-02-19 20:01 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.setDir(i)
Recycled Plasma Fist code. Will DM.

2018-02-19 20:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(findtext(streak,BUSTER_COMBO))
You sure about this? I can certainly do it, but every other martial art works this way.

2018-02-19 20:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
2bad

2018-02-19 20:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 2) // Checks Armstrong's current level.
Intentional for nothing to happen

2018-02-19 20:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
reee

2018-02-19 20:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 5) // Checks Armstrong's current level.
eeee

2018-02-19 20:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
eee!

2018-02-19 20:04 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
:japanese_goblin:

2018-02-19 20:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 6 && !D.stat && !D.IsKnockdown())
eee!

2018-02-19 20:05 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(D.stat != DEAD) // Checks if they're dead.
It already returns the regular help intent action.

2018-02-19 20:06 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 2) // Checks Armstrong's current level.
either way, don't make it clear combos or let the user they're too "inexperienced" to land the move, both are fair just silent failing sucks for feedback

2018-02-19 20:11 UTC, JohnGinnane commented on code/modules/mob/living/carbon/human/species.dm
> +//hippie edit - martial arts check because this was never implemented. sorry not sorry
Standard is either `//hippie - reason`  or `// Hippie - reason` for single line. If it's gonna be a block it's

```
/proc/thing()
    // Hippie Start - reason
    stuff we do
    // Hippie End
```

2018-02-19 20:21 UTC, ghost commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/effects/fart.ogg', 100, FALSE, pressure_affected = FALSE)
:ok_hand:

2018-02-19 20:22 UTC, ghost commented on hippiestation/code/datums/martial/armstrong.dm
> +		A.playsound_local(get_turf(A), 'hippiestation/sound/misc/oof.ogg', 100, FALSE, pressure_affected = FALSE)
:ok_hand:

2018-02-19 20:28 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 2) // Checks Armstrong's current level.
They are already informed when they unlock the combo, and in the menu where they can check for combos they are told what level they'll need to be to unlock it. Every time you level up, you're given a message.

2018-02-19 20:56 UTC, McBawbaggings commented on hippiestation/code/datums/martial/armstrong.dm
> +	if(current_level >= 2) // Checks Armstrong's current level.
moreso having the combo clear and nothing happening without feedback isn't great

2018-02-19 21:08 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +				owner.facial_hair_style = "Broken Man"
Tested. They still get the beard.

2018-02-19 21:41 UTC, Kawaii-Big-Boss commented
I did what @McBawbaggings suggested. Now merge dis. 👺

2018-02-19 21:44 UTC, praisenarsie commented
eat my shorts

2018-02-19 21:55 UTC, praisenarsie commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
add a higher price for surplus or exclude it from surplus

2018-02-19 21:55 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
Why?

2018-02-19 21:56 UTC, praisenarsie commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
balance

2018-02-19 21:56 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
It already seems totally balanced to me. If I exclude it from surplus, it'd be because you can't use it with guns - something surplus crates tend to give you a lot of.

2018-02-19 21:58 UTC, praisenarsie commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
you can still get implants, spacesuits, soap, etc.

2018-02-19 21:59 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
To be fair you could still get those from the uplink after purchasing the style.

2018-02-19 22:00 UTC, praisenarsie commented on hippiestation/code/modules/uplink/uplink_item.dm
> +	cost = 14
except surplus has the potential to give more in value, just make the surplus like 15 or 16 and i'll be ok with it i guess

2018-02-19 22:04 UTC, praisenarsie submitted a review, later dismissed

2018-02-19 22:42 UTC, bardofrage commented
Sounds cool, +1/

2018-02-19 22:44 UTC, Iamgoofball commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
you lifted this straight from monk code come on dude

2018-02-19 22:44 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
you were already told about this come on dude

2018-02-19 22:45 UTC, GuyonBroadway commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
Get codecuked!

2018-02-19 22:45 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
will credit you immediately in the code, but you didn't respond when I pinged ya telling you about it

sorry mate

2018-02-19 22:45 UTC, Iamgoofball commented on hippiestation/code/datums/martial/armstrong.dm
> +		to_chat(owner, "<span class = 'notice'><b>You level up! Your new level is [current_level].</b></span>")
stolen from monk code

2018-02-19 22:46 UTC, Iamgoofball commented on hippiestation/code/datums/martial/armstrong.dm
> +/obj/effect/proc_holder/spell/targeted/horse_stance/
why did you use spells for this when you could of used an action, rip off monk properly

2018-02-19 22:46 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		to_chat(owner, "<span class = 'notice'><b>You level up! Your new level is [current_level].</b></span>")
do note that monk code was mentioned in a previous commit, but I had to remove it because "modular"

apologies

2018-02-19 22:47 UTC, GuyonBroadway commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
remove it

2018-02-19 22:47 UTC, Iamgoofball commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
thats fair

2018-02-19 22:47 UTC, GuyonBroadway commented on hippiestation/code/datums/martial/armstrong.dm
> +		return
Remove dat too

2018-02-19 22:47 UTC, Iamgoofball commented on hippiestation/code/datums/martial/armstrong.dm
> +		to_chat(owner, "<span class = 'notice'><b>You level up! Your new level is [current_level].</b></span>")
who chewed you out for it

2018-02-19 22:47 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +/obj/effect/proc_holder/spell/targeted/horse_stance/
because action code uses some weird shit with the streak, I tested it before and it just didn't do anything

2018-02-19 22:47 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		to_chat(owner, "<span class = 'notice'><b>You level up! Your new level is [current_level].</b></span>")
carbonhell

2018-02-19 22:51 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +	var/level_cap = 30
@Iamgoofball committed the credit, sorry about this. respond next time when ya can

2018-02-19 22:55 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +		to_chat(owner, "<span class = 'notice'><b>You level up! Your new level is [current_level].</b></span>")
also in the OP, monk code was credited there too
"Some of the code is taken from the currently test-merged Monk martial art from /tg/station. If this causes merge conflicts, yell at me and I'll see about fixing them."
added extra credit in the code so in the future it's obvious what was taken and what wasn't

2018-02-19 23:17 UTC, praisenarsie commented on hippiestation/code/datums/martial/armstrong.dm
> +/obj/effect/proc_holder/spell/targeted/horse_stance/
wtf why are you using spells

2018-02-19 23:17 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/martial/armstrong.dm
> +/obj/effect/proc_holder/spell/targeted/horse_stance/
because action code uses some weird shit with the streak, I tested it before and it just didn't do anything

2018-02-19 23:56 UTC, 2Dollarbill commented
Spaghetti code approved by local Italian headmin. +1.

2018-02-20 00:15 UTC, Kawaii-Big-Boss commented
+2 merge dis

2018-02-20 03:27 UTC, TDcoolguy300 approved these changes
2Dollar says Carbon checked it, merging.

2018-02-20 03:28 UTC, merged