Flyswatter changes.
HippieStation/HippieStationdeprecated2020 pull request #6702
Opened 2018-02-18 04:24 UTC by Thelolswat

BUFF! FLYSWATTER! WHAT MORE COULD YOU WANT

:cl: TheLoLSwat
tweak: After seeing how extremely unbalanced the flyswatter was, we at Nanotrasen have decided to use an all new material for these, ultimately making stronger flyswatters
/:cl:

[why]: # Mostly testing out making PRs with this, bigger projects will come soon

2018-02-18 09:46 UTC, Spankmonkey777 commented
Proud of you

2018-02-18 10:17 UTC, JohnGinnane submitted a review, later dismissed
😅 💦

2018-02-18 10:17 UTC, JohnGinnane commented
I was actually kinda hoping the flyswatter would do extra damage against moths

2018-02-18 10:19 UTC, Carbonhell commented
Sure, +1
I dont really want to see this damaging moths more tho unless it is kept below force 10

2018-02-18 10:30 UTC, JohnGinnane commented
Yeah just more as a meme thing, similar to the laser stunning cats

2018-02-18 14:52 UTC, GuyonBroadway commented
The swatter already does bonus damage to moths. Not as much as it does to flypeople but it does.

2018-02-18 14:56 UTC, GuyonBroadway requested changes

2018-02-18 14:56 UTC, GuyonBroadway commented on code/game/objects/items/weapons/weaponry.dm
> -	force = 1
Tut tut, not modular.

2018-02-18 14:57 UTC, praisenarsie commented
this is redundant anyway since barely anybody plays janitor

2018-02-18 15:03 UTC, McBawbaggings commented
flyswatters are part of the loadout system, making this CHANGE OF THE YEAR

2018-02-18 15:10 UTC, praisenarsie commented
i don't like this anyway since this will allow you to crit flies and moths in 5 hits (or more if they have a bit of armor)

2018-02-18 20:52 UTC, ghost commented on code/game/objects/items/weapons/weaponry.dm
> -	force = 1
[Spank spank spank! Naughty programmer!](https://what.thedailywtf.com/topic/15001/enlightened)

2018-02-19 04:26 UTC, fluxcapacitor1337 commented
+1

2018-02-19 05:13 UTC, bardofrage commented
Congrats on your first PR. +1

2018-02-19 07:11 UTC, Spankmonkey777 commented on code/game/objects/items/weapons/weaponry.dm
> -	force = 1
Amari don't you have fun features to be removing from other servers?

2018-02-19 22:36 UTC, GuyonBroadway requested changes

2018-02-19 22:36 UTC, GuyonBroadway commented on hippiestation/code/game/objects/items/weapons/weaponry.dm
> +/obj/item/weapon/melee/flyswatter
all you need in this entire file is
``/obj/item/weapon/melee/flyswatter
	force = 2``

2018-02-19 22:37 UTC, GuyonBroadway submitted a review, later dismissed

2018-02-19 22:37 UTC, GuyonBroadway commented on code/game/gamemodes/wizard/soulstone.dm
> +/obj/item/device/soulstone/proc/transfer_soul(choice as text, target, mob/user)
why did you commit this? change it back.

2018-02-19 22:37 UTC, Kawaii-Big-Boss commented on code/game/gamemodes/wizard/soulstone.dm
> +/obj/item/device/soulstone/proc/transfer_soul(choice as text, target, mob/user)
Pretty sure he forgot to branch and instead just did it all on his Master.

2018-02-20 16:30 UTC, tortellinitony requested changes
Also, if this is a new file you have added, you need to implement changes in `hippiestation.dme`

2018-02-20 16:30 UTC, tortellinitony commented on code/game/gamemodes/wizard/soulstone.dm
> +/obj/item/device/soulstone/proc/transfer_soul(choice as text, target, mob/user)
Get rid of this change.

2018-02-20 16:30 UTC, tortellinitony commented on hippiestation/code/game/objects/items/weapons/weaponry.dm
> +	force = 2
This and `/obj/item/weapon/melee/flyswatter` are the only lines you need to keep. Get rid of the rest of the lines.

2018-02-23 02:51 UTC, Manly-Dwarf requested changes

2018-02-23 02:51 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/weapons/weaponry.dm
> -/obj/item/weapon
yes I think I see the problem here

2018-02-23 03:01 UTC, Thelolswat commented
Kawaii-Big-Boss helped me through the issues i was having, closing and making a new and improved PR by tommorow

2018-02-23 03:01 UTC, closed without merging