holy shit this commit thing is annoying
HippieStation/HippieStationdeprecated2020 pull request #6723
Opened 2018-02-19 05:54 UTC by zamolxius

[Changelogs]:

:cl: Hacker Gloves
add: Hacker gloves. Makes your hands work as multitools on wires, are also insulated. I'll probably figure out how to add them to the CE's inventory or something.
/:cl:

[why]: Was suggested in accepted suggestions. 
huge kudos to Carbonhell for his help

2018-02-19 06:54 UTC, Spankmonkey777 commented
It is bro but once you get it you'll be able to do it quick as hell... Travis failed let's see why

2018-02-19 07:04 UTC, Spankmonkey777 commented
You have an indentation error, if you click on the "Details" link on travis it'll take you to the attempted builds. You just need to change hackergloves.dm to be evenly spaced and your PR should be running proper.

2018-02-19 09:33 UTC, Carbonhell commented
This will only work on doors! But pmuch anything else requiring a multitool will fail since the checks check for inhand,not gloves. Not sure if it is the behaviour you want

2018-02-19 21:08 UTC, Spankmonkey777 commented
DM compiler version 512.1403
loading hippiestation.mdme
hippiestation/code/game/objects/items/hackergloves.dm:19:error: inconsistent indentation
hippiestation/code/game/objects/items/hackergloves.dm:27:error: inconsistent indentation
hippiestation.mdme.dmb - 2 errors, 0 warnings (2/19/18 6:19 am)
mv: cannot stat ‘hippiestation.mdme.dmb’: No such file or directory
mv: cannot stat ‘hippiestation.mdme.rsc’: No such file or directory


``
/datum/wires/ui_act(action, params) //enormous thanks to Carbonhell for helping enormously with this
    if("pulse")
        var/mob/living/user = usr 
        if(istype(user.slot_gloves, /obj/item/clothing/gloves/color/hacker))
``

``
if(..())
    . = TRUE//So we dont end up pulsing twice if we have both gloves and multitool.
``

2018-02-19 21:08 UTC, Spankmonkey777 commented
Wow I formatted that comment terribly. Point being fix the indent errors on line 19 and 27

2018-02-20 05:05 UTC, zamolxius commented
ill have to redo it anyways,  possibly have to also eddit wires.dmi

2018-02-20 05:22 UTC, zamolxius commented
can i just add a check to wires.dmi, @Carbonhell?  or is that snowflake

2018-02-20 05:22 UTC, zamolxius commented
dm*

2018-02-21 02:36 UTC, Spankmonkey777 commented
That does sound a little snowflakey.. IDK, but the more disconnected the code gets the harder it is for someone new to walk in and modify it.

2018-02-23 10:54 UTC, FantasticFwoosh commented
Petty thieving assistant puts their hacker-man insulated gloves to use.

![I love the powerglove, its so bad.](https://media.giphy.com/media/S2foJZNnwQFxu/giphy.gif)

2018-02-23 12:20 UTC, Carbonhell commented
Wrong way to approach the problem. I would prefer if you made the tool quality check mob proc to check for gloves too, and then just give your gloves the MULTITOOL flag.

2018-02-23 12:21 UTC, Carbonhell commented
The idea got my +1 anyway, next time try to use suggestion forum first tho

2018-02-23 22:43 UTC, Dudeinyourbackyard commented
if it works and is tested, yeah is pretty cool +1

2018-02-24 13:05 UTC, Pyko1 commented
+1

2018-03-02 22:28 UTC, tortellinitony requested changes

2018-03-02 22:28 UTC, tortellinitony commented on hippiestation/code/game/objects/items/hackergloves.dm
> +                var/mob/living/user = usr
fix all of this indentation

2018-03-02 22:28 UTC, tortellinitony commented on hippiestation/code/modules/jobs/job_types/engineering.dm
> +  backpack_contents = list(/obj/item/melee/baton/stungun=1, /obj/item/device/modular_computer/tablet/preset/advanced=1, /obj/item/clothing/gloves/color/hacker=1)
Space this list out into multiple lines to avoid conflicts

2018-03-10 10:31 UTC, praisenarsie commented
stale ass bread, ping a maintainer for reopen

2018-03-10 10:31 UTC, closed without merging