Mime/Clown Pets Addition and Revamp
HippieStation/HippieStationdeprecated2020 pull request #6754
Opened 2018-02-20 09:42 UTC by Spankmonkey777

[Changelogs]: # 

:cl: Spankmaster
add: Added mime cat which lives in mime's office, it can be emagged to become a hostile feral mime cat which will attack anyone but the person who emags it.
add: Puke overlay to emagged clown cat
soundadd: Sound effects for cats.
/:cl:

[why]: # I think you know why.

2018-02-20 09:42 UTC, Spankmonkey777 commented
I also fixed a spelling error on RunTime's emag effect. (GREAT WORK /tg/)

2018-02-20 15:08 UTC, ghost requested changes

2018-02-20 15:08 UTC, McBawbaggings commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +	visible_message("<span class='narsie'>Silent Meow has broken his vow of silence!</span>")
Silent Meow -> [src]

2018-02-20 15:08 UTC, McBawbaggings commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/emagged = FALSE
unneeded since you qdel(src) on emag act

2018-02-20 15:08 UTC, McBawbaggings commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +
empty lines for daysss

2018-02-20 15:08 UTC, McBawbaggings commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	desc = "Punished mime cat.. this one has been tampered with, its vow of silence broken."
"this" -> "This"

2018-02-20 16:26 UTC, tortellinitony commented
The mime should have an invisible pet

2018-02-20 16:27 UTC, McBawbaggings commented
also runtime emag act was done by popnotes, not /tg/
get owned

2018-02-20 19:02 UTC, Spankmonkey777 commented
Tony, the mime's cat is invisible. 

Upon emagging it begins flashing in and out of existence while screeching and attacking people.

2018-02-20 19:05 UTC, Spankmonkey777 commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/emagged = FALSE
Wait which part do you mean is unneeded?

2018-02-20 19:07 UTC, Spankmonkey777 commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	desc = "Punished mime cat.. this one has been tampered with, its vow of silence broken."
I mean grammatically I'm pretty sure it's all one one sentence but I'll change

2018-02-20 19:26 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	var/static/meows = list("hippiestation/sound/creatures/mimeCatScream.ogg", "hippiestation/sound/creatures/mimeCatScream2.ogg")
did you forget to upload these or am I going crazy?

2018-02-20 19:30 UTC, Spankmonkey777 commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	var/static/meows = list("hippiestation/sound/creatures/mimeCatScream.ogg", "hippiestation/sound/creatures/mimeCatScream2.ogg")
Oh fuck I did LOL

2018-02-20 19:32 UTC, Spankmonkey777 commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +	var/static/meows = list("hippiestation/sound/creatures/mimeCatScream.ogg", "hippiestation/sound/creatures/mimeCatScream2.ogg")
There we go.

2018-02-20 20:54 UTC, tortellinitony commented
you can't emag an invisible thing

2018-02-20 21:06 UTC, Spankmonkey777 commented
Tortellini, it's not totally invisible. I redrew the sprite with alpha set to 10, so it's barely visible. You can vaguely, VAGUELY see a silhouette wandering mime's office and it's clickable.

2018-02-20 21:15 UTC, praisenarsie commented on _maps/map_files/HippieStation/hippiestation.dmm
> +/mob/living/simple_animal/pet/cat/mime,
use mob spawners, placing mobs directly onto maps is illegal

2018-02-20 21:15 UTC, praisenarsie commented on hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
> +
what's this blank space, cut it down

2018-02-20 21:31 UTC, GuyonBroadway commented
You can emag n invisible thing actually if you alt+click the tile its on and then click its name in the top right window.

2018-02-20 22:31 UTC, Spankmonkey777 commented on _maps/map_files/HippieStation/hippiestation.dmm
> +/mob/living/simple_animal/pet/cat/mime,
OK... my cat clown was done this way as well, guess I'll have to fix both.

2018-02-20 23:58 UTC, tortellinitony commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/emagged = FALSE
`var/emagged` Remove it, since it has no purpose.

2018-02-21 02:23 UTC, Spankmonkey777 commented on _maps/map_files/HippieStation/hippiestation.dmm
> +/mob/living/simple_animal/pet/cat/mime,
I'm not sure if you're right here, or at least if you are there are a lot of other spawns done in this way. Going through current codebase, this is how Runtime's spawn in CMO office is handled

```
"bLD" = (
/obj/structure/table/glass,
/obj/item/pen,
/obj/item/clothing/neck/stethoscope,
/mob/living/simple_animal/pet/cat/Runtime,
/turf/open/floor/plasteel/barber,
/area/crew_quarters/heads/cmo)
```


This is how my cat's spawn is handled:
```
"aIh" = (
/obj/machinery/light{
    dir = 1
    },
/mob/living/simple_animal/pet/cat/mime,
/turf/open/floor/plasteel/white,
/area/hippie/mime)
```


both are fully functional

2018-02-21 02:24 UTC, Spankmonkey777 commented on _maps/map_files/HippieStation/hippiestation.dmm
> +/mob/living/simple_animal/pet/cat/mime,
I'm happy to change it to having a spawner built-in but it doesn't seem necessary, no one has been able to tell me how to do it or why it is necessary.

2018-02-21 02:24 UTC, Spankmonkey777 commented
And on that note I am pretty sure this PR is ready to go.. can we get some reviews up in heah

2018-02-21 02:35 UTC, Spankmonkey777 commented on hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/emagged = FALSE
Ah fuck you're right, was having a brain fart and thinking this was for clown cat, in which case it def needs the emag verb.

2018-02-21 08:02 UTC, t-f-w commented
+1

2018-02-21 09:43 UTC, Pyko1 commented
+1

2018-02-21 17:05 UTC, bardofrage commented
+1

2018-02-21 17:06 UTC, fluxcapacitor1337 commented
+1

2018-02-21 20:56 UTC, Carbonhell approved these changes

2018-02-21 20:56 UTC, merged