[WIP] Adds 2 new cloaks and adds new function for them
HippieStation/HippieStationdeprecated2020 pull request #6825
Opened 2018-02-24 19:02 UTC by XElectricX

:cl:
add: Black and Unathi (green) cloak
add: Cloaks have 2 small pockets and can quickdraw items
tweak: Cloaks have very slight cold resistance
balance: Cloaks are classified as "normal" size items to prevent infinite storage (cloak inside a cloak)
/:cl:

[why]: FASHION CHOICE! But also so crew members can have the option of wearing a cloak, not just heads. Also allows cloaks to be able to be used as a place for storing small items (like a pistol) and hiding it there.

2018-02-24 19:07 UTC, Carbonhell requested changes
What is in the neck dmi? Can it be modularized?

2018-02-24 19:07 UTC, Carbonhell commented on code/modules/clothing/suits/cloaks.dm
> +	w_class = 3	//Classified as normal instead of small items to prevent infinite storage capabilities!!!
Use defines instead of numbers please, WEIGHT_CLASS_NORMAL

2018-02-24 19:07 UTC, Carbonhell commented on code/game/objects/items/storage/internal.dm
> +/obj/item/storage/internal/pocket/small/cloak
Modularize this code(just put it in a hippie file with similar path to tg, so:
hippiestation/code/game/objects/items/storage/internal.dm

2018-02-24 19:07 UTC, Carbonhell commented on code/modules/clothing/suits/cloaks.dm
> +	cold_protection = CHEST | ARMS | HANDS
Modularize this file(you can have multiple definitions of the same objects,they will be unified at compiletime

2018-02-24 19:07 UTC, Carbonhell commented on code/modules/clothing/suits/cloaks.dm
> +/obj/item/clothing/neck/cloak/black
Modularize(put it in a hippie file with similar path)

2018-02-24 19:09 UTC, ghost requested changes
Please don't modify tg versions of .dmi files since they conflict heavily. Recreate the file in the hippiestation directory and point our versions of clothes to there instead.

2018-02-24 19:09 UTC, McBawbaggings commented on code/modules/clothing/suits/cloaks.dm
> +	w_class = 3	//Classified as normal instead of small items to prevent infinite storage capabilities!!!
Move this change from `code/modules/clothing/suits/cloaks.dm` to a new file: `hippiestation/modules/clothing/suits/cloaks.dm` along with everything else you modified. Add this file to hippestation.dmb.

2018-02-24 19:09 UTC, McBawbaggings commented on code/modules/clothing/suits/cloaks.dm
> +	min_cold_protection_temperature = 257
Magic number, can this be contextualized?
https://github.com/HippieStation/HippieStation/blob/edfcd4580860cd273fc8fa8145bb01df9605e2f2/code/__DEFINES/atmospherics.dm#L102 has some DEFINES you can use.

2018-02-26 04:41 UTC, Dudeinyourbackyard commented
yeah it'd be cool if everything wasn't fucked in code

2018-03-01 03:27 UTC, XElectricX commented
This is not abandoned in case anyone thinks of closing it, heh. Just post-poning it because I am going to add a few things to it.

2018-03-07 15:25 UTC, XElectricX commented
Added the last part I needed. The black and green cloaks will have a 40% chance to spawn in the black, green, and mixed wardrobe lockers.

2018-03-07 15:37 UTC, GuyonBroadway commented
Its worth noting that cloaks got refactored elsewhere to be backpacks with storage and everything. You may need to add "slot = SLOT_NECK" or something along those lines under your cloaks.


And if anyone complains about being able to have to cloaks laugh at them for not wanting to be Johnny two cloaks.

2018-03-07 16:54 UTC, XElectricX commented
I don't remember too well since the last time I worked on it was like mid-February, but I know I did something regarding that so it should not be a problem. 😃

2018-03-09 14:22 UTC, JohnGinnane commented on hippiestation.dme
> +#include "code\modules\mob\living\carbon\human\physiology.dm"
what is this

2018-03-09 14:25 UTC, XElectricX commented on hippiestation.dme
> +#include "code\modules\mob\living\carbon\human\physiology.dm"
Carbonhell said to just ignore it.

2018-03-11 12:33 UTC, JohnGinnane commented
@Carbonhell @XElectricX this is ready now

2018-03-11 16:29 UTC, Carbonhell approved these changes

2018-03-11 16:29 UTC, merged