Adds Carbonhell's Cheap Cuisine to vendors near you!
HippieStation/HippieStationdeprecated2020 pull request #6859
Opened 2018-02-27 01:07 UTC by Kawaii-Big-Boss

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kawaii-Big-Boss
add: Adds Carbonhell's Can of Cheap Cuisine, a mini microwave that makes food for you!
fix: fixes Carbonhell's ego being larger than I'd want
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
It's a goofy item that spices up vendors a bit. Some of the items it gives are more robust than you'd think at first glance (outside of the obvious "poisoning yourself/others to death") while also mocking a Headmin's cooking skills.

It's all banter, but you can't act like once you proudly display fucking _**ham discs**_ on the discord that someone wouldn't eventually mock you for it.

2018-02-27 01:12 UTC, fluxcapacitor1337 commented
+1

2018-02-27 01:14 UTC, Dudeinyourbackyard commented
ham disc update is live

2018-02-27 01:17 UTC, Carbonhell commented
+1

2018-02-27 01:26 UTC, Kawaii-Big-Boss commented
code is good, +3 merge dis

2018-02-27 01:36 UTC, McBawbaggings commented
BBORN 2 LATE TO EXPLORE THE SEAS
BORN 2 EARLY TO EXPLOR THE STARS
BORN JUST IN TIME TO WITNESS HAM DIS

PR OF THE FUCKING YEARS BRO

2018-02-27 01:41 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	list_reagents = list("amanitin" = 5, "soymilk" = 12, "atomicbomb" = 10, "hearty_punch" = 8) //guaranteed to fuck you up, soylent. also surprisingly robust if used before crit
wow!!

2018-02-27 01:43 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	icon_state = "carboncan-open"
add an update 2 the descrpition here about how "It looks spent." or such

2018-02-27 01:43 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	icon_state = "carboncan-open"
k

2018-02-27 01:46 UTC, 2Dollarbill commented
+1, fugged'boutit

2018-02-27 09:51 UTC, JohnGinnane commented on hippiestation.dme
> +#include "hippiestation\code\game\objects\items\carbonhell.dm"
Can you change the filename to something like "cheapcuisine.dm"? It doesn't seem right to name files after players..

2018-02-27 09:53 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 5)
How come there's a 5 here?

2018-02-27 09:53 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 2)
Same here?

2018-02-27 09:59 UTC, JohnGinnane commented
@Kawaii-Big-Boss did you test this?

2018-02-27 10:31 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 5)
that's how tastes work

2018-02-27 10:36 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 5)
Yeah I did some checking and it looks like it's to give some weight to some tastes over others? e.g. for the jelly donut, "jelly" = 1 and "donut" = 3 so you're 3 times more likely to see "You can taste donut"? Should this list contain the names of reagents or can any fluff go here? If there's only one item then isn't the 5 redundant? Does this list combine with the reagents when forming tastes or does it override?

2018-02-27 11:08 UTC, praisenarsie commented on hippiestation.dme
> +#include "hippiestation\code\game\objects\items\carbonhell.dm"
can you not change the filename to something like "cheapcuisine.dm"? It's alright to name files after players.

2018-02-27 11:10 UTC, praisenarsie commented on hippiestation.dme
> +#include "hippiestation\code\game\objects\items\carbonhell.dm"
ok and john and i talked and yeah you should change it to cheapcuisine.dm

2018-02-27 16:21 UTC, dreamcrab commented
lol.......................... +6

2018-02-27 20:05 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 5)
Overrides.

2018-02-27 20:05 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/carbonhell.dm
> +	tastes = list("pure, unadulterated misery" = 2)
Overrides.

2018-02-27 20:13 UTC, Kawaii-Big-Boss commented
I renamed the file and checks are failing, good news.

2018-02-27 20:22 UTC, Kawaii-Big-Boss commented on hippiestation.dme
> +#include "hippiestation\code\game\objects\items\carbonhell.dm"
donezo

2018-02-27 23:19 UTC, Kawaii-Big-Boss commented
Codecheck this now, it's almost been 24 hours and it's got +3

2018-02-27 23:50 UTC, McBawbaggings commented
What happens if you Destroy() the thing as it is cooking?
Does the sound loop runtime? I think the timer should be okay since https://github.com/HippieStation/HippieStation/blob/c58fb1bfc600b72bb52a6c69ffa3a25c39fdbee5/code/datums/callback.dm#L62
It checks to see if the object exists first before actually trying to call the proc. But I still remain unsure for the behaviour of the sound loop.

2018-02-27 23:51 UTC, Kawaii-Big-Boss commented
Haven't checked, but it's the same as the microwave code. Pretty sure it'll be okay.

2018-02-28 10:44 UTC, Carbonhell requested changes

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	if(!used)
Why do you have both used and operating, can't you just use a single var?

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	if(isnull(foodtype))
Move this check in attack_self, nothing should run if you select Cancel in the input call.

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	desc = "It's been used already."
Desc += not = or it will overwrite the normal desc

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	foodtype = GROSS | TOXIC // none of the food is actually real, it's just gross.
Corn potato is tasty you fuck

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	tastes = list("death" = 10)
Lmfao

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	bonus_reagents = list("fartium" = 1, "coniine" = 3)
Coniine is a traitor only chem,with this you will make it available to normal people, are you sure about this choice

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	bonus_reagents = list("impedrezene" = 3, "initropidril" = 1) // chance to have a heart attack and die
Initropidril too? Holy fuck wtf

2018-02-28 10:44 UTC, Carbonhell commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	list_reagents = list("nutriment" = 1, "vitamin" = 1, "soymilk" = 6)
>soymilk
What the fuck do you think i eat

2018-02-28 11:30 UTC, DaydreamPuppeh commented
Merge this shit. Also I am pretty sure carbon also eats chef boyardee.

2018-02-28 11:30 UTC, Pyko1 commented
+1 concept is good, not sure about those 2 traitor chems tho, as someone is just going to just use them in mech syringegun to murderbone.

2018-02-28 15:59 UTC, GuyonBroadway commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	bonus_reagents = list("fartium" = 1, "coniine" = 3)
That's also six times a lethal dose.

2018-02-28 21:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	if(!used)
Unfortunately, no. I use them both because it'd be cleaner.

2018-02-28 21:03 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	desc = "It's been used already."
That's the point. Like how cans replace the desc with "This is rubbish"

2018-02-28 21:03 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	foodtype = GROSS | TOXIC // none of the food is actually real, it's just gross.
no

2018-02-28 21:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	bonus_reagents = list("fartium" = 1, "coniine" = 3)
Coniine is not a traitor only chem, and because it's in bonus_reagents it's not guaranteed to show up.
Coniine can show up in the Botanist's death berries, for instance. If you want me to lower the values, I can.

2018-02-28 21:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	bonus_reagents = list("impedrezene" = 3, "initropidril" = 1) // chance to have a heart attack and die
Random chance, very small amount. Can remove.

2018-02-28 21:04 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	list_reagents = list("nutriment" = 1, "vitamin" = 1, "soymilk" = 6)
I think you eat ham discs.

2018-02-28 21:05 UTC, Kawaii-Big-Boss commented
@Pyko1 Only initropidril is a traitor chem and I can swap it out if needed.

2018-02-28 21:06 UTC, GuyonBroadway commented
Coniine is traitor only jackass!

2018-02-28 21:06 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	if(isnull(foodtype))
You do realize that would require completely rewriting a proc, right?

2018-02-28 21:07 UTC, Kawaii-Big-Boss commented
https://tgstation13.org/wiki/Guide_to_chemistry#Toxins

>death berries

2018-02-28 21:57 UTC, Kawaii-Big-Boss commented
Added Formaldehyde at the request of Guyon and Bantz in place of Coniine, replaced Initropidril with Sulfonal.
Still deadly, but not botany exclusive/traitor chems.

2018-02-28 22:09 UTC, Kawaii-Big-Boss commented on hippiestation/code/game/objects/items/cheapcuisine.dm
> +	if(!used)
ok

2018-03-01 01:23 UTC, Carbonhell approved these changes

2018-03-01 01:24 UTC, merged