[WIP] Changeling Nerf-A-Thon - Because /tg/ won't do it
HippieStation/HippieStationdeprecated2020 pull request #7063
Opened 2018-03-11 22:45 UTC by Kawaii-Big-Boss

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kawaii-Big-Boss
add: Added two new Changeling weapons, the Arm Cannon and Stun Arm
add: Added a couple new stings
del: Carbonhell's desire for modularity
tweak: Made the Tentacle not delete its self on hit, Tentacle now deals decent damage.
balance: Rebalanced Changeling.
balance: Regenerative Stasis replaced with Fake Death, **no longer works when you're actually dead.**
balance: Merges https://github.com/tgstation/tgstation/pull/35958 by Xhuis. Changelings are now inhibited by fire.
tweak: Merged the Organic Space Suit and Chitinous Armor into one item, giving Changeling the ability to walk through space and have decent armor - at the cost of having next to no chemical regen rate.
tweak: Absorption now takes 15 seconds as opposed to 45, requires a dead target.
del: Killed Changeling team objectives
add: Horror Form.
add: Horror Glands, an ability that grants changeling very quick chemical regen and a higher storage rate - but demands that you feed it absorptions or else you'll go crazy.
balance: Changeling weapons now have their prices changed. Armblade is now 4 DNA points instead of 2, for instance.
balance: Lesser Form now knocks you out upon use, to stop people from cheesing stuns/cuffs with it.
balance: Fleshmend is now on par with Armstrong Style's Horse Stance, a longer effect that gives you healing over time as opposed to a quick instaheal.
balance: Last Resort no longer stuns/knocks out people who are nearby when the ability is activated.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

# Changeling is the worst antagonist currently on the server.

I don't mean that they're terrible like Devils were, I mean that they're so ridiculously overpowered that they stand out as direct upgrades from Traitor or potentially even Wizard. Throw in some baffling design decisions, and you have an awful antagonist that is zero fun to play as or against.

## This PR is still a work in progress, do not merge.

**Arm Blade:**
_Price increased to 4_
It's an esword that cannot be detected once the changeling puts it back. The esword is regularly 8 TC out  of 20, but the Armblade is 2 TC out of 10 - which is half the price of the esword for zero downsides.
Fuck off.

**Tentacle:**
_Now deals 15 damage on hit, doesn't delete its self on use_
The Tentacle is bad. It wants to be like the meat hook but instead stands out as a terrible wanna-be that wastes chemicals and DNA points. You couldn't even hit people with it.
In return I made the Tentacle not delete its self on use, gave it 15 brute damage, and made it more like an actual weapon instead of a bad idea.

**Horror Form**
_???_
I still have yet to see how to implement Horror Form. I'm not sure if it'll be a purchasable or if it'll just be a free item that Changeling spawns with. Do note that if I add the latter, **blood tests will be added**.

**Last Resort**
_No longer knocks people out, Headslug health reduced drastically_
Antagonists coming back to life at all is bad. If it's through cloning, that's fine - but if the antagonist has the ability to come back to life with no way to stop it then there's a problem. I changed Regenerative Stasis to compliment this, however Last Resort would very quickly become the next "hurrdurr I'm ling you can't kill me" ability. Last Resort knocking people out immediately already guaranteed a win, and could even knock off people's limbs, making changeling a pain in the ass to fight and impossible for the average grey to beat one in a fight - no matter how robust.
Headslug health was reduced because that thing is way tankier than it has any reason to be, especially thanks to its short sprite making melee weapons difficult to use on it.

**Regenerative Stasis**
_Cannot be used when you're actually dead, eats up 35 chemicals as opposed to 15, cannot be used if you're on fire_
It's amazing that this feature has remained untouched through out all of the changeling reworks. You want your changeling to be hard to kill? Fine. Let's make them not impossible to kill, how about that?
This ability is a huge part as to why Changeling is so overpowered. 
inb4 some ca/tg/irl coder will say "but changeling is supposed to be super overpowered".

**Lesser Form**
_Knocks you out shortly upon use_
Lesser Form gives you temporary invincibility after being used, and lets you scurry through vents to avoid being killed. It immediately removes cuffs a la Biodegrade, with the downside being you might not recover all of your stuff.
Get stunned again in Monkey form? Well, just use the ability again and turn back into a human - then run around and repeat until you somehow escape or get blown up.

**Chitinous Suit**
_Merged Organic Space Suit and Chitinous Armor into one item_
They were both redundant. Nobody purchased the Space Suit because it was entirely dwarfed by the armor, which was cheaper and honestly stupidly powerful. Chitinous Suit is meant to fix that, by giving Changeling the option to roam around space at the cost of the item almost shutting off their chemical regeneration entirely - meaning running around armblading people in a suit of armor is no longer easy mode.

**Fire now inhibits Changelings, by Xhuis**
If a changeling is on fire, several of their abilities will cease to work or will be incredibly weakened. Check out the PR for more information. https://github.com/tgstation/tgstation/pull/35958

**Arm Cannon**
_Gives changeling a gun, to help branch out playstyles_
Currently incomplete, but the item exists to help Changeling branch out its style of play without being too powerful. Essentially a Glock that gobbles up DNA, the Arm Cannon lets changelings shoot people like Traitors, Wizards, etc. already can.
Plus Armblade is boring.

**Stun Arm**
_Gives changeling a stungun, again to help out the poor lad_
Currently incomplete, but it'll be similar to a changeling's own "ebow", except not ranged.

# This PR is currently incomplete. Extra details will be added in the future.

2018-03-12 00:45 UTC, Kawaii-Big-Boss commented
That's all the nerfs for now! It's time for Horror Form.

2018-03-12 02:25 UTC, Kawaii-Big-Boss commented
Added Horror Form. This is pretty much 90% complete.

2018-03-12 02:45 UTC, GuyonBroadway commented
Personally I think part of the ling is its ability to come back from death time after time. 

But I also agree that just "press the magical get back up button" is bad.

What if the ling could put down and "egg" some semi obvious doodad that dies in depressurized areas (no hiding yer egg in space) is about the size of a ayylamo egg and hatches into a ling monkey some time after the ling dies. 

Easy to spot, very fragile but cleverly hidden means a ling CAN come back if the crew isn't on their "Kill the fucking ling" game. 

Or, what if a ling can "last resort" from a dead corpse but the creature that emergest from the corpse isn't a headslug, rather this creature has to scurry off somewhere safe and "evolve" back into a ling by sitting still for a period of time. 

Part of my ALMOST wants a way to infest a human with some kind of ling seed so if the ling dies it can take over the seed host, much like the changeling from the movie. Goons head-spiders make a nice version of this feature. Think of it like a facehugger, if the infested goy doesn't get to surgery in time, or gets killed, the ling takes over and can carry on.

And of course a lot of these abilities would be weakened/negated by fire, keeping in line with the movie.

Also any ca/tg/oy faggot who tells you "The changeling is from prototype, not "The thing"." can go suck a fat one, probably their own "girlfriends" dick.

2018-03-12 02:48 UTC, Kawaii-Big-Boss commented
I really like the "egg" idea, but for now I think sticking with headslug would be for the best.

2018-03-12 02:50 UTC, GuyonBroadway commented
I think making it so a cling can headslug from a corpse so long as the corpse isn't presently on fire is a good mid point.

Means that with some prep a ling can be dealt for good but sloppily catching a ling with a toolbox and a lucky KO won't keep them down for good unless you can catch the slug.

2018-03-12 20:34 UTC, ghost requested changes
hehe no more `<<` 4 u....

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	src << playstyle_string
to_chat()

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		usr << "<span class='warning'>We do not have a form other than this!</span>"
to_chat()

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		usr << "<span class='warning'>Our human form is dead!</span>"
to_chat()

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		T << "<span class='warning'>We are already feasting on a human!</span>"
to_chat()

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		T << "<span class='warning'>There are no humans nearby!</span>"
to_chat()

2018-03-12 20:34 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		lunch << "<span class='userdanger'>[T] takes a huge bite out of you!</span>"
to_chat()

2018-03-12 20:34 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	src << playstyle_string
👺

2018-03-12 20:34 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		usr << "<span class='warning'>We do not have a form other than this!</span>"
👺

2018-03-12 20:35 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		usr << "<span class='warning'>Our human form is dead!</span>"
👺

2018-03-12 20:35 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		T << "<span class='warning'>We are already feasting on a human!</span>"
👺

2018-03-12 20:35 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		lunch << "<span class='userdanger'>[T] takes a huge bite out of you!</span>"
👺

2018-03-12 20:35 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		T << "<span class='warning'>There are no humans nearby!</span>"
👺

2018-03-13 06:24 UTC, Kawaii-Big-Boss commented
sure do love how the only person who reviewed this was bawb
👺

2018-03-13 10:36 UTC, McBawbaggings commented
>reviewed
i looked at it for 5 seconds and did a mass search for `<<` that ain't a review.

2018-03-13 10:42 UTC, GuyonBroadway commented
I'll review it when you say its done.

2018-03-13 16:02 UTC, Armhulen commented
because tg won't do it

but tg will make all of these disgusting verbs into action buttons jesus christ

2018-03-13 16:08 UTC, Armhulen commented
Make sure to add that xhuis did every single bit of original horror form code but you can take credit for updating it

2018-03-13 16:12 UTC, Armhulen commented
and actually it's kind of hilarious you said because tg won't do it while using all of our code just conceptually

2018-03-13 16:35 UTC, Armhulen commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	var/mob/living/simple_animal/hostile/true_changeling/T = usr
don't let me catch you using var/T to define a mob ever again do you hear me

2018-03-13 16:49 UTC, Armhulen commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +/mob/living/simple_animal/hostile/true_changeling/adminbus
no no non no you don't need this admins can just var edit adminbus to TRUE

also adminbus as a var makes the code completely unreadable just saying

i'm not going to remove it because i'm just here to help with action buttons but please don't

2018-03-13 19:59 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +/mob/living/simple_animal/hostile/true_changeling/adminbus
Actually, it starts runtiming if they forget. It's just for convenience.

2018-03-13 20:01 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	var/mob/living/simple_animal/hostile/true_changeling/T = usr
hey, tell that to xhuis

2018-03-14 14:30 UTC, ghost requested changes
Compiler bugs from travis pointed out with how to fix.

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	icon_icon = 'icons/mob/changeling.dmi'
hippiestation/code/modules/antagonists/changeling/horrorform.dm:149:error: 'icons/mob/changeling.dmi': cannot find file
undefined file and shouldn't this be modularised?

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	var/mob/living/simple_animal/hostile/true_changeling/M = owner
stored_changeling is not a variable inherit to datum buttons.
You'll need to do something like `var/stored_ling = M.stored_changeling`

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(!stored_changeling)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:163:error: stored_changeling: undefined var
replace code with the fix above

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(stored_changeling.stat == DEAD)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:166:error: stored_changeling.stat: undefined var
replace code with the fix above

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	stored_changeling.loc = get_turf(M)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:171:error: stored_changeling.loc: undefined var
replace code with the fix above

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	mind.transfer_to(stored_changeling)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:172:error: stored_changeling: undefined var
hippiestation/code/modules/antagonists/changeling/horrorform.dm:172:error: mind.transfer_to: undefined var
replace the code with the fix above, second error should sort itself out by then

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	stored_changeling.Knockdown(100)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:173:error: stored_changeling.Knockdown: undefined var
please i'm losing my voice here!!! i'm just reporting all the compile errors currently outputted.

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		if(H == stored_changeling) // You can't eat yourself.
hippiestation/code/modules/antagonists/changeling/horrorform.dm:192:error: stored_changeling: undefined var
Since this another proc, you'll have to fetch the variable in the same way you did previously

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		if(client && !adminbus)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:216:error: client: undefined var
hippiestation/code/modules/antagonists/changeling/horrorform.dm:216:error: adminbus: undefined var
`M.client` and `!M.adminbus`

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +			var/datum/antagonist/changeling/changeling = mind.has_antag_datum(/datum/antagonist/changeling)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:217:error: mind.has_antag_datum: undefined var
`var/datum/antagonist/changeling/changeling = M.mind.has_antag_datum(/datum/antagonist/changeling)`

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +		if(client && !adminbus)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:230:error: client: undefined var
`M.client` and `!M.adminbus`

2018-03-14 14:30 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +			var/datum/antagonist/changeling/changeling = mind.has_antag_datum(/datum/antagonist/changeling)
hippiestation/code/modules/antagonists/changeling/horrorform.dm:231:error: mind.has_antag_datum: undefined var
`var/datum/antagonist/changeling/changeling = M.mind.has_antag_datum(/datum/antagonist/changeling)`

2018-03-14 14:35 UTC, Carbonhell commented
Dna costs can be modularized, pm me on discord when you can and we will look into fully modularizing this shit

2018-03-14 21:23 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	icon_icon = 'icons/mob/changeling.dmi'
Was made by Armhulen, so no?

2018-03-14 21:27 UTC, Kawaii-Big-Boss commented
Reverted Armhulen's action buttons, they nuked the PR violently.

Will contact him later and reconstruct them.

2018-03-15 02:22 UTC, McBawbaggings commented
i think i broke it trying to fix conflicts
gimme a bit

2018-03-15 02:42 UTC, McBawbaggings commented
in my defense it worked on my machine
![image](https://user-images.githubusercontent.com/15840795/37441658-7625caa6-27fa-11e8-8aba-d51e86dd30e1.png)

2018-03-15 02:54 UTC, Kawaii-Big-Boss commented
I apologize for the horrifying coder sprites that Bawb has committed.

2018-03-15 03:19 UTC, t-f-w commented
overall agree with the changes. seems to be more inspired by the thing (which i am a fan of when it comes to changelings) with more weakness to fire n shit. imo should also use these old but nice horror form sprites that have gone to waste https://hippiestation.com/threads/change-the-changelings-horror-form-sprite.5924/
+1 from me

2018-03-15 04:07 UTC, Dudeinyourbackyard commented
fuck yeah +1

2018-03-15 04:08 UTC, Kawaii-Big-Boss commented
Not a single maintainer has checked this out when it's at +4. A /tg/ headcoder and Bawb had to help me write all of this.

C'mon lads

2018-03-15 04:20 UTC, Kawaii-Big-Boss commented
This PR is done, by the way.

2018-03-15 16:04 UTC, Armhulen commented
you guys made it speed 3

this is incorrect!

also, sorry for nuking ya pr i made this exact same pr (cough but better) and i coded action buttons and it worked fine. must be something inbetween servers that's fucking it up i guess. you should totally take my thingling sprites and action button background sprite, but you'll have to go to our codebase and search the pr and you might get infected with a deadly case of wokebloke

2018-03-15 16:04 UTC, Armhulen commented
er sorry not OUR thingling sprites but the action button sprites

2018-03-15 19:08 UTC, Kawaii-Big-Boss commented
ey no problem armhulen, I'll check out your sprites and see about using them
Thanks for your help.

2018-03-15 19:52 UTC, Carbonhell commented
Giving this my head +1 but i honestly have some doubts on its balance. We can test it out, yeah

2018-03-15 20:07 UTC, Kawaii-Big-Boss commented
The balance is, admittedly, not perfect. I did my best to try and make it so ling isn't overpowered and horror form isn't a get-out-of-jail free card, but in the end ling still may likely be skewed in terms of power.

Their "perfect stealth" is part of what makes them so stupid good.

2018-03-15 20:07 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +				target.take_overall_damage(40)
Does this generate an admin attack log?

2018-03-15 20:08 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +				target.take_overall_damage(40)
If changeling absorb never generated an admin attack log, then no.

2018-03-15 20:08 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/changeling.dm
> +//Kills team objectives by removing the if statement which assigns "forge_team_objectives". This is untested.
Then test it

2018-03-15 20:10 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/changeling.dm
> +//Kills team objectives by removing the if statement which assigns "forge_team_objectives". This is untested.
How? Team objectives are only available with several players on.

2018-03-15 20:10 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	 "teegee coder", "fun destroyer", "lean sipper", "guy who put pineapple on cornpotato pizza", "oversized ham disc", "greyshirt's bane")
Lmfao love it

2018-03-15 20:10 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
Hol up
???

2018-03-15 20:11 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
It just makes the "stored changeling" godmode. The "stored changeling" is inside of the horror form, and invincible while the player controls the not-invincible-horror-form.
When the horror form dies or runs out, the stored changeling plops out and is no longer godmode.

It's old code, god knows why it's designed this way.

2018-03-15 21:02 UTC, JohnMcLaime commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
What if horror form gets into gibbing bomb range?

2018-03-15 21:03 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
The ling dies.

2018-03-15 23:22 UTC, Kawaii-Big-Boss commented
merge dis

2018-03-16 00:20 UTC, JohnMcLaime commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
Dies or gibs

2018-03-16 00:24 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
Haven't checked, but last I remember if the horror form got gibbed so did the changeling. This was oldbase. I'll test in a little bit, but if the ling pops out just fine then I'll fix that.

2018-03-16 00:27 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
Tested, ling was annihilated.

2018-03-16 21:38 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	changeling.isabsorbing = 1
TRUE

2018-03-16 21:38 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	changeling.isabsorbing = 1
Are you sure? Isn't "1" the exact same?

2018-03-16 21:40 UTC, GuyonBroadway commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	changeling.isabsorbing = 1
if you are using Boolean logic only ever use TRUE and FALSE

its a readability thing, a good practise thing and a "so someone else can fix your shit" thing.

2018-03-16 21:41 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +			changeling.isabsorbing = 0
FALSE

2018-03-16 21:41 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
shouldn't you also add a check for isabsorbing, to avoid multiple absorbings?

2018-03-16 21:41 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
That's impossible by the game's own rules.

2018-03-16 21:42 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	changeling.isabsorbing = 1
oke

2018-03-16 21:44 UTC, GuyonBroadway commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
It's a sanity check, if there's one thing that's true about ss13 is that the games own rules quite often stop applying.

2018-03-16 21:45 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
I fail to see why we need to do this, but okay. On it.

2018-03-16 21:46 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/fakedeath.dm
> +	if(user.stat == DEAD || user.on_fire)
why the extra check on user.stat, can't you do it by leaving req_stat set to the default value(CONSCIOUS) or at most set it to UNCONSCIOUS so it can be done as that,too?

2018-03-16 21:48 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/fakedeath.dm
> +	if(user.stat == DEAD || user.on_fire)
What? I'm confused.

This is just a check if the user is on fire or dead, and if so it blocks the sting_action from going through.

2018-03-16 21:48 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +	sleep(5) // So it's not killed in explosion
wut? what explosion? why is this even needed?

2018-03-16 21:49 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +	sleep(5) // So it's not killed in explosion
Not my code, not even sure.

2018-03-16 21:51 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +		S.Knockdown(25)
balance: Last Resort no longer stuns/knocks out people who are nearby when the ability is activated.
Doesn't knockdown knock the borg down..?

2018-03-16 21:51 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +		S.Knockdown(25)
I said people, not borgs. Borgs can effortlessly deal with changelings now, so I felt this would be a bit necessary.

2018-03-16 21:52 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/pizzaslice/cornpotato = 15) //We've solved the mystery!
what the fuck lmao

2018-03-16 21:52 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/pizzaslice/cornpotato = 15) //We've solved the mystery!
![smug_high-res](https://user-images.githubusercontent.com/33744849/37546358-ce6784b8-2942-11e8-8216-c0e625b22f1d.png)

2018-03-16 21:54 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
why checking for client if you are not even using it? rather, check if mind exists, no?

2018-03-16 21:56 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
We do the client check so we can do all the code below. If there's no client then it just behaves like a normal mob.
Honestly, the mind check wouldn't be necessary.

2018-03-16 21:57 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M_turf && M_turf.z == src.z)
>src.z
AAAAAAAAAAA JUST USE Z

2018-03-16 21:57 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	var/mob/living/simple_animal/hostile/true_changeling/M = owner
It's a good thing we have working datum buttons then, eh Bawb?

2018-03-16 21:58 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M.stat == DEAD && (M.client.prefs.chat_toggles & CHAT_GHOSTSIGHT) && !(M in viewers(get_turf(src),null)))
wait what's going on here? why are you showing the message only to dead people?

2018-03-16 21:58 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M.stat == DEAD && (M.client.prefs.chat_toggles & CHAT_GHOSTSIGHT) && !(M in viewers(get_turf(src),null)))
does audible message only show the msg to alive people?

2018-03-16 21:58 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M_turf && M_turf.z == src.z)
IT'S OLD, CRAPPY CODE

2018-03-16 21:58 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(act, m_type, message)
you could just do ..(), no need to repeat the arguments

2018-03-16 21:59 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(1)
what does passing TRUE to death do?

2018-03-16 21:59 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M.stat == DEAD && (M.client.prefs.chat_toggles & CHAT_GHOSTSIGHT) && !(M in viewers(get_turf(src),null)))
Pretty sure, yeah. This is old as fuck code, all the way back from pre-rebase.

2018-03-16 22:01 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	return 1
why returning 1?

2018-03-16 22:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(1)
Isn't there an else clause right below this with a visible message?
I removed some code from this as it caused horror forms (without stored_changelings) to come back to life. Seeing as that's no longer a feature in lings, we don't need it.

2018-03-16 22:02 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	return 1
I dunno.

2018-03-16 22:04 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(adminbus)
is the adminbus var even needed?can't you just always check if there's no internal changeling( since spawned true_changeling s won't have it), thus rendering the need for the adminbus var useless?

2018-03-16 22:07 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code.
...you can't throw it, this is not needed

2018-03-16 22:07 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code.
same for the two other throw shits

2018-03-16 22:08 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			loc.visible_message("<span class='warning'>[loc.name]\'s arm starts stretching inhumanly!</span>", "<span class='warning'>Our arm twists and mutates, transforming it into a tentacle.</span>", "<sp
you sure loc always has a value,ye?

2018-03-16 22:08 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code.
I don't know why this is here, but it was in the original tentacle code.

2018-03-16 22:08 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			loc.visible_message("<span class='warning'>[loc.name]\'s arm starts stretching inhumanly!</span>", "<span class='warning'>Our arm twists and mutates, transforming it into a tentacle.</span>", "<sp
ye

2018-03-16 22:09 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/gun/magic/hippietentacle/shoot_with_empty_chamber(mob/living/user as mob|obj)
mob/living/user as mob|obj is fucking weird syntax
avoid using the "as mob|obj" syntax, it is basically typecasting so use actual typecast like (mob/user) or whatever you need
why can the arg be an obj even, just...do mob/user

2018-03-16 22:10 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	var/obj/item/gun/magic/tentacle/gun //the item that shot it
why do you need this?

2018-03-16 22:12 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/projectile/hippietentacle/proc/reset_throw(mob/living/carbon/human/H)
hold on i'm confused
you can catch this or something?

2018-03-16 22:12 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +				C.apply_damage(I.force, BRUTE, "chest")
is this logged?

2018-03-16 22:13 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/gun/magic/hippietentacle/shoot_with_empty_chamber(mob/living/user as mob|obj)
Tentacle is coded like dogshit, none of this is mine. I had to insert some things midway which is why this is all copypasted.

2018-03-16 22:13 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	var/obj/item/gun/magic/tentacle/gun //the item that shot it
Who the fuck knows

2018-03-16 22:14 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code.
okay this may actually be needed depending on how the fuck this code works

2018-03-16 22:14 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/projectile/hippietentacle/proc/reset_throw(mob/living/carbon/human/H)
No, you can steal items from people. It resets your throw for this reason.

2018-03-16 22:14 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +				C.apply_damage(I.force, BRUTE, "chest")
I dunno.

2018-03-16 22:15 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +		H.reagents.add_reagent("salbutamol", REAGENTS_METABOLISM) // you'll be able to breathe in SPACE, sort've not really.
this doesn't really have the same effect, isn't there any better way to do this

2018-03-16 22:16 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +		H.reagents.add_reagent("salbutamol", REAGENTS_METABOLISM) // you'll be able to breathe in SPACE, sort've not really.
I tested it though. It pretty much keeps you from taking oxygen damage when the suit is on. I could spacewalk forever.

Also, not sure.

2018-03-16 22:17 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code. Keeping it here, too.
this is 100% not related to this code at all,you can remove it

2018-03-16 22:17 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	throwforce = 0 //I don't know why this is here, but it was in the original tentacle code. Keeping it here, too.
Will do.

2018-03-16 22:17 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
why Arm Cannon? why are the letters capitalized, edgy

2018-03-16 22:18 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
I dunno. This message pretty much never shows up unless the game spergs out. Other than that, it's never capitalized.

2018-03-16 22:18 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	caliber = "cornpotato pizza" // Is this var ever actually used?
it is used but not by your code so shrug

2018-03-16 22:19 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/melee/baton/stungun/changeling
tbh this is the idea i like the least... is this actually needed

2018-03-16 22:19 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	shaded_charge = 1
wtf are all those charge vars
can't you just make it not use power at all

2018-03-16 22:20 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +/obj/item/melee/baton/stungun/changeling
No, it's not. But I figured giving changeling a method of stunning would be fair considering they just lost everything. Every other antagonist has a means of stunning, why can't changeling?

2018-03-16 22:20 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	shaded_charge = 1
Aye what the fuck? The charge vars are there to make the thing weaker than your normal stungun.

2018-03-16 22:20 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	missing -= "head" // headless changelings are funny
???

2018-03-16 22:21 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	changeling.purchasedpowers -= src
if(changeling)

2018-03-16 22:21 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	missing -= "head" // headless changelings are funny
This is probably a goof, I saw it in-game the other day where Lisa Green ran around the place as a headless changeling. It won't happen any more, since if you're missing a head you can't regenerate any way.

2018-03-16 22:21 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +		changeling.purchasedpowers -= src
if(changeling)

2018-03-16 22:21 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	changeling.purchasedpowers -= src
Why? Nobody is getting this except changelings.

2018-03-16 22:22 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +		changeling.purchasedpowers -= src
Why? Nobody is getting this except changelings.

2018-03-16 22:26 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +				target.take_overall_damage(40)
can you check?

2018-03-16 22:26 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/changeling.dm
> +//Kills team objectives by removing the if statement which assigns "forge_team_objectives". This is untested.
fair nuff,it should work, but the comment is pretty useless y'know

2018-03-16 22:26 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	user.status_flags |= GODMODE
yeah this is ok

2018-03-16 22:29 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/fakedeath.dm
> +	if(user.stat == DEAD || user.on_fire)
what i mean is, is if(user.stat == DEAD   actually useful? you know,there's that var you set up called req_stat, which i am 90% sure does what this check actually does

2018-03-16 22:30 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +	sleep(5) // So it's not killed in explosion
yeah remove it,seems like a useless delay

2018-03-16 22:30 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +		S.Knockdown(25)
fair nuff

2018-03-16 22:31 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/fakedeath.dm
> +	if(user.stat == DEAD || user.on_fire)
Yeah, it's useful. I don't get what you're goin on about.

2018-03-16 22:31 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
okay that's actually nice but since you're using mind, why not add it to the check
if(client && mind)
pls

2018-03-16 22:31 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/headcrab.dm
> +	sleep(5) // So it's not killed in explosion
ok

2018-03-16 22:31 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M_turf && M_turf.z == src.z)
then FUCKING FIX IT LAZY BASTARD

2018-03-16 22:32 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
but maaan, that's so much work...

2018-03-16 22:32 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M_turf && M_turf.z == src.z)
YOU'RE THE CODE MAID, YOU FIX IT

2018-03-16 22:33 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +				if(M.stat == DEAD && (M.client.prefs.chat_toggles & CHAT_GHOSTSIGHT) && !(M in viewers(get_turf(src),null)))
could you test it, cause from what i can see it may display both messages to alive people and this could be bad

2018-03-16 22:34 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(1)
sorry what do you actually mean? i referred to passing 1 to the parent in
..(1)

2018-03-16 22:34 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	return 1
then find out

2018-03-16 22:35 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +				C.apply_damage(I.force, BRUTE, "chest")
find out

2018-03-16 22:35 UTC, McBawbaggings commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	missing -= "head" // headless changelings are funny
intentional feature of /tg/ lings, their brain so to speak is located in the chest canonically due to ling crabs or some shit?

2018-03-16 22:35 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +		H.reagents.add_reagent("salbutamol", REAGENTS_METABOLISM) // you'll be able to breathe in SPACE, sort've not really.
this also has unintended side effects like healing you from crit though. You know, salbutamol heals ANY sort of oxygen damage.

2018-03-16 22:36 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
if it doesn't show up, just remove it entirely, why keep it lmao

2018-03-16 22:37 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
It's in armblade and tentacle code, that's why.

2018-03-16 22:38 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	shaded_charge = 1
i thought this actually used the chemicals off your tank everytime you used it?

2018-03-16 22:38 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +		H.reagents.add_reagent("salbutamol", REAGENTS_METABOLISM) // you'll be able to breathe in SPACE, sort've not really.
You know this ability drastically slows down their chemical recharge rate, and they could always just fake death to get out of crit, right?

That's hardly an issue.

2018-03-16 22:39 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	missing -= "head" // headless changelings are funny
so wait what does happen for heads here
do they always get regenerated?

2018-03-16 22:39 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +	shaded_charge = 1
What?

2018-03-16 22:40 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/revive.dm
> +	missing -= "head" // headless changelings are funny
No, it's just a little coding joke that lets changelings run around without heads when they revive.

Considering that you can't regenerate when dead any more, this code is now pretty much worthless.

2018-03-16 22:44 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +				C.apply_damage(I.force, BRUTE, "chest")
found out

2018-03-16 22:45 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(1)
Oh. Then I don't know. This is old code, god knows how it even functions

2018-03-16 23:16 UTC, Carbonhell commented
this can't be merged until we untangle tentacle code

2018-03-16 23:16 UTC, Kawaii-Big-Boss commented
Okay. I'll untangle it ASAP.
![smug_high-res](https://user-images.githubusercontent.com/33744849/37548475-91db796c-294e-11e8-90f9-43d904d658e5.png)

2018-03-16 23:23 UTC, Kawaii-Big-Boss commented
>removed tentacle code

**NO CODE NO PROBLEM**
![xjkpyqx](https://user-images.githubusercontent.com/33744849/37548595-6fb727a4-294f-11e8-8c84-3ec58b575440.jpg)

2018-03-16 23:38 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
do it

2018-03-16 23:39 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
I did do it.

2018-03-16 23:42 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/absorb.dm
> +	if(target.stat != DEAD)
ok

2018-03-16 23:49 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
do it

2018-03-16 23:49 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	..(act, m_type, message)
as in, do it

2018-03-16 23:49 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/horrorform.dm
> +	if(client)
fine

2018-03-16 23:54 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +		H.reagents.add_reagent("salbutamol", REAGENTS_METABOLISM) // you'll be able to breathe in SPACE, sort've not really.
fair nuff i guess

2018-03-16 23:56 UTC, Carbonhell commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
it's just a var made to not throw any messages when newed, it isn't needed at all here, and probably not needed in tentacle code aswell
remove it

2018-03-16 23:57 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/antagonists/changeling/mutations.dm
> +			to_chat(loc, "<span class='notice'>Your Arm Cannon begins to shake, it's ready to fire!</span>")
will do

2018-03-17 00:22 UTC, Carbonhell submitted a review, later dismissed

2018-03-17 00:25 UTC, Carbonhell approved these changes

2018-03-17 00:33 UTC, merged