Adds a Spurdo Sparde mask to Loadout, featuring Pyko!
HippieStation/HippieStationdeprecated2020 pull request #7083
Opened 2018-03-13 10:01 UTC by Kawaii-Big-Boss

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kawaii-Big-Boss, Satou Tatsuhiro, JohnFG and Pyko
add: Added a Spurdo Sparde mask to loadout. Check it out!
add: Immortalized our favorite finnish head coder named Pyko into the game.
server: Despite the .json "not being modular", it won't cause conflicts because it's a new file.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
I just wanted something silly to code.

Equipping the Spurdo Sparde mask endows you with the ability to speak "Spurdish", replacing several of your words as well as giving you a thick finnish accent.
(say "bitch" it's hilarious)
Scream sounds are replaced by Pyko's ramblings that I managed to record. They're not amazing, since LoLSwat wouldn't stop ruffling his Doritos/Keyboard when Pyko was talking, damaging the audio for 90% of them. This is what I could safely grab.

Credit to Satou Tatsuhiro for the sprites, JohnFG for cracking a bag bud in the code, and Pyko for his voice.

2018-03-13 10:03 UTC, JohnGinnane commented
@Kawaii-Big-Boss pics pls

2018-03-13 10:04 UTC, JohnGinnane commented
how come no chance of ":DDD!!!" at the end of each message?

2018-03-13 10:06 UTC, Kawaii-Big-Boss commented
Isn't that against the rules? The only reason I didn't add it was because emotes like ":-DDDD" are banned.

2018-03-13 10:07 UTC, JohnGinnane commented
that's a good point, maybe @HippieStation/head should weigh in on it

It would be nice if we could that, it's part of spurdo

2018-03-13 10:11 UTC, Kawaii-Big-Boss commented
added images

2018-03-13 10:21 UTC, JohnGinnane commented
I was hoping for some text :(

2018-03-13 15:58 UTC, Pyko1 commented
Sure, why not. +1

Even tho should had gotten more meaningful ramblings.

2018-03-13 16:02 UTC, Pyko1 commented
Also, we need the random :DDD for the mask, without it its not complete.
Not to mention at least my idea of spurdo is that he actually says the ex dee dee, instead of it being just random emote.

2018-03-13 16:04 UTC, Armhulen commented
>Also, we need the random :DDD for the mask

yikes!

2018-03-13 16:43 UTC, McBawbaggings commented
You could have it like as "colon d d d" as if he's saying it out loud.

2018-03-13 17:16 UTC, Armhulen commented
what bawbaggings said

2018-03-13 21:08 UTC, 2Dollarbill commented
+1 +1 +1

2018-03-13 23:44 UTC, Kawaii-Big-Boss commented
merge dis next, carbrony

2018-03-14 18:23 UTC, praisenarsie commented
fucking do the thing i told you

2018-03-14 18:33 UTC, Pyko1 commented on hippiestation/code/modules/clothing/masks/spurdo.dm
> +		C.say("SUOMI PERKELE") // bawb made me do this
Should be SUOMI PERKELE!

2018-03-14 18:39 UTC, Pyko1 commented on hippiestation/code/modules/clothing/masks/spurdo.dm
> +		M = replacetext(M,"t","j")
seems a bit off, maybe replace "th","d" and "to","do"

2018-03-14 18:40 UTC, Pyko1 commented on hippiestation/code/modules/clothing/masks/spurdo.dm
> +		M = replacetext(M,"ck","gg")
maybe add "ca",ka" here

2018-03-14 19:05 UTC, Pyko1 commented
Also If the wearer hears "finland" or "suomi" he should say "TORILLA TAVATAAN!"

2018-03-14 20:52 UTC, Kawaii-Big-Boss commented
did the requested changes

2018-03-14 21:08 UTC, JohnGinnane commented
I don't feel comfy merging this without pics of the text, it seems risky

2018-03-14 21:08 UTC, JohnGinnane commented
You should be able to pull this branch from your remote repo

2018-03-14 21:57 UTC, Kawaii-Big-Boss commented
Added images

2018-03-14 22:02 UTC, praisenarsie requested changes
change the sound file like i asked you to

2018-03-14 22:03 UTC, Kawaii-Big-Boss commented
no fuck off

2018-03-14 22:04 UTC, praisenarsie commented
change the sound file like i asked you to

2018-03-14 22:05 UTC, Kawaii-Big-Boss commented
no fuck off, it sounds awful when you cut it that short

2018-03-14 22:06 UTC, praisenarsie commented
@Pyko1 do us both a favour and record yourself saying fucking hell

2018-03-14 22:07 UTC, DaydreamPuppeh commented
Fugging hell

2018-03-14 22:11 UTC, JohnGinnane commented
Translation isn't good or true to spurdo imo, "th" isn't handled correctly at all so it just looks like dutch at times

2018-03-14 22:12 UTC, Kawaii-Big-Boss commented
Figured out the problem causing that, fixing.

2018-03-14 22:29 UTC, JohnGinnane commented
Video of the sound playing: https://streamable.com/kvpvz

The pitch range is really low to normal which is weird, idk exactly how to fix it

2018-03-14 23:21 UTC, JohnGinnane commented on hippiestation/code/modules/clothing/masks/spurdo.dm
> +		M = replacetext(M,"t","j")
https://gist.github.com/JohnGinnane/7980052a6bc5c48c5d597ef98f5c9ad3#file-sprudo_translator-ntsl-L18

2018-03-14 23:59 UTC, Pyko1 commented
should be more like
`Whad dhe fugg did you jusd fugging say aboud me, you liddle bidgh? i’ll have you gnow i graduaded :DD dob of my glass in dhe navy seals, and i’ve been involved :DD in numerous segred :DD raids on al-quaeda, and i have over 300 gonfirmed :DD gills. I am drained :DD in gorilla warfare and i’m dhe dob sniber in dhe endire us armed :DD forges. You are nodhing do me bud jusd anodher darged :DD. I will wibe you dhe fugg oud widh bregision dhe liges of whigh has never been seen before on dhis eardh, marg my fugging words. You dhing you gan ged :DD away widh saying dhad shid do me over dhe inderned? dhing again, fugger. As we sbeag i am gondagding my segred :DD nedworg of sbies agross dhe usa and your ib is being draged :DD righd now so you bedder brebare for dhe sdorm, maggod. Dhe sdorm dhad wibes oud dhe badhedig liddle dhing you gall your life. You’re fugging dead, gid. I gan be anywhere, anydime, and i gan gill you in over seven hundred :DD ways, and dhad’s jusd widh my bare hands. Nod only am i egsdensively drained :DD in unarmed :DD gombad, bud i have aggess do dhe endire arsenal of dhe unided :DD sdades marine gorbs and i will use id do ids full egsdend do wibe your miserable ass off dhe fage of dhe gondinend, you liddle shid. If only you gould have gnown whad unholy redribudion your liddle “glever” gommend was aboud do bring down ubon you, maybe you would have held your fugging dongue. Bud you gouldn’d, you didn’d, and now you’re baying dhe brige, you goddamn idiod. I will shid fury all over you and you will drown in id. You’re fugging dead, giddo.`

2018-03-15 03:22 UTC, t-f-w commented
fugg :DDD +1

2018-03-15 04:00 UTC, fluxcapacitor1337 commented
+1

2018-03-15 05:41 UTC, Dudeinyourbackyard commented
incredible
+1

2018-03-15 11:58 UTC, JohnGinnane commented
@Kawaii-Big-Boss if you fixed the "t" -> "d" can you update pics with more text on them? Would like to see it in action before merging

2018-03-15 19:32 UTC, Pyko1 commented
I think the t -> j makes it bad as it is now

2018-03-15 19:32 UTC, Kawaii-Big-Boss commented
Want to replace t -> j with something else?

2018-03-15 19:35 UTC, JohnGinnane commented
"t" -> "d" like the original

2018-03-15 19:35 UTC, JohnGinnane commented
https://gist.github.com/JohnGinnane/7980052a6bc5c48c5d597ef98f5c9ad3

2018-03-15 19:36 UTC, Pyko1 commented
I wonder if it would work with just t=d, c/k=g, ed = ed :DD (after conversion), like in my copy paste

2018-03-15 19:36 UTC, JohnGinnane commented
![image](https://user-images.githubusercontent.com/3355198/37487020-2d1028a0-2888-11e8-98d1-32511f8cde56.png)

this is from when I originally wrote the NTSL at like 4am and it was wonderful

2018-03-15 19:39 UTC, Pyko1 commented
I generally just want it to work mostly like
https://lingojam.com/SpurdoTranslator

2018-03-15 19:44 UTC, Pyko1 commented
the :DDD is definitely needed for spurdo

2018-03-15 20:19 UTC, Kawaii-Big-Boss commented
I fixed T-to-J. Can we merge this yet

2018-03-15 20:20 UTC, JohnGinnane commented
homey i still want pics((

2018-03-15 20:38 UTC, Kawaii-Big-Boss commented
here's your pictures of spiderman
![johnfg](https://user-images.githubusercontent.com/33744849/37489831-3eef4894-286f-11e8-853c-6b960fd58cd0.png)

2018-03-16 02:02 UTC, Kawaii-Big-Boss commented
@praisenarsie dismiss your review lardass

2018-03-16 08:33 UTC, JohnGinnane commented on hippiestation/code/modules/clothing/masks/spurdo.dm
> +		if(prob(50))
I don't think we need the fluff at the end, people are gonna do that if they have spurdo mask anyway I think. But for the emotes I suggest this as it's more variable and looks a little more natural:

```
if (prob(50))
	M += " :"
	if (prob(50))
		M += "-"

	var/smiles = rand(3, 8)
	
	while (smiles > 0)
		M += "D"

	if (prob(50))
		var/exclaim = rand(3, 8)

		while (exclaim > 0)
			M += "!"
```

2018-03-16 08:45 UTC, JohnGinnane submitted a review, later dismissed
Looks alright to me

2018-03-16 21:26 UTC, Kawaii-Big-Boss commented
@praisenarsie DISMISS YER FECKIN REVIEW YE SCOTT WEASEL

2018-03-17 00:41 UTC, praisenarsie commented
literally refusing to do one thing i asked

change a soundfile, you are lucky i haven't closed your pr yet due to your insolence.

2018-03-17 00:42 UTC, Kawaii-Big-Boss commented
I explained why I'm not going to do that, and you refused. The soundfile is cut off short and it sounds awful. Fuck off.

2018-03-17 00:45 UTC, praisenarsie approved these changes

2018-03-17 00:46 UTC, praisenarsie commented
don't make me deal with your shit behavior in the future

2018-03-17 00:46 UTC, merged