Adds four new butt related traits.
HippieStation/HippieStationdeprecated2020 pull request #7203
Opened 2018-03-21 23:28 UTC by GuyonBroadway

:cl: GuyonBroadway
add: Added the iron butt trait, you are less likley to lose your butt when farting.
add: Added the volatile butt trait, your butt is more likely to go supernova or fly off into the galaxy.
add: Added the Involuntary flatulence trait, you will fart at random intervals and occasionally superfart.
add: Added the Small anal cavity trait, your butt has one less inventory slot than normal.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

2018-03-21 23:28 UTC, Kawaii-Big-Boss commented
fart

2018-03-22 01:04 UTC, DaydreamPuppeh commented
Weren't traits disabled? +1

2018-03-22 09:40 UTC, McBawbaggings commented
not disabled, modularised and running our own trait system.

2018-03-22 10:28 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +	medical_record_text = "Patient has a muscular spasam in their rectal sphincter, gaseous discharge may occour."
"spasm"

2018-03-22 10:29 UTC, JohnGinnane commented on hippiestation/code/datums/traits/good.dm
> +	desc = "Your butt is stronger than other butts, it will be half as likley to come off when farting."
"likely"

2018-03-22 10:29 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +			trait_holder.adjustBruteLoss(rand(2,6))
ouch

2018-03-22 10:30 UTC, JohnGinnane requested changes
just some minor typos

2018-03-22 11:24 UTC, ghost requested changes
carbon hate the implicit src

2018-03-22 11:24 UTC, McBawbaggings commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
implicit src

2018-03-22 11:24 UTC, McBawbaggings commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
implicit src

2018-03-22 12:27 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
we should get an angry pepe frog, make it italian and have a speech bubble "src reeeeeeee"

2018-03-22 12:28 UTC, JohnGinnane commented
@GuyonBroadway didn't you mention about putting the fart sounds onto the butts?

2018-03-22 12:30 UTC, GuyonBroadway commented
Gon do dat in another PR. Atomicness and whatnot

2018-03-22 12:36 UTC, JohnGinnane commented
cool but also good

2018-03-22 13:07 UTC, GuyonBroadway commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
its how tg does things to directly remove traits. 
https://github.com/HippieStation/HippieStation/blob/master/code/datums/traits/negative.dm#L59

2018-03-22 13:58 UTC, McBawbaggings commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
those aren't functionally the same are they?

2018-03-22 14:01 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
I think they actually do qdel(src):

https://github.com/HippieStation/HippieStation/blob/master/code/datums/traits/negative.dm#L59

2018-03-22 14:04 UTC, McBawbaggings commented on hippiestation/code/datums/traits/negative.dm
> +		src.remove()
further to add: remove() is called during Destroy() which i think qdel() calls

2018-03-22 22:37 UTC, Carbonhell commented
>butt in the pr title
automatic +1

2018-03-22 22:52 UTC, Dudeinyourbackyard commented
gut +1

2018-03-22 22:56 UTC, t-f-w commented
aye +1

2018-03-24 11:33 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +	desc = "A spasam in the patients sphincter will cause them to uncontrollably fart at random intervals."
bruh this still a typo?

2018-03-24 11:33 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +	desc = "Muscular contractions cause the patients anal cavity to be undersized."
"patient's"

2018-03-24 11:35 UTC, JohnGinnane requested changes

2018-03-24 11:35 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +	desc = "A spasam in the patients sphincter will cause them to uncontrollably fart at random intervals."
oh there was two of them

2018-03-24 11:35 UTC, JohnGinnane commented on hippiestation/code/datums/traits/negative.dm
> +	desc = "A spasam in the patients sphincter will cause them to uncontrollably fart at random intervals."
my b

2018-03-24 16:59 UTC, Pyko1 commented
+1

2018-03-25 03:42 UTC, McHatters commented
+1

2018-03-26 09:29 UTC, JohnGinnane approved these changes

2018-03-26 09:49 UTC, merged