Adds a new trait: Super lungs
HippieStation/HippieStationdeprecated2020 pull request #7301
Opened 2018-03-27 16:38 UTC by Jujumatic

Bruhhhhh what is all this weird fancy shit i dont understand any of this lmao

anyway this thing adds a new trait that lets you scream twice as loudly as normal. it costs no points but is balanced out by giving you double the normal oxyloss damage from screaming.

added cause i remember some guy saying they wanted it and because le meme ecks dee

2018-03-27 16:47 UTC, GuyonBroadway requested changes
pretty good, just needs a little thing.

2018-03-27 16:47 UTC, GuyonBroadway commented on hippiestation/code/datums/traits/neutral.dm
> +/datum/trait/super_lungs/add()
You'll want to add a "/datum/trait/super_lungsremove()" c that resets these values to default, You can see how to do that here.

https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/datums/traits/good.dm#L15

2018-03-27 16:48 UTC, Jujumatic commented
oh SHIT whoops

2018-03-27 16:59 UTC, Jujumatic commented
oh hey look, the thing updated on its own

2018-03-27 17:06 UTC, GuyonBroadway submitted a review, later dismissed
Looks good codewise.

2018-03-27 17:43 UTC, Pyko1 commented
we need this for farts as well!

Anyways +1

2018-03-27 17:45 UTC, Jujumatic commented
@Pyko1 soonTM

that should be easier for me now that i kinda got the hang of the traits system with this pr

2018-03-27 17:56 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +	desc = "Your extra powerful lungs allow you to scream much louder than normal."
I think this definitely needs a "at the cost of more oxygen damage"

2018-03-27 17:57 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>You feel unable to scream as loudly as before.</span>"
I would maybe saying "You feel as if your screaming as returned to normal" because without context this could be interpreted as your scream is weaker ("before" being considered normal, rather than what's intended, loud)

2018-03-27 19:18 UTC, JohnGinnane submitted a review, later dismissed
looks great

2018-03-27 19:46 UTC, fluxcapacitor1337 commented
+1

2018-03-27 19:47 UTC, Dudeinyourbackyard commented
+1 big meme if true

2018-03-27 20:21 UTC, Jujumatic commented
shit my fucking around with github is fucking up this pr, apologies while i try and unfuck everything

2018-03-27 22:08 UTC, JohnGinnane submitted a review, later dismissed

2018-03-29 20:19 UTC, JohnGinnane approved these changes

2018-03-29 20:19 UTC, merged