Tourettes stun duration reduced from 10 seconds to 2 seconds
HippieStation/HippieStationdeprecated2020 pull request #7312
Opened 2018-03-27 20:31 UTC by Jujumatic

After managing to somehow decontaminate the master branch for long enough to put this, it's finally here. I've learned branch management the hard way.

Stun time for Tourettes has been reduced from 10 seconds to 2 seconds, because these poor fucking souls are already suffering enough if they have Tourettes to begin with. The stun spam is already bad enough yo

2018-03-27 20:32 UTC, JohnGinnane commented
hhhhhhhhhhhhholy fuck thank you

2018-03-27 21:36 UTC, JohnGinnane requested changes

2018-03-27 21:36 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +-/* Currently, there are none */
this dash shouldn't be here

2018-03-27 21:39 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +-/* Currently, there are none */
how did that get there lmao

2018-03-28 07:20 UTC, Jujumatic commented
Is fixed aaaaaaaa

2018-03-28 14:50 UTC, Pyko1 commented
sure why not

2018-03-29 20:21 UTC, JohnGinnane commented
oops, didn't mean to add that tag

do this need head input as it's maybe balance? @HippieStation/head

2018-03-30 22:47 UTC, JohnGinnane commented
I think I broke this PR, would you mind doing it up again?

2018-03-30 23:47 UTC, Spankmonkey777 commented
Good work bro

2018-03-30 23:48 UTC, Spankmonkey777 commented
To juju for his PR I mean, proud of u ducky boy

2018-03-31 00:09 UTC, Jujumatic commented
oof fuck what happened

2018-03-31 00:09 UTC, Jujumatic commented
also ty dude

2018-03-31 00:20 UTC, Jujumatic commented
Unfucked everything this should be ready to merge now

2018-04-01 20:50 UTC, JohnGinnane approved these changes

2018-04-01 20:51 UTC, merged