*STILL TESTING - DO NOT MERGE* Adds Vibrancy Trait
HippieStation/HippieStationdeprecated2020 pull request #7383
Opened 2018-03-31 12:32 UTC by Jujumatic

Added a new trait: Vibrancy

This is supposed to be like the opposite of the Monochromacy trait - it will make you see colours far more brightly and vibrantly than normal. It'll be a neutral trait cause fuck needing points to get traits lmao. Also it will be overridden by Monochromacy if you pick both at the same time because you can't see brighter colours if you can't see colours

Why - cause extra colour is cool as heck yo

2018-03-31 12:52 UTC, JohnGinnane commented
don't forget to add pics

2018-03-31 14:52 UTC, ghost requested changes

2018-03-31 14:52 UTC, McBawbaggings commented on hippiestation/code/datums/traits/neutral.dm
> +/datum/trait/vibrancy/add() = /datum/client_colour
this isn't valid
make this:
`/datum/trait/vibrancy/add()`

2018-03-31 14:52 UTC, McBawbaggings commented on hippiestation/code/datums/traits/neutral.dm
> +		sleep(20) //Don't want the two messages to pop up instantly, muh immershun
firstly, the sleep shouldn't be used, and even if you were to use it, it should be before the to_chat() code

2018-03-31 14:55 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +		sleep(20) //Don't want the two messages to pop up instantly, muh immershun
After sleep it triggers the remove trait which activates the lose text. The to_chat is just to tell the person that having monochromacy and vibrancy at the same time won't work

2018-04-01 05:33 UTC, Spankmonkey777 commented
Honestly a really cool idea/PR for someone who is just learning to code. A+

2018-04-01 20:35 UTC, Jujumatic commented
Closing this pr because the vibrancy dream is dead (for now) opening a new pr as I have some other things instead

2018-04-01 20:35 UTC, closed without merging