Adds Old School Vision trait, Inverted Colour Vision and adds some leftover code from my attempt at the Vibrancy trait
HippieStation/HippieStationdeprecated2020 pull request #7412
Opened 2018-04-01 20:45 UTC by Jujumatic

Hey there, I just got some new colour schemes out.

Old School Vision is like Monochromacy except it's *actually* black and white, instead of some weird shitty sepia-esque thing.

Inverted Colour Vision reverses the colours of red and blue, so wherever you see red, you see blue instead. Couldn't change green cause it caused some really weird effects on the colour scheme, mainly turning everything pink and stuff.

I also made sure to set priorities on these colour schemes to prevent any potentially horrible things happening because only one set of colours can be active at a time.

I've also left the code in for the Vibrancy trait I tried making in my previous pr in case it can be revisited sometime in the future. I made sure to have it disabled because it's obviously not working properly right now. I also have put some leftover code from my faffing around into the client_colours.dm in case anyone finds a use for it.

2018-04-01 20:45 UTC, JohnGinnane commented
\>no pics
to what end

2018-04-01 20:47 UTC, JohnGinnane commented on hippiestation/code/modules/client/client_colour.dm
> +	priority = 2
Like with monochrome, I think you'll want this to be INFINITY so that things like blood don't override it

2018-04-01 20:47 UTC, JohnGinnane commented on hippiestation/code/modules/client/client_colour.dm
> +	priority = 2
Same goes for the other colours

2018-04-01 20:51 UTC, Jujumatic commented on hippiestation/code/modules/client/client_colour.dm
> +	priority = 2
Problem is you can pick multiple of these traits, so then which colour will appear? If it's all on priority infinity then... idek what could happen

2018-04-01 20:53 UTC, JohnGinnane commented on hippiestation/code/modules/client/client_colour.dm
> +	priority = 2
Oh good point, I think do `INFINITY - 1`, `INFINITY - 2`, etc. then, so it'll still be on top

2018-04-02 09:39 UTC, JohnGinnane requested changes

2018-04-02 09:39 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +	gain_text = "<span class='notice'>...Huh? You can't see colour anymore!"
Missing closing tag and same below

2018-04-02 09:43 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	gain_text = "<span class='notice'>...Huh? You can't see colour anymore!"
`lose_text = "<span class='notice'>You can see colour again!"`

`gain_text = "<span class='notice'>You feel like you're seeing colours differently.</span>"
lose_text = "<span class='notice'>You feel like you're seeing colours normally again.</span>"`

2018-04-02 09:45 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	gain_text = "<span class='notice'>...Huh? You can't see colour anymore!"
ah whoops im stoopid lmao

2018-04-02 12:04 UTC, Jujumatic commented
fixed, for some reason the changes wouldn't go into the remote even though it said they were getting pushed

2018-04-02 20:52 UTC, Jujumatic commented
this is fixed and ready to merge

2018-04-06 07:46 UTC, JohnGinnane commented
need @HippieStation/head input pls

2018-04-06 07:48 UTC, JohnGinnane requested changes

2018-04-06 07:48 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +	desc = "Did you get stuck in an old video recorder? You can only see in black and white!</span>"
Don't need the span here

2018-04-07 18:32 UTC, Carbonhell commented
fix please

2018-04-07 19:40 UTC, Jujumatic commented
fixed

2018-04-08 12:10 UTC, JohnGinnane approved these changes
Code looks good

2018-04-08 12:26 UTC, Carbonhell commented
Shit i forgot,+1

2018-04-09 07:56 UTC, JohnGinnane approved these changes

2018-04-09 07:56 UTC, merged