Adds a new trait, Advanced Autism
HippieStation/HippieStationdeprecated2020 pull request #7452
Opened 2018-04-03 20:52 UTC by Jujumatic

This is a negative trait that gives you +1 points, it gives you 2 brain damage every minute so look out and keep that mannitol close by! Added cause we need more ways to bring brain damage into relevancy since it's so rare to get.

2018-04-03 21:21 UTC, Manly-Dwarf commented
Name it something like "Delayed Brainrot" or "Alzheimer's" or something instead, as this isn't really "autism" as much as it is the brainrot disease.

2018-04-03 21:23 UTC, Jujumatic commented
It's autism that's become so powerful it's destroying your brain slowly

2018-04-03 21:25 UTC, Kawaii-Big-Boss commented
It's a lazy excuse for an autism joke, honestly. It'd be executed better if it gave you more effects outside of just gradual brain damage.

The gradual brain damage is already a disease in the game called Brainrot, so just stick with the theme for this one I'd say.

2018-04-03 21:32 UTC, Pyko1 commented
sure, why not +1

2018-04-03 21:48 UTC, Kawaii-Big-Boss commented
Also 2 brain damage every minute is extremely weak, especially because you can just chug a shitton of mannitol to negate the damage entirely. Make the damage faster or harsher.

2018-04-03 23:56 UTC, Spankmonkey777 commented
I agree with KBB, the straight up jokey shit needs to be either executed somewhat well or changed to be more tied into the space setting. We're getting PRs for "nigium" chems and "autism" traits, and I know I'm the last guy to talk about this but there is a value to keeping the immersion.

2018-04-04 01:21 UTC, GuyonBroadway commented
This is just a more complicated version of a tg negative trait.

https://github.com/HippieStation/HippieStation/blob/57b20e2d599999f0ff95980c6827fde97419e63b/code/datums/traits/negative.dm#L83

2018-04-04 01:23 UTC, Jujumatic commented
what if i made it so this trait also makes you permanently retarded as long as you have this trait, and it never goes away even with mannitol till the trait is somehow gone?

2018-04-04 14:44 UTC, Jujumatic commented
how about NOW

2018-04-04 14:46 UTC, McBawbaggings commented
the tramua should be gained on add
brain damage part should be in process

2018-04-04 14:49 UTC, Jujumatic commented
@McBawbaggings will it keep recalling addtimer in on_process if I remove the addtimer in the braindamage proc?

2018-04-04 22:56 UTC, fluxcapacitor1337 commented
Gonna chime in here and agree with KBB.

2018-04-05 13:17 UTC, Jujumatic commented
revamped this thing, come check it out

2018-04-05 16:17 UTC, Manly-Dwarf requested changes

2018-04-05 16:17 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
rename it you lazy nard

2018-04-05 18:48 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
gimme a new name then

2018-04-05 20:42 UTC, Dudeinyourbackyard commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
chronic brainrot

2018-04-05 20:49 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
what about calling it chronic retardifying brainrot

2018-04-05 20:52 UTC, Kawaii-Big-Boss commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
just call it chronic brainrot, delayed onset brainrot, something other than fucking "hurrdurr autism joke"

brainrot its self is already retardifying, calling it "chronic retardifying brainrot" is both redundant and a mouth full.

make a proper autism joke you nerd

2018-04-05 20:53 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
no u

2018-04-05 20:58 UTC, Dudeinyourbackyard commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
why are you so bad at NAMES

2018-04-05 20:58 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
I SUCK AT NAMES OK IM SORRY

2018-04-05 20:58 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	name = "Advanced Autism"
CRIE

2018-04-05 21:02 UTC, Jujumatic commented
RENAMED BOIS

2018-04-05 21:04 UTC, Dudeinyourbackyard commented
cool

2018-04-05 21:05 UTC, Jujumatic commented
this legit took me like 5 years to make pls let it go thru

2018-04-06 08:05 UTC, JohnGinnane commented
FYI, PR https://github.com/HippieStation/HippieStation/pull/7448 makes this PR kind of one sided. There's no risk with pumping yourself full of mannitol and so people can get themselves a virtually free imaginary friend

2018-04-10 17:55 UTC, Jujumatic commented
the pr mentioned has since been changed, originally it was to make mannitol cure severe traumas but i have since made a new chemical to do that, which is gated behind uranium and plasma instead

2018-04-11 13:55 UTC, JohnGinnane commented
Cool, although I wonder if anybody would pick the trait and then rush science to get the static spawn uranium to nullify the effects anyway 🤔

2018-04-11 13:57 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>You no longer feel as if you're getting dumber..</span>"
Should this only have one fullstop or should the gain text have two or is this all intentional?

2018-04-11 13:58 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +		H.adjustBrainLoss(rand(0.25, 1))
Does rand return whole numbers only or decimals?

2018-04-11 13:58 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>You no longer feel as if you're getting dumber..</span>"
oof, i missed that one

2018-04-11 13:58 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +		H.adjustBrainLoss(rand(0.25, 1))
the rand returns decimals too, as long as it's 0.25 or above. anything lower than 0.2 doesn't get registered

2018-04-11 14:03 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +			searching = FALSE
I think we need to make sure to always set this flag to "FALSE" when we call "get_trauma" otherwise it only searches once:

* process() is called for the first time
* the holder doesn't have the trauma and we're not searching for a friend
* we say we're searching for a friend and add a callback to get_trauma() to fire in 2 minutes
* during these two minutes we gain more brain damage, no problems here
* after 2 minutes get_trauma is called
* this checks if the holder has an imaginary friend
* If no imaginary friend not then try give it to them and say we're no longer searching
* If holder has imaginary friend then nothing happens

If you give someone the imaginary friend trauma (and set `has_friend = TRUE` and `searching = FALSE`), does that prompt ghosts for the role? What happens if after we give them the trauma not nobody answers?

2018-04-11 14:04 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +		H.adjustBrainLoss(rand(0.25, 1))
Cool, I'm not familiar with rand, so I wasn't sure

2018-04-19 11:20 UTC, Carbonhell commented
is this stale

2018-04-19 11:21 UTC, JohnGinnane commented
no, i think we should merge it to trial it and see what happens

2018-04-19 11:21 UTC, Jujumatic commented
what do you mean by stale

2018-04-19 11:22 UTC, Carbonhell commented on hippiestation/code/datums/traits/neutral.dm
> +			searching = FALSE
^^^

2018-04-19 11:22 UTC, Carbonhell commented on hippiestation/code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>You no longer feel as if you're getting dumber..</span>"
remove the dot

2018-04-19 11:23 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +			searching = FALSE
discussed this with him a few days ago on discord, it just resets and after another 2 minutes gives another prompt

2018-04-19 11:26 UTC, JohnGinnane commented on hippiestation/code/datums/traits/neutral.dm
> +			searching = FALSE
yeah I was just having trouble following this but worst case ontario we either fix it or revert it (ideally the former)

2018-05-01 18:18 UTC, Jujumatic commented
@JohnGinnane still not testmerged?

2018-05-01 18:53 UTC, Jujumatic commented
I fixed up a ton of stuff in the code, feel free to upstream but I'm not doing it because I already tried to get a tg branch and it was a nightmare to work with, so otherwise it's staying non-modular as the whole thing should be overriden by a tg fix in the future anyway

2018-05-01 21:22 UTC, Jujumatic commented on code/datums/brain_damage/imaginary_friend.dm
> +		return FALSE
help i can't get this bit working, friend_initialized is an undefined var even after all this

2018-05-02 13:15 UTC, Jujumatic commented
alright i've come into a huge problem: the human icon doesn't change directions correctly when the imaginary friend moves, and forceMove keeps being called and then complains that there's no destination. i think this is happening because forceMove tries moving the imaginary friend when it doesn't exist, but i have no idea what is really going on. upon testing, everything else that I changed works correctly. i looked at tg's repo and they don't have any fixes for this imaginary friend shit either. please help.

2018-05-02 14:09 UTC, Jujumatic commented
human ico should actually be changing if both clients are active at once, i can't test this without a second player as i cannot be active on two clients at exactly the same time, even if logged in with 2 clients. anyway that issue is not a huge one. i made it so that imaginary friends can be examined, but still need help on forceMove. i'm completely out of ideas but apart from the spammy runtimes it works fine

2018-05-03 14:50 UTC, Jujumatic commented
fixed up the forceMove issue, lots of thanks to @JohnGinnane for the massive help. everything has been fixed up, the only issue left is that the imaginary friend's image doesn't update correctly when they move in a direction. i also have done a few fixes on an inventory deletion proc, left it as non modular because the fix that i put in needs to occur before butts are forceMoved. ping me or w/e if you want it modularised, regardless. also any help on the imaginary friend images would also be appreciated, however this pr can now be merged as that is only a minor issue

2018-05-04 14:14 UTC, Jujumatic commented
nearly done guys!!

2018-05-05 09:26 UTC, Jujumatic commented
this is fully complete! will update the pr's description now

2018-05-05 10:10 UTC, JohnGinnane commented
@Pyko1 I know you +1'd this a month ago but would you mind having another look just to make sure that's still valid?

Can I also get some @HippieStation/head input pls))

2018-05-06 21:36 UTC, Jujumatic commented
ok so uh big problem, everything works but when someone ghosts, then when a person joins back in the split personality, one of the clients crash upon swapping. i have no idea how to fix this, but i think it's got something to do with having .clients being = to other .clients, however this was the only way i could get the backseat.clients working properly. send help

2018-06-01 15:48 UTC, zamolxius commented
merge pl0x

2018-06-01 16:11 UTC, Jujumatic commented
no do not merge this yet because i still need to test with another person if client crashes still happen - i asked if anyone wanted to help a little while ago but nobody volunteered. after that i got busy but hey I'll ask for a volunteer to help me test this out again

2018-06-11 10:01 UTC, Carbonhell commented
Any news on this?

2018-06-11 10:33 UTC, Jujumatic commented
hhhholy fuck conflicts. um no not much news on this as ive been super busy with other stuff and i will still need a tester due to issues with crashing

2018-06-11 12:47 UTC, Jujumatic commented
yeah this is not gonna work till i can get someone to help me test anyway, and nobody likes to volunteer so

2018-06-11 12:57 UTC, Jujumatic commented
reopening in a new pr because of git fuckery

2018-06-11 12:57 UTC, closed without merging