Makes the megaphone let you scream bigly enough
HippieStation/HippieStationdeprecated2020 pull request #7468
Opened 2018-04-05 13:17 UTC by zamolxius

with '#' will be ignored, and an empty message aborts the commit.

[Changelogs]: Adds 3 cool new screams which are used when you scream with a megaphone

:cl: Megaphone screams!
add: 3 new ogg files to sounds/voices
del: Removed old things
tweak: edited megaphone.dm a bit
soundadd: added new screams for the megaphone
code: megaphone.dm
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Was also suggested in a forum post and accepted. please tell me if something is wrong.

2018-04-05 13:21 UTC, ghost requested changes

2018-04-05 13:21 UTC, ghost commented on code/game/objects/items/devices/megaphone.dm
> +	alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
modularise this please!
make a new file:
hippiestation/code/game/objects/items/devices/megaphone.dm

in that file do this
```
/obj/item/device/megaphone
    alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
```

2018-04-05 13:23 UTC, ghost commented
also i was gonna link [this](https://www.youtube.com/watch?v=CCVdQ8xXBfk) before i actually even looked at the files)))

2018-04-05 13:26 UTC, JohnGinnane commented on code/game/objects/items/devices/megaphone.dm
> +	alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
i don't even think it'll work, i should check this out..

2018-04-05 13:26 UTC, JohnGinnane commented on code/game/objects/items/devices/megaphone.dm
> +	alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
yeah i should total add the hand slots for this: https://github.com/HippieStation/HippieStation/blob/27e4596befb785dd2db7f75a7cd2a28f91cd8b68/hippiestation/code/modules/mob/living/carbon/reindex_screams.dm#L4

2018-04-05 13:26 UTC, zamolxius commented on code/game/objects/items/devices/megaphone.dm
> +	alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
how do i exit the commit thing in git bash?

2018-04-05 13:27 UTC, McBawbaggings commented on code/game/objects/items/devices/megaphone.dm
> +	alternate_screams = list('hippiestation/sound/voice/scream_cowboy1.ogg', 'hippiestation/sound/voice/scream_cowboy2.ogg', 'hippiestation/sound/voice/scream_cowboy3.ogg')
the virtual machine?
i usually fucking close the git bash terminal and reboot it lmfao

2018-04-05 15:12 UTC, KayeArray requested changes
Currently this won't work because the reindex_screams proc used by alternate_screams only works for clothes. You need to call add_screams() directly when the object is picked up and remove them when it is dropped

2018-04-05 16:57 UTC, zamolxius commented
will do

2018-04-05 17:41 UTC, JohnGinnane commented
@banthebantz I think will update the scream code this weekend to allow for this

2018-04-05 17:51 UTC, zamolxius commented
oh cool

2018-04-05 21:06 UTC, Kawaii-Big-Boss commented
did you test this

2018-04-06 06:59 UTC, zamolxius commented
waiting for reindex_screams refactor from john ginnane

2018-04-16 19:48 UTC, JohnGinnane commented
i forgot to do the thing im sorry ((

2018-04-24 21:46 UTC, praisenarsie commented
@JohnGinnane either close this or do the refactor!!!

2018-04-24 21:55 UTC, JohnGinnane commented
i worked on it on weekend but stopped ((

2018-05-23 19:37 UTC, t-f-w commented
+1

2018-05-28 12:12 UTC, Pyko1 commented
sure +1

2018-05-30 20:03 UTC, Jujumatic commented
stale? it's been nearly 2 months now with no changes

2018-06-08 17:02 UTC, closed without merging