Makes you able to select you e-sword's color with a multi-tool
HippieStation/HippieStationdeprecated2020 pull request #7486
Opened 2018-04-06 13:19 UTC by ExpAntique

:cl: 
add: added using a multi-tool on e-sword making you able to choose your color out of a list
add: also added rainbow as a mode, i guess
/:cl:

[why]: # TBH is this stupid snowflake shit, but it was easy so i did it.

2018-04-06 13:28 UTC, Pyko1 commented
-1 rainbow or nothing!

2018-04-07 00:59 UTC, fluxcapacitor1337 commented
+1

2018-04-07 10:16 UTC, JohnGinnane submitted a review, later dismissed

2018-04-07 10:16 UTC, JohnGinnane commented on code/game/objects/items/melee/energy.dm
> +		var/color = input("Select a color!", "Esword color") in list("red", "green", "blue", "purple", "rainbow")
This needs to be modularised. The way to do this is by creating a file at `/hippiestation/code/game/objects/items/melee/energy.dm` if it's not already there (notice how it's the same path as the original file, but under the /hippiestation/ directory)

In there you can just have this proc with your code in it, and that will override the /tg/ proc without conflicting with it

Let me know if you need help

2018-04-07 20:34 UTC, Kawaii-Big-Boss commented
stop making unmodularized shitcode

2018-04-07 20:37 UTC, Kawaii-Big-Boss commented
JohnGinnane deleted a comment from Kawaii-Big-Boss 2 minute ago

2018-04-07 20:39 UTC, JohnGinnane commented on code/game/objects/items/melee/energy.dm
> +		var/color = input("Select a color!", "Esword color") in list("red", "green", "blue", "purple", "rainbow")
now that you've modularised this, you can undo these changes, just copy the original code and put it back in here so there's technically no changes to the file

2018-04-07 20:39 UTC, Kawaii-Big-Boss commented
make more modularized goodcode

2018-04-07 21:03 UTC, JohnGinnane requested changes

2018-04-07 21:03 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/melee/energy.dm
> +/obj/item/melee/transforming/energy/sword/saber/attackby(obj/item/W, mob/living/user, params)
I suspect you'll need to save your hippiestation.dme, close down dreammaker and then commit those changes, so we can see the new file being included in the game

2018-04-07 21:04 UTC, McBawbaggings commented
force a compile and then save to have it appear in hippiestation.dmb for git commiting

2018-04-08 19:03 UTC, JohnGinnane commented
@ExpAntique like with the nukeop PR, you need to include the new file in the hippiestation.dme

2018-04-09 07:58 UTC, JohnGinnane submitted a review, later dismissed
:ok:

2018-04-09 23:34 UTC, t-f-w commented
+1

2018-04-11 16:41 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/melee/energy.dm
> +		item_color	=	"[color]"
I don't think this is necessary, is it? This would change the colour of the shaft when we don't want it to?

2018-04-11 16:43 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/melee/energy.dm
> +		item_color	=	"[color]"
`var/color` controls that IIRC

2018-04-11 16:47 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/melee/energy.dm
> +		item_color	=	"[color]"
Ah cool

Also the "if" statement and the two lines that follow should be indented back once I think, so the "if" is in line with this line

Also for this line you can just do `item_color = color`

2018-04-11 19:18 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/melee/energy.dm
> +			user.update_inv_hands()
you're going to have to call
`..()`
one tab in after this line
but I think that might call the /tg/ version of the file too which defeat the purpose.

2018-04-12 22:14 UTC, ExpAntique commented on hippiestation/code/game/objects/items/melee/energy.dm
> +			user.update_inv_hands()
I tried adding the ..() and it just added the effects of the /tg/ rainbow code. Tested it without it and it works perfectly

2018-04-13 08:06 UTC, JohnGinnane commented on hippiestation/code/game/objects/items/melee/energy.dm
> +			user.update_inv_hands()
I think he means something like this:
```
else
    ..()
```
You can see it in the original:
https://github.com/HippieStation/HippieStation/blob/e81162e5983f7272598a0c18e3e2f41e41464f95/code/game/objects/items/melee/energy.dm#L187

2018-04-15 12:56 UTC, McBawbaggings commented on hippiestation/code/game/objects/items/melee/energy.dm
> +			user.update_inv_hands()
holy fuck that's a really clever way of handling it john never thought about that

2018-04-15 13:01 UTC, JohnGinnane submitted a review, later dismissed

2018-04-15 13:20 UTC, Carbonhell submitted a review, later dismissed

2018-04-15 13:20 UTC, Carbonhell commented on hippiestation/code/game/objects/items/melee/energy.dm
> +		if	(!color)
This indentation is triggering me,can you fix it

2018-04-15 13:20 UTC, Carbonhell commented on hippiestation/code/game/objects/items/melee/energy.dm
> +		var/color = input(user,	"Select a color!",	"Esword color") as null|anything in list("red",	"green",	"blue",	"purple",	"rainbow")
Wtf is going on with those random tabs

2018-04-16 19:50 UTC, JohnGinnane approved these changes

2018-04-16 19:50 UTC, merged