Displays lobby theme name when playing.
HippieStation/HippieStationdeprecated2020 pull request #7499
Opened 2018-04-06 22:20 UTC by McBawbaggings

:cl: McBawbaggings
tweak: The game now displays the current lobby theme when playing.
/:cl:
![image](https://user-images.githubusercontent.com/15840795/38446614-ec938004-39f0-11e8-8be7-7592a8ff98d7.png)

Idea suggested by JohnGinnane: https://hippiestation.com/threads/post-lobby-and-round-end-music-when-it-plays.8575/

2018-04-06 22:20 UTC, ghost commented
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2018-04-06 22:24 UTC, t-f-w commented
+1

2018-04-06 22:31 UTC, McBawbaggings commented
got an idea to fully modularise will do tomorrow morning

2018-04-06 23:16 UTC, Spankmonkey777 commented
+1

2018-04-06 23:22 UTC, ExpAntique commented
+1

2018-04-07 00:56 UTC, fluxcapacitor1337 commented
+1

2018-04-07 09:46 UTC, JohnGinnane commented
hey i wanted to do this :(

2018-04-07 09:48 UTC, Carbonhell requested changes

2018-04-07 09:48 UTC, Carbonhell commented on code/controllers/subsystem/ticker.dm
>  	var/round_end_sound						//music/jingle played when the world reboots
Modularize?

2018-04-07 09:49 UTC, Carbonhell commented
Only issue is that some oggs have nondescriptive names, but it's all good

2018-04-07 09:49 UTC, JohnGinnane commented
yeah to get around that I was going to add in "You can find this song here: https://github.com/HippieStation/HippieStation/tree/master/hippiestation/sound/lobby"

2018-04-07 10:19 UTC, JohnGinnane commented
![image](https://user-images.githubusercontent.com/3355198/38453924-78a91fea-3a55-11e8-85ee-44e0787451e7.png)
Not immediately sure if there's a way around the space issue and I noticed a fullstop at the end for some reason

2018-04-07 17:44 UTC, McBawbaggings commented
tried wrapping it inside an href but i couldn't get it to work nicely
![image](https://user-images.githubusercontent.com/15840795/38458222-ac087f6e-3a93-11e8-9e0a-c8be55d82cad.png)

2018-04-07 18:24 UTC, JohnGinnane commented
what's wong with what you have there?

2018-04-07 18:36 UTC, McBawbaggings commented
it's like a personal computer link and doesn't work properly idk how to explain it

2018-04-08 12:07 UTC, Pyko1 commented
sure +1

2018-04-19 11:26 UTC, Carbonhell submitted a review, later dismissed

2018-04-24 21:47 UTC, praisenarsie approved these changes

2018-05-01 16:51 UTC, GuyonBroadway commented
Oh this has a +2 and successful code review, how did THAT slip by?

2018-05-01 16:51 UTC, merged