HERE WE GO, ADDS WHEELCHAIRS *READY TO MERGE*
HippieStation/HippieStationdeprecated2020 pull request #7502
Opened 2018-04-07 01:17 UTC by Jujumatic

FIXING UP THIS SHIT CODE WAS A FUCKING NIGHTMARE AAAGHHHH

adds the ability to craft wheelchairs from the misc category by using 6 metal rods and 4 metal sheets, you can move around in the chair yourself which i think is awesome. you should be able to move in it if you don't have legs, you will not be able to use it without arms, however. it moves pretty slowly, i think slightly slower than walking speed.

:cl:
add: Wheelchairs are now in! You can make them using 4 metal and 6 metal rods, and is found in the misc crafting section. You can ride around in them as long as you have arms to move the wheels.
/:cl:

2018-04-07 12:13 UTC, Chnkr commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +				spawn(delay)
🤔

2018-04-07 12:22 UTC, praisenarsie commented
i don't want this merged because ueeuugghegh it's not a vehicle

2018-04-07 12:35 UTC, Jujumatic commented
ok i think i got everything fixed up now

2018-04-07 16:57 UTC, Jujumatic commented
i can't figure out for the life of me how to get mobs to face the same direction as the chair when you push them, anyone know how to fix it up? it seems the same thing happens with office chairs, actually

2018-04-07 21:12 UTC, Jujumatic commented
yeah it doesn't seem possible to change the mob direction when the chair is pushed, but tbh it's a relatively minor thing. the same thing happens with office chairs even in live so shrug. this is ready to merge, regardless

2018-04-08 12:05 UTC, Pyko1 commented
+1

2018-04-09 17:32 UTC, fluxcapacitor1337 commented
+1

2018-04-10 17:55 UTC, Dinopeaks commented
+1

2018-04-12 15:38 UTC, Jujumatic commented
this is approved plx merge

2018-04-12 15:56 UTC, JohnGinnane commented
\>no pics
![image](https://user-images.githubusercontent.com/3355198/38689011-5e4433da-3e72-11e8-886a-ae194cb879bf.png)

2018-04-12 15:57 UTC, McBawbaggings commented
i'm assuming these go over things like broken shards without hurting the user when they have no shoes?

2018-04-12 15:58 UTC, Jujumatic commented
oh shit good point im gonna check that mcbaw, also will get pics now

2018-04-12 16:02 UTC, JohnGinnane submitted a review, later dismissed
Just looking at the code, we generally put the definition of the object (`/obj/structure/chair/movable`) before the proc overrides

Also you (inadvertently?) changed a /tg/ file. It's minor but it might cause conflicts

2018-04-12 16:04 UTC, JohnGinnane commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +	var/is_movable = FALSE
I think these vars, and the procs you have, only appear on the movable subtype as that's where they're relevant?

2018-04-12 16:09 UTC, Jujumatic commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +	var/is_movable = FALSE
ah yes, i had to put it there otherwise when the deconstruct for the wheelchair is cancelled, the default chair deconstruction proc would be called instead for some reason. putting this var fixed that by cancelling any calls for the default deconstruction if you say that it's a movable chair

2018-04-12 16:12 UTC, JohnGinnane commented
McBaw and I are discussing how best to implement this using existing methods (vehicle code vs rideable code), rather than introducing a whole new method that's kind of snowflakey

2018-04-12 21:32 UTC, Jujumatic commented
front:
![image](https://user-images.githubusercontent.com/34321231/38705302-6e1b9d84-3ea9-11e8-85ce-078decae69da.png)

side:
![image](https://user-images.githubusercontent.com/34321231/38705322-7ef6688c-3ea9-11e8-88ef-7a73e1ebeeef.png)

back:
![image](https://user-images.githubusercontent.com/34321231/38705345-8c7657ba-3ea9-11e8-8193-d9ddcf4e9c9a.png)

side view without buckled mob, this is the only one that changes depending on whether a mob is buckled or not:
![image](https://user-images.githubusercontent.com/34321231/38705371-a17703da-3ea9-11e8-8434-f5d4147e5362.png)

2018-04-13 19:34 UTC, Jujumatic commented
this is ready to merge

2018-04-17 12:26 UTC, ghost requested changes
this code is kinda snowflakely in general

2018-04-17 12:26 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +	if(is_movable) //first snowflake check? :) so it begins!
will make chairs indestructible to weapons when movable i believe

2018-04-17 12:26 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +				sleep(cooldown_amount/H.get_num_arms()) //Moving doesn't seem to be possible with an addtimer, not sure why
sleep(((((
i'd prefer not to merge any more sleep code

2018-04-17 12:26 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +	var/obj/structure/chair/movable
uninitialized variable being used later in the proc

2018-04-17 12:31 UTC, ghost submitted a review, later dismissed

2018-04-17 12:31 UTC, McBawbaggings commented on hippiestation/code/game/objects/structures/beds_chairs/chair.dm
> +	else
unnecessary else and return

2018-04-17 20:04 UTC, Jujumatic commented
holy fuck, ok i ported this over to vehicles and is fully functional

2018-04-18 11:13 UTC, Jujumatic commented
fixed up the destroy proc, the deconstruction process and added the damage flavour text to ALL vehicles :)

2018-04-18 11:14 UTC, Jujumatic commented
this is done now, plx review

2018-04-19 11:25 UTC, Carbonhell commented
+1

2018-04-24 21:42 UTC, praisenarsie commented on hippiestation/code/modules/vehicles/wheelchair.dm
> +	name = "Wheelchair"
decapitalize

2018-04-24 21:43 UTC, praisenarsie commented
someone remind me to review this tomorrow on discord

2018-04-25 06:18 UTC, Jujumatic commented
fixed

2018-04-25 15:50 UTC, praisenarsie approved these changes

2018-04-27 17:48 UTC, Jujumatic commented
MARRG TSHISDS DCRAPAP  NOIWW!!!!

2018-04-27 18:04 UTC, merged

2018-04-27 18:14 UTC, praisenarsie commented
oops i forgot to merge it