Made super mannitol, more powerful version that can heal severe traumas
HippieStation/HippieStationdeprecated2020 pull request #7505
Opened 2018-04-07 21:28 UTC by Jujumatic

Reopened cause a certain someone didn't wait for actual votes or opinions after the revamp, thanks.

Made using mannitol, plasma and uranium, this is a more powerful version of mannitol that can heal severe brain traumas as well. Has an overdose limit of 30, with some very, very nasty effects if you overdose. Be careful!

2018-04-08 09:37 UTC, ghost requested changes

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		M.adjustBrainLoss(-4*REM)
C.adjustBrainLoss(-4*REM)

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	var/overdosing = FALSE
don't believe overdosing is needed since on_mob_life() isn't called during overdose?

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				to_chat(M, "<span class='warning'>You feel like you're getting dumber!</span>")
to_chat(H, "<span class='warning'>You feel like you're getting dumber!</span>")

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				to_chat(M, "<span class='warning'>You don't feel so good... it's almost like the world is spinning!</span>")
to_chat(H, "<span class='warning'>You don't feel so good... it's almost like the world is spinning!</span>")

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				to_chat(M, "<span class='warning'>You feel awful!</span>")
to_chat(H, "<span class='warning'>You feel awful!</span>")

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		if(4>=current_cycle)
not required but more readable imo:
`if(current_cycle <= 4)`
Code tends to be easier to read when you compare a variable forwards to a constant

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		if(5<=current_cycle)
`if(current_cycle >= 5)`

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				M.emote("gasp")
H.emote("gasp")

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			H.drowsyness = max(M.drowsyness, 10)
H.drowsyness = max(H.drowsyness, 10)

also you do realise this won't be a hardcap of 10 but rather a minimum of 10, is this intended?

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			M.hallucination = 30
H.hallucination = 30

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		if(30<=current_cycle)
`if(current_cycle => 30)`

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				M.hallucination = 30
H.hallucination = 30

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				H.drowsyness = max(M.drowsyness, 10)
H.drowsyness = max(H.drowsyness, 10)

also you do realise this won't be a hardcap of 10 but rather a minimum of 10, is this intended?

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +/datum/reagent/medicine/supermannitol/on_mob_delete(mob/living/M)
if overdosing isn't required then this isn't needed

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +
if it is required we should have a `..()` here

2018-04-08 09:37 UTC, McBawbaggings commented on hippiestation/code/modules/reagents/chemistry/recipes/medicine.dm
> +	mix_message = "The solution bubbles and becomes extremely thick, turning into paste-like consistency."
"The solution bubbles and becomes viscous as it turns into a paste." would read better imo, it's kind of a comma splice in here

2018-04-08 09:39 UTC, Jujumatic commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +				H.drowsyness = max(M.drowsyness, 10)
Yees

2018-04-08 09:40 UTC, McBawbaggings commented
also quite a bit of repeated code so it'd be nice to reduce it down, i would have to have a second read

2018-04-08 11:22 UTC, Jujumatic commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			M.hallucination = 30
i tried doing H.Hallucination but for some reason that never worked when i OD'd, M.hallucination worked

2018-04-08 11:33 UTC, Jujumatic commented on hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	var/overdosing = FALSE
on_mob_life is still called during overdose, i just checked. adding back the overdosing flag

2018-04-08 11:40 UTC, McBawbaggings commented
just use `overdosed` which is set to work automatically anyway

2018-04-08 11:42 UTC, Jujumatic commented
so like if(overdosed?)

2018-04-08 11:42 UTC, McBawbaggings commented
yep

2018-04-08 12:06 UTC, Pyko1 commented
I kinda want to keep brain traumas as annoying they are. -1

2018-04-08 12:33 UTC, Carbonhell commented
Same as pyko. I think it requiring surgery is balanced. -1

2018-04-08 12:54 UTC, Jujumatic commented
i mean it takes uranium and plasma to make, on top of that it has a super nasty overdose. if you don't have uranium conveniently nearby you'd be better off doing brain surgery anyway

2018-04-08 13:16 UTC, McBawbaggings commented
just to state its currently gated behind uranium and plasma and doesn't act as another murderchem on OD so I don't really object to it

I think if anything it will be underused

2018-04-08 16:15 UTC, Jujumatic commented
tbf not a lot of people will know about it as it'll be one of the big secret chems hidden in the codebase, so yeah it'll probably be underused.

just want to give some other options for fixing brain damage without making it as piss easy as lol make mannitol

2018-04-19 11:28 UTC, Carbonhell commented
this has two heads -1 btw

2018-04-24 21:50 UTC, praisenarsie commented
the heads have spoken

just do the surgery mang

2018-04-24 21:50 UTC, closed without merging