Stamina hud
HippieStation/HippieStationdeprecated2020 pull request #753
Opened 2017-04-24 02:29 UTC by tortellinitony

2017-04-24 11:02 UTC, JamieH commented on code/modules/mob/living/carbon/human/life.dm
> +	if(client && hud_used)
I'd rather this was a hook proc.

2017-04-24 23:16 UTC, tortellinitony commented on code/modules/mob/living/carbon/human/life.dm
> +	if(client && hud_used)
ok I'll squash it all into one

2017-04-26 23:38 UTC, GuyonBroadway approved these changes

2017-04-26 23:39 UTC, GuyonBroadway commented
Looks fine, has also been tested Approving for merge.

2017-04-27 01:14 UTC, ghost requested changes
Could you add a changelog?

2017-04-27 01:16 UTC, GuyonBroadway commented
It's a port of something that's been core to hippie for ages, not sure it needs a changelog.

2017-04-27 01:18 UTC, QuarianCommando commented
Sorry, thought skipped my mind. No point putting in a changelog if nobody will notice the change after the rebase.

2017-04-27 01:18 UTC, ghost approved these changes

2017-04-27 01:20 UTC, merged