Nanosuit (WIP)
HippieStation/HippieStationdeprecated2020 pull request #7540
Opened 2018-04-10 04:27 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Adds the Crysis Nanosuit 
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Hey guys, I've been working for the past couple of months on this. I will update this and include more screenshots and information later on. 

So, what is it? 
Well it's the nanosuit from crysis.
What it do?
Super powerful armor/hardsuit that has 4 modes: Armor, cloak, speed and strength. Passive modes include toggleable night vision and zooming. Comes with a built-in disintegration implant that activates upon user death or request. 
Armor does exactly what it says it does and gives you a major buff to your helmet and suit armor + a shield which makes you immune from most attacks at the cost of suit energy. 
Cloak is very similar to the genetic mutation or ninja cloak mode.
Speed lets the user run faster than full speed while also ignoring any slowdowns.
Strength makes you a strong man.
Is it OP?
Sorta. But not. It has a charge which self charges when not in use but is quickly depleted using certain modes. Armor drains energy at a rate of 5 + damage per hit. Cloak drains passively at once per process and on movement. Speed is just like cloak but only drains when you move. Strength gives you a slighter more robust krav maga that lets you deal increased damage with your fist to objects, doors and players and also increases the power of items in your hand. In addition to increasing your physical strength it gives you the ability to jump over objects (similar to jump boots but less overpowered and better code). 
Upon equipping the suit all your items are dropped below you are equipped with a non-droppable outfit which includes a syndie bowman headset that can't be emped, shock and fireproof gloves, slip proof boots, night vision goggles and mask. Everything has radiation proofing and completely seals the user from the outside world to prevent the operator from being infected by diseases. 

The suit also comes equipped with a series of sensors which constantly monitor user vitals.
There is also a built-in very minor medical injector which will activate when the user gets hit below 50 health, the chance being random and increases depending on how much damage was taken. The injector has 3 and regenerates every 20 seconds. 

Also do not merge.

2018-04-10 09:56 UTC, JohnGinnane commented
@yoyobatty can you post screenshots and/or video?

2018-04-11 01:45 UTC, yoyobatty commented
@JohnGinnane hey man, sorry just been busy with school and work, I'll get some screenshots and maybe a video going on everything. As for testing and functionality, I've probably compiled over 200 times extensively testing and rewriting code, so I'm hoping to have this out sometime this week.

As for it being a traitor item, I am certain that this will cost 20tc and I plan on having it available as a special kit item in traitor uplinks, similar to Kanana or Bowling.

2018-04-12 16:18 UTC, JohnGinnane commented
@yoyobatty no worries, don't rush yourself

2018-04-15 07:30 UTC, JohnMcLaime commented
Strength mode should buff/speed up grabbing and increase the throwing power too.

2018-04-16 02:21 UTC, yoyobatty commented
Hey @johnmclaime this is already a feature,  strength grants you a martial art that defaults you to have aggressive grab also it grants you the push immunity trait.

2018-04-16 13:43 UTC, JohnMcLaime commented
What about throwing stuff?
Anyway this seems too good for 20 tc, maybe make a centcom announcement if someone buys one and then crew can order similar chinese knockoff suits from cargo too as a countermeasure.

2018-04-16 22:26 UTC, yoyobatty commented
I am still working on getting thrown items to hit harder, essentially I just have to make them throw faster whenever the suit is in strength mode. One of the last things I need to complete as well is making firing guns and attacking disable cloak mode + adding overlays to the suit for specific modes.

2018-04-23 12:27 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	keyslot = new /obj/item/device/encryptionkey/binary
Just to be clear, this is the key that lets you talk and listen to the AI Binary channel and not the one that lets you listen to all channels. Is this what you intended?

2018-04-23 12:34 UTC, McBawbaggings commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			switch(on)
could just have this as not a switch statement
if(on)
else

2018-04-23 12:48 UTC, GuyonBroadway requested changes

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			return 1
return TRUE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 1
return TRUE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 1
return TRUE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 1
return TRUE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			return 0
return FALSE

2018-04-23 12:48 UTC, GuyonBroadway commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		bonus_damage += 5
Correct me if I am wrong here but won't this make the bonus damage grow by 5 every time? like so the bonus would go 5, 10, 15 etc?

2018-04-23 15:22 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		bonus_damage += 5
no, the var/bonus_damage is reset to 10 every time the harm_act is called as it called every time so long as the proc returns true

2018-04-23 15:22 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			switch(on)
yes, I will change that

2018-04-23 15:23 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	keyslot = new /obj/item/device/encryptionkey/binary
yeah, that is the intention of this, it's designed to intercept all types of signals

2018-04-23 15:31 UTC, JohnGinnane commented
@yoyobatty I haven't looked through the code (yet!) but is there a way for people to acquire this? Like 20TC item or something?

2018-04-23 15:52 UTC, GuyonBroadway commented
@JohnGinnane Yeah its 20tc. Even has an announcement when someone uses it but I do feel it might be a bit OTT.

2018-04-23 15:58 UTC, JohnGinnane commented
cool cool cool

2018-04-23 16:24 UTC, yoyobatty commented
Feel free to test it out if you feel it is unbalanced. I think it cosumes and recharges power at fair rates so you want simply spam abilities. Also Ion rifles zap the cell charge. For what it is it forces you to wear an outfit that gives you protective gear that disallows combining with other traitor items such as thermals or gloves of North star. You also start with a no dismemberment trait which ensures that does not happen. Not to mention the idea is that everything that comes with it is built into suit just like the game of origin.

2018-04-23 16:32 UTC, JohnGinnane commented
I'm happy to merge as is and if it turns out to be OP we can make changes accordingly. This way we get the item in asap

2018-04-23 16:56 UTC, yoyobatty commented
I'm pushing a new commit soon considering the changes suggested. I will run a test to make sure all is well and then go.

2018-04-23 17:37 UTC, JohnGinnane commented
Need @HippieStation/head input pls))

2018-04-25 00:08 UTC, Pyko1 commented
Definitely should not be denied, but it sounds a bit op.

But no harm testing, I guess.

2018-04-25 00:08 UTC, Pyko1 commented
so +1 to see how much it needs to be tuned

2018-04-25 14:01 UTC, GuyonBroadway approved these changes

2018-04-25 16:36 UTC, Carbonhell commented
A cautious +1 from me, but i think we will have to lock this to nukies, or nerf it, it sounds too op even for 20tcs

2018-04-25 17:47 UTC, yoyobatty commented
@Carbonhell lets give it a test first and after a day or 2 if it seems unfair then I'll nerf it. Just let me remind you that the ion rifle is the suits worst enemy.

2018-04-25 21:07 UTC, GuyonBroadway commented
has +2 and the code looks ok... here goes.

2018-04-25 21:08 UTC, merged