Old virology healing symptoms have been brought back!
HippieStation/HippieStationdeprecated2020 pull request #7546
Opened 2018-04-12 15:16 UTC by Jujumatic

Old virology healing symptoms have been brought back! Virology healing can become good again! 
Been wanting to do this for a while now, and it's finally here. This should make virology less useless for those people who want to be awesome and spread good stuff around the station.

Signed-off-by: Juju <julian1999@live.co.uk>

:cl: optional name here
add: Old virology healing symptoms have been brought back! On top of this, *some of the required reagents to get them have been adjusted, as TG symptoms will still be present
/:cl:

2018-04-13 06:30 UTC, zamolxius commented
oh my god! amazing

2018-04-13 12:20 UTC, Jujumatic commented
I just need to fetch the descriptions from the hippie wiki since I didn't manage to find the descriptions in oldcode for some reason. Not sure why I couldn't find it...

2018-04-17 11:51 UTC, Jujumatic commented
>tfw erik still hasnt brought back the forums and wiki so i cant continue with this pr 

![image](https://user-images.githubusercontent.com/34321231/38868154-6c0c3670-4246-11e8-9fe4-463e4c45dd21.png)
![image](https://user-images.githubusercontent.com/34321231/38868156-6c4647de-4246-11e8-9855-f116fe9108a5.png)
![image](https://user-images.githubusercontent.com/34321231/38868157-6c8fb8ba-4246-11e8-981e-8ac5ed26cfb8.png)
![image](https://user-images.githubusercontent.com/34321231/38868158-6cccfd6a-4246-11e8-8dc9-9f7a8873abb9.png)

2018-04-17 11:52 UTC, JohnGinnane commented
you can still use tg wiki which is *mostly* the same

2018-04-17 11:53 UTC, Jujumatic commented
nope, all the old virology healing symptoms got removed and so did their descriptions as well as their bonus thresholds, effects and descriptions. and from what i checked there isn't an archived version of it either, and i couldn't find any trace of the old virology descriptions in the archived code either ???

2018-04-19 11:33 UTC, Carbonhell commented
sure +1

2018-04-24 21:49 UTC, praisenarsie commented
they were removed with good reason

you are honestly a chumboid if you support this pr because it's not that hard to get an op healing virus and that's a problem

2018-04-25 06:07 UTC, Jujumatic commented
they were removed cause tg is ghey

2018-05-01 17:02 UTC, GuyonBroadway requested changes

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/starlight
This symptom is already in game, there's no need to copy it.

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/metabolism
This symptom also is in game.

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/darkness
This one exists too!.

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/coma
And this one.

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/water
And this one!

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/plasma
This one as well!

2018-05-01 17:02 UTC, GuyonBroadway commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +/datum/symptom/heal/radiation
This one as well.

2018-05-01 17:03 UTC, GuyonBroadway commented
Instead of copying just the "Healing" and "Better healing" symptoms I'd suggest looking to make them work with thresholds.

2018-05-01 17:03 UTC, Jujumatic commented
I'm waiting for Erik to bring the wiki back up so I can get more info on the symptoms, because there's nothing regarding the symptoms, their descriptions and thresholds in oldcode

2018-05-01 17:06 UTC, Jujumatic commented
I've also copied some of tg's healing stuff because otherwise what'll end up happening is the symptom pool will have too many symptoms in it, therefore making it horribly difficult to get specific symptoms. So I disabled tg's healing symptom stuff and copied the cool ones over to hippie code

2018-05-12 17:11 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/sensory.dm
> +		M.drowsyness = max(0, M.drowsyness - 2)
just to be sure, if you're on stage 3 or above then you will be removing 4 drowsyness, correct?

2018-05-12 17:12 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:12 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:12 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:12 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:13 UTC, JohnGinnane submitted a review, later dismissed
🎏

2018-05-12 17:13 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:13 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:13 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +	return 1
return TRUE

2018-05-12 17:13 UTC, JohnGinnane commented on hippiestation/code/datums/diseases/advance/symptoms/heal.dm
> +		M.take_bodypart_damage(0, 1) //Deals BURN damage, which is not cured by this symptom
can you use the BURN define because this isn't obvious even with comment

2018-05-12 17:14 UTC, JohnGinnane commented
@HippieStation/head need one more +1

2018-05-12 17:50 UTC, Jujumatic commented on hippiestation/code/datums/diseases/advance/symptoms/sensory.dm
> +		M.drowsyness = max(0, M.drowsyness - 2)
yes this is to remove all drowsyness that the mob has

2018-05-13 11:06 UTC, Jujumatic commented
this is fully done now, i will test it later. i just got the inspiration to get descriptions and threshold stuff from tg's old PRs, as our wiki is probably never coming back, and it turns out most of the stuff was there!

2018-05-20 11:12 UTC, Jujumatic commented
Tested, the pandemic machine and the reagent bottles seem to cause some runtimes, especially when adding reagents to the bottle that causes the virus to gain a symptom or the like. However these seem like some general virology runtimes rather than being related to this PR, so yeah. The symptoms work as intended based on what I tested, and the TG ones I changed have not popped up so that's good. This is ready for merging

2018-05-20 12:44 UTC, Pyko1 commented
sure, why not +1

2018-05-23 19:34 UTC, t-f-w commented
+1

2018-05-25 21:05 UTC, Jujumatic commented
Need a maintainer review plssss

2018-05-25 21:38 UTC, GuyonBroadway approved these changes
the code looks ok but these diseases are a little strong. Balance concerns in a later post.

2018-05-26 11:40 UTC, Jujumatic commented
ok yeah the runtime is actually an issue with reagents calling add_reagent on null, will fix it at some point but it's an issue with virology in live too

2018-05-27 17:07 UTC, merged