Makes reverse bear traps craftable and lowers tc cost from 5 to 3
HippieStation/HippieStationdeprecated2020 pull request #7551
Opened 2018-04-14 10:07 UTC by Jujumatic

Doesn't really make sense why it costs so much to get, but anyway this should help a bit. I also made it craftable because crew should be able to meme bad guys with it as well.

:cl: optional name here
add: Reverse bear traps are now craftable! You will need a bear trap, 5 cable coil and a timer, and will need to use a screwdriver. Just remember to not use it on your friends!
balance: Adjusted the cost of reverse bear traps from 5 TC to 3 TC. Didn't make much sense why they were so expensive anyway.
/:cl:

2018-04-14 10:11 UTC, McBawbaggings commented
i should vocalise my opinion has no weight behind it but i don't think headmins will at all approve of an idea where uplink gear can be made on station

2018-04-14 10:18 UTC, ghost submitted a review, later dismissed

2018-04-14 10:18 UTC, ghost commented on code/modules/uplink/uplink_items.dm
> +	cost = 3
if this can't be modularised then add a comment like so at the end
`// hippie - reason`

2018-04-14 10:50 UTC, Jujumatic commented
well hey it's worth a try at least

2018-04-14 10:51 UTC, Jujumatic commented on code/modules/uplink/uplink_items.dm
> +	cost = 3
modularised

2018-04-14 10:54 UTC, Jujumatic commented
tbh i don't think it should have been uplink gear to begin with - but my opinion isn't worth much here, either

2018-04-14 10:56 UTC, McBawbaggings commented
could always make it not uplink gear and just craft able if that's how you feel

2018-04-14 11:03 UTC, Jujumatic commented
gonna wait for headmin input first - i like to keep doors open so i'm going to keep both options in for now

2018-04-14 11:15 UTC, McBawbaggings commented
just noticed that we incorrectly named our version of the uplink_items.dm and put everything in uplink_item.dm
for clarities sake this should be FIXED although i'll do that in a later PR.

2018-04-14 11:36 UTC, ghost submitted a review, later dismissed
Tested locally, appears in captain uplink at 3TC and is craftable. does not appear twice in clown uplink

2018-04-14 12:39 UTC, zamolxius commented
this strong imo maybe make it an improvised version?

2018-04-14 13:55 UTC, Pyko1 commented
I don't have anything against for them being craftable, but if they are craftable no point of having them in uplink really.

2018-04-14 22:45 UTC, Kawaii-Big-Boss commented
Remove them from the Uplink. Honestly, I was going to make this PR any way so you saved me some time.

Reverse Beartraps are just an infinitely worse version of the Executioner's Sword. Double the time required to kill someone, it's completely quiet unlike the Executioner's, they can escape it, wearing a hat makes you immune to it, etc. Plus, someone can just take it off of you.

If the issue is "tying someone to a chair and leaving the beartrap on them", well, if they're tied to a chair you can just beat them to death with a toolbox any way. You've already won. The beartrap just takes longer and is a bit flashier.

2018-04-14 22:49 UTC, Jujumatic commented
Aye, I'll remove them from the uplink when I can next get to it

2018-04-15 07:40 UTC, JohnMcLaime commented
You dont even need to tie someone, iirc putting the reverse beartrap is fast, you could potentially do it during push stun.

2018-04-15 14:19 UTC, Jujumatic commented
@JohnMcLaime  it's a 3 second delay to put on the reverse bear trap and they need to be wearing nothing on their head, which will never happen unless you take it off yourself

2018-04-15 14:27 UTC, Jujumatic commented
updated, removed reverse bear traps from the uplink

2018-04-16 18:41 UTC, Manly-Dwarf requested changes
Nein!

2018-04-16 18:41 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_items.dm
> -	cost = 1
You're doing it wrong. This won't actually remove it from the uplink, all it will do is make it exclusive to the Clown and raise its price to 5 TC.
Don't remove this...

2018-04-16 18:41 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_items.dm
> -
...and add the following instead:
`exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/traitor)`

2018-04-16 18:51 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/uplink/uplink_items.dm
> -
The code should look like this:
`/datum/uplink_item/role_restricted/reverse_bear_trap
(indentation)exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/traitor)`

2018-04-16 20:52 UTC, Jujumatic commented
alright, this should be fixed

2018-04-19 11:34 UTC, Carbonhell commented
sure +1

2018-04-25 00:03 UTC, Pyko1 commented
mine is also +1 as long as is its removed from uplink

2018-05-01 17:04 UTC, GuyonBroadway commented
CONFLIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIICTS!!!!!

2018-05-01 17:06 UTC, Jujumatic commented
how did this get conflicts lol

2018-05-01 17:23 UTC, Jujumatic commented
oh fuck i think i just lost everything :'(

2018-05-01 17:29 UTC, Jujumatic commented
fixed, should have no conflicts now

2018-05-07 12:43 UTC, Jujumatic commented
this should be fixed now plx merge

2018-05-08 08:39 UTC, Jujumatic commented
this is fixed MERG NOWW!!!!!1

2018-05-08 09:52 UTC, praisenarsie approved these changes

2018-05-08 10:04 UTC, JohnGinnane approved these changes
cool

2018-05-08 10:04 UTC, merged