Improved names of certain gear categories in traitor/nukie uplinks
HippieStation/HippieStationdeprecated2020 pull request #7575
Opened 2018-04-30 22:39 UTC by Oiobi7

:cl: Oiobi7
spellcheck: Most of the categories for uplinks have had their wording changed to be more concise.
/:cl:

The wording on these categories has always bugged me a little bit. I feel like this fixes that issue to some degree. Most importantly, this removes the (Pointless) part from the beginning of the Badassery category, as that really isn't true anymore with items like the Contender, Gloves of the North Star, surplus crates etc.

2018-05-01 17:32 UTC, GuyonBroadway approved these changes
it looks ok..

2018-05-01 21:03 UTC, Kawaii-Big-Boss commented
Did you test this?

2018-05-02 21:29 UTC, Oiobi7 commented
abbrove this before it stales

2018-05-03 18:11 UTC, zamolxius commented
cool beans

2018-05-04 19:27 UTC, Oiobi7 commented
bls abbrove

2018-05-04 19:33 UTC, zamolxius commented
@Carbonhell

2018-05-04 21:18 UTC, Carbonhell commented
tbh this is more a fix than a feature but okay, +1

2018-05-12 17:03 UTC, JohnGinnane commented
apparently this has conflicts? @Oiobi7

2018-05-23 19:18 UTC, t-f-w commented
+1

2018-05-29 19:15 UTC, Jujumatic commented
MUH CONFLICTS

2018-06-11 16:27 UTC, KayeArray approved these changes

2018-06-11 20:32 UTC, Carbonhell commented
>approving a PR that is conflicting
are you even checking the PR ree

2018-06-11 20:33 UTC, Carbonhell requested changes

2018-06-11 20:33 UTC, Carbonhell commented on hippiestation/code/modules/uplink/uplink_item.dm
> +/datum/uplink_item/collab/romerol_kit
collab subtype doesn't exist

2018-06-11 20:34 UTC, Carbonhell commented
@Oiobi7 you still here? could you fix the merge conflict and the pathing issue?

2018-06-13 17:57 UTC, closed without merging