Nanosuit upgrades
HippieStation/HippieStationdeprecated2020 pull request #7613
Opened 2018-05-29 23:21 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Bomb radar + reagent scanner to nanosuit
add: Can now attack mob/living/carbon with nano damage (strength unarmed attack)
add: Shooting an empty gun in cloak no longer cancels cloak
add: Shooting a suppressed gun in cloak temporarily pauses and unpauses cloak.
tweak: Changed radiation insulation on nanosuit suit and head to medium
balance: Increased nano damage to 25 from 22
balance: Increased melee protection in armour mode to 70 from 60 and default armour to 50 from 40
fix: Headset is now under obj/item/radio rather than obj/item/device/radio
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

2018-05-30 09:15 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(mode != "armor" && cell.charge > 0)
so putting on armor mode will make you immune to all emps?

2018-05-30 09:28 UTC, Jujumatic requested changes
see if you can fix the sleep procs cause sleep is :(

2018-05-30 09:28 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
carbon reaaaaally doesnt like it when sleep is used literally anywhere

2018-05-30 09:28 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
how is severity affected, also when does the shutdown flag get changed? since i'm not sure about the value of severity i'm wondering if the value of severity might end up making the probability go down from 5% to like 3% for example

2018-05-30 09:28 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +							NS.toggle_mode("armor", TRUE)
so whenever you run out of charge you get automatically reset to armor mode?

2018-05-30 09:28 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			sleep(1)
this one too

2018-05-30 09:30 UTC, Jujumatic commented
lol i kinda fucked this up just see if you can fix the sleeps, everything else looks ok 👍

2018-05-30 19:54 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(mode != "armor" && cell.charge > 0)
lol no?

2018-05-30 19:57 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
Yeah but I've tested this shit, it works.

2018-05-30 19:57 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
the code is severity is strong = 1, light = 2, 5/(1*1.5) = 3.3 on severe, 5/(2*1.5) = 1.66_ on light.

2018-05-30 19:57 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
he still doesn't like it tho

2018-05-30 19:57 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +							NS.toggle_mode("armor", TRUE)
Yes, this has always been apart of the suit. Crysis accuracy.

2018-05-30 19:58 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			sleep(1)
Literally copy and pasted from hulk code.

2018-05-30 20:00 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
won't that make it so emps will in general be extremely unlikely to affect the suit?

2018-05-30 20:03 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
this has always been the case, it still happens more often than you think

2018-05-30 20:04 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
yeah, well I can't exactly see any other form of delay, the callback proc doesn't liter me call .proc/animate

2018-05-30 20:04 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
my bad, didn't see the deleted lines. am blind

2018-05-30 20:06 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
typing out the full path of the proc works in a callback so doing something like mob/living/carbon/proc/destroyEVERYTHING would still be able to call it

2018-05-30 20:07 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			sleep(1)
hulk code is shitcode though :D

2018-05-30 20:18 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(5/severity*1.5) && !shutdown)
hmm  I realized I should probably replace line 242 with if((mode == armor && cell.charge == 0) || (mode != armor))

2018-05-30 20:20 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			sleep(1)
it just werks

2018-05-30 20:21 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +				sleep(4)
yeah but animate is a built in proc

2018-05-31 05:46 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			addtimer(CALLBACK(src, .proc/resume_cloak), CLICK_CD_RANGE, TIMER_UNIQUE)
what is click_cd_range and timer_unique for here?

2018-05-31 05:46 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		animate(U, alpha = 40, time = 2)
nice

2018-05-31 05:50 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			addtimer(CALLBACK(src, .proc/resume_cloak), CLICK_CD_RANGE, TIMER_UNIQUE)
click_cd_range is the time delay between firing range weapons aka guns, you must wait 4 ticks to fire again and so since this gets called on the tick of the gun, it waits that 4 seconds to recloak you also timer_unique is just the flag for setting what type of timer it is

2018-05-31 05:55 UTC, Jujumatic commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			addtimer(CALLBACK(src, .proc/resume_cloak), CLICK_CD_RANGE, TIMER_UNIQUE)
ok. i don't think timer_unique is needed but it probably won't hurt to keep either

2018-05-31 05:58 UTC, Jujumatic approved these changes
you've tested this I'm guessing?

2018-05-31 06:25 UTC, merged