Fire Suppression Sprinklers
HippieStation/HippieStationdeprecated2020 pull request #7615
Opened 2018-05-30 06:31 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBAtty
add: Adds craftable fire suppression sprinklers
imageadd: Adds icon for sprinklers
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Fire suppression sprinklers you can craft. Requires 1 metal, 1 glass, 1 beaker. Has 10 uses, and can be replenished one use by adding 50 units of water from a beaker. The sprinkler sprays out firefighting foam and can be reset or opened prematurely using a wrench. Attacking it in any way has a 33% chance of setting it off.

Hopefully atmos techs find these things useful as they are extremely effective at neutralizing fires.

2018-05-30 06:40 UTC, praisenarsie commented on hippiestation/code/game/machinery/sprinkler.dm
> +	layer = 5.2
RIPPLE_LAYER

2018-05-30 06:40 UTC, yoyobatty commented on hippiestation/code/game/machinery/sprinkler.dm
> +	layer = 5.2
yeah fam, that's just for the effects like crushers

2018-05-30 06:50 UTC, praisenarsie commented on hippiestation/code/game/machinery/sprinkler.dm
> +	user.visible_message("[uses ? "It now has <b>[uses]</b> uses of foam remaining.":""]")
I kind of don't like this, it should just update the desc with how many charges it has. i dislike this QoL!!!!

2018-05-30 06:51 UTC, praisenarsie commented on hippiestation/code/game/machinery/sprinkler.dm
> +	if(istype(W,/obj/item/reagent_containers/glass/beaker))
you do realise this will only accept beakers and nothing more

2018-05-30 12:28 UTC, praisenarsie commented on hippiestation/code/game/machinery/sprinkler.dm
> +	desc = "A compacted ball of expansive fire fighting foam, used to combat fires."
compact* and expensive*

2018-05-30 20:01 UTC, yoyobatty commented on hippiestation/code/game/machinery/sprinkler.dm
> +	desc = "A compacted ball of expansive fire fighting foam, used to combat fires."
no, it's a dense and expanding ball

2018-05-31 12:11 UTC, Jujumatic commented
@HippieStation/head input pls

2018-06-01 00:02 UTC, ExpAntique commented
+1 as long as you actually have to craft and install them. If these things started out already on map, they would completely neuter fires

2018-06-01 00:04 UTC, yoyobatty commented
yup, they craft and remain installed wherever you craft them

2018-06-08 20:36 UTC, Jujumatic submitted a review, later dismissed
approved because fuck others.dm

on a serious note you should check out the foam_container thing because the foam probably is weird. if you could show a video or something of it working that would be cool

2018-06-08 20:36 UTC, Jujumatic commented on hippiestation.dme
> -#include "hippiestation\code\modules\reagents\chemistry\recipes\others.dm"
good, fuck others.dm. auto approved because of this :agony:

2018-06-08 20:36 UTC, Jujumatic commented on hippiestation/code/game/machinery/sprinkler.dm
> +	qdel(src)
this may end up deleting the beaker that holds all the reagents to be spewed out

2018-06-08 20:36 UTC, Jujumatic commented on hippiestation/code/game/machinery/sprinkler.dm
> +	qdel(src)
actually no, this will probably end up instantly deleting any of the foam that comes out

2018-06-08 20:56 UTC, yoyobatty commented on hippiestation.dme
> -#include "hippiestation\code\modules\reagents\chemistry\recipes\others.dm"
hmm it seems it caused my build to fail

2018-06-10 01:31 UTC, MaxwelltheThird commented
as much as i love a good plasma fire, i honestly wouldnt mind seeing some of these preinstalled in certain areas, say the mainhallways. people need some safe zones

2018-06-11 20:47 UTC, Carbonhell commented
interesting, +1

2018-06-12 22:08 UTC, ShizCalev commented
I'd be a fan of this making it's way upstream tbh.

2018-06-12 22:13 UTC, ShizCalev requested changes

2018-06-12 22:13 UTC, ShizCalev commented on hippiestation/code/game/machinery/sprinkler.dm
> +		W.play_tool_sound(src)
you returned before this

2018-06-12 22:13 UTC, ShizCalev commented on hippiestation/code/game/machinery/sprinkler.dm
> +	if(istype(W, /obj/item/wrench))
wrench_act()?

2018-06-12 22:30 UTC, yoyobatty commented on hippiestation/code/game/machinery/sprinkler.dm
> +	if(istype(W, /obj/item/wrench))
I suppose I could use that

2018-06-12 22:30 UTC, yoyobatty commented on hippiestation/code/game/machinery/sprinkler.dm
> +		W.play_tool_sound(src)
shit

2018-06-13 08:21 UTC, yoyobatty commented on hippiestation/code/game/machinery/sprinkler.dm
> +	qdel(src)
no, it works and it's the same code from the ai_slipper

2018-06-13 09:42 UTC, Jujumatic approved these changes

2018-06-13 09:42 UTC, Jujumatic commented
H I P P I E  E X C L U S I V E  C O N T E N T  O N L Y

2018-06-13 09:45 UTC, t-f-w commented
+1

2018-06-13 09:45 UTC, merged