Fixed abductor tongues and maybe alien butts
HippieStation/HippieStationdeprecated2020 pull request #7616
Opened 2018-05-30 09:42 UTC by Jujumatic

Yeah what the title says lol

I looked at lighting.dm cause we still have the fire list index out of bounds issue but I still have no idea how to fix that.

Also the alien butts issue happens because there's an alien butt in ghetto chem on mapload, so if this doesn't fix then maybe getting it to initialize on mapload will work instead.

🆑 
fix: Fixed a runtime in abductor tongues
/:cl:

2018-05-30 20:30 UTC, yoyobatty commented
+1 fuck ya

2018-05-30 21:29 UTC, Jujumatic commented
30 minutes with an active singularity and bomb spam, no runtimes in lighting at all. however i found out that maxcaps cause a shitton of runtimes because it applies damage to objects that are deleted. also the handle state change proc in reagents seems to end up calling on null reagent containers

2018-05-30 21:31 UTC, yoyobatty commented
pls fix

2018-05-31 10:09 UTC, Jujumatic commented
@HippieStation/maintainers review pls

2018-06-01 11:29 UTC, Jujumatic commented
i fixed fire extinguishers and testing has shown it to work properly, along with all these other fixes (at least thus far)

yall better love me now

2018-06-01 17:38 UTC, yoyobatty commented
>FIXED FIRE EXTINGUISHERS!!!!! THEY WORK PROPERLY NOW!!!!

thank you, my lord

2018-06-01 17:39 UTC, yoyobatty commented
One more thing now for fire extinguishers is when dropped, they can't be picked up by clicking them, you have to right click and click pick up. Any chance you could look into that?

2018-06-01 17:49 UTC, praisenarsie commented on code/game/objects/items/extinguisher.dm
> +	reagents.add_reagent("water", max_water) // Hippie: finally removed cryogenic fluid because water now cools down people, extinguishes them, works on monkey cubes AND hurts slimes properly. Woo!
no need for this comment tbh

2018-06-01 17:56 UTC, praisenarsie submitted a review, later dismissed
did a quick skim of this and everything seems normal

2018-06-01 18:36 UTC, GuyonBroadway commented
@yoyobatty is that the ones on the shuttle? they are always buggy for some reason.

2018-06-01 18:37 UTC, GuyonBroadway commented on code/game/objects/items/extinguisher.dm
> +	reagents.add_reagent("water", max_water) // Hippie: finally removed cryogenic fluid because water now cools down people, extinguishes them, works on monkey cubes AND hurts slimes properly. Woo!
there's actually no need for the //Hippie comment IIRC because this is reverting it to the tg state.

2018-06-01 19:28 UTC, yoyobatty commented
and yeah the shuttle ones

2018-06-01 19:43 UTC, Jujumatic commented
yeah shuttle fire extinguishers are completely borked. probably a result of the fire extinguisher cabinets on the shuttle not properly calling new - or something like that. no runtimes pop up though, which is interesting. i'll let tg fix this one, i'm kinda dead right now

2018-06-02 13:32 UTC, Carbonhell submitted a review, later dismissed

2018-06-02 13:32 UTC, Carbonhell commented on code/controllers/subsystem/lighting.dm
> +	if (!i)	//Hippie add to stop fire lighting runtimes
..what? This way this if check will never run,cause i can only be 0 here dude

2018-06-02 13:32 UTC, Carbonhell commented on code/controllers/subsystem/lighting.dm
> +	if (!i)	//Hippie add to stop fire lighting runtimes
I mean, it will always run since !i, so this if check has no point

2018-06-02 13:32 UTC, Carbonhell commented on hippiestation/code/datums/traits/good.dm
> +		H.fart_fly = 18
all those things should be butts' vars tbh

2018-06-02 13:32 UTC, Carbonhell commented on hippiestation/code/datums/traits/neutral.dm
> +		H.scream_vol = 100
should be lungs vars

2018-06-02 13:32 UTC, Carbonhell commented on hippiestation/code/modules/mob/living/carbon/carbon.dm
> +		loc = get_turf(src)
this could still be null, and it will if loc is null since get turf is based on loc

2018-06-02 13:33 UTC, tortellinitony commented
they're on human vars for traits or something

2018-06-02 14:29 UTC, Jujumatic commented
yeah the scream vol var is on humans themselves

2018-06-02 14:29 UTC, Jujumatic commented on code/controllers/subsystem/lighting.dm
> +	if (!i)	//Hippie add to stop fire lighting runtimes
fug pls fix this then, reverting :(

2018-06-02 14:30 UTC, Jujumatic commented on hippiestation/code/datums/traits/good.dm
> +		H.fart_fly = 18
make the guy who coded this do it, not me :(

IM SICK OF THIS SHIT

2018-06-03 09:31 UTC, Jujumatic commented on hippiestation/code/datums/traits/good.dm
> +		H.fart_fly = 18
oh actually what this would end up doing is making only that butt have the increased super fart chances - by taking off the butt and getting a new butt you would have the trait but the chances on the butts would not increase up to what they're supposed to be with this trait. this is because the vars are only changed on mob add

2018-06-03 09:31 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +		H.scream_vol = 100
same as up above

2018-06-03 09:31 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +		H.scream_vol = 100
err same reason as up above i mean

2018-06-03 09:39 UTC, Jujumatic commented on hippiestation/code/datums/traits/neutral.dm
> +		H.scream_vol = 100
of course, it's entirely possible to change the specified organs' vars when they go into the person with traits, but that'd require us to use on_process which imo will be unnecessarily expensive and exploitable as well, they could just get an organ, put it in them and remove it and then the increased screaming or whatever would happen to anyone else who takes the organ and puts it in themselves

2018-06-03 09:43 UTC, Jujumatic commented
we can testmerge this and see how it does because i'm unsure how well specifically the lighting fix will work - however so far it hasn't complained to me after another half hour of stress testing on my server. also the lighting is actually working properly now, instead of causing all humans to literally have a 3 tile viewing radius

2018-06-03 09:48 UTC, Jujumatic commented
wat why did the map change wtf

2018-06-03 09:51 UTC, Jujumatic commented
fixed the map being a dumbdumb

2018-06-04 08:41 UTC, Jujumatic commented
review and merg pls @HippieStation/maintainers

2018-06-04 14:18 UTC, GuyonBroadway commented on hippiestation/code/datums/traits/good.dm
> +		H.fart_fly = 18
These are on the mob for traits, putting it on the butt means you might have issues if for whatever reasona  person has no butt when it tries to apply the trait, no I'm not going to re-write the whole bloody trait jut so you can put a var elsewhere, there is no need.

2018-06-04 14:43 UTC, GuyonBroadway requested changes

2018-06-04 14:43 UTC, GuyonBroadway commented on code/controllers/subsystem/lighting.dm
> +	var/i = resumed
please add a comment starting with //Hippie and has an appropriate dscription of why its different.

2018-06-04 14:43 UTC, GuyonBroadway commented on code/controllers/subsystem/lighting.dm
> +			L.needs_update = LIGHTING_NO_UPDATE
add //Hippie end here

2018-06-04 14:43 UTC, GuyonBroadway commented on code/controllers/subsystem/lighting.dm
> +			if(init_tick_checks)
please add a comment starting with //Hippie and has an appropriate dscription of why its different.

2018-06-04 14:43 UTC, GuyonBroadway commented on code/controllers/subsystem/lighting.dm
> +			return
Add //Hippie end here

2018-06-04 14:52 UTC, yoyobatty commented on code/controllers/subsystem/lighting.dm
> +			L.needs_update = LIGHTING_NO_UPDATE
glad you figured it out

2018-06-04 18:53 UTC, Jujumatic commented
@HippieStation/maintainers updated the text in lighting.dm to explain the hippie change now MARG DIDSSSS

2018-06-04 22:30 UTC, GuyonBroadway commented
You missed a spot.

2018-06-04 22:31 UTC, Jujumatic commented
WHERE

2018-06-04 22:31 UTC, GuyonBroadway commented
nevermind github being a shit.

2018-06-04 22:32 UTC, GuyonBroadway commented
As these are fixes I am bypassing headmin approval.

2018-06-04 22:32 UTC, GuyonBroadway approved these changes

2018-06-04 22:32 UTC, merged