makes escape pod storage safes start unlocked
HippieStation/HippieStationdeprecated2020 pull request #7762
Opened 2018-06-15 15:35 UTC by zamolxius

[Changelogs]: escape pods start unlocked. complements the other related PR but may be mutually exclusive because the other one adds a lot of fragile spacesuits among the station and this may be just too much. Feed back appreciated

:cl: zamolxius
add: unlocks space pod safes and replaces the standard orange suits in there with fragile ones
tweak: unlocks escape pod safes and replaces the standard orange suits in there with fragile ones
balance: unlocks escape pod safes and replaces the standard orange suits in there with fragile ones
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

2018-06-15 15:37 UTC, Carbonhell commented on code/modules/shuttle/emergency.dm
> +		return TRUE
owo whats this

2018-06-15 15:37 UTC, zamolxius commented
DNM testing

2018-06-15 15:50 UTC, zamolxius commented
![9f488342e359175850fa0be3bcfcd476](https://user-images.githubusercontent.com/29981240/41477436-fc1fbd90-70cc-11e8-9336-a49729f16e85.png)

2018-06-15 16:15 UTC, Jujumatic commented
S P E E D M E R G E 

no but seriously +1 this right now or else

2018-06-15 17:28 UTC, Jujumatic requested changes
rrrreeeeeeeeeeee just fix the spelling shit cause it irks me so hard aaaaghh

2018-06-15 17:28 UTC, Jujumatic commented on code/modules/shuttle/emergency.dm
> +	new /obj/item/clothing/suit/space/fragile(src)
why change them to "fragile" spacesuits? what's the difference?

2018-06-15 17:28 UTC, Jujumatic commented on code/modules/shuttle/emergency.dm
> +	desc = "A wall mounted safe containing space suits. Originally opens only during emergencies; budget cuts caused by various shenanigans have lead to streamlining efforts in Nanotrasen's ruling body.
m-muh grammar nazi has been provoked! put "originally opened" instead of "originally opens" - you're referring to the past tense here

2018-06-15 17:32 UTC, zamolxius commented on code/modules/shuttle/emergency.dm
> +	new /obj/item/clothing/suit/space/fragile(src)
fragile spacesuits  that have a 50% chance to tear on hit for extra shenanigans.  want to go explore space roundstart?  watch out for that carp,  or bring a spare.  the original orange spacesuits are pretty much as good as the EVA ones

2018-06-15 17:32 UTC, zamolxius commented on code/modules/shuttle/emergency.dm
> +	desc = "A wall mounted safe containing space suits. Originally opens only during emergencies; budget cuts caused by various shenanigans have lead to streamlining efforts in Nanotrasen's ruling body.
budget cut lead to outsourcing packaging/documentation personnel to Space Uzbekistan?  will do tomorrow tho

2018-06-15 17:38 UTC, Jujumatic commented on code/modules/shuttle/emergency.dm
> +	new /obj/item/clothing/suit/space/fragile(src)
then i think this will need some headmin input D:

2018-06-16 15:21 UTC, zamolxius commented
lol i forgot to modularize it shit

2018-06-16 15:26 UTC, ghost commented
ill redo it

2018-06-16 15:26 UTC, closed without merging