Scrake antag kit !! (WIP)
HippieStation/HippieStationdeprecated2020 pull request #7776
Opened 2018-06-16 05:26 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Adds the fucking scrake antag kit! 
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Well what the fuck is it yoyo, you evil genius ? It's a scrake from the game KILLING FLOOR!! You get this handy dandy uplink kit which gives your evil scrake apron, surgical mask and chainsaw arm! You also walk a little slow and look like a zombie, but you have a ton of armour and health! Don't piss this guy off though or he'll go into a rage sprinting and screaming at you!

Pic of the evil guy: 
![image](https://user-images.githubusercontent.com/32651551/41496070-6c67c3e0-7104-11e8-866b-050a67f71026.png)

To be continued...

2018-06-16 10:11 UTC, zamolxius commented
its wonderful

2018-06-17 08:04 UTC, zamolxius commented on hippiestation/code/game/objects/items/storage/uplink_kits.dm
> +	The only cost is your right to not suck at parenting."
you problably seen this but just in case

2018-06-18 06:04 UTC, yoyobatty commented on hippiestation/code/game/objects/items/storage/uplink_kits.dm
> +	The only cost is your right to not suck at parenting."
yeah, thanks, I just copy pasted the thing to get it to show up ingame

2018-06-23 11:12 UTC, Carbonhell requested changes

2018-06-23 11:12 UTC, Carbonhell commented on hippiestation.dme
> +#include "hippiestation\code\modules\evil\scrake.dm"
Isn't there a mob subfolder for simple mobs?

2018-06-23 11:12 UTC, Carbonhell commented on hippiestation/code/modules/evil/scrake.dm
> +	armor = list("melee" = 70, "bullet" = 45, "laser" = 80, "energy" = 45, "bomb" = 75, "bio" = 0, "rad" = 30, "fire" = 80, "acid" = 100)
Isn't armor a component, does this still work?

2018-06-23 11:12 UTC, Carbonhell commented on hippiestation/code/modules/evil/scrake.dm
> +	var/pure_red = list(0,0,0,0,0,0,0,0,0,1,0,0)
What are those two lists supposed to be

2018-06-23 11:12 UTC, Carbonhell commented on hippiestation/code/modules/evil/scrake.dm
> +		spawn(180)
Timer?

2018-06-26 04:48 UTC, yoyobatty commented on hippiestation/code/modules/evil/scrake.dm
> +		spawn(180)
timers are gay

2018-06-26 14:07 UTC, Carbonhell commented
do we really need yet another boring way to murderbone?

2018-06-30 11:51 UTC, Carbonhell commented
I would prefer if this was a Select equipment option (an outfit) for admins to fuck around, rather than yet another traitor murderbone-focused item when we're actually trying to move away from that
-1

2018-07-02 20:55 UTC, fluxcapacitor1337 commented
+1 seems cool

2018-07-07 04:29 UTC, nichlas0010 commented on hippiestation/code/modules/evil/scrake.dm
> +	var/pure_red = list(0,0,0,0,0,0,0,0,0,1,0,0)
colour matrices probably

2018-07-09 21:36 UTC, t-f-w commented
would be better as an adminbus sort of thing rather than a traitor item imo. -1

2018-07-09 21:37 UTC, Carbonhell commented
may you change it so that it cannot be bought, and make it an admin select equipment outfit?

2018-07-16 14:12 UTC, Carbonhell commented
Closing due to inactivity/denied, but you may reopen it if you do the changes requested.

2018-07-16 14:12 UTC, closed without merging