Adds the locker mech
HippieStation/HippieStationdeprecated2020 pull request #7854
Opened 2018-06-20 17:28 UTC by GuyonBroadway

:cl: GuyonBroadway
add: Adds the bane of security everywhere, the locker mech is a basic mecha assembled out of a locker and spare electronics. Also available is a drill and clamp for the locker mech. 
imageadd: Sprites by SaturonBroadway (actual name unknown)
/:cl:

[why]: IT'S FINALLY HERE, THE MUCH REQUESTED GREYTIDE MECH BUILDABLE BY ANY GREYSHIT WITH ENOUGH TOOLS AND RESOURCES.

Right now it's basically just a very shitty Ripley but we can add new parts to it later if we like.

It's primary use is that it is spaceworthy and can EVENTUALLY drill open an airlock. 

And steal shit with it's clamp.

2018-06-20 17:36 UTC, zamolxius commented
quickmerge

2018-06-20 17:37 UTC, Jujumatic commented
only if my 500 other prs are merged simultaneously

2018-06-20 18:46 UTC, Kawaii-Big-Boss commented
give screenshots

2018-06-20 19:28 UTC, GuyonBroadway commented
Dangint where did Icondiffbot go? I'll get some later.

2018-06-20 19:48 UTC, Pyko1 commented
![assistank_concept_art](https://user-images.githubusercontent.com/12048747/41681025-0d1fdb9e-74dc-11e8-8740-8385a8fc5c3e.png)
should had coded an assistank!

2018-06-20 19:54 UTC, Carbonhell commented
The clamp sounds a bit op but honestly fuck it, graytide worldwiee

2018-06-20 20:20 UTC, GuyonBroadway commented
the clamp is weaker than the ripley clamp by a fair margin, ripley clamp does about 30 damage between oxy and brute (forget the exact ratio) the makeshift clamp only deals 15.

2018-06-20 20:20 UTC, GuyonBroadway commented
Not to mention anything the mech is holding falls out its cargo hold on destruction,l which is easy to do as its made of scrap metal and thus has weak armour.

2018-06-21 23:03 UTC, yoyobatty submitted a review, later dismissed
Nice work.

2018-06-21 23:13 UTC, yoyobatty commented
Fixed the merge conflicts

2018-06-21 23:24 UTC, GuyonBroadway commented
theres gonna be more once that fix for the watcher beam projector gets merged.

2018-06-22 15:32 UTC, ghost requested changes

2018-06-22 15:32 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	cargo.Cut()
shouldn't this be in the for loop to cut each element in cargo as they're flying out?

2018-06-22 15:32 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		if(O && O in src.cargo)
implicit src in this entire code block

2018-06-22 15:32 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	return
return isn't needed here

2018-06-22 15:32 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +/obj/mecha/makeshift/Destroy()
you've defined this proc twice?

2018-06-22 16:08 UTC, GuyonBroadway commented
![image](https://user-images.githubusercontent.com/22083966/41786952-d3793d04-763e-11e8-8feb-9f6c8d6a32ed.png)
![image](https://user-images.githubusercontent.com/22083966/41786962-d9c362de-763e-11e8-8ba4-a30d44174878.png)

Here icons, i'll go over code later.

2018-06-22 16:19 UTC, praisenarsie commented
@GuyonBroadway i just told where the icons are....................

2018-06-22 16:19 UTC, praisenarsie commented
also sorry for deleting your comment i just got mad

2018-06-22 16:44 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	cargo.Cut()
you should not remove elements in a list you are currently looping, i think guyon implementation is correct

2018-06-22 17:23 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	cargo.Cut()
does cut remove the entire list when no arguments given?
i thought it was similar to pop where it removes one element only

2018-06-22 17:24 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	cargo.Cut()
oh okay it does, this part is fine

2018-06-22 22:53 UTC, GuyonBroadway commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		if(O && O in src.cargo)
It's a copy of the Ripley code as seen here

https://github.com/HippieStation/HippieStation/blob/master/code/game/mecha/working/ripley.dm#L129

I had to add it because cargo reasons not handled by other mechs.

There are differences between this and a ripley backend wise even if its behaviour is somewhat similar.

2018-06-23 10:45 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		if(O && O in src.cargo)
Doesn't matter, src. is not needed here.

2018-06-23 12:08 UTC, Pyko1 commented
anyways +1

2018-06-23 14:26 UTC, GuyonBroadway commented
Removed the SRC's and duplicate proc definitions.

2018-06-26 17:22 UTC, ghost submitted a review, later dismissed
just a few things i'd like to verify primarily

2018-06-26 17:22 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	var/list/cargo = new
is this safe?
shouldn't this be
`var/list/cargo = new()`

2018-06-26 17:22 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	..()
does super() handle malicious href calls @Carbonhell?

2018-06-26 17:22 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +			output += "<a href='?src=\ref[src];drop_from_cargo=\ref[O]'>Unload</a> : [O]<br>"
don't all hrefs including non-admin ones require tokens now for security?

2018-06-26 17:22 UTC, McBawbaggings commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		cargo -= O
subjective but it would be nice to have a clunk sound or something on exit or to make this a visible message.
while it should be obvious for the mech rider to actually see someone escape the cargo, the no sound and visible message don't reflect that

2018-06-26 17:44 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	var/list/cargo = new
just do var/list/cargo = list()

2018-06-26 17:49 UTC, Carbonhell submitted a review, later dismissed

2018-06-26 17:49 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		var/obj/O = locate(href_list["drop_from_cargo"])
this defaults to in world and i can use it to move anything existant on loc. Sanitize it.

2018-06-26 17:49 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	..()
depends on what you mean by malicious,it does some checks yes but the code under this is very bad

2018-06-26 17:49 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +			output += "<a href='?src=\ref[src];drop_from_cargo=\ref[O]'>Unload</a> : [O]<br>"
Only secure ones require security, aka stuff that should only be used by admins or mentors

2018-06-27 15:21 UTC, GuyonBroadway commented
A lot of this is copy pasted from existing ripely code (I needed to make it not a child for reasons mostly involving existing ripley parts) but I'll take a look to see if tg made them better recently.

2018-06-27 15:29 UTC, GuyonBroadway commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		var/obj/O = locate(href_list["drop_from_cargo"])
Rather concerning is that this is exactly how it works for the ripley as of right now.

2018-06-27 15:33 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +		var/obj/O = locate(href_list["drop_from_cargo"])
nvm i am blind and i didn't see the if check after this

2018-06-29 10:15 UTC, yoyobatty submitted a review, later dismissed

2018-06-29 10:26 UTC, Carbonhell commented
+1 to the idea

2018-06-29 10:29 UTC, Carbonhell submitted a review, later dismissed

2018-06-29 10:29 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	return ..()
isn't nearly all of this code already done by ..()?

2018-06-29 10:30 UTC, Dudeinyourbackyard commented
+1/3
looks Cool and Good

2018-07-02 20:55 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	return ..()
waiting for this

2018-07-02 21:42 UTC, dreamcrab commented
+9887

2018-07-03 17:39 UTC, GuyonBroadway commented
changes pushed.

2018-07-03 21:05 UTC, yoyobatty submitted a review, later dismissed
It's been code checked and changes have been honoured. +1

2018-07-03 21:38 UTC, Carbonhell commented on hippiestation/code/game/mecha/makeshift/lockermech.dm
> +	return ..()
WHAT IS THIS

2018-07-04 20:40 UTC, Carbonhell approved these changes

2018-07-04 20:55 UTC, merged