Refactors nanosuit code and fixes/rebalance stuff.
HippieStation/HippieStationdeprecated2020 pull request #7959
Opened 2018-06-29 09:17 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Proper regen system.
balance: Consumes energy faster, regens a bit slower, +regen delay changes.
fix: Fixed certain projectiles and attacks not draining energy properly.
refactor: Completely cleaned up the energy recharge and discharge code.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I've spent the past 3 days studying the original source code of Crysis only to scrap and rewrite it just to make this work. Please love it.

2018-06-29 10:54 UTC, fluxcapacitor1337 commented
+1

2018-07-02 21:07 UTC, Carbonhell commented
+1

2018-07-02 21:09 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> -	QDEL_NULL(cell)
why this?

2018-07-02 21:09 UTC, Carbonhell commented
wait did you just cut out cell code and make a snowflake version of it?why?

2018-07-02 21:41 UTC, dreamcrab commented
looks cool and if it aint broke +8

2018-07-08 08:25 UTC, Carbonhell submitted a review, later dismissed

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		current_charges = CLAMP((current_charges + 1), 0, max_charges)
Can't you just create a timer when a charge is used, that replenishes it after medical_cooldown time?

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		defrosted = FALSE
Setting those two vars to false every tick is pretty ugly. Can't you set them strictly when you need them?

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(!shutdown) //Is the suit working? Good, spawn a while loop
Is the code above supposed to run even if the suit is offline? Wat

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if((energy < cell.maxcharge) && mode != "cloak" && nn_block_recharge == 0) //if our energy is less than 100, we're not in cloak and don't have a recharge delay timer
var == 0 is ugly, just use !var reeeeeee

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(msg_time_upper)
What are those three vars you are reducing? It's dangerous to assume this proc will run every x time and bad practice, it could go faster or slower if shit happens

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		amount = 0 //set our energy to 0
Why are you setting an arg's value? You probably meant to edit cell.charge here.

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(8/severity*1.5) && !shutdown)
severity can't be 0 right?

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(!U.mind)
Why are you checking if the mind exists? You aren't even using it, you should rather check if U exists

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	toggle_mode("none", TRUE)
Modes should be defines for style purposes and so that it is more easily maintainable

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +			stat("Energy Charge:", "[round(NS.cell.charge)]%")
To keep this fully modular you could do NS.cell.charge*100/NS.cell.maxcharge (or max_charge idk) so that it returns a value between 0 and 100

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
>  /obj/item/gun/attack(mob/M as mob, mob/living/carbon/user)
Wait what is this for? I think this triggers if you bash someone with a gun, you already did this didn't you

2018-07-08 08:25 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(!shutdown) //Is the suit working? Good, spawn a while loop
Also outdated comments

2018-07-08 08:38 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if((energy < cell.maxcharge) && mode != "cloak" && nn_block_recharge == 0) //if our energy is less than 100, we're not in cloak and don't have a recharge delay timer
meh

2018-07-08 08:38 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(!shutdown) //Is the suit working? Good, spawn a while loop
I gotta change

2018-07-08 08:38 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		defrosted = FALSE
yup

2018-07-08 08:39 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		current_charges = CLAMP((current_charges + 1), 0, max_charges)
that's what it does

2018-07-08 08:39 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		if(prob(8/severity*1.5) && !shutdown)
severity should never be zero, but I'll put a check for it

2018-07-08 08:40 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	if(!U.mind)
probably a good idea, that code is super old

2018-07-08 08:40 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	toggle_mode("none", TRUE)
agreed

2018-07-08 08:40 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
>  /obj/item/gun/attack(mob/M as mob, mob/living/carbon/user)
afterattack is for firing and attack is for melee

2018-07-09 20:43 UTC, yoyobatty commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +		amount = 0 //set our energy to 0
woops

2018-07-09 20:51 UTC, Carbonhell requested changes

2018-07-09 20:51 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	return TRUE
Why return TRUE? Do you actually use this value? Doesn't seems so

2018-07-09 20:51 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +	to_chat(usr, "<span class='notice'>Cloak</span>: Become a ninja. Cloaking technology alters the outer layers to refract light through and around the suit, making the user appear almost completely in
It doesn't just cancel the cloak, it empties your cell, should specify that

2018-07-09 21:09 UTC, Carbonhell approved these changes

2018-07-09 21:30 UTC, merged