Re-adds hiding tiny items in vent pumps
HippieStation/HippieStationdeprecated2020 pull request #7960
Opened 2018-06-29 10:34 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
add: Adds ability to crowbar and hide tiny items in vent pumps
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Because this shit was so cool. Ported and refactored the code.

2018-06-29 10:35 UTC, Carbonhell commented
+1

2018-06-29 10:38 UTC, Carbonhell commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +		to_chat(user, "It's cover is open.")
Its, not It's

2018-06-29 10:38 UTC, Carbonhell commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			to_chat(user, "<span class='warning'>You insert [W] into [src]</span>")
ending dots please

2018-06-29 10:53 UTC, fluxcapacitor1337 commented
+1

2018-06-29 11:33 UTC, ghost submitted a review, later dismissed
shouldn't this be refactored to use /datum/component/storage/ instead of just implementing storage on your own?

2018-06-29 11:47 UTC, yoyobatty commented
No, it's using contents which is a built in list. Several machineries follow this setup. it's directly copied from other code more or less

2018-06-29 12:10 UTC, Carbonhell commented
The storage component may be too complex for what we want to achieve here. A simpler implementation like this is better, imo.

2018-06-29 12:10 UTC, Carbonhell commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +	return TRUE
what's this for?

2018-06-29 12:32 UTC, yoyobatty commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +	return TRUE
Plays the tool sound and sets the cover to off

2018-06-29 12:32 UTC, yoyobatty commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +	return TRUE
Plays the tool sound and sets the cover to off

2018-06-29 15:02 UTC, Amelia0010 requested changes

2018-06-29 15:02 UTC, nichlas0010 commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			if(!user.transferItemToLoc(W, src) || contents.len>=max_n_of_items)
These two should change places, as it currently places the item inside the vent before checking whether or not if fits.

2018-06-29 15:17 UTC, yoyobatty commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			if(!user.transferItemToLoc(W, src) || contents.len>=max_n_of_items)
Are you certain? I've tested it and it's simply not the case.

2018-06-29 15:39 UTC, McBawbaggings commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			if(!user.transferItemToLoc(W, src) || contents.len>=max_n_of_items)
have you tested the maximum length?
what if the vent is full in this case?
it would check to see if the item can be transferred in (which i assume doesn't consider size of the vent but rather if the item can be inserted)
then it checks to see if it should fit inside with but at that point, hasn't it already managed to do transferItemToLoc?

2018-06-29 15:39 UTC, yoyobatty commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			if(!user.transferItemToLoc(W, src) || contents.len>=max_n_of_items)
AH, so as it turns out I wasn't sure what line you were referring to and doing a test, it seems as though I can fit unlimited items inside it.

2018-06-29 15:57 UTC, yoyobatty commented on hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
> +			if(!user.transferItemToLoc(W, src) || contents.len>=max_n_of_items)
Another thing as well, adding stacks seems to infinite. As a band-aid fix "test" I checked to see if the contents.w_class was set to tiny, so if you were to add more than 20 items in a stack, it would not allow any more. I need a better soluton than this.

2018-06-29 17:42 UTC, zamolxius commented
this is cool,  look even yog is stealing it

2018-06-29 17:44 UTC, nichlas0010 commented
>this is cool, look even yog is stealing it
As if that's a measure for coolness

2018-06-29 17:46 UTC, Jujumatic commented
mfw yog gets mentioned in anything
LOL

mfw yog gets used as a measurement for coolness
LMAFAAOOOOO AHAHAHA IM DEAD

2018-06-29 23:42 UTC, yoyobatty commented
I should note that this is not yet complete.

2018-07-02 21:11 UTC, Carbonhell approved these changes

2018-07-02 21:18 UTC, bardofrage commented
+1

2018-07-02 21:40 UTC, dreamcrab commented
+9

2018-07-02 22:33 UTC, t-f-w commented
+1

2018-07-02 22:39 UTC, merged

2018-07-02 22:39 UTC, Dudeinyourbackyard commented
plus one