[ready] overcharged flashes
HippieStation/HippieStationdeprecated2020 pull request #8375
Opened 2018-07-28 16:19 UTC by zamolxius

[Changelogs]: ports back overcharged flashes from old hippie. they are made by using a wirecutter on a flash, then applying a power cell to the battery slot. One use only, will ignite the target and apply 2 firestacks but will not stun.

:cl: zamolxius
add: Added overcharged flashes back
imageadd: added the overcharge overlay image
/:cl:

[why]:  old hippie port why not

2018-07-28 16:56 UTC, steamp0rt commented
travis CI needs to re-ran, solar flares back at it again

2018-07-28 17:48 UTC, Dudeinyourbackyard commented
yay yes +1 sure

2018-07-29 10:00 UTC, Carbonhell commented
Are you actually sure we don't have them already from tg? I swear i used them ingame just a month ago

2018-07-29 10:04 UTC, zamolxius commented
i searched, i'm fully sure, tg doesnt have such cool shit. i actually found the port you made in one of the rebases and remade it after that, it used the wirecutter

2018-07-30 21:13 UTC, JohnGinnane commented
@zamolxius github is complaining about some conflicts, can you copy your icons out, copy the latest version of the device.dmi and then copy your icons back in?

2018-07-30 21:14 UTC, JohnGinnane requested changes
It looks a lot of the code is indented by 2 spaces, rather than default of 1 tab, can you check this out

2018-07-30 21:20 UTC, ghost commented
will do tomorrow

2018-07-30 21:45 UTC, JohnGinnane commented
Sorry I think github was showing it that way, lemme have another look

2018-07-30 21:45 UTC, JohnGinnane commented
Yep, code is fine, just need to fix icon conflicts

2018-07-31 10:31 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +	var/battery_panel = 0 //If it can be modified or not!
FALSE instead of 0, TRUE instead of 1 please

2018-07-31 10:31 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +			battery_panel = 0
same

2018-07-31 10:31 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +			battery_panel = 1
same

2018-07-31 10:31 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +			overcharge = 1
ame

2018-07-31 10:33 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +		if(battery_panel)
you can do this all in two lines without this if/else with:
battery_panel = !battery_panel
to_chat(user, "<span class='notice'>You [battery_panel ? "pull out" : "push in"] the pin holding the battery compartment in \the [src].</span>")
It should be a to_chat(user, "stuff"), not a visible message, aswell. Only the user should know about it

2018-07-31 10:34 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +			qdel(W)
instead of qdelling, move it to the flash contents, so it can be removed too.

2018-07-31 10:34 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +			qdel(W)
(and also write some code to remove it)

2018-07-31 10:35 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
>  /obj/item/assembly/flash/flash_carbon/(mob/living/carbon/M, mob/user, power = 15, targeted = TRUE, generic_message = FALSE)
what? what's that / between the proc args and the path wtf

2018-07-31 10:36 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +		add_overlay(image('hippiestation/icons/obj/device.dmi', "overcharge"))
save the images and new them on Initialize, it's pretty ugly to create an image everytime this proc is called, laggy.

2018-07-31 10:37 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +/obj/item/assembly/flash/update_icon(flash = FALSE)
does this replace a proc from tg?

2018-07-31 17:35 UTC, zamolxius commented on hippiestation/code/modules/assembly/flash.dm
> +/obj/item/assembly/flash/update_icon(flash = FALSE)
yes

2018-08-02 10:40 UTC, Carbonhell commented
+1 but it needs the code to be fixed.

2018-08-03 14:09 UTC, zamolxius commented on hippiestation/code/modules/assembly/flash.dm
> +		add_overlay(image('hippiestation/icons/obj/device.dmi', "overcharge"))
how do I do that?

2018-08-03 15:56 UTC, Carbonhell commented on hippiestation/code/modules/assembly/flash.dm
> +		add_overlay(image('hippiestation/icons/obj/device.dmi', "overcharge"))
var/image/overchargeoverlay   on the obj definition
in Initialize() write:
overchargeoverlay = new('hippiestation/icons/obj/device.dmi', "overcharge")
then in this particular line just do
add_overlay(overchargeoverlay)

2018-08-05 16:36 UTC, Carbonhell commented
fix it FIX IT REEEEEEEEE

2018-08-13 08:41 UTC, JohnGinnane commented
@zamolxius you still working on this? would be neat to get this merged soon

2018-08-16 10:25 UTC, zamolxius commented
i'll do it sometime else

2018-08-16 10:25 UTC, closed without merging