Add MetaLake map
HippieStation/HippieStationdeprecated2020 pull request #8380
Opened 2018-07-28 20:13 UTC by steamp0rt

:cl: steamp0rt
add: MetaLake map
/:cl:

If i'm missing any Hippie features, tell me. And yes, I realize one of the window pairs in sci-chem doesn't have grilles, I fixed that.

![metalake_bar](https://user-images.githubusercontent.com/25724666/43360282-24572dc2-9281-11e8-96c1-32e47a88f023.PNG)
![metalake_maint](https://user-images.githubusercontent.com/25724666/43360286-30972902-9281-11e8-8005-e9a31c4cc07a.PNG)
![metalake_pool](https://user-images.githubusercontent.com/25724666/43360287-31c12fa8-9281-11e8-8476-d954991a1f1e.PNG)
![metalake_scichem](https://user-images.githubusercontent.com/25724666/43360288-3412fab6-9281-11e8-8361-821329ed1745.PNG)

2018-07-28 20:44 UTC, steamp0rt commented
Darn solar flares causing CI builds to fail!

2018-07-28 21:03 UTC, praisenarsie commented
Do you have the reagent forge?

2018-07-28 21:16 UTC, steamp0rt commented
@praisenarsie Oh, uh, pic?

2018-07-28 21:16 UTC, steamp0rt commented
nvm i'll look at it myself

2018-07-28 22:39 UTC, steamp0rt commented
Reagent Forge added

2018-07-28 22:49 UTC, steamp0rt commented
And yes, I am aware the alarm and warning sign look like they are on top of each other in the reagent forge, but you can only see one at a time in game. Same with "fire warning" sign and the extinguisher cabinet in the firing range

2018-07-29 07:33 UTC, steamp0rt commented
Just gonna ping maintainers that i know of

@praisenarsie @JohnGinnane @Pyko1

2018-07-29 12:34 UTC, praisenarsie commented on config/maps.txt
> +	#voteweight 0.5
eh change this to 1.5 or remove it

2018-07-29 12:38 UTC, praisenarsie commented
Testing something

2018-07-29 12:39 UTC, praisenarsie commented
I need you to commit something to the map again so MDB actually gives a diff.

2018-07-29 13:09 UTC, steamp0rt commented
Done

2018-07-29 17:04 UTC, yoyobatty commented
Can you do a map render using dmmtools?

2018-07-29 17:07 UTC, praisenarsie commented
@yoyobatty YOYO PLEASE

2018-07-29 17:40 UTC, steamp0rt commented
![metalake-1](https://user-images.githubusercontent.com/25724666/43369005-3bebb418-9334-11e8-85ce-1e16caf0859d.png)

2018-07-29 17:59 UTC, steamp0rt commented
It is done, @yoyobatty

2018-07-29 20:14 UTC, yoyobatty commented
So this is a hippified version of metastation?

2018-07-29 20:26 UTC, praisenarsie commented
no, it's a hippified version of runtimestation

2018-07-29 20:27 UTC, praisenarsie commented
the location of the forge is garbage + it isn't surrounded by reinforced walls

2018-07-29 22:57 UTC, steamp0rt commented
@praisenarsie It was the only space I could find that met the requirements of 

A. big enough
B. nothing really important there
C. won't bulge out from the station like a tumor

2018-07-30 20:35 UTC, steamp0rt commented
Anyways I added rwalls @praisenarsie

2018-07-31 04:45 UTC, steamp0rt commented
@Carbonhell What's your discord?

2018-07-31 10:41 UTC, Carbonhell commented
Carbonhell#4499
anyway this PR requires atleast 2 experienced mappers to check it carefully with the map editor. I don't want a broken map to get in, so whoever can, check it please.
Wouldn't be against it, but it has to be manually set by an admin, I'm still against map rotation.
+1

2018-08-02 10:41 UTC, Carbonhell commented
@HippieStation/maintainers Mapcheck this.

2018-08-09 20:21 UTC, Carbonhell commented
http://mapdiffbot.dextraspace.net/Files/84665083/11592525/1/diff.png
to mapcheck more easily

2018-08-22 19:18 UTC, praisenarsie commented on config/maps.txt
> +endmap
actually you might as well add #voteweight 1.5 since it's a hippie map

2018-08-24 18:57 UTC, Carbonhell requested changes

2018-08-24 18:57 UTC, Carbonhell commented on _maps/metastation.dm
> +#define FORCE_MAP "_maps/metalake.json"
??

2018-08-24 18:57 UTC, Carbonhell commented on hippiestation/code/modules/paperwork/paper_premade.dm
> +/obj/item/paper/fluff/stations/hippie/dontletcarbonseethis
what the fuck

2018-08-24 18:57 UTC, Carbonhell commented on tgstation.dme
> -#include "code\__DEFINES\bsql.dm"
what..

2018-08-24 19:04 UTC, steamp0rt commented on tgstation.dme
> -#include "code\__DEFINES\bsql.dm"
whoops

2018-08-24 19:05 UTC, steamp0rt commented on hippiestation/code/modules/paperwork/paper_premade.dm
> +/obj/item/paper/fluff/stations/hippie/dontletcarbonseethis
@praisenarsie's joke. i'll remove it.

2018-08-24 19:05 UTC, steamp0rt commented on _maps/metastation.dm
> +#define FORCE_MAP "_maps/metalake.json"
will fix.

2018-08-24 19:14 UTC, fluxcapacitor1337 commented
+1

2018-08-24 19:16 UTC, steamp0rt commented on _maps/metastation.dm
> +#define FORCE_MAP "_maps/metalake.json"
Fixed

2018-08-25 00:36 UTC, Carbonhell approved these changes

2018-08-25 00:37 UTC, Carbonhell commented
>no bots checked this pr
the fuck
well anyway i assume the dmi is good too, everything else is fine and the map really needs to be tested ingame properly
Merging this as disabled, admins will have to force it

2018-08-25 00:40 UTC, Carbonhell commented
there's this which kinda gives me a bad feeling
/obj/effect/spawner/lootdrop/armory_contraband{
	loot = list(/obj/item/gun/ballistic/automatic/pistol = 5, /obj/item/gun/ballistic/shotgun/automatic/combat = 5, /obj/item/gun/ballistic/revolver/mateba, /obj/item/gun/ballistic/automatic/pistol/deagle, /obj/item/storage/box/syndie_kit/throwing_weapons = 3)
	},
but if it's a problem it can very easily be removed

2018-08-25 00:40 UTC, merged