Clone scanners will not attemp to scan if the clone pod is in use
HippieStation/HippieStationdeprecated2020 pull request #8484
Opened 2018-08-02 01:20 UTC by xTrainx

[Changelogs]: 
:cl: xTrainx
tweak: Clone scanners will not attemp to scan if the clone pod is in use

/:cl:

[why]: fixes issue  #8219

2018-08-06 11:50 UTC, JohnGinnane submitted a review, later dismissed
Looks good, did you test this?

2018-08-06 16:26 UTC, Carbonhell commented
test it

2018-08-07 23:28 UTC, Carbonhell commented on code/game/machinery/computer/cloning.dm
> +		if (!pod.occupant) //HIPPIE CODE -start- (PREVENTS SOUND WHILE THE POD IS IN USE)
move the comment above, the code doesn't start here,no?

2018-08-13 08:33 UTC, JohnGinnane commented
@xTrainx what's the story with this

2018-08-16 12:54 UTC, Carbonhell submitted a review, later dismissed

2018-08-19 14:03 UTC, Carbonhell submitted a review, later dismissed

2018-08-19 14:07 UTC, Carbonhell commented
needs the edited tg file filepath to be added in changes.md (update your code before doing this)

2018-08-19 14:07 UTC, Carbonhell requested changes
update changes.md

2018-08-20 14:28 UTC, Carbonhell approved these changes

2018-08-20 14:29 UTC, merged