Adds all of the Atmos Circuits
HippieStation/HippieStationdeprecated2020 pull request #8508
Opened 2018-08-03 19:31 UTC by Hate9

:cl:
add: A few new circuits for dealing with atmospherics have been uploaded to your local printers.
/:cl:
Original PR: #7859.
[why]: TG was apparently worried about people depressurizing rooms with the equivalent of a vacuum cleaner, so the original PR (tgstation/tgstation#38111) didn't include any of the things mentioned in the original PR, except for the atmospheric analyzer.

2018-08-03 19:56 UTC, Carbonhell commented on code/modules/integrated_electronics/subtypes/input.dm
> -	name = "atmospheric analyzer"
Why did you move this to the hippie file?

2018-08-03 19:58 UTC, Carbonhell commented
Holy shit, this is really cool. +1

2018-08-03 21:39 UTC, Hate9 commented on code/modules/integrated_electronics/subtypes/input.dm
> -	name = "atmospheric analyzer"
What do you mean by the hippie file?
If you mean to ask why I moved it to the Atmos file, that's because it's how it was in the original PR, before all of the cool things got removed.

2018-08-05 21:57 UTC, Shdorsh commented on code/modules/integrated_electronics/subtypes/input.dm
> -	name = "atmospheric analyzer"
i believe they thought it wasn't necessary to make a special category only for 1 circuit, since that's all that remained after the massive atmos circuit fearmongering

2018-08-06 10:06 UTC, Carbonhell commented on code/modules/integrated_electronics/subtypes/input.dm
> -	name = "atmospheric analyzer"
Basically, if tg has it, unless you're changing something in particular you should leave the code in the tg .dm file, to prevent conflicts when this same file is edited. There's no need to group this with the other circuits you're adding, you can just leave the code for it here

2018-08-06 19:46 UTC, Hate9 commented on code/modules/integrated_electronics/subtypes/input.dm
> -	name = "atmospheric analyzer"
Ok.

2018-08-09 23:03 UTC, Hate9 commented
@Carbonhell @Shdorsh I've got it changed to only add the one file. Review?

2018-08-09 23:05 UTC, McBawbaggings commented
could this file be moved into the hippiestation subfolder?
should be compliant with the modular standards then

all that needs to be done is to move
`code/modules/integrated_electronics/subtypes/atmos.dm`
to
`hippiestation/code/modules/integrated_electronics/subtypes/atmos.dm`
and to reforce a compile to clean up hippiestation.dmb

2018-08-09 23:12 UTC, McBawbaggings commented
i'm half asleep but i've had a scan over the code and have a few more suggestions, mainly just clarification and potentially adding defines

2018-08-10 15:49 UTC, ghost requested changes
honestly don't know an awful lot about circuits but that's the major stuff i see

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +#define SOURCE_TO_TARGET 0
this file should be moved into the hippiestation subfolder so it becomes
`hippiestation/code/modules/integrated_electronics/subtypes/atmos.dm`
so we can better manage our what are our files and what we inherit from /tg/ and in the case of future rebases, we can port features in the hippiestation subfolder

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +		new_amount = -new_amount
i've never seen this syntax being used before
even if it works this would be more clear by using
`new_amount = abs(new_amount)`

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +	if(isnum(new_amount))
i don't know how new_amount can't be a number but in the case it isn't a number the direction of the pump can be changed and it would reject the pressure change

move this if check to the top of the proc so the direction changing only happens if new_amount is indeed a number

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +	if((source_air.total_moles() > 0) && (source_air.temperature>0))
assuming you're checking if the gas is at least above 0K
we have the define `TCMB` which acts as the coldest a gas can be so the check should use that instead.

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +	complexity = 5
this inherits the value from the  `/pump` path so this can be removed

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +	size = 3
this inherits the value from the  `/pump` path so this can be removed

2018-08-10 15:49 UTC, McBawbaggings commented on code/modules/integrated_electronics/subtypes/atmos.dm
> +	if(source_air.temperature > 0)
previous comment about temperature, use `TCMB`

2018-08-16 12:52 UTC, Carbonhell commented
Do the changes requested by McBawbaggings so i can futher review this

2018-08-16 12:53 UTC, fluxcapacitor1337 commented
+1

2018-08-17 02:15 UTC, Hate9 commented
@Carbonhell Got it.

2018-08-22 13:32 UTC, Shdorsh commented
Add the [Ready] tag to the title once you're done. Also, I could add a heater/cooler circuit to it if you want to. I've been getting into atmos coding with all the stuff I did from my miasma PR https://github.com/tgstation/tgstation/pull/39735.

2018-08-22 16:20 UTC, Hate9 commented
@Shdorsh The heater and cooler should probably be a separate PR, but thanks for the offer. I'll probably be working on fixing this for a while, since I've got IRL issues to deal with at the same time.

2018-08-22 17:53 UTC, Shdorsh commented
If you want to, I got a hippiestation homeserver running with this stuff in its cleaned version, I can post it and credit you along.

2018-08-23 00:22 UTC, Shdorsh commented
**IMPORTANT:** So, since this was in the old atmos PR, we kinda took it for granted and thought its functionality would be evident, but it seems like there are multiple problems with this PR.

In other words: the current atmos circuits _don't_ work.

 I'll take on the task to overhaul the code and post a PR with a fixed version of these, possibly also adding one or another circuit to this.

2018-08-23 04:28 UTC, Hate9 commented
Thanks fam. I guess the lesson here is never to assume that the TG maintainers have done due diligence.

2018-08-23 04:28 UTC, closed without merging