DEATH TO LOSERS
HippieStation/HippieStationdeprecated2020 pull request #8519
Opened 2018-08-05 00:03 UTC by Kawaii-Big-Boss

FUCK IT
KILL LOSERS

who needs to test this shit amiright we use the losers for that
no runtimes here

2018-08-05 00:06 UTC, Kawaii-Big-Boss commented
don't close this yet we're gonna make the code even **BETTER**

2018-08-05 00:07 UTC, GuyonBroadway requested changes

2018-08-05 00:07 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/carbon/life.dm
> +	if(rand(50))
if(client)

2018-08-05 00:09 UTC, lcass commented on hippiestation/code/modules/mob/living/carbon/life.dm
> +	if(rand(50))
If Life() is called every tick then this is just gonna clock up the chat, no.

2018-08-05 00:09 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/mob/living/carbon/life.dm
> +	if(rand(50))
omega

2018-08-05 00:12 UTC, Eagle-Eyess commented
idk this doesnt seem like a good pr...

2018-08-05 00:21 UTC, GuyonBroadway commented
@Eagle-Eyess you lost your rights to complain when you lost the match

2018-08-05 00:26 UTC, GuyonBroadway commented on hippiestation/code/modules/mob/living/carbon/life.dm
> +	if(rand(50))
It will kill the **FAILURES** once and then be over and done with.

2018-08-05 00:27 UTC, Kawaii-Big-Boss commented
Got a loser to test it, and guess what, it runtimed every tick!
Fixed that.

2018-08-05 00:29 UTC, Kawaii-Big-Boss commented on hippiestation/code/modules/mob/living/carbon/life.dm
> +	if(rand(50))
okay fixed

2018-08-05 00:39 UTC, GuyonBroadway approved these changes

2018-08-05 00:56 UTC, geylard commented
+1

2018-08-05 00:56 UTC, GuyonBroadway commented
CODE IS GOOD!!

2018-08-05 00:58 UTC, Eagle-Eyess commented
-1 we all winners at heart...

2018-08-05 01:05 UTC, frozen-is-a-fag commented
+1 LOSER YOUR A LOSER ARE YOU FEELING SORRY FOR YOURSELF? WELL YOU SHOULD BECAUSE YOU'RE A LOSER

2018-08-05 03:24 UTC, CitrusGender commented
![image](https://user-images.githubusercontent.com/31262308/43682259-76d49780-983d-11e8-9bb6-2ec765dbc3b4.png)

2018-08-05 16:46 UTC, Carbonhell commented
No

2018-08-05 16:46 UTC, closed without merging

2018-08-05 19:23 UTC, Manly-Dwarf commented
TYRANT
![aaaaaaaaaaa](https://user-images.githubusercontent.com/33744849/43689125-802e7ab8-98c3-11e8-96ce-5125b2e96a8b.png)

2018-08-06 00:54 UTC, blobbernaut commented
pass it or i will return to fulfill the prophecy

2018-08-06 01:05 UTC, Dudeinyourbackyard commented
what the fuck blob no
you're not allowed back
snail down nigga wtf