Adds martial arts to security, removing the krav maga implant "system"
HippieStation/HippieStationdeprecated2020 pull request #8617
Opened 2018-08-13 21:03 UTC by GuppyLaxx

What the title says.
HoS gets CQC.
Warden gets Krav Maga, known rather than an implant you can toggle. Removed the Krav Maga gloves.
Security officers randomly get 1 of 6 martial arts, all with different effects to some degreee, sharing a `very minimal` melee block chance.
Detective gets nothing because they still have `what is essentially the most OP gun on station`
### The martial arts are : 
**Cool Flips Bro** : You commonly do flip attacks.
**Block Affinity** : You're prone to preemptively blocking.
**Heavy Hitter** : You beat the shit out of people.
**Hard Headed** : You lack a couple brain cells and usually headbutt people.
**Fierce Grabber** : Your grip is pretty strong.  
**Tactical Disarmer** : You yank those weapons right out.
*Figure out what they do better by playing or being a lame shit and looking at the code.*

2018-08-13 21:18 UTC, yoyobatty commented
This is very interesting and will make playing security roles a lot more appealing.

2018-08-13 21:22 UTC, ghost commented
speed merge

2018-08-14 03:48 UTC, Dudeinyourbackyard commented
cool
+1
maybe HoS shouldn't have CQC, what does it do again?

2018-08-14 05:53 UTC, GuppyLaxx commented
@Dudeinyourbackyard REALLY good at melee, has things like a sleep attack, stamina damaging punches, a block, etc. BUT, doesn't affect ranged at all, so it's not that drastic of a change

2018-08-14 06:20 UTC, GuyonBroadway commented
I don't like how the sec martial art is roundstart rng. That just means a sec player might get something they don't want with no way to know about it or thorough any fault of their own.

2018-08-14 06:25 UTC, GuppyLaxx commented
Except there's a clear chat message of what they get.
Also `"Something they don't want"`, this is a random bonus, not some shitty boost you get to be nit-picky about

2018-08-14 06:31 UTC, GuyonBroadway commented
Its still roundstart rng which is bad, some sec officers might get a better martial art than another. If they spawned with an item that let them pick an art that would be better.

2018-08-14 06:33 UTC, GuppyLaxx commented
`"some sec officers might get a better martial art than another"` It's almost as if that's the whole point of it being random.

2018-08-14 06:36 UTC, GuyonBroadway commented
>" It's almost as if that's the whole point"


Then it's shit.

2018-08-14 06:56 UTC, GuppyLaxx commented
great criticism, thanks bro. Sadly I'm not here to let you pick instant aggro grabs or 75% chance flip ckicking

2018-08-14 07:10 UTC, GuyonBroadway commented
If you think its too strong to be given out at roundstart what makes it ok to be given out in a mystery box at roundstart?

2018-08-14 07:13 UTC, zamolxius commented
E M E R G E N T G A M E P L A Y
also it practically FORCES people to play sec officer a few rounds until they get to test out every martial art!

2018-08-14 07:14 UTC, GuppyLaxx commented
Did I ever say it was too strong? lol no, I made some better than others for the specific reason to add variety, and made them have lower odds to happen

2018-08-14 07:39 UTC, GuyonBroadway commented
Having some players be better off than others via roundstart rng is bad.

You might say "variety" but its still bad balance, a sec officer with kickflip is going to be stronger in combat than an officer with robust disarm. I'm all for jobs having pros and cons but this is like xenobio sometimes getting a random reward from the mining voucher at roundstart as opposed to being able to choose.

2018-08-14 08:07 UTC, JohnGinnane commented
RNG is a shit way to balance things. Could make it something they can learn. If we see a lot of sec using one or two abilities then we know which ones are perhaps OP

2018-08-14 08:09 UTC, JohnGinnane commented on code/datums/martial/krav_maga.dm
> +		//to_chat(H, "<span class = 'userdanger'>You know the arts of [name]!</span>") - Hippie change and shit
why comment this out?

2018-08-14 08:09 UTC, JohnGinnane commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	//new /obj/item/clothing/gloves/krav_maga/sec(src) - Hippie change, Warden starts with Krav Maga in them instead
I think leave this in here to let non-sec get the gloves

2018-08-14 08:19 UTC, JohnGinnane requested changes
These are very powerful abilities that cost nothing and are randomly given at roundstart

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +/datum/martial_art/sec/flipper
Needs a cooldown I think, because 75% every attack is a too often

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
3.5 seconds is way too long imo, 1.5 should be enough i think. Is this supposed to replace stuns or just buy you time to get them out?

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +			D.Stun(20) //minimal stun
A 2 second stun at 10% chance? Lower the time, maybe add a cooldown so it doesn't stack

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +	desc = "Getting dropped as a child has given you some pretty hard times in life, now it shines. You can headbutt people, just make sure you AIM FOR THEIR HEAD and they have no helmets on."
I think change the end of the description to "when they have no helmet on" instead of "and they have no helmets on"

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(rand(5,30))
Again need a cooldown for these. 50% chance to 3 second stun every time is too much

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/modules/jobs/job_types/security.dm
> +	to_chat(H, "<span class='bold info'><font size='2'>In the academy not only did you essentially get abused, but you've gained a life skill, the art of Close Quarters Combat.</span></font>")
Closing tags are in wrong order. Do `</font></span>`

2018-08-14 08:19 UTC, JohnGinnane commented on hippiestation/code/modules/jobs/job_types/security.dm
> +	to_chat(H, "<span class='bold info'><font size='2'>During your strict training to become a mall cop, they gave you some sort of nanites and a promotion. You know the arts of Krav Maga.</span></font>
Same here

2018-08-14 08:22 UTC, ghost commented
maybe add a tackle one that jumps onto somebody and renders them stunned and in your agressive grasp?  blocked by shields ala alien pounce.  2-3 tiles

2018-08-16 13:47 UTC, GuppyLaxx commented on code/datums/martial/krav_maga.dm
> +		//to_chat(H, "<span class = 'userdanger'>You know the arts of [name]!</span>") - Hippie change and shit
For the sake of adding the special description on warden spawn

2018-08-16 13:48 UTC, GuppyLaxx commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	//new /obj/item/clothing/gloves/krav_maga/sec(src) - Hippie change, Warden starts with Krav Maga in them instead
If a lot of people want it, sure

2018-08-16 13:48 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
Neither, this is a pretty much last resort, a stunbaton is still miles better

2018-08-16 13:49 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +			D.Stun(20) //minimal stun
50% chance then 20% chance for a 2 second stun is very bad, 2 seconds in general is nothing

2018-08-16 13:50 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(rand(5,30))
it's from 0.5 seconds to 3 seconds, randomly picked in there, keep in mind this is VERY easily countered by wearing a helmet.

2018-08-16 13:50 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +	desc = "Getting dropped as a child has given you some pretty hard times in life, now it shines. You can headbutt people, just make sure you AIM FOR THEIR HEAD and they have no helmets on."
g r a m m a r

2018-08-16 13:54 UTC, JohnGinnane commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	//new /obj/item/clothing/gloves/krav_maga/sec(src) - Hippie change, Warden starts with Krav Maga in them instead
Eh I'd rather you keep it in so that if a lot of people don't want it, it can be removed

2018-08-16 13:56 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
It takes 3 seconds to apply cuffs. There's no cooldown or charge to this. How is a limited stun baton which you can drop miles better than this?

2018-08-16 13:57 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +			D.Stun(20) //minimal stun
2 seconds is not nothing, it gives the suspect time to change equipment, run away, etc. Any stun can be fatal

2018-08-16 13:57 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(rand(5,30))
Yeah but helmets aren't very common outside of sec. 3 Seconds is huge, RNG is also shit for balancing

2018-08-16 14:00 UTC, Carbonhell commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
fix the comment anyway,it's seconds,not milliseconds. Knockdown and similar procs accept time in deciseconds.

2018-08-16 14:05 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
i made this at 3 am, just a dumb error from me
also @JohnGinnane you're relying on RNG to go cuffing with this, not just that, beating the shit out of the "prisoner"

2018-08-16 14:07 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(rand(5,30))
I just realized I forgot to add hardhat to the immunities, I thought they were a helmet subtype. Those are common as shit

2018-08-16 14:18 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
75% is very high. Too much of this is reliant on RNG and that's terrible to balance, there's not counter play, it's a simple "you're shit outta luck" or not. The main problem is that sec officers can get a lucky ability that grants them unlimited 3 second stuns with no consequences other than "25% chance not to happen"

2018-08-16 14:22 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
Except here's the common thing of all of these things....... None of them touch ranged combat, at all.
If you see an officer absolutely destroying antags by just flipping with their fists, more power to them, because 90% of their gear can do all of this better, except pepper spray, no one likes pepper spray.

2018-08-16 14:25 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
\>"90% of their gear can do this"
\>adds another item to empower sec
is that why you added this? just to buff sec?

I forgot that this is just melee, so I'd expect sec to just get kited

2018-08-16 14:27 UTC, GuppyLaxx commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
These are all essentially crutches, crutches for people who don't play a lot of officer or don't feel confident enough in how robust they are, with a 5% chance to block by default, and a small bonus to unarmed attacks in case they get their weapons disarmed, they might get their ass saved, they might not, simple as that.

2018-08-16 14:29 UTC, JohnGinnane commented on hippiestation/code/datums/martial/security_arts.dm
> +		D.Knockdown(35) //3.5 milisecond stun, because why not
Yeah to be fair I'm extremely critical of sec but I still think RNG is the worst way to balance because you can't play for/against it, it's a gamble

2018-08-22 19:12 UTC, Carbonhell commented
Too RNG based and honestly krav maga works fine and fits sec more than randomly headbutting people and such. -1, sorry

2018-08-22 21:03 UTC, yoyobatty commented
In contrast to shit like monk this is hardly overpowered. It does need a lot of revision however.

2018-08-22 22:59 UTC, ghost requested changes
Please use the requested format so we have a consistent format.

2018-08-22 22:59 UTC, Chnkr commented on code/datums/martial/krav_maga.dm
> +		//to_chat(H, "<span class = 'userdanger'>You know the arts of [name]!</span>") - Hippie change and shit
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:59 UTC, Chnkr commented on code/datums/martial/krav_maga.dm
> +		//to_chat(H, "<span class = 'danger'>Place your cursor over a move at the top of the screen to see what it does.</span>")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:59 UTC, Chnkr commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	//new /obj/item/clothing/gloves/krav_maga/sec(src) - Hippie change, Warden starts with Krav Maga in them instead
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-24 19:17 UTC, fluxcapacitor1337 commented
-1

2018-08-25 08:37 UTC, Carbonhell commented
I am sorry but this is denied. Next time you may want to make a feature first to avoid wasted implementations.

2018-08-25 08:37 UTC, closed without merging