re-adds our roundstart sound
HippieStation/HippieStationdeprecated2020 pull request #8621
Opened 2018-08-15 21:21 UTC by yoyobatty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: YoYoBatty
fix: Roundstart sound is now our custom one.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

2018-08-15 21:26 UTC, JohnGinnane commented on code/modules/mob/dead/new_player/new_player.dm
> -			character.playsound_local(get_turf(character), 'sound/voice/ApproachingTG.ogg', 25)
wait what, when did this change? i thought we had our own?

2018-08-15 21:35 UTC, yoyobatty commented on code/modules/mob/dead/new_player/new_player.dm
> -			character.playsound_local(get_turf(character), 'sound/voice/ApproachingTG.ogg', 25)
a while ago, it never got fixed

2018-08-15 21:44 UTC, Carbonhell submitted a review, later dismissed

2018-08-15 21:44 UTC, Carbonhell commented
We have our own??

2018-08-15 21:44 UTC, Carbonhell commented
Also this should be fix, not add

2018-08-15 21:52 UTC, yoyobatty commented
done

2018-08-16 03:40 UTC, fluxcapacitor1337 commented
+1

2018-08-16 12:31 UTC, Carbonhell commented
this sound sounds like shit wtf, @JohnGinnane has a better one

2018-08-17 10:17 UTC, Carbonhell commented
i mean theorically this is just a fix but i don't want it in with the shit sound it has currently,if you could get the proper sound and put it in the PR aswell i'll merge

2018-08-17 20:19 UTC, JohnGinnane commented
@yoyobatty ping me if you want I can send on the ogg I have, and the .aup file (for audicity)

2018-08-19 14:11 UTC, Carbonhell requested changes
update the sound too, current one is shit, also fix the comment with // hippie -- reason

2018-08-20 21:00 UTC, nalarmg commented
Comment needs fixing, but otherwise code is fine.

2018-08-22 22:57 UTC, ghost requested changes
Please mark your changes

2018-08-22 22:57 UTC, Chnkr commented on code/modules/mob/dead/new_player/new_player.dm
> +			character.playsound_local(get_turf(character), 'hippiestation/sound/voice/approaching.ogg', 25)//hippie edit for custom shuttle approach sound
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-25 08:38 UTC, Carbonhell commented
You just need to swap a sound file, when will this get done...?

2018-08-27 23:25 UTC, Carbonhell commented
@yoyobatty ree

2018-08-30 21:02 UTC, Eagle-Eyess commented
+1 old hippie stuff needed

2018-09-06 14:08 UTC, Carbonhell commented
Stale.

2018-09-06 14:08 UTC, closed without merging