Various Sling fixes
HippieStation/HippieStationdeprecated2020 pull request #8708
Opened 2018-08-21 23:03 UTC by steamp0rt

:cl: steamp0rt
fix: Ascendants should now be able to use hypnosis/gore/gib
fix: Thrall roundend report shouldn't repeat 50 times
tweak: Combined shadowling and thrall roundend report
tweak: Melee-range glare now knocks the target down like a normal stun, instead of paralyzing them.
/:cl:

2018-08-21 23:12 UTC, Carbonhell requested changes

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/datums/antagonists/shadowling.dm
> +			if(!H.owner)
those loops are pretty weird, why don't you just make the team a static variable shared by all shadowling antag datums instead? So you just new it if it is null

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/datums/antagonists/shadowling.dm
> +	if(!istype(new_team))
meh honestly this if check isn't needed

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/datums/antagonists/shadowling.dm
> +		var/datum/species/shadow/ling/SL = dna.species
Isn't there any sort of hook inside human Stat? It feels weird to have to redefine human Stat instead

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/datums/antagonists/thrall.dm
> +	var/datum/team/shadowling/sling_team
Wait, why aren't thralls a subtype of shadowling? Aaaaaa

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/datums/antagonists/thrall.dm
> +/datum/antagonist/thrall/create_team(datum/team/shadowling/new_team)
Ugly

2018-08-21 23:12 UTC, Carbonhell commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +/obj/effect/proc_holder/spell/proc/shadowling_check(var/A)
argument should be mob/living/L rather

2018-08-21 23:16 UTC, ghost commented on hippiestation/code/datums/antagonists/thrall.dm
> +	var/datum/team/shadowling/sling_team
Literally every proc would need to be changed for thralls, making it moot point

2018-08-21 23:16 UTC, ghost commented on hippiestation/code/datums/antagonists/shadowling.dm
> +	if(!istype(new_team))
This is copy-paste from cult antag datum

2018-08-21 23:17 UTC, ghost commented on hippiestation/code/datums/antagonists/shadowling.dm
> +			if(!H.owner)
This is copy-paste from cult antag datum. And plus, not a single antag datum has a static team, which leads me to think there's a reason for non-static team vars./

2018-08-21 23:17 UTC, ghost commented on hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
> +/obj/effect/proc_holder/spell/proc/shadowling_check(var/A)
Done

2018-08-21 23:34 UTC, Carbonhell commented
I will handle this PR, dnm till i say it is good

2018-08-22 13:55 UTC, steamp0rt commented on hippiestation/code/datums/antagonists/shadowling.dm
> +		var/datum/species/shadow/ling/SL = dna.species
No, not really. plus I don't think it'll work with a hook

2018-08-22 14:01 UTC, Carbonhell approved these changes

2018-08-22 14:02 UTC, Carbonhell commented
I don't like how copypasta it is, but it's true that making thralls a subtype of shadowlings is not feasible for now. The way to collect the team seems really stupid though, since the antagonist list is pretty small i guess it can be ignored but still, it's bad practice. Anyway,not the scope of this PR,merging

2018-08-22 14:04 UTC, merged