Sopa de gondola
HippieStation/HippieStationdeprecated2020 pull request #8709
Opened 2018-08-22 01:36 UTC by Shdorsh

[Changelogs]: # Added Sopa de Gondola, a nice treat from Centcomm nobody can say no to. Also, thanks to Basilman for making the sopa de macaco icon

:cl: Shdorsh, Basilman
add: Sopa de gondola
add: Gondola parts for cooking
imageadd: Sopa de gondola and sopa de macaco icons
/:cl:

[why]:  As a meme and also to make sopa de macaco look more like its real life equivalent.
![gondola](https://user-images.githubusercontent.com/32726535/44437384-5bf3bb00-a5ba-11e8-9613-58af806afe45.png)
![macaco](https://user-images.githubusercontent.com/32726535/44437445-a1b08380-a5ba-11e8-9e0a-05a009ef7341.png)

2018-08-22 01:44 UTC, McBawbaggings commented
uma delicia

2018-08-22 01:47 UTC, fluxcapacitor1337 commented
+1

2018-08-22 01:53 UTC, Shdorsh commented
Hoitoa ::::DDDDD

2018-08-22 10:17 UTC, Carbonhell commented
Hell yeah +1

2018-08-22 10:27 UTC, biggiOS commented
uma delicia +1

2018-08-23 01:51 UTC, Dudeinyourbackyard commented
haha yes uma delicia +1

2018-08-23 20:30 UTC, JohnGinnane commented on code/modules/mob/living/simple_animal/friendly/gondola.dm
> +	loot = list(/obj/effect/decal/cleanable/blood/gibs, /obj/item/stack/sheet/animalhide/gondola = 1, /obj/item/reagent_containers/food/snacks/gondoface, /obj/item/reagent_containers/food/snacks/gondole
You can modularise this by creating a file with the same path and name but in the hippiestation folder:

Current:
` code/modules/mob/living/simple_animal/friendly/gondola.dm`
New:
`hippiestation/code/modules/mob/living/simple_animal/friendly/gondola.dm`

Then you can just specify the loot list in there, so you don't have to touch the /tg/ file at all

2018-08-25 01:43 UTC, Shdorsh commented on code/modules/mob/living/simple_animal/friendly/gondola.dm
> +	loot = list(/obj/effect/decal/cleanable/blood/gibs, /obj/item/stack/sheet/animalhide/gondola = 1, /obj/item/reagent_containers/food/snacks/gondoface, /obj/item/reagent_containers/food/snacks/gondole
I'll do this once I'm back from my trip

2018-08-26 11:23 UTC, Carbonhell requested changes

2018-08-26 11:23 UTC, Carbonhell commented on hippiestation/code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
> +	/datum/crafting_recipe/food/gondolasoup
What is this indent

2018-08-26 11:23 UTC, Carbonhell commented on hippiestation/code/modules/food_and_drinks/food/snacks_soup.dm
> +		h.dna.species.liked_food |= GONDOLA
I am unsure about this, is it worth the new bitflag?

2018-08-26 17:13 UTC, Shdorsh commented on hippiestation/code/modules/food_and_drinks/food/snacks_soup.dm
> +		h.dna.species.liked_food |= GONDOLA
Yeah, because I just want whoever who eats it to directly add the gondola soup to liked types of food. I don't want to change it to an already existing type, as this could have wider consequences gameplay-wise: It would mean that flypeople could suddenly eat other stuff besides gross etc. just by eating gondola soup.

2018-08-26 17:13 UTC, Shdorsh commented on hippiestation/code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
> +	/datum/crafting_recipe/food/gondolasoup
huh, something that I didn't see, must have happened while I copypasted the code from my desktop onto that.

2018-08-29 14:13 UTC, Carbonhell approved these changes

2018-08-30 21:01 UTC, Eagle-Eyess commented
More meme foods why not? +1

2018-09-01 13:17 UTC, merged