Sound options - voice, scream and main
HippieStation/HippieStationdeprecated2020 pull request #8712
Opened 2018-08-22 04:34 UTC by nalarmg

Adds new sound options in the OOC tab. I'll probably split this into seperate PRs to avoid one overly huge PR with hundreds of file changes. 

Allows players to set their own sound volume for voices (things said ingame), screaming sounds, and anything that isn't the previous two things.

Does not affect adminhelps or mentorhelps, as due to being relatively ancient code they use a different proc entirely to playsound, which was modified to allow these new options to happen. They'll need to be adjusted in the future if sound options are desired for those. Also does not affect anything that does not use the playsound proc, such as round-end or round-start sounds. 

![screenshot_1](https://user-images.githubusercontent.com/7481072/44442953-0248bc00-a5cd-11e8-9fd2-494237fdbf12.png)

2018-08-22 09:49 UTC, JohnGinnane commented
gonna piggy back on this later on with TTS as it's perfect for that too

2018-08-22 10:20 UTC, Carbonhell commented
This touches a lot of files and could be modularized futher, but the idea is pretty good. +1

2018-08-22 22:56 UTC, ghost requested changes
Please make sure you annotate your changes in TG files.

2018-08-22 22:56 UTC, Chnkr commented on code/game/objects/items/robot/robot_upgrades.dm
> +		playsound(loc, 'sound/voice/liveagain.ogg', 75, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/game/objects/items/toys.dm
> +		playsound(get_turf(src), chosen_sound, 50, 1, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/game/sound.dm
> +/proc/playsound(atom/source, soundin, vol as num, vary, extrarange as num, falloff, frequency = null, channel = 0, pressure_affected = TRUE, ignore_walls = TRUE, type = "default")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/game/sound.dm
> +				M.playsound_local(turf_source, soundin, pref_vol, vary, frequency, falloff, channel, pressure_affected, S)
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/antagonists/clockcult/clock_mobs/_eminence.dm
> +		playsound(src, 'sound/machines/clockcult/ark_scream.ogg', 50, FALSE, type = "scream")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
> +					M.playsound_local(M, 'sound/machines/clockcult/ark_scream.ogg', 100, FALSE, pressure_affected = FALSE, type = "scream")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/client/preferences.dm
> +
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/clothing/masks/hailer.dm
> +		playsound(src.loc, "sound/voice/complionator/[phrase_sound].ogg", 100, 0, 4, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +			target.playsound_local(target,'sound/voice/liveagain.ogg', 75, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +			target.playsound_local(source, 'sound/voice/bfreeze.ogg', 35, 0, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +				target.playsound_local(source, 'sound/voice/human/womanlaugh.ogg', 50, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +				target.playsound_local(source, pick('sound/voice/human/manlaugh1.ogg', 'sound/voice/human/manlaugh2.ogg'), 50, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/holiday/halloween.dm
> +		playsound(loc, 'sound/spookoween/girlscream.ogg', 300, 1, type = "scream")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/carbon/alien/emote.dm
> +		playsound(user.loc, 'sound/voice/hiss5.ogg', 40, 1, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
> +	playsound(src, 'sound/voice/hiss5.ogg', 40, 1, 1, type="voice")  //Alien roars when starting to break free
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
> +		playsound(get_turf(src), pick('sound/voice/lowHiss2.ogg', 'sound/voice/lowHiss3.ogg', 'sound/voice/lowHiss4.ogg'), 50, 0, -5, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/emote.dm
> +		playsound(user.loc, 'sound/voice/hiss6.ogg', 80, 1, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/emote.dm
> +				playsound(H, 'sound/voice/human/womanlaugh.ogg', 50, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/emote.dm
> +				playsound(H, pick('sound/voice/human/manlaugh1.ogg', 'sound/voice/human/manlaugh2.ogg'), 50, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/silicon/robot/robot.dm
> +	playsound(loc, 'sound/voice/liveagain.ogg', 75, 1, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +			playsound(src, pick('sound/voice/bcriminal.ogg', 'sound/voice/bjustice.ogg', 'sound/voice/bfreeze.ogg'), 50, FALSE, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			playsound(src, pick('sound/voice/ed209_20sec.ogg', 'sound/voice/edplaceholder.ogg'), 50, FALSE, type="voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +			playsound(loc, messagevoice[message], 50, 0, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +			playsound(loc, messagevoice[message], 50, 0, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +		playsound(loc, messagevoice[message], 50, 0, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +		playsound(loc, messagevoice[message], 50, 0, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +		playsound(loc, 'sound/voice/minsult.ogg', 50, 0, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +			playsound(src, pick('sound/voice/bcriminal.ogg', 'sound/voice/bjustice.ogg', 'sound/voice/bfreeze.ogg'), 50, FALSE, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
> +		playsound(src, 'sound/voice/mook_leap_yell.ogg', 100, 1, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/photography/photos/photo.dm
> +		playsound(user, 'sound/voice/human/manlaugh1.ogg', 50, 1, type = "voice")//EVERY TIME I DO IT MAKES ME LAUGH
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/photography/photos/photo.dm
> +		playsound(user, 'sound/voice/human/womanlaugh.ogg', 50, 1, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-22 22:56 UTC, Chnkr commented on code/modules/spells/spell_types/wizard.dm
> +		playsound(C.loc, 'sound/voice/hiss5.ogg', 80, 1, 1, type = "voice")
## Please mark your changes

All modifications to non-hippie files should be marked.

- Single line changes should have `// hippie -- reason` at the end of the exact line that was edited
- Multi line changes start with `// hippie start -- reason` and end with `// hippie end`. The reason MUST be included in the change in all cases, so that future coders looking at the line will know why it is needed.
- The reason should generally be about what it was before, or what the change is.
- Commenting out some /tg/ code must be done by putting `/* hippie start -- reason` one line before the commented out code, with said line having only the comment itself, and `hippie end */` one line after the commented out code, always in an empty line.
- Some examples:
```
var/obj/O = new(hippie) // hippie -- added hippie argument to new
```
```
/* hippie start -- mirrored in our file
/proc/del_everything
	del(world)
	del(O)
	del(everything)
hippie end */
```

Once marking your changes to the /tg/ files with the proper comment standards, be sure to include the file path of the tg file in our changes.md in this folder. Keep the alphabetical order.

2018-08-23 01:50 UTC, Dudeinyourbackyard commented
cool +1

2018-08-24 00:07 UTC, fluxcapacitor1337 commented
+1

2018-08-27 23:27 UTC, Carbonhell commented on code/game/sound.dm
> +		//Hippie start -- sound prefs
Maybe this can be avoided by directly editing the vol argument?
/playsound(arguments,vol as num,other arguments)
vol = yourcode
..(vol = vol)

not sure if this works but it'd let us fully modularize this

2018-08-27 23:28 UTC, Carbonhell commented on code/game/sound.dm
> +		//Hippie start -- sound prefs
i am especially being a bit nitpicky because sounds are planned to be reworked into a decent system, and modularizing this fully would make our job easier when it happens.

2018-09-10 15:42 UTC, Carbonhell commented
I am extremely sorry that this PR took a long while. It is mainly my fault because i intended to do a proper system to add our preferences to the panel without touching tg code. This pr seems fine, it just needs the options to be moved in our prefs. If you cannot do it, just ask me, i can do it quickly and easily in a new PR.

2018-09-25 17:03 UTC, Carbonhell commented
Stale, closing.

2018-09-25 17:03 UTC, closed without merging