[READY] [HOLY FUCK FINALLY] Adding atmos circuits
HippieStation/HippieStationdeprecated2020 pull request #8728
Opened 2018-08-23 03:21 UTC by Shdorsh

[Changelogs]: # Adding what was once planned to be added in atmos circuits, plus other circuits while trying to fix the coding. 13 new circuits, have fun, folks.

:cl: Shdorsh, Hate9, McDonald072
add: Small and normal gas tank circuits
add: Heater and freezer tank circuits
add: Gas filter and mixer circuits
add: Gas volume and pressure pump circuit
add: Connector circuits to connect to connector pipes
add: Gas vent circuits
add: Atmospheric cooler and heater circuits
add: Tank slot circuit
/:cl:

[why]: Because that's what it was once supposed to be, as seen in the early versions of https://github.com/tgstation/tgstation/pull/38111. Also, this is just me continuing the work of Hate9 in #8508 , who is currently busy, by fixing all the complaints people had and massively overhauling the code.

While atmospheric analyzer circuits are bugged ( https://github.com/tgstation/tgstation/pull/40150 ), it shouldn't have much impact on this PR, except that people can't check their own circuit for pressure/gastype etc.

https://github.com/tgstation/tgstation/pull/40129 got accepted and the upstream PR aswell, so I changed the self reference pin to real selfref. Easier to wire together.

All is tested and ready. It could be better if the selfref pin finally were in, but we'll just wait for that PR to be accepted then overhaul hippie circuits on another PR with it.

2018-08-23 06:21 UTC, Amelia0010 commented
@1fbff5f83b23d39d38b1dfcb4cac8d9b

2018-08-23 10:58 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b reviewed
Sweet

2018-08-23 10:58 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +/obj/item/integrated_circuit/atmospherics/pump/proc/update_target(new_amount)
This proc doesn't actually update `target_pressure`

2018-08-23 11:17 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
You'll probably want to include the analyzer too

2018-08-25 01:25 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +/obj/item/integrated_circuit/atmospherics/pump/proc/update_target(new_amount)
I'll do that once I'm back from my trip.

2018-08-25 08:48 UTC, Carbonhell commented
Hell ye +1

2018-08-26 17:37 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +/obj/item/integrated_circuit/atmospherics/pump/proc/update_target(new_amount)
recently changed to update pressure.

2018-08-26 17:39 UTC, Shdorsh commented
@1fbff5f83b23d39d38b1dfcb4cac8d9b analyzers are already inside the old PR, it would be redundant to include unless there needs to be some change in functionality due to the introduction of atmos circuits.

2018-08-26 18:50 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
whoops, brain fart

2018-08-29 12:35 UTC, Carbonhell commented
this will be a fun one to codecheck
tell us when it's ready to be codechecked aye

2018-08-30 16:51 UTC, HippieBartels commented
More circuit autism +1

2018-08-30 20:59 UTC, Eagle-Eyess commented
I have no clue how circuits work but atmos and circuits well now... +1

2018-08-30 23:15 UTC, Shdorsh commented
Hey there folks, sorry if I'm a bit absent, I got a few things to prepare in real life. Anyway, this can be pretty much tested to check for functionality and so on. The problem is that I haven't checked on most of the circuits yet and I believe the space heater and cooler might be somewhat strongly unbalanced. You guys can test it out on a private server for now and I'll come back once I'm no longer busy and do the whole balancing and fixing stuff, if you don't mind.

2018-09-05 20:34 UTC, Shdorsh commented
Just for info, I'm still working on this, but it is bugged. Also, I plan a major tgstation PR that will overhaul some of the functions of this.

2018-09-06 22:19 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b requested changes

2018-09-06 22:19 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	target_pressure = abs(min(200,new_amount))
You can set new amount to -9999999999999, swap the abs and min around

2018-09-06 22:21 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	target_pressure = abs(min(200,new_amount))
yeah, better idea. I also messed up some stuff on the cooler and heater.

2018-09-06 22:29 UTC, Shdorsh commented
I'll possibly add a tank slot just like I did a beaker slot for reagents.

2018-09-07 11:02 UTC, Shdorsh commented
Only 2 more circuits to go.

2018-09-07 23:55 UTC, Shdorsh commented
Done and ready. The selfref fix will be done when tgstation finally reviews and merges my selfref pins.

2018-09-08 07:07 UTC, Shdorsh commented
The selfref PR is in, and the code got changed to accept it. All done.

2018-09-11 16:40 UTC, Shdorsh commented
Can we remove the *requires upstream pr* tag please?

2018-09-12 16:00 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	to_chat(world,"Start do_work()")
uhhhhhh

2018-09-12 16:02 UTC, Carbonhell requested changes
Don't most of those circuits need a self reference?For example the tank?

2018-09-12 16:03 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	to_chat(world,"mix successful")
aaaaaaaa

2018-09-12 16:03 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		to_chat(view(0),"<span class='notice'>The [src.name] ruptures, releasing its gases!</span>")
what's this view(0)?

2018-09-12 16:03 UTC, nichlas0010 commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	to_chat(world,"mix successful")
lol

2018-09-12 16:04 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		playsound(src.loc, 'sound/effects/spray.ogg', 10, 1, -3)
src.

2018-09-12 16:04 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		to_chat(view(0),"<span class='notice'>The [src.name] ruptures, releasing its gases!</span>")
also src.

2018-09-12 16:05 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
looks [READY] to me

2018-09-12 16:11 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	to_chat(world,"mix successful")
hey, at least you can see that it was tested

2018-09-12 16:13 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		to_chat(view(0),"<span class='notice'>The [src.name] ruptures, releasing its gases!</span>")
It makes sure only the person on the same tile as the assembly sees it rupture. should I increase?

2018-09-12 16:17 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		to_chat(view(0),"<span class='notice'>The [src.name] ruptures, releasing its gases!</span>")
wouldn't people next to it be able to see it rupturing too? atleast adjacent makes sense imo

2018-09-12 16:22 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +		to_chat(view(0),"<span class='notice'>The [src.name] ruptures, releasing its gases!</span>")
I set it to 2, for detectability's sake. That way people can prepare their internals right away.

2018-09-12 16:58 UTC, Carbonhell approved these changes

2018-09-12 17:01 UTC, merged

2018-09-13 09:56 UTC, Shdorsh commented
Apparently, someone managed to make maxcaps with these, so an unmerge would be cool. I'll try to rewrite it so that atmos explosions are impossible with it.

2018-09-13 10:36 UTC, GuyonBroadway commented
Good luck lad atmos code is black fucking voodoo.

2018-09-13 10:37 UTC, GuyonBroadway commented
Also the culprit is tank slot circuits. If you can move gas from one tank to another you can make a bomb.

2018-09-13 10:56 UTC, Shdorsh commented
@GuyonBroadway you know what type of transfer into the tank they use? Just make a cap on transfer between them: Starting a certain pressure gas shouldn't transfer. That would block it all.

PM me on discord, chuckster#8566

2018-09-13 11:34 UTC, Shdorsh reviewed
In other words, if I nerf gas transfer circuits, it's going to be good, aight? Well, that's where I'm going at least.

2018-09-13 11:34 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +	if((source_air.return_pressure() < 0.01) || (target_air.return_pressure() > 9000))
try setting this to 1000 or less, making it so that people can't overpressurize stuff.

2018-09-13 11:34 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
> +/obj/item/integrated_circuit/atmospherics/pump/proc/move_gas(datum/gas_mixture/source_air, datum/gas_mixture/target_air)
Needs a return() after target_air.return_pressur() is above 1000 or something equal to cap pressure generation and nerf explosions