Fixes defib nanites
HippieStation/HippieStationdeprecated2020 pull request #8845
Opened 2018-08-29 23:28 UTC by steamp0rt

Since /tg/ maintainers are completely ignoring https://github.com/tgstation/tgstation/pull/39914, let's port it ourselves!

🆑 McDonald072
fix: Defibrillator nanites work properly.
/🆑

2018-08-29 23:29 UTC, Carbonhell commented
only four days passed tho

2018-08-29 23:38 UTC, steamp0rt commented
Yeah, but it's a fix, it's unusual to see a fix PR untouched for days, not even commented on.

Also people constantly complain on the server about defib nanites not working.

2018-08-29 23:39 UTC, Carbonhell commented
Why didn't you just cherrypick the commit? It would keep history aswell so we can just close the mirror when it shows up

2018-08-29 23:40 UTC, Carbonhell requested changes

2018-08-29 23:40 UTC, Carbonhell commented on code/modules/research/nanites/nanite_programs/healing.dm
> +	sleep(30)
Sleep????

2018-08-29 23:42 UTC, steamp0rt commented on code/modules/research/nanites/nanite_programs/healing.dm
> +	sleep(30)
normal defibs use do_after but since these aren't items you can't use that

2018-09-01 12:27 UTC, Carbonhell commented
Honestly, it's PRed upstream, just wait for them to merge this, it isn't critical enough to require us to speedmerge it.

2018-09-01 12:27 UTC, closed without merging