Adding beaker slot circuit
HippieStation/HippieStationdeprecated2020 pull request #8991
Opened 2018-09-06 14:40 UTC by Shdorsh

[Changelogs]: # Adds a beaker slot to assemblies so you can easily extract reagents.
:cl: Shdorsh
add: Added beaker slot circuit
/:cl:

[why]: This is the first circuit that adds some easy way to extract reagents from your assembly easily. In case where you want to make a portable grinder/portable chem filter or a chempile absorber using the drain, to collect chems as you go.

2018-09-06 14:53 UTC, Eagle-Eyess commented
+1

2018-09-07 00:13 UTC, fluxcapacitor1337 commented
+1

2018-09-08 07:04 UTC, Shdorsh commented
Seems like I was making and drinking cocktails while coding again, this time with the result of accidentally coding the new circuit in the nonmodular circuit code. This here should do it right.

2018-09-10 15:41 UTC, Carbonhell requested changes

2018-09-10 15:41 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +var/obj/item/reagent_containers/glass/beaker/current_beaker
Wrong indentation?

2018-09-10 15:41 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +	to_chat(user,"<span class='warning'>You put the [I.name] inside the beaker connector.</span>")
Why warning? Notice would fit better

2018-09-10 15:41 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +	if(istype(src.loc,/obj/item/integrated_circuit/input/beaker_connector))
Src. Is not needed

2018-09-10 15:41 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +/obj/item/reagent_containers/glass/beaker/on_reagent_change()
Is this absolutely needed? Seems snowflakey, can't it be completely handled by the circuit?

2018-09-10 16:17 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +var/obj/item/reagent_containers/glass/beaker/current_beaker
yeah, copypaste was being a bitch to me, I'll change that.

2018-09-10 16:18 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +	to_chat(user,"<span class='warning'>You put the [I.name] inside the beaker connector.</span>")
You're right about that one.

2018-09-10 16:19 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +	if(istype(src.loc,/obj/item/integrated_circuit/input/beaker_connector))
Done

2018-09-10 16:21 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +/obj/item/reagent_containers/glass/beaker/on_reagent_change()
Well, I could use a process that would run on a timer and update it livetime, which would be useless. The other beaker circuits work, since they mostly have a proc that updates their own reagent content, but since this one here updates another beaker's content, it has no other way to update. There is no proc being called on the circuit when it changes its beaker's contents and it would be hard to code around, I'd have to change more non-modular procs, so this addendum seems fine.

2018-09-10 17:30 UTC, Shdorsh commented
Huild has completed but github didn't manage to detect, it seems.

2018-09-12 11:18 UTC, Shdorsh commented
Good to see someone have the same approach as me when it comes to coding. A good cocktail or two never harms creativity.

2018-09-12 11:31 UTC, Carbonhell approved these changes

2018-09-12 11:31 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +/obj/item/integrated_circuit/input/beaker_connector/attackby(var/obj/item/reagent_containers/I, var/mob/living/user)
the var/ inside arguments aren't needed fyi, not an issue but you may want to know

2018-09-12 11:31 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +	if(!istype(I,/obj/item/reagent_containers/glass/beaker))
Theorically you could allow /obj/item/reagent_containers/glass instead of just beakers, so you could use buckets or glasses, your choice though. I guess beakers only would be more science-y

2018-09-12 11:31 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
> +/obj/item/reagent_containers/glass/beaker/on_reagent_change()
Theorically you could make a component to handle this. But, it's just three lines, it's fine as it is right now and it'd require some changes upstream to componentize it properly. Yeah,all good.

2018-09-12 11:31 UTC, Carbonhell commented
Good to go? Have you tested it?

2018-09-12 12:41 UTC, Shdorsh commented
Yeah, tested and working.

2018-09-12 15:48 UTC, Carbonhell approved these changes

2018-09-12 15:48 UTC, merged