[READY] Adds new easter egg for sec access
HippieStation/HippieStationdeprecated2020 pull request #8994
Opened 2018-09-06 19:23 UTC by JohnGinnane

:cl: JohnGinnane
add: People with sec access now have a 2% chance to hear an easter egg when opening doors
/:cl:

2% chance for a meme sound to play

2018-09-07 00:12 UTC, fluxcapacitor1337 commented
+1

2018-09-07 11:02 UTC, Carbonhell commented
Why so many easter eggs just for doors? This feels weird

2018-09-07 11:22 UTC, JohnGinnane commented
\>2 sounds
\>"so many"
:thinking:

2018-09-07 14:16 UTC, Eagle-Eyess commented
+1

2018-09-08 15:04 UTC, HippieBartels commented
+1

2018-09-10 19:52 UTC, Carbonhell commented
Ready?

2018-09-10 20:32 UTC, JohnGinnane commented
Yep

2018-09-13 16:02 UTC, Carbonhell commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	if (H)
No istype? Also this copypasta is ugly man

2018-09-13 16:03 UTC, Carbonhell requested changes
Copypasta

2018-09-13 17:47 UTC, JohnGinnane commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	if (H)
it's not copy pasta ;_;

2018-09-14 00:32 UTC, yoyobatty commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	if (istype(H) && H)
Maybe ishuman works better

2018-09-25 17:12 UTC, Carbonhell requested changes

2018-09-25 17:12 UTC, Carbonhell commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	if (istype(H) && H)
checking H is useless if you also istype, istype returns false if the argument is null

2018-09-25 17:12 UTC, Carbonhell commented on hippiestation/code/game/machinery/doors/airlock.dm
> +	if (H)
alright

2018-10-13 17:16 UTC, Carbonhell commented
Stale...

2018-10-13 17:16 UTC, closed without merging