Makes reagent states subsystem a processing SS
HippieStation/HippieStationdeprecated2020 pull request #8998
Opened 2018-09-07 01:57 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
Doesn't really need a CL.
/:cl:

[why]: Copypasting subsystems are bad.

2018-09-07 10:58 UTC, Carbonhell commented
This is not how the changelog nor the subsystems work, dude.

2018-09-07 10:59 UTC, Carbonhell requested changes
as i said on discord, subsystems do not use process. they use fire() at most, and even then i am sure you can avoid redefining it completely. Also if you dont want a changelog just do not write :cl: and /:cl:, you will break everything with the current changelog

2018-09-09 08:49 UTC, Carbonhell requested changes

2018-09-09 08:49 UTC, Carbonhell commented on hippiestation/code/controllers/subsystem/reagent_states.dm
> +		for(var/I in GLOB.smoke)
This stuff could be locking the server up if those lists are big. Not sure how big they can be but a MC_CHECK_TICK check at the end of each for cycle could help.

2018-09-11 23:59 UTC, Carbonhell commented
DNM this unless you know exactly what you are doing, also dnm right now since it is not ready

2018-09-13 04:56 UTC, yoyobatty commented
@Carbonhell ready

2018-09-15 15:19 UTC, Carbonhell commented on hippiestation/code/controllers/subsystem/reagent_states.dm
> +		if(!deleting && cost > 1000)
why did you lower the cost

2018-09-16 18:48 UTC, yoyobatty commented on hippiestation/code/controllers/subsystem/reagent_states.dm
> +		if(!deleting && cost > 1000)
Because anything over 1000 is already ridiculous. Let's keep this number for now.

2018-09-17 15:15 UTC, Carbonhell approved these changes

2018-09-17 15:15 UTC, Carbonhell commented
Please be ready to fix anything if this breaks.

2018-09-17 15:15 UTC, merged