Adds radial mode selection menu into Nanosuit
HippieStation/HippieStationdeprecated2020 pull request #8999
Opened 2018-09-07 07:55 UTC by yoyobatty

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: YoYoBatty
add: The nanosuit now has a radial mode selection menu which you can activate by holding C.
/:cl:

[why]:

2018-09-07 09:12 UTC, JohnGinnane commented
very cool

2018-09-07 09:21 UTC, ghost commented
It'd be convenient to be able to have it set to middle-click

2018-09-07 10:11 UTC, McBawbaggings commented
middle mouse button swaps hands so no

2018-09-07 10:14 UTC, steamp0rt commented
it does?

2018-09-07 14:14 UTC, Eagle-Eyess commented
+1

2018-09-07 15:52 UTC, ExpAntique commented
Thank you yoyo, very cool

 +1

2018-09-08 15:03 UTC, HippieBartels commented
Fancy stuff +1

2018-09-08 23:23 UTC, Carbonhell requested changes

2018-09-08 23:23 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +mob/living/carbon/human/key_down(_key, client/user)
What the hell no

2018-09-10 00:01 UTC, fluxcapacitor1337 commented
+1

2018-09-12 15:42 UTC, Carbonhell commented on hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
> +mob/living/carbon/human/key_down(_key, client/user)
are you sure key_down/up don't require any return value?

2018-09-12 15:43 UTC, Carbonhell approved these changes

2018-09-12 15:43 UTC, Carbonhell commented
Other redefinitions return ..() but it seems useless. merging

2018-09-12 15:43 UTC, merged