Ports mentor systems + fixes
HippieStation/HippieStationdeprecated2020 pull request #905
Opened 2017-05-01 16:42 UTC by GuyonBroadway

Does not port Narlar's WHO, will get on that in another PR.

2017-05-02 23:14 UTC, tortellinitony requested changes

2017-05-02 23:14 UTC, tortellinitony commented on code/controllers/configuration.dm
> +	var/mentors_mobname_only = 0		// Only display mob name to mentors in mentorhelps
You could have these in a different file as /datum/configuration/var/mentors_mobname_only .

2017-05-02 23:14 UTC, tortellinitony commented on code/world.dm
> +	load_mentors()
You could also add this in a different file.

2017-05-02 23:14 UTC, tortellinitony commented on interface/skin.dmf
> +		name = "F4"
Please apply these changes to the hippiestation skin.dmf.

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorpm.dm
> +			to_chat(A, "<B><font color='green'>Mentor PM: [key_name_mentor(src, A, 0, 0, show_char_sender)]-&gt;[key_name_mentor(C, A, 0, 0, show_char_recip)]:</B> \blue [msg]</font>") //inform A
`<font color ='blue'>` instead of just \blue

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorpm.dm
> +			to_chat(X, "<B><font color='green'>Mentor PM: [key_name_mentor(src, X, 0, 0, show_char_sender)]-&gt;[key_name_mentor(C, X, 0, 0, show_char_recip)]:</B> \blue [msg]</font>") //inform X
`<font color ='blue'>` instead of just \blue

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorhelp.dm
> +	src << "<span class='mentornotice'><font color='purple'>PM to-<b>Mentors</b>: [msg]</font></span>"
Use to_chat.

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentor_ranks.dm
> +			world.log << "Failed to connect to database in load_mentors()."
Use log_world

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentor_ranks.dm
> +		world.log << "Using legacy mentor system."
Use log_world

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorhelp.dm
> +		X << 'sound/items/bikehorn.ogg'
Use X.playsound_local(X, 'sound/items/bikehorn.ogg')

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorhelp.dm
> +		A << 'sound/items/bikehorn.ogg'
playsound_local

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorpm.dm
> +	C << 'sound/items/bikehorn.ogg'
playsound_local

2017-05-02 23:14 UTC, tortellinitony commented on hippiestation.dme
> +#include "interface\skin.dmf"
Remove this

2017-05-02 23:25 UTC, tortellinitony requested changes

2017-05-02 23:25 UTC, tortellinitony commented on code/modules/client/verbs/ooc.dm
> +					ooc_color = "#FF3E96"
You may want to add a configurable mentor OOC color.

2017-05-02 23:25 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentor_ranks.dm
> +	#ifdef TESTING
I don't think this is necessary.

2017-05-02 23:25 UTC, tortellinitony commented on hippiestation/code/modules/mentor/follow.dm
> +	to_chat(GLOB.admins, "<span class='mentor'><span class='prefix'>MENTOR:</span> <EM>[key_name(usr)]</EM> is now following <EM>[key_name(M)]</span>")
You probably want to use message_admins

2017-05-02 23:25 UTC, tortellinitony commented on hippiestation/code/modules/mentor/follow.dm
> +	to_chat(GLOB.admins, "<span class='mentor'><span class='prefix'>MENTOR:</span> <EM>[key_name(usr)]</EM> is no longer following <EM>[key_name(following)]</span>")
message_admins

2017-05-02 23:25 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorsay.dm
> +		to_chat(GLOB.admins, msg)
message_admins

2017-05-02 23:25 UTC, tortellinitony commented on hippiestation/code/modules/mentor/mentorsay.dm
> +		to_chat(GLOB.admins, msg)
message_admins

2017-05-03 23:00 UTC, GuyonBroadway commented on hippiestation/code/modules/mentor/mentorpm.dm
> +	C << 'sound/items/bikehorn.ogg'
playsound_local doesn't work with things like adminpm, or in this case mentorpm.

2017-05-03 23:23 UTC, GuyonBroadway commented on hippiestation/code/modules/mentor/mentorhelp.dm
> +		X << 'sound/items/bikehorn.ogg'
playsound_local doesn't work with things like adminpm, or in this case mentorpm. It actually throws a compiler error when i try.

2017-05-03 23:23 UTC, GuyonBroadway commented on hippiestation/code/modules/mentor/mentorhelp.dm
> +		A << 'sound/items/bikehorn.ogg'
playsound_local doesn't work with things like adminpm, or in this case mentorpm. It actually throws a compiler error when i try.

2017-05-03 23:24 UTC, GuyonBroadway commented on hippiestation/code/modules/mentor/mentor_ranks.dm
> +	#ifdef TESTING
I have no idea what it did but it was part of the old port and am loathe to touch it.

2017-05-03 23:33 UTC, JamieH commented on hippiestation/code/modules/mentor/mentor_ranks.dm
> +	#ifdef TESTING
yeah, remove this

2017-05-04 16:05 UTC, JamieH commented on code/modules/client/client_procs.dm
> -
Don't mess with the whitespace down here?

2017-05-04 16:05 UTC, JamieH commented on code/modules/client/client_procs.dm
> -
Here too

2017-05-04 16:05 UTC, JamieH commented on code/modules/client/client_procs.dm
> -
Here too

2017-05-04 16:05 UTC, JamieH commented on code/modules/client/client_procs.dm
> -
Here too

2017-05-04 16:05 UTC, JamieH commented on code/modules/client/client_procs.dm
> -
Here too

2017-05-04 16:05 UTC, JamieH commented on config/config.txt
> +## Add a # infront of this if you want to use the SQL based mentor system, the legacy system uses mentors.txt You need to set up your database to use the SQL based system.
Store this in config/hippiestation.txt

2017-05-04 16:05 UTC, JamieH commented on hippiestation/code/interface/skin.dmf
> -		command = "say *fart"
???

2017-05-04 16:05 UTC, JamieH commented on hippiestation/code/interface/skin.dmf
> -		command = "say *scream"
???

2017-05-04 16:05 UTC, JamieH commented on hippiestation/code/interface/skin.dmf
> -		command = "say *fart"
???

2017-05-04 16:05 UTC, JamieH commented on code/controllers/configuration.dm
> +				if ("mentor_mobname_only")
we need a config loader which is called from init which does this from the hippie config file

2017-05-04 16:49 UTC, GuyonBroadway commented on code/modules/client/client_procs.dm
> -
I never touched that whitespace... dunno why it's suddenly marked as changed.

2017-05-04 16:53 UTC, GuyonBroadway commented
HACKY FIX TO WHITESPACE ISSUE INBOUND!

2017-05-04 17:55 UTC, GuyonBroadway commented on code/modules/client/client_procs.dm
> -
IT HAS BEEN DONE!!!

2017-05-04 17:56 UTC, GuyonBroadway commented
Whitespace issue fixed,

2017-05-04 21:29 UTC, tortellinitony approved these changes

2017-05-04 21:29 UTC, merged