[Ready][Tested] New circuit: Wire connector
HippieStation/HippieStationdeprecated2020 pull request #9181
Opened 2018-09-20 21:02 UTC by Shdorsh

[Changelogs]: # Added a circuit which lets you connect to an exposed wire, read its powernet load and availability as well as either insert a certain amount of energy up to the assembly's batter charge or charge your assembly up to the wire's available power.

:cl: Shdorsh
add: Wire connector
/:cl:

[why]: You could do some very shitty solars with assemblies now. Or syphon a near insignificant amount of energy.

2018-09-20 21:20 UTC, lolmemelord123 commented
.

2018-09-20 21:46 UTC, yoyobatty commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +/obj/item/integrated_circuit/power/transmitter/wire_connector/process()
`..()`

2018-09-20 22:10 UTC, Shdorsh commented
Done it.

2018-09-21 21:06 UTC, Carbonhell commented
As long as you cannot make a ghetto powersink with this, especially if you stack those circuits, it seems fine. +1

2018-09-21 21:10 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +		var/obj/structure/cable/foundcable = locate(/obj/structure/cable) in get_turf(src)
locate() since the var is already typecasted
Also will get turf work here? Don't you need to use that special function that returns the assembly if the circuit is in one

2018-09-21 21:10 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	amount_to_move = CLAMP(amount_to_move, -min(connected_cable.powernet.avail,battery.maxcharge - battery.charge), battery.charge)
Battery can be null, can't it?

2018-09-21 21:10 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	amount_to_move = CLAMP(amount_to_move, -min(connected_cable.powernet.avail,battery.maxcharge - battery.charge), battery.charge)
I also believe some helpers to get powernet avail was made recently which is sanitized/is better than directly accessing the var, you may wanna look into it

2018-09-21 21:10 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	battery.charge -= amount_to_move
Don't batteries have an use function to handle this better

2018-09-22 01:23 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +		var/obj/structure/cable/foundcable = locate(/obj/structure/cable) in get_turf(src)
All I can say is: it works.

2018-09-22 01:34 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	battery.charge -= amount_to_move
The fact that the battery needs to both give power and take makes it so that the easier way to code this is this way. takes less space, quicker to code. If you insist though, I can change it to something that uses those functions.

2018-09-22 09:04 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	amount_to_move = CLAMP(amount_to_move, -min(connected_cable.powernet.avail,battery.maxcharge - battery.charge), battery.charge)
I thought that since the assembly needs a battery for its circuits to work it shouldn't be the case, but you're right, you can actually use the debugger tool to pulse it.

2018-09-22 09:18 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	amount_to_move = CLAMP(amount_to_move, -min(connected_cable.powernet.avail,battery.maxcharge - battery.charge), battery.charge)
Did this, resolved.

2018-09-22 09:18 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	battery.charge -= amount_to_move
Did this, resolved.

2018-09-22 09:19 UTC, Shdorsh commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	amount_to_move = CLAMP(amount_to_move, -min(connected_cable.powernet.avail,battery.maxcharge - battery.charge), battery.charge)
Also, couldn't find any helpers for powernet avail in the powernet file, so I guess no. Would also be somewhat weird to make an entire proc just to return a variable.

2018-09-22 09:43 UTC, Shdorsh commented
Done and working.

2018-09-22 10:05 UTC, Shdorsh commented
There we go: takes energy from available energy, and gives energy in the new available var that handles any new energy put into the powernet.

2018-09-22 18:09 UTC, Shdorsh commented
So, what's the verdict on this? Fine?

2018-09-23 20:45 UTC, Carbonhell commented
Ask headmins on discord to +1 it if they're too lazy to do it themself

2018-09-24 09:13 UTC, HippieBartels commented
Sure why not +1

2018-09-25 21:31 UTC, fluxcapacitor1337 commented
+1

2018-09-26 20:48 UTC, Shdorsh commented
Seems like everyone's fine with it, can we merge it plz?

2018-09-28 10:05 UTC, Carbonhell commented on hippiestation/code/modules/integrated_electronics/subtypes/power.dm
> +	var/obj/structure/cable/connected_cable
Null this out on Destroy() or it'll fail to delete cleanly. Just do
/your/obj/Destroy()
connected_cable = null
return ..()

2018-09-28 10:07 UTC, Carbonhell requested changes
Do the destroy() stuff and it's good to go

2018-09-28 10:42 UTC, Shdorsh commented
Doneroo

2018-09-28 10:46 UTC, Carbonhell approved these changes

2018-10-01 19:28 UTC, merged