i fucking hate AI vox
HippieStation/HippieStationdeprecated2020 pull request #9311
Opened 2018-09-30 01:26 UTC by steamp0rt

:cl: steamp0rt
add: Added an independent preference for AI VOX.
/:cl:

2018-09-30 01:32 UTC, Kawaii-Big-Boss commented
Are you for real
Bringing back the pref for vox is fine, but seriously removing the word "accelerating" because a player said "CLOWN ASS ACCELERATING" a couple times one round is just stupid. Stop dongcoding.

2018-09-30 01:46 UTC, steamp0rt commented
i've seen AIs that pretty much just copy/paste ACCELERATING until they hit the word limit

2018-09-30 02:11 UTC, inkticious commented
honestly, VOX is useless because of how many words are banned, if youre gonna ban every word just remove VOX, when ever im AI i can't even annouce something i saw to the station because of how many words are banned, so i end up having to turn on the common radio, if you're so worried about people spamming job ban them instead of removing something that someone who isnt gonna spam is going to use for a good reason, and helpful reason.

2018-09-30 02:40 UTC, MrWankman commented
> honestly, VOX is useless because of how many words are banned, if youre gonna ban every word just remove VOX, when ever im AI i can't even annouce something i saw to the station because of how many words are banned, so i end up having to turn on the common radio, if you're so worried about people spamming job ban them instead of removing something that someone who isnt gonna spam is going to use for a good reason, and helpful reason.

I don't think words are banned, so much that words are just limited because the VOX's audio is only the intro audio to Half Life and such is not very robust for replicating most of the language. It is however a good meme.

2018-09-30 02:53 UTC, inkticious commented
good meme is good

2018-09-30 08:49 UTC, Carbonhell commented
+1 for the pref, -1 for the word removal. Just turn off your prefs if someone is fucking with words that trigger you.

2018-09-30 09:12 UTC, ghost commented
ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING 
ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING 
ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING 
ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING ACCELERATING
WOOP

2018-09-30 09:37 UTC, GuyonBroadway commented
CLOWN ACCELERATING 20 KILO METER JONSON INTO CAPTAIN ASS HOLE

2018-09-30 12:50 UTC, steamp0rt commented
ACCELERATING has been re-added

2018-09-30 12:52 UTC, Carbonhell commented
Make it start enabled. It should be opt-out, not opt-in.

2018-09-30 12:54 UTC, steamp0rt commented
Done

2018-09-30 18:48 UTC, praisenarsie commented
![image](https://user-images.githubusercontent.com/31222036/46261316-da147d00-c4e9-11e8-8283-0bc3247f23b0.png)

2018-09-30 18:49 UTC, praisenarsie commented
also i dislike the lack of use of the dongcode label

2018-10-01 19:36 UTC, Carbonhell requested changes

2018-10-01 19:36 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences_toggles.dm
> +	SSblackbox.record_feedback("nested tally", "preferences_verb", 1, list("Toggle AI VOX", "[usr.client.prefs.toggles & SOUND_VOX ? "Enabled" : "Disabled"]")) //If you are copy-pasting this, ensure the
should be hippie_toggles, not toggles

2018-10-01 19:36 UTC, Carbonhell commented on hippiestation/code/modules/client/preferences_toggles.dm
> +	SSblackbox.record_feedback("nested tally", "preferences_verb", 1, list("Toggle AI VOX", "[usr.client.prefs.toggles & SOUND_VOX ? "Enabled" : "Disabled"]")) //If you are copy-pasting this, ensure the
i bet you just copypasted this you lazy scum reeEE

2018-10-02 14:29 UTC, Carbonhell approved these changes

2018-10-02 14:29 UTC, Carbonhell commented
+1

2018-10-02 14:30 UTC, bardofrage commented
Sure, +1.

2018-10-02 14:31 UTC, merged