Telescience Restoration
HippieStation/HippieStationdeprecated2020 pull request #9386
Opened 2018-10-04 04:35 UTC by BlueNothing

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl:
Restores the functionality of Telescience to all stations by adding the telepad and control console to the techweb as a node after Bluespace Travel.
/:cl:

[why]: Telescience is a famous and well-loved part of the SS13 experience that has been replicated only in hollow fashion in recent days with devices like the quantum pad (which still has a useful niche if you want A->B->C->A transportation, or A->B->A transportation without a second person involved), the bluespace launchpad (which mostly everyone treats as useless, because its range means that it rarely gets you anywhere interesting unless you're already somewhere at least almost as interesting, but which does have a much simpler control scheme), or the traitor briefcase launchpad (which is still somewhat useful, if only due to being portable and letting you yoink things from another room (pairing well with x-ray or thermal vision)). A proper restoration would likely be no shortage of amusement to many.

2018-10-04 06:12 UTC, Kawaii-Big-Boss commented
Oh shit what are you doing
Telescience was one of the most abused features on the server. There's a reason why it was replaced, science powergame is already incredibly obnoxious and nobody enjoys scientists immediately rushing the teleporter so they can steal the captain's locker.

also you thumbs up'd your own post.

2018-10-04 06:16 UTC, Manly-Dwarf requested changes

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +	if(istype(I, /obj/item/screwdriver))
None of this should be in this PR. Also it's not modular.

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/modules/research/designs/bluespace_designs.dm
> +*/
Why comment all of this out?

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/modules/research/designs/comp_board_designs.dm
> + 	departmental_flags = DEPARTMENTAL_FLAG_SCIENCE
Modularize this.

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/modules/research/techweb/all_nodes.dm
>  	export_price = 5000
Again, whole file needs to be modularized.

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/modules/shuttle/supply.dm
> +		/obj/machinery/computer/telescience,
You're gonna give Carbonhell a stroke, man.

2018-10-04 06:16 UTC, Kawaii-Big-Boss commented on code/modules/telesci/telepad.dm
> +///SCI TELEPAD///
To explain what modularization is, you need to go to our hippiestation folder. Not the code folder. That's all /tg/. Don't change that or add anything to that.
All you have to do to modularize some of your changes is go into a hippiestation folder, create the file you need, edit the var you need changed, and done. You modularize your code to prevent conflicts.

2018-10-04 11:41 UTC, BlueNothing commented on code/modules/research/designs/bluespace_designs.dm
> +*/
It was code for another related concept that I wasn't able to get working, and it was outside of scope. Probably should just remove it, in hindsight.

2018-10-04 12:14 UTC, Carbonhell commented
Hell yeah +1 but i think it should be slightly reworked after this to not make it easily abusable as before

2018-10-04 12:16 UTC, bubberducky2 commented
how about you make some areas blocked from telescience just like goon? would be a nice and easy nerf to telesci.

2018-10-04 13:18 UTC, BlueNothing commented
I don't know how to do that at the moment, but I figured a good way could be to have like four null beacons or so spread out in the station (mostly in armory to start) that blocked out a 4x4 region or so, allowing for dynamic shielding.

2018-10-04 13:19 UTC, BlueNothing commented on code/modules/telesci/telepad.dm
> +///SCI TELEPAD///
I'll be away a few hours, but it should fortunately be a pretty easy fix. Just set the tgstation stuff back to normal and make the changes in the Hippie modules, circuit board file, etc. Right?

2018-10-04 13:57 UTC, praisenarsie commented
i'd prefer telesci powergame over any other science powergame

2018-10-04 13:59 UTC, Dinopeaks commented
just have the telespace blocker or what ever there called

2018-10-04 18:50 UTC, zamolxius commented
telesci is cool, just have passive bluespace shielding in some areas such as armory, vault, perma, chapel (the holiness which prevents revenants or other things normalizes the bluespace punch-hole-through world thing)

2018-10-04 19:25 UTC, BlueNothing commented
I'm not sure that perma or chapel really need that. Armory, vault, tcomms, AI upload, AI Core, and Gravity would be the only places I'd think *might* need it.

2018-10-04 19:36 UTC, Kawaii-Big-Boss commented on code/modules/telesci/telepad.dm
> +///SCI TELEPAD///
Yeah pretty much. Of course, test it and make sure everything works.

2018-10-04 19:48 UTC, yoyobatty commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +	if(istype(I, /obj/item/screwdriver))
Yes, please use tool behaviour not istype

2018-10-04 19:51 UTC, yoyobatty commented
Bubbers idea is good, we could also have x y and z coords and distance settings locked to different nodes, meaning going specific places requires higher levels of research, just an idea.

2018-10-04 19:51 UTC, BlueNothing commented on code/game/objects/items/circuitboards/computer_circuitboards.dm
> +	if(istype(I, /obj/item/screwdriver))
I'll be honest, this part was probably voodoo to me. Also not sure why it's there.

2018-10-04 19:52 UTC, BlueNothing commented
It kind of already did, batty. Higher power settings *were* gated... behind capacitor upgrades.

2018-10-04 22:38 UTC, BlueNothing commented
Would it be alright to put off changing the computation for the offsets for another PR? Carbonhell had an idea of how it might be done, but I'm not sure how quickly I could turn it around.

2018-10-05 08:59 UTC, MrWankman commented
I'm not too sure how telesci works but from what little I read, I think you could just make it so when you try to teleport into areas yall want to blacklist for the sake of avoiding too much powergaming then you can have it coded to make the offshoots that are always present in the accuracy to always have the offshoot land the aim outside of a blacklisted area if that area is targeted.  Something along those lines at least.

2018-10-05 13:57 UTC, McBawbaggings commented
issue with telescience is it gives far too much power to people willing to maths it outside of the game
there's no point of calculating in-game unlike the potential for goon and secrets

it also has other issues like being able to instantly bomb areas without consequence

2018-10-05 20:06 UTC, closed without merging