Re-adds some sound effects all the way back from 2015 + 2015 egun sprite
HippieStation/HippieStationdeprecated2020 pull request #9471
Opened 2018-10-09 09:36 UTC by Kawaii-Big-Boss

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: Kawaii-Big-Boss
soundadd: Some machine sounds have been reverted to their 2015 state.
imageadd: The Egun has its old sprite from 2015.
/:cl:

[why]: This is not a complete re-add of all of our older sprites, nor our older sounds, just the ones that immediately came to mind.
The following sounds have been changed:
Windoors
Announcements/Alerts
Airlocks
Spray Bottles
Punches
Lasers

Windoor Sound Change:
Because the old one just sounds more like a piece of shit. It's also 100% synced with the actual animation of the windoor.

Announcements/Alerts:
Simpler, quieter, but still to the point. Should no longer violate your ears with loud alarms

Airlocks:
Honestly I just prefer this one. Way back when, everyone loved the sound effect when it was first re-added.

Spray Bottles:
Much shorter sound effect, doesn't play the sound twice in a row, but still works.

Punches:
Older sound effects, simply put, had more of a punch to them. They're a bit quiet right now for reasons I don't want to tinker around with until Carbonhell gives me the okay.

Lasers:
See above.

### Egun Sprite Change

The older egun has a much better design to it. Unfortunately, the sprite has also aged quite a bit and doesn't have that same "polish" as the current egun.
![old egun sprite](https://user-images.githubusercontent.com/33744849/46660360-d9808400-cb84-11e8-8bca-4e787530b122.png)
Personally I would still take it over the current one any day. It has better visual clarity in the in-hands, and the design is a lot less clean and refined. It, simply put, looks like a cheap or retro piece of crap that Nanotrasen would hand out for mall cop security.

In stark contrast, another sprite I wanted to add was a laser gun resprite, also from 2015 base (but was used for a different item)
![old laser sprite](https://user-images.githubusercontent.com/33744849/46660439-059c0500-cb85-11e8-8472-341118678765.png)
This sprite looks way more advanced and/or modern, but I can't quite tell if I like it over the current laser gun sprite, which is why I didn't add it in this PR. Also because Tortellini Tony's inevitable -1 and or ragging is already going to be annoying, don't need to give him more ammo :smug:

A video will go up soon demonstrating all of the new sounds.

2018-10-09 09:47 UTC, ghost requested changes

2018-10-09 09:47 UTC, McBawbaggings commented on code/modules/mob/living/carbon/human/species.dm
> +	var/sound/attack_sound = 'hippiestation/sound/weapons/punch1.ogg'
can be modularised by making a new file

2018-10-09 09:47 UTC, McBawbaggings commented on code/modules/mob/living/carbon/human/species.dm
> +	var/sound/miss_sound = 'hippiestation/sound/weapons/punchmiss.ogg'
can be modularised by making a new file

2018-10-09 09:48 UTC, Carbonhell commented
Sure +1

2018-10-09 09:50 UTC, Carbonhell requested changes
All the comments in tg files are one line or at most two line. Just do
code // hippie -- reason
No need for new lines, also be sure to use uncapitalized "hippie" and double -

2018-10-16 08:01 UTC, praisenarsie commented
Old egun looks like somebody left it in an attic for 50+ years and when they found it, they accidently chipped off some of the material while dusting it off.

2018-10-16 16:08 UTC, DaydreamPuppeh commented
The old egun Sprite is better than the current one. +1, though I want the Sprite to be updated to fit the other sprites

2018-10-19 14:33 UTC, Eagle-Eyess commented
+1

2018-11-08 16:50 UTC, t-f-w commented
egun sprite is eh, laser gun sprite is good. +1 tho

2018-11-12 16:20 UTC, yskefunky commented
i'd like if you'd be able to make it a small percentage just to change things up a bit for the newer sounds, like how we have doom sounds rarely play. also make the new sprite egun another weapon for mappers to use as a nice loot drop but otherwise +1

2018-11-12 20:58 UTC, yobob591 commented
+1 PEW PEW

2018-11-19 04:29 UTC, ghost commented
cool af

2018-11-20 19:43 UTC, danhibiki commented
+2 headmins vote this should be good

2018-11-20 20:23 UTC, GuyonBroadway commented
This still requires modularization.

2018-11-20 22:59 UTC, Kawaii-Big-Boss commented
i don't wanna modularize this it's BORING

2018-11-26 05:41 UTC, zamolxius commented
it should be easy to modularize, also make the new egun a premium egun from the security vendor for 200 bucks

2018-11-27 01:16 UTC, bardofrage commented
+1 again

2018-12-04 03:14 UTC, t-f-w commented
fking modularize you lazy bastard.................

2018-12-04 15:36 UTC, k-k-karma commented
Reopen when this is modularized.

2018-12-04 15:36 UTC, closed without merging