Makes bags of holding great again
HippieStation/HippieStationdeprecated2020 pull request #9487
Opened 2018-10-09 22:14 UTC by steamp0rt

:cl: steamp0rt
add: Bags of holding now make singulos again
/:cl:

2018-10-09 22:30 UTC, WarRage333 commented
Bad

2018-10-09 22:57 UTC, Kawaii-Big-Boss commented
I'm not a fan of the singulo change either, but a better alternative would be to just buff the tear in reality. Make it much bigger.
You also just straight up unincluded the whole file, so...

2018-10-09 22:59 UTC, steamp0rt commented
>  You also just straight up unincluded the whole file, so...

Because sometimes using `...()` makes warnings

2018-10-10 09:40 UTC, MrWankman commented
I mean I suppose whether you prefer singulo to tear is dependent on whether you think bag of holding should either just be an obstical in the station or end the round. I'm fine with it making a tear myself tho.

2018-10-10 18:56 UTC, ExpAntique commented
-1

2018-10-15 11:53 UTC, Jujumatic requested changes

2018-10-15 11:53 UTC, Jujumatic commented on hippiestation.dme
> -#include "code\datums\components\storage\concrete\bag_of_holding.dm"
we still need this included in our tg code, the hippiestation code should overwrite it anyway but just makes it easier for us to keep original tg code and keep it updated

2018-10-15 12:05 UTC, Iamgoofball commented
terrible idea

2018-10-19 09:42 UTC, steamp0rt commented on hippiestation.dme
> -#include "code\datums\components\storage\concrete\bag_of_holding.dm"
no, even the old code calls `..()`

2018-10-31 20:05 UTC, Lxtoofonea commented
No, that was way too OP in the past, but I agree with kbb on one, just make the tear worse

2018-10-31 20:07 UTC, steamp0rt commented
tear is dumb tho

2018-11-03 19:08 UTC, JohnMcLaime commented
Tear in reality is already strong enough, i would say it is better than singularity which was easy to escape compared to this. When someone boh bombed, singu would appear in smallest form, easy to run away from and if someone was boh bombing with auto cloning, it had potential to fuck them over, unless they invested extra time in making autocloner off station zlvl. This current one is retarded, just upgrade cloner and boh bomb spam, everyone in screen range gets instafucked, if they dont get gibbed by tear, they will get stuck in all the clutter or will die to space since ladders lead there iirc, unless they HAPPEN to get lucky with tear rng and have hand tele locked on station beacon or hardsuit with enough oxy for a trip to station.

2018-11-03 19:09 UTC, JohnMcLaime commented
Revert this tg piece of shit, they wanted to nerf it with this change iirc, but they actually buffed it, fuck their monkey coders.

2018-11-12 16:21 UTC, yskefunky commented
what if as a middle ground you'd have to do some shit to the bag of holding to shit out sings? emag or something? otherwise nah -1

2018-11-20 19:44 UTC, danhibiki commented
-2 headmins this has been voted out

2018-11-20 20:07 UTC, t-f-w commented
-1

2018-11-20 20:24 UTC, GuyonBroadway commented
Two headmins have denied this, closing until you convince them otherwise.

2018-11-20 20:24 UTC, closed without merging