Allows the Mime to communicate via Ventriloquist Dummy
HippieStation/HippieStationdeprecated2020 pull request #9775
Opened 2018-11-15 23:25 UTC by Tranquill6

[Guidelines]: # Good enough.

[Changelogs]: # Adds a spell that Mimes start with that enable it to communicate while holding the Ventriloquist Dummy in their hand. Relates to issue #9647 

[why]: This allows the Mime, who wishes not to break the vow of silence, a method of communication to our lovely, not special, crew members.

2018-11-16 13:34 UTC, yoyobatty submitted a review, later dismissed
Code seems good to me

2018-11-16 15:37 UTC, k-k-karma commented on code/game/objects/items/toys.dm
> + GLOBAL_VAR_INIT(doll_name, "Dummy")
wrong section and why a global var

2018-11-16 16:09 UTC, Tranquill6 commented on code/game/objects/items/toys.dm
> + GLOBAL_VAR_INIT(doll_name, "Dummy")
It's fine, the global var is so I can pull up the name of the doll in the mime's spell dm.

2018-11-16 16:11 UTC, k-k-karma commented on code/game/objects/items/toys.dm
> + GLOBAL_VAR_INIT(doll_name, "Dummy")
or just use .name?
global vars are overused

2018-11-16 16:19 UTC, k-k-karma commented on code/modules/spells/spell_types/mime.dm
> +// This spell enables muted Mimes to use the Ventriloquist Dummy to communicate
modularize please

2018-11-16 16:20 UTC, k-k-karma commented on code/modules/spells/spell_types/mime.dm
> +		I.say(input)
I.talk_into(input)

2018-11-16 16:22 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +// This spell enables muted Mimes to use the Ventriloquist Dummy to communicate
you mean hippie comment, didn't see this oops

2018-11-16 16:32 UTC, yoyobatty requested changes

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +/obj/effect/proc_holder/spell/targeted/mime/dummy_talk_into/Click(atom/movable/A)
Remove the argument `atom/movable/A`

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +/obj/effect/proc_holder/spell/targeted/mime/dummy_talk_into/Click(atom/movable/A)
Insert `var/mob/living/carbon/human/owner = usr` line below

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +	var/obj/item/I = usr.is_holding_item_of_type(/obj/item/toy/dummy)
replace usr with owner

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +		var/mob/M = A
remove this line

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +		if (istype(M))
remove this line

2018-11-16 16:32 UTC, yoyobatty commented on code/modules/spells/spell_types/mime.dm
> +			M.log_talk(message, LOG_SAY, tag="dummy toy")
replace M with `owner`

2018-11-16 16:43 UTC, k-k-karma commented on code/modules/spells/spell_types/mime_dummy.dm
> +		I.say(input)
```suggestion
		I.say_into(input)
```

2018-11-16 16:45 UTC, k-k-karma commented on code/modules/spells/spell_types/mime_dummy.dm
> +// This spell enables muted Mimes to use the Ventriloquist Dummy to communicate
To modularize, you must put your code where your code would originally go on TG, but in the hippiestation folder

2018-11-16 17:31 UTC, yoyobatty commented on code/modules/spells/spell_types/mime_dummy.dm
> +// This spell enables muted Mimes to use the Ventriloquist Dummy to communicate
code/modules/spells/spell_types/mime_dummy.dm = tg
hippiestation/code/modules/spells/spell_types/mime_dummy.dm = hippie modularized

2018-11-16 19:40 UTC, bardofrage commented
eh +1

2018-11-17 04:40 UTC, closed without merging

2018-12-19 00:05 UTC, DaydreamPuppeh commented
+1

2018-12-19 00:11 UTC, yoyobatty commented
wut?

2018-12-19 00:11 UTC, DaydreamPuppeh commented
Meant to say. Why was this closed

2018-12-19 00:59 UTC, yoyobatty commented
I actually don't know, I thought this got remade?