botany balance changes
HippieStation/HippieStationdeprecated2020 pull request #9916
Opened 2018-11-28 21:24 UTC by uBadush

this remove the extraction cap from yield and production speed based on stock parts

2018-11-28 21:32 UTC, yoyobatty commented
right branch but why didn't you do the edits I told you to do?

2018-11-28 21:34 UTC, uBadush commented
> right branch but why didn't you do the edits I told you to do?

wait what changes, sorry

2018-11-28 21:42 UTC, danhibiki reviewed
You got a lot of stuff you don't need to define, and mostly you should be defining your base values for what your modding limits are on gene_modder machinery and the check for parts to manipulate potency.

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +			min_production = 1
if statement that yields same result regardless of value, shouldn't bother with this for loop

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +		add_overlay("dnamod-open")
this whole chain isn't necessary, predefined in gene_modder.dm

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +		..()
Unnecessary and predefined

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +	popup.open()
Unnecessary

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +	interact(usr)
Unnecessary

2018-11-28 21:42 UTC, danhibiki commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +	update_icon()
unnecessary

2018-11-28 21:44 UTC, uBadush commented
@danhibiki  i did not made this code, this the actual /tg/, hippie code is using i just changed numbers

2018-11-29 02:54 UTC, yoyobatty commented
Uh, so why did you repaste tg code, why couldn't you just override the desired proc and put the var edits, you literally copy pasted the old cold and then editted numbers, this entire file already looks at the values from the tg version of gene_modder.dm, you're overwriting the code you want, not replacing the original file.

2018-11-29 03:00 UTC, uBadush commented
Gene_modder.dm did not existed in hippiestation/code/modules/hydroponics, you said to put it here, I did with the changes I made, the code is the same Hippie is using right now I don't understand what is the problem here

2018-12-09 23:15 UTC, bardofrage commented
+1

2018-12-22 02:36 UTC, t-f-w commented
+1

2018-12-22 21:51 UTC, t-f-w commented
+1

2018-12-22 21:57 UTC, uBadush commented
@yoyobatty  i think its aproved to be merged but i forgot to add  hippiestation.dme

2018-12-22 21:58 UTC, DaydreamPuppeh commented
+1

2018-12-23 00:32 UTC, yoyobatty submitted a review, later dismissed
This looks fine

2018-12-23 00:35 UTC, yoyobatty requested changes

2018-12-23 00:35 UTC, yoyobatty commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +			max_potency = initial(max_potency) + (M.rating+12) // 62,74,86,98 	 Clamps at 100
this doesn't do what you think it does, you want M.rating+12 to be M.rating*12

2018-12-23 00:35 UTC, yoyobatty commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +		max_endurance = initial(max_endurance) + (SM.rating * 25) // 35,60,85,100	Clamps at 10min 100max
I think your comments are a little misleading

2018-12-23 00:36 UTC, yoyobatty commented
Please reply to those review comments.

2018-12-23 00:51 UTC, uBadush commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +		max_endurance = initial(max_endurance) + (SM.rating * 25) // 35,60,85,100	Clamps at 10min 100max
I don't know what do toou mean by this one sorry

2018-12-23 00:52 UTC, uBadush commented on hippiestation/code/modules/hydroponics/gene_modder.dm
> +			max_potency = initial(max_potency) + (M.rating+12) // 62,74,86,98 	 Clamps at 100
Fixed

2018-12-23 18:39 UTC, yoyobatty approved these changes

2018-12-23 18:40 UTC, merged