fixes vitamin making you fat
HippieStation/HippieStationdeprecated2020 pull request #9982
Opened 2018-12-02 22:18 UTC by uBadush

:cl: vitamin does not make you fat anymore as intended
/:cl:

2018-12-03 18:34 UTC, tortellinitony requested changes

2018-12-03 18:34 UTC, tortellinitony commented on hippiestation/code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	. = ..()
`return ..()`

2018-12-03 19:05 UTC, uBadush commented on hippiestation/code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	. = ..()
What is the function of return here

2018-12-20 14:30 UTC, Carbonhell commented
Code's wrong. This is already implemented here, aswell:
https://github.com/HippieStation/HippieStation/blob/master/code/modules/reagents/chemistry/reagents/food_reagents.dm#L96
Is 600 too much?Are you actually sure it makes you fat?

2018-12-22 16:04 UTC, uBadush commented
@Carbonhell  above 600 you are fat and slowed, if you have 599 nutriment it will pump more 30 and keep you fat changing it to 570 will make that vitamin will never make you fat and slow

2019-01-19 10:04 UTC, Carbonhell commented
Yea but you are calling the tg definition with ..(), so this code will just cause people to be filled twicely. You need to edit the value in the tg file directly.

2019-02-11 11:12 UTC, Carbonhell commented
Stale.

2019-02-11 11:12 UTC, closed without merging